bipedal-locomotion-framework: BipedalLocomotion::TSID::SO3Task Class Reference
BipedalLocomotion::TSID::SO3Task Class Reference
SO3Task is a concrete implementation of the System::LinearTask.
#include <BipedalLocomotion/TSID/SO3Task.h>
Public Member Functions
bool initialize (std::weak_ptr< ParametersHandler::IParametersHandler > paramHandler)
Initialize the SO3Task.
bool setKinDyn (std::shared_ptr< iDynTree::KinDynComputations > kinDyn)
Set the kinDynComputations object.
bool setVariablesHandler (const System::VariablesHandler &variablesHandler) override
Set the set of variables required by the task.
bool update () override
Update the content of the element.
bool setSetPoint (const manif::SO3d &I_R_F, const manif::SO3d::Tangent &angularVelocity, const manif::SO3d::Tangent &angularAcceleration)
Set the desired reference point.
std::size_t size () const override
Get the size of the task.
Type type () const override
The SO3Task is an equality task.
bool isValid () const override
Determines the validity of the objects retrieved with getA() and getB()
Public Member Functions inherited from BipedalLocomotion::System::LinearTask
Eigen::Ref< const Eigen::MatrixXd > getA () const
Get the matrix A.
Eigen::Ref< const Eigen::VectorXd > getB () const
Get the vector b.
const std::string & getDescription () const
Get the description of the task.
Additional Inherited Members
Public Types inherited from BipedalLocomotion::System::LinearTask
enum Type { equality, inequality }
Type of the task.
Protected Member Functions inherited from BipedalLocomotion::System::LinearTask
iDynTree::MatrixView< double > subA (const System::VariablesHandler::VariableDescription &description)
Extract the submatrix A associated to a given variable.
iDynTree::MatrixView< const double > subA (const System::VariablesHandler::VariableDescription &description) const
Extract the submatrix A associated to a given variable.
Protected Attributes inherited from BipedalLocomotion::System::LinearTask
Eigen::MatrixXd m_A
Task Matrix.
Eigen::VectorXd m_b
Task Vector.
std::string m_description {"Generic Linear Task Element"}
String describing the content of the task.
Detailed Description
SO3Task is a concrete implementation of the System::LinearTask.
Please use this element if you want to control the orientation of a given frame rigidly attached to the robot. The task assumes perfect control of the robot acceleration \(\dot{\nu}\) that contains the base linear and angular acceleration expressed in mixed representation and the joints acceleration. The task represents the following equation
\[ J \dot{\nu} + \dot{J} \nu = \dot{\mathrm{v}} ^ * \]
where \(J\) is the robot jacobian and \(\dot{\mathrm{v}} ^ *\) is the desired acceleration. The desired acceleration is chosen such that the frame orientation will asymptotically converge to the desired trajectory. The angular acceleration is computed by a PD controller in \(SO(3)\).
Note
Please refer to https://github.com/dic-iit/lie-group-controllers if you are interested in the implementation of the PD controllers.
Definition at line 40 of file SO3Task.h.
Member Function Documentation
initialize()
bool SO3Task::initialize (std::weak_ptr< ParametersHandler::IParametersHandler > paramHandler)
Initialize the SO3Task.
Parameters
paramHandler pointer to the parameters handler.
Note
the following parameters are required by the class
Parameter Name Type Description Mandatory
robot_acceleration_variable_name string Name of the variable contained in VariablesHandler describing the robot acceleration Yes
frame_name string Name of the frame controlled by the SO3Task Yes
kp_angular double Gain of the orientation controller Yes
kd_angular double Gain of the angular velocity controller Yes
Returns
True in case of success, false otherwise.
Definition at line 70 of file SO3Task.cpp.
References std::weak_ptr< T >::lock(), and BipedalLocomotion::log().
isValid()
bool SO3Task::isValid () const override virtual
Determines the validity of the objects retrieved with getA() and getB()
Returns
True if the objects are valid, false otherwise.
Implements BipedalLocomotion::System::LinearTask.
Definition at line 205 of file SO3Task.cpp.
setKinDyn()
bool SO3Task::setKinDyn (std::shared_ptr< iDynTree::KinDynComputations > kinDyn)
Set the kinDynComputations object.
Parameters
kinDyn pointer to a kinDynComputations object.
Returns
True in case of success, false otherwise.
Definition at line 58 of file SO3Task.cpp.
References BipedalLocomotion::log().
setSetPoint()
bool SO3Task::setSetPoint (const manif::SO3d & I_R_F, const manif::SO3d::Tangent & angularVelocity, const manif::SO3d::Tangent & angularAcceleration)
Set the desired reference point.
Parameters
I_R_F Rotation between the link and the inertial frame.
angularVelocity angular velocity of the frame F wr.t. the inertial frame expressed in the inertial frame.
angularAcceleration angular acceleration of the frame F wr.t. the inertial frame expressed in the inertial frame.
Returns
True in case of success, false otherwise.
Definition at line 183 of file SO3Task.cpp.
setVariablesHandler()
bool SO3Task::setVariablesHandler (const System::VariablesHandler & variablesHandler) override virtual
Set the set of variables required by the task.
The variables are stored in the System::VariablesHandler.
Parameters
variablesHandler reference to a variables handler.
Note
The handler must contain a variable named as the parameter robot_acceleration_variable_name stored in the parameter handler. The variable represents the generalized acceleration of the robot, where the generalized robot acceleration is a vector containing the base spatial-acceleration (expressed in mixed representation) and the joints acceleration.
Returns
True in case of success, false otherwise.
Reimplemented from BipedalLocomotion::System::LinearTask.
Definition at line 19 of file SO3Task.cpp.
References BipedalLocomotion::System::VariablesHandler::getNumberOfVariables(), BipedalLocomotion::System::VariablesHandler::getVariable(), and BipedalLocomotion::log().
size()
std::size_t SO3Task::size () const override virtual
Get the size of the task.
(I.e the number of rows of the vector b)
Returns
the size of the task.
Implements BipedalLocomotion::System::LinearTask.
Definition at line 195 of file SO3Task.cpp.
type()
SO3Task::Type SO3Task::type () const override virtual
The SO3Task is an equality task.
Returns
the type of the task.
Implements BipedalLocomotion::System::LinearTask.
Definition at line 200 of file SO3Task.cpp.
update()
bool SO3Task::update () override virtual
Update the content of the element.
Returns
True in case of success, false otherwise.
Reimplemented from BipedalLocomotion::System::LinearTask.
Definition at line 149 of file SO3Task.cpp.
References BipedalLocomotion::log().
The documentation for this class was generated from the following files:
TSID/include/BipedalLocomotion/TSID/SO3Task.h
TSID/src/SO3Task.cpp