bipedal-locomotion-framework: BipedalLocomotion::GenericContainer::Vector< T >::Ref Class Reference
BipedalLocomotion::GenericContainer::Vector< T >::Ref Class Reference
The class ref is used a substitution to a classical reference to a Vector.
#include <BipedalLocomotion/GenericContainer/Vector.h>
Public Member Functions
Ref ()=delete
A reference cannot exist on its own.
Ref (BipedalLocomotion::GenericContainer::Vector< T >::Ref &other)
Copy constructor.
Ref (BipedalLocomotion::GenericContainer::Vector< T >::Ref &&other)
Move constructor.
Ref (BipedalLocomotion::GenericContainer::Vector< T > &other)
Constructor from a GenericContainer::Vector<T>&.
Ref (BipedalLocomotion::GenericContainer::Vector< T > &&other)
Constructor from a GenericContainer::Vector<T>&.
template<class Vector , typename = typename std::enable_if<!GenericContainer::is_vector<Vector>::value && !std::is_same<Vector, std::string>::value && GenericContainer::is_vector_ref_constructible<T,Vector>::value && !std::is_const_v<T> && !is_container_const<Vector>::value>::type>
Ref (Vector &input)
Constructor from another container.
template<class Vector , typename = typename std::enable_if<!GenericContainer::is_vector<Vector>::value && !std::is_same<Vector, std::string>::value && GenericContainer::is_vector_ref_constructible<T,Vector>::value && std::is_const_v<T>>::type>
Ref (const Vector &input)
Constructor from another container.
~Ref ()=default
Default constructor.
Ref operator= (const Ref &other)
Copy operator.
Ref operator= (Ref &&other)
Copy operator.
Public Member Functions inherited from BipedalLocomotion::GenericContainer::Vector< T >
Vector (iDynTree::Span< T > span, resize_function_type resizeLambda)
Constructor.
Vector (iDynTree::Span< T > span)
Constructor.
~Vector ()=default
Destructor.
Vector (const Vector< T > &other)=delete
Copy constructor.
Vector (Vector< T > &&other)
Move constructor.
bool clone (const Vector< T > &other)
Copies the content of the vector.
bool clone (iDynTree::Span< T > other)
Copies the content of the vector.
Vector< T > & operator= (const Vector< T > &other)
operator = Copies the content
Vector< T > & operator= (iDynTree::Span< T > other)
operator = Copies the content
Vector< T > & operator= (Vector< T > &&other)
Move operator = Copies the content.
bool resizeVector (index_type newSize)
resizeVector It resize the original vector (if possible)
void resize (index_type newSize)
resize It resize the original vector (if possible)
index_type size () const
size Get the size of the Vector
bool empty () const
empty Checks if the container is empty (zero size)
const_reference operator[] (index_type idx) const
operator [] Accessor
reference operator[] (index_type idx)
operator [] Accessor
vector_element_type getVal (index_type idx) const
getVal Accessor
bool setVal (index_type idx, vector_element_type val)
setVal Setter
const_reference at (index_type idx) const
at Accessor
reference at (index_type idx)
at Accessor
const_reference operator() (index_type idx) const
operator () Accessor
reference operator() (index_type idx)
operator () Accessor
pointer data () const
data Raw pointer to the data
iterator begin ()
begin Iterator
iterator end ()
end Iterator
const_iterator begin () const
begin Iterator
const_iterator end () const
end Iterator
const_iterator cbegin () const
cbegin Iterator
const_iterator cend () const
cend Iterator
reverse_iterator rbegin ()
rbegin Iterator to the first element of the reversed vector
reverse_iterator rend ()
rend Iterator to the element following the last element of the reversed vector.
const_reverse_iterator rbegin () const
rbegin Iterator to the first element of the reversed vector
const_reverse_iterator rend () const
rend Iterator to the element following the last element of the reversed vector.
const_reverse_iterator crbegin () const
crbegin Iterator to the first element of the reversed vector
const_reverse_iterator crend () const
crend Iterator to the element following the last element of the reversed vector.
eigen_map_type toEigen ()
Get an Eigen map corresponding to the current generic vector (see https://eigen.tuxfamily.org/dox/classEigen_1_1Map.html).
eigen_map_const_type toEigen () const
Get an Eigen const map corresponding to the current generic vector (see https://eigen.tuxfamily.org/dox/classEigen_1_1Map.html).
Additional Inherited Members
Public Types inherited from BipedalLocomotion::GenericContainer::Vector< T >
using vector_element_type = typename iDynTree::Span< T >::element_type
Utility aliases depending on the type T.
using value_type = typename iDynTree::Span< T >::value_type
using index_type = typename iDynTree::Span< T >::index_type
using pointer = typename iDynTree::Span< T >::pointer
using reference = typename iDynTree::Span< T >::reference
using const_reference = const value_type &
using size_type = typename iDynTree::Span< T >::size_type
using iterator = typename iDynTree::Span< T >::iterator
Utility aliases to define iterators.
using const_iterator = typename iDynTree::Span< T >::const_iterator
using reverse_iterator = typename iDynTree::Span< T >::reverse_iterator
using const_reverse_iterator = typename iDynTree::Span< T >::const_reverse_iterator
using resize_function_type = std::function< iDynTree::Span< T >(index_type)>
Alias for the type of lambda used to resize the original vector.
using eigen_map_type = typename Eigen::Map< Eigen::Matrix< T, Eigen::Dynamic, 1 > >
Alias to determine the output type of toEigen()
using eigen_map_const_type = typename Eigen::Map< const Eigen::Matrix< T, Eigen::Dynamic, 1 > >
Protected Member Functions inherited from BipedalLocomotion::GenericContainer::Vector< T >
Vector ()=default
The default constructor is private.
Protected Attributes inherited from BipedalLocomotion::GenericContainer::Vector< T >
iDynTree::Span< T > m_span
Span of the pointed vector.
resize_function_type m_resizeLambda
User specified lambda to resize the existing container.
Detailed Description
template<typename T>
class BipedalLocomotion::GenericContainer::Vector< T >::Ref
The class ref is used a substitution to a classical reference to a Vector.
The advantage of using this, is that custom vectors (all those supported by GenericContainer::Vector) can be implicitly casted to Ref. Ref does not allocate any memory in construction, hence can be used as a parameter to be passed by copy. The = operator clones the content. Ref inherits Vector<T>, hence it can be used as it was a Vector<T>.
Definition at line 905 of file Vector.h.
Constructor & Destructor Documentation
Ref() [1/7]
template<typename T > BipedalLocomotion::GenericContainer::Vector< T >::Ref::Ref () delete
A reference cannot exist on its own.
Ref() [2/7]
template<typename T > BipedalLocomotion::GenericContainer::Vector< T >::Ref::Ref (BipedalLocomotion::GenericContainer::Vector< T >::Ref & other) inline
Copy constructor.
Parameters
other The ref from which to copy the context.
Definition at line 918 of file Vector.h.
References BipedalLocomotion::GenericContainer::Vector< T >::m_resizeLambda, and BipedalLocomotion::GenericContainer::Vector< T >::m_span.
Ref() [3/7]
template<typename T > BipedalLocomotion::GenericContainer::Vector< T >::Ref::Ref (BipedalLocomotion::GenericContainer::Vector< T >::Ref && other) inline
Move constructor.
Parameters
other The ref from which to get the context.
Definition at line 928 of file Vector.h.
References BipedalLocomotion::GenericContainer::Vector< T >::m_resizeLambda, and BipedalLocomotion::GenericContainer::Vector< T >::m_span.
Ref() [4/7]
template<typename T > BipedalLocomotion::GenericContainer::Vector< T >::Ref::Ref (BipedalLocomotion::GenericContainer::Vector< T > & other) inline
Constructor from a GenericContainer::Vector<T>&.
Parameters
other The input vector from which the context is copied
Definition at line 938 of file Vector.h.
References BipedalLocomotion::GenericContainer::Vector< T >::m_resizeLambda, and BipedalLocomotion::GenericContainer::Vector< T >::m_span.
Ref() [5/7]
template<typename T > BipedalLocomotion::GenericContainer::Vector< T >::Ref::Ref (BipedalLocomotion::GenericContainer::Vector< T > && other) inline
Constructor from a GenericContainer::Vector<T>&.
Parameters
other The input vector from which the context is taken In principle, Ref should be the reference of a Vector<T> which should remain alive while Ref is alive. On the other hand, Vector<T> is only a pointer to some data which does not own. Hence, Ref can remain alive even if the Vector<T> is deleted, provided that the original container stays alive.
Definition at line 952 of file Vector.h.
References BipedalLocomotion::GenericContainer::Vector< T >::m_resizeLambda, and BipedalLocomotion::GenericContainer::Vector< T >::m_span.
Ref() [6/7]
template<typename T > template<class Vector , typename = typename std::enable_if<!GenericContainer::is_vector<Vector>::value && !std::is_same<Vector, std::string>::value && GenericContainer::is_vector_ref_constructible<T,Vector>::value && !std::is_const_v<T> && !is_container_const<Vector>::value>::type> BipedalLocomotion::GenericContainer::Vector< T >::Ref::Ref (Vector & input) inline
Constructor from another container.
This is used if:
the input container is not a GenericContainer::Vector, to avoid ambiguities with other constructors
the input container is not a string. This allows using Ref and string with overloaded methods.
a GenericContainer::Vector<T>::Ref can be constructed from the Container
T is not const
the input container is not const.
Definition at line 972 of file Vector.h.
References BipedalLocomotion::GenericContainer::Vector< T >::data(), BipedalLocomotion::GenericContainer::Vector< T >::m_resizeLambda, BipedalLocomotion::GenericContainer::Vector< T >::m_span, and BipedalLocomotion::GenericContainer::Vector< T >::size().
Ref() [7/7]
template<typename T > template<class Vector , typename = typename std::enable_if<!GenericContainer::is_vector<Vector>::value && !std::is_same<Vector, std::string>::value && GenericContainer::is_vector_ref_constructible<T,Vector>::value && std::is_const_v<T>>::type> BipedalLocomotion::GenericContainer::Vector< T >::Ref::Ref (const Vector & input) inline
Constructor from another container.
This is used if:
the input container is not a GenericContainer::Vector, to avoid ambiguities with other constructors
the input container is not a string. This allows using Ref and string with overloaded methods.
a GenericContainer::Vector<T>::Ref can be constructed from the Container
T is const.
Definition at line 1006 of file Vector.h.
References BipedalLocomotion::GenericContainer::Vector< T >::data(), BipedalLocomotion::GenericContainer::Vector< T >::m_resizeLambda, BipedalLocomotion::GenericContainer::Vector< T >::m_span, and BipedalLocomotion::GenericContainer::Vector< T >::size().
~Ref()
template<typename T > BipedalLocomotion::GenericContainer::Vector< T >::Ref::~Ref () default
Default constructor.
Member Function Documentation
operator=() [1/2]
template<typename T > Ref BipedalLocomotion::GenericContainer::Vector< T >::Ref::operator= (const Ref & other) inline
Copy operator.
Parameters
other The other Ref, from which the data is copied
Returns
A reference to the vector resulting from the copy.
Definition at line 1031 of file Vector.h.
operator=() [2/2]
template<typename T > Ref BipedalLocomotion::GenericContainer::Vector< T >::Ref::operator= (Ref && other) inline
Copy operator.
Parameters
other The other Ref, from which the data is copied
Returns
A reference to the vector resulting from the copy.
Definition at line 1041 of file Vector.h.
The documentation for this class was generated from the following file:
GenericContainer/include/BipedalLocomotion/GenericContainer/Vector.h