bipedal-locomotion-framework: BipedalLocomotion::Contacts::ContactPhaseList Class Reference
BipedalLocomotion::Contacts::ContactPhaseList Class Reference
The ContactPhaseList class computes the contact phases according to a bunch of input contact lists.
#include <BipedalLocomotion/Contacts/ContactPhaseList.h>
Public Types
using const_iterator = std::vector< ContactPhase >::const_iterator
Internal method to compute the phases.
using const_reverse_iterator = std::vector< ContactPhase >::const_reverse_iterator
Public Member Functions
ContactPhaseList ()=default
Constructor.
~ContactPhaseList ()=default
Destructor.
ContactPhaseList (const ContactPhaseList &other)
Copy constructor.
ContactPhaseList (ContactPhaseList &&other)=default
Move constructor.
ContactPhaseList & operator= (const ContactPhaseList &other)
Copy assignment operator.
ContactPhaseList & operator= (ContactPhaseList &&other)=default
Move assignment operator.
void setLists (const ContactListMap &contactLists)
Set the input lists.
bool setLists (const std::initializer_list< ContactList > &contactLists)
Set the input lists.
const ContactListMap & lists () const
A reference to the lists stored in this class.
const_iterator begin () const
Const iterator to the begin of the phases.
const_iterator cbegin () const
Const iterator to the begin of the phases.
const_reverse_iterator rbegin () const
Const reverse iterator to the the phases (basically starting from the last phase, going backward).
const_reverse_iterator crbegin () const
Const reverse iterator to the the phases (basically starting from the last phase, going backward).
const_iterator end () const
Return a const iterator to the end of the list.
const_iterator cend () const
Return a const iterator to the end of the list.
const_reverse_iterator rend () const
Return a const reverse iterator to the end of the list.
const_reverse_iterator crend () const
Return a const reverse iterator to the end of the list.
const ContactPhase & operator[] (size_t index) const
Access phases by index.
const_iterator firstPhase () const
A const iterator to the first phase.
const_iterator lastPhase () const
A const iterator to the last phase.
size_t size () const
Get the number of phases.
void clear ()
Clear the phases and the stored lists.
Detailed Description
The ContactPhaseList class computes the contact phases according to a bunch of input contact lists.
Warning
All the iterators stored inside the contact phases refer to the lists stored within this class, not the original input lists.
Definition at line 32 of file ContactPhaseList.h.
Member Typedef Documentation
const_iterator
using BipedalLocomotion::Contacts::ContactPhaseList::const_iterator = std::vector<ContactPhase>::const_iterator
Internal method to compute the phases.
Definition at line 43 of file ContactPhaseList.h.
Constructor & Destructor Documentation
ContactPhaseList() [1/3]
BipedalLocomotion::Contacts::ContactPhaseList::ContactPhaseList () default
Constructor.
Note
This definition is necessary because the Copy constructor and the Move constructor are manually defined.
~ContactPhaseList()
BipedalLocomotion::Contacts::ContactPhaseList::~ContactPhaseList () default
Destructor.
Note
This definition is necessary to satisfy the rule of five.
ContactPhaseList() [2/3]
ContactPhaseList::ContactPhaseList (const ContactPhaseList & other)
Copy constructor.
Parameters
other another ContactPhaseList.
Note
When the copy constructor operator is called the content of other.m_contactList will be copied in this->m_contactList, while this->m_phases will be regenerated using the content of this->m_contactList. Notice that Contacts::ContactPhase class stores an std::unordered_map<std::string, ContactList::const_iterator> called Contacts::ContactPhase::activeContacts. So copying the content of other.m_phases into this->m_phases is wrong since all the iterators stored inside the contact phases should refer to the lists stored within this class, not the original input lists.
Definition at line 16 of file ContactPhaseList.cpp.
References setLists().
ContactPhaseList() [3/3]
BipedalLocomotion::Contacts::ContactPhaseList::ContactPhaseList (ContactPhaseList && other) default
Move constructor.
Parameters
other another ContactPhaseList.
Note
This definition is necessary to satisfy the rule of five.
Member Function Documentation
begin()
ContactPhaseList::const_iterator ContactPhaseList::begin () const
Const iterator to the begin of the phases.
Definition at line 149 of file ContactPhaseList.cpp.
cbegin()
ContactPhaseList::const_iterator ContactPhaseList::cbegin () const
Const iterator to the begin of the phases.
Definition at line 154 of file ContactPhaseList.cpp.
Referenced by BipedalLocomotion::Planners::TimeVaryingDCMPlanner::computeTrajectory().
cend()
ContactPhaseList::const_iterator ContactPhaseList::cend () const
Return a const iterator to the end of the list.
This is only a placeholder, it does not reference any phase.
Definition at line 174 of file ContactPhaseList.cpp.
clear()
void ContactPhaseList::clear ()
Clear the phases and the stored lists.
Definition at line 209 of file ContactPhaseList.cpp.
References std::unordered_map< K, T >::clear().
crbegin()
ContactPhaseList::const_reverse_iterator ContactPhaseList::crbegin () const
Const reverse iterator to the the phases (basically starting from the last phase, going backward).
Definition at line 164 of file ContactPhaseList.cpp.
crend()
ContactPhaseList::const_reverse_iterator ContactPhaseList::crend () const
Return a const reverse iterator to the end of the list.
This is only a placeholder, it does not reference any phase.
Definition at line 184 of file ContactPhaseList.cpp.
end()
ContactPhaseList::const_iterator ContactPhaseList::end () const
Return a const iterator to the end of the list.
This is only a placeholder, it does not reference any phase.
Definition at line 169 of file ContactPhaseList.cpp.
firstPhase()
ContactPhaseList::const_iterator ContactPhaseList::firstPhase () const
A const iterator to the first phase.
Definition at line 194 of file ContactPhaseList.cpp.
Referenced by BipedalLocomotion::Contacts::FixedFootDetector::setContactPhaseList().
lastPhase()
ContactPhaseList::const_iterator ContactPhaseList::lastPhase () const
A const iterator to the last phase.
Definition at line 199 of file ContactPhaseList.cpp.
Referenced by BipedalLocomotion::Planners::TimeVaryingDCMPlanner::computeTrajectory().
lists()
const BipedalLocomotion::Contacts::ContactListMap & BipedalLocomotion::Contacts::ContactPhaseList::lists () const
A reference to the lists stored in this class.
Warning
All the iterators stored inside the contact phases refer to the lists viewable via this method.
Returns
A const reference to the input lists.
Definition at line 144 of file ContactPhaseList.cpp.
Referenced by BipedalLocomotion::Contacts::FixedFootDetector::setContactPhaseList().
operator=() [1/2]
ContactPhaseList & ContactPhaseList::operator= (const ContactPhaseList & other)
Copy assignment operator.
Parameters
other another ContactPhaseList.
Note
When the copy assignment operator is called the content of other.m_contactList will be copied in this->m_contactList, while this->m_phases will be regenerated using the content of this->m_contactList. Notice that Contacts::ContactPhase class stores an std::unordered_map<std::string, ContactList::const_iterator> called Contacts::ContactPhase::activeContacts. So copying the content of other.m_phases into this->m_phases is wrong since all the iterators stored inside the contact phases should refer to the lists stored within this class, not the original input lists.
Definition at line 21 of file ContactPhaseList.cpp.
References setLists().
operator=() [2/2]
ContactPhaseList& BipedalLocomotion::Contacts::ContactPhaseList::operator= (ContactPhaseList && other) default
Move assignment operator.
Parameters
other another ContactPhaseList.
Note
This definition is necessary to satisfy the rule of five.
operator[]()
const ContactPhase & ContactPhaseList::operator[] (size_t index) const
Access phases by index.
Parameters
index of the phase to be accessed.
Returns
A const reference to the desired phase.
Definition at line 189 of file ContactPhaseList.cpp.
rbegin()
ContactPhaseList::const_reverse_iterator ContactPhaseList::rbegin () const
Const reverse iterator to the the phases (basically starting from the last phase, going backward).
Definition at line 159 of file ContactPhaseList.cpp.
rend()
ContactPhaseList::const_reverse_iterator ContactPhaseList::rend () const
Return a const reverse iterator to the end of the list.
This is only a placeholder, it does not reference any phase.
Definition at line 179 of file ContactPhaseList.cpp.
setLists() [1/2]
void ContactPhaseList::setLists (const ContactListMap & contactLists)
Set the input lists.
Parameters
contactLists The set of lists to be used for computing the phases.
Definition at line 117 of file ContactPhaseList.cpp.
Referenced by ContactPhaseList(), and operator=().
setLists() [2/2]
bool ContactPhaseList::setLists (const std::initializer_list< ContactList > & contactLists)
Set the input lists.
Parameters
An initializer list (use as {list1, list2, ...,listN}) to the lists to be used for computing the phases. A ContactListMap will be created with the provided list, using the defaultName as a key.
Returns
False if some lists have the same defaultName.
Definition at line 123 of file ContactPhaseList.cpp.
References std::unordered_map< K, T >::clear(), std::unordered_map< K, T >::insert(), and BipedalLocomotion::log().
size()
size_t ContactPhaseList::size () const
Get the number of phases.
Definition at line 204 of file ContactPhaseList.cpp.
The documentation for this class was generated from the following files:
Contacts/include/BipedalLocomotion/Contacts/ContactPhaseList.h
Contacts/src/ContactPhaseList.cpp