bipedal-locomotion-framework: BipedalLocomotion::Estimators::FloatingBaseEstimator Class Reference
BipedalLocomotion::Estimators::FloatingBaseEstimator Class Reference
FloatingBaseEstimator class contains the bare-bones implementation for a LeggedOdometry based or Extended Kalman Filter based floating base estimation algorithms for bipedal robots.
#include <BipedalLocomotion/FloatingBaseEstimators/FloatingBaseEstimator.h>
Data Structures
class ModelComputations
iDynTree based model-specific computations class This is class is used in a required configuration step for the estimator All the model related kinematics and dynamics computations specific to the floating base estimator are contained within this class.
Public Member Functions
bool initialize (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler, std::shared_ptr< iDynTree::KinDynComputations > kindyn)
Configure generic parameters and the model.
bool initialize (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler)
Configure generic parameters, calling this overloaded method assumes model information is not going to be used.
bool setIMUMeasurement (const Eigen::Vector3d &accMeas, const Eigen::Vector3d &gyroMeas)
Set the polled IMU measurement.
bool setContacts (const bool &lfInContact, const bool &rfInContact)
Set feet contact states.
bool setContactStatus (const std::string &name, const bool &contactStatus, const double &switchTime, double timeNow=0.)
Set contact status.
bool setKinematics (const Eigen::VectorXd &encoders, const Eigen::VectorXd &encoderSpeeds)
Set kinematic measurements.
bool setLandmarkRelativePose (const int &landmarkID, const Eigen::Quaterniond &quat, const Eigen::Vector3d &pos, const double &timeNow)
Set the relative pose of a landmark relative to the base link.
virtual bool advance () final
Compute one step of the estimator.
virtual bool resetEstimator (const FloatingBaseEstimators::InternalState &newState)
Reset the internal state of the estimator.
virtual bool resetEstimator (const Eigen::Quaterniond &newBaseOrientation, const Eigen::Vector3d &newBasePosition)
Reset the base pose estimate and consequently the internal state of the estimator.
virtual const FloatingBaseEstimators::Output & getOutput () const final
Get estimator outputs.
virtual bool isOutputValid () const final
Determines the validity of the object retrieved with get()
ModelComputations & modelComputations ()
Get ModelComputations object by reference.
Public Member Functions inherited from BipedalLocomotion::System::Source< FloatingBaseEstimators::Output >
bool setInput (const EmptySignal &input) final
Get the object.
Public Member Functions inherited from BipedalLocomotion::System::Advanceable< EmptySignal, FloatingBaseEstimators::Output >
virtual const Output & getOutput () const=0
Get the output of the advanceable.
virtual bool isOutputValid () const=0
Determines the validity of the object retrieved with getOutput()
virtual bool close ()
Close the Advanceable.
Protected Types
enum State { State::NotInitialized, State::Initialized, State::Running }
Enumerator used to determine the running state of the estimator.
Protected Member Functions
virtual bool customInitialization (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler)
These custom parameter specifications should be specified by the derived class.
virtual bool predictState (const FloatingBaseEstimators::Measurements &meas, const double &dt)
Propagate the states through the prediction model, if there exists any (eg.
virtual bool updateKinematics (FloatingBaseEstimators::Measurements &meas, const double &dt)
Update the predicted state estimates using kinematics and contact measurements.
virtual bool updateLandmarkRelativePoses (FloatingBaseEstimators::Measurements &meas, const double &dt)
Update the predicted state estimates using relative pose measurements of static landmarks in the environment.
bool updateBaseStateFromIMUState (const FloatingBaseEstimators::InternalState &state, const FloatingBaseEstimators::Measurements &meas, manif::SE3d &basePose, Eigen::Ref< Eigen::Matrix< double, 6, 1 >> baseTwist)
Wrapper method for getting base state from internal IMU state.
bool setupOptions (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler)
Setup estimator options.
bool setupSensorDevs (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler)
Setup measurement noise standard deviations The parameters in the SensorsStdDev group are,.
bool setupInitialStates (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler)
Setup initial states.
bool setupPriorDevs (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler)
Setup initial state standard deviations.
Protected Attributes
ModelComputations m_modelComp
Model computations object.
FloatingBaseEstimators::Options m_options
Struct holding estimator options.
FloatingBaseEstimators::Measurements m_meas
FloatingBaseEstimators::Measurements m_measPrev
Struct holding the latest measurements that were set to the estimator.
FloatingBaseEstimators::InternalState m_state
FloatingBaseEstimators::InternalState m_statePrev
Structs holding the curent and previous internal states of the estimation algorithm.
FloatingBaseEstimators::Output m_estimatorOut
Struct holding outputs of the estimator.
FloatingBaseEstimators::StateStdDev m_priors
FloatingBaseEstimators::StateStdDev m_stateStdDev
Struct holding standard deviations associated to prior state estimates.
FloatingBaseEstimators::SensorsStdDev m_sensorsDev
Struct holding standard deviations associated to sensor measurements.
State m_estimatorState {State::NotInitialized}
State of the estimator.
double m_dt {0.01}
Fixed time step of the estimator, in seconds.
bool m_useIMUForAngVelEstimate {true}
Use IMU measurements as internal state imu angular velocity by default set to true for strap down IMU based EKF implementations, if IMU measurements not used, corresponding impl can set to false.
bool m_useIMUVelForBaseVelComputation {true}
Compute base velocity using inertnal state IMU velocity.
bool m_useModelInfo {true}
Flag to enable running the estimator without using the URDF model information.
bool m_isInvEKF {false}
Flag to maintain soon to be deprecated functionalities currently existing only in InvEKFBaseEstimator.
Additional Inherited Members
Public Types inherited from BipedalLocomotion::System::Advanceable< EmptySignal, FloatingBaseEstimators::Output >
using Input = EmptySignal
using Output = FloatingBaseEstimators::Output
Detailed Description
FloatingBaseEstimator class contains the bare-bones implementation for a LeggedOdometry based or Extended Kalman Filter based floating base estimation algorithms for bipedal robots.
Note
it is assumed that if an IMU (primary) is specified in the inherited implementation, then this IMU is rigidly attached to the specified base link in the implementation
Definition at line 32 of file FloatingBaseEstimator.h.
Member Enumeration Documentation
State
enum BipedalLocomotion::Estimators::FloatingBaseEstimator::State strong protected
Enumerator used to determine the running state of the estimator.
Enumerator
NotInitialized
The estimator is not initialized yet call FloatingBaseEstimator::initialze method to initialize it.
Initialized
The estimator is initialized and ready to be used.
Running
The estimator is running.
Definition at line 406 of file FloatingBaseEstimator.h.
Member Function Documentation
advance()
bool FloatingBaseEstimator::advance () final virtual
Compute one step of the estimator.
Returns
True in case of success, false otherwise.
Implements BipedalLocomotion::System::Advanceable< EmptySignal, FloatingBaseEstimators::Output >.
Definition at line 106 of file FloatingBaseEstimator.cpp.
References BipedalLocomotion::Estimators::FloatingBaseEstimators::Options::accelerationDueToGravity, BipedalLocomotion::Estimators::FloatingBaseEstimators::Output::basePose, BipedalLocomotion::Estimators::FloatingBaseEstimators::Output::baseTwist, std::map< K, T >::clear(), BipedalLocomotion::Estimators::FloatingBaseEstimators::Options::ekfUpdateEnabled, BipedalLocomotion::Estimators::FloatingBaseEstimators::Measurements::encodersSpeed, Initialized, BipedalLocomotion::Estimators::FloatingBaseEstimators::Options::kinematicsUpdateEnabled, BipedalLocomotion::log(), m_dt, m_estimatorOut, m_estimatorState, m_measPrev, m_modelComp, m_options, m_statePrev, m_stateStdDev, m_useModelInfo, BipedalLocomotion::Estimators::FloatingBaseEstimator::ModelComputations::nrJoints(), predictState(), Running, BipedalLocomotion::Estimators::FloatingBaseEstimators::Measurements::stampedContactsStatus, BipedalLocomotion::Estimators::FloatingBaseEstimators::Measurements::stampedRelLandmarkPoses, BipedalLocomotion::Estimators::FloatingBaseEstimators::Output::state, BipedalLocomotion::Estimators::FloatingBaseEstimators::Output::stateStdDev, BipedalLocomotion::Estimators::FloatingBaseEstimators::Options::staticLandmarksUpdateEnabled, updateBaseStateFromIMUState(), updateKinematics(), and updateLandmarkRelativePoses().
customInitialization()
virtual bool BipedalLocomotion::Estimators::FloatingBaseEstimator::customInitialization (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler) inline protected virtual
These custom parameter specifications should be specified by the derived class.
If setupOptions() is called from within customInitialization(), ensure the group "Options" exist. Please check the documentation of setupOptions() for relevant parameters
If setupSensorDevs() is called from within customInitialization(), ensure the group "SensorsStdDev" exist. Please check the documentation of setupSensorDevs() for relevant parameters
If setupInitialStates() is called from within customInitialization(), ensure the group "InitialStates" exist. Please check the documentation of setupInitialStates() for relevant parameters
If setupPriorDevs() is called from within customInitialization(), ensure the group "PriorsStdDev" exist. Please check the documentation of setupPriorDevs() for relevant parameters
Parameters
[in] handler configure the custom parameters for the estimator
Returns
bool
Reimplemented in BipedalLocomotion::Estimators::LeggedOdometry, and BipedalLocomotion::Estimators::InvariantEKFBaseEstimator.
Definition at line 284 of file FloatingBaseEstimator.h.
Referenced by initialize().
getOutput()
const FloatingBaseEstimators::Output & FloatingBaseEstimator::getOutput () const final virtual
Get estimator outputs.
Returns
A struct containing he estimated internal states of the estiamtor and the associated covariance matrix
Definition at line 412 of file FloatingBaseEstimator.cpp.
References m_estimatorOut.
initialize() [1/2]
bool FloatingBaseEstimator::initialize (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler) virtual
Configure generic parameters, calling this overloaded method assumes model information is not going to be used.
Parameters
[in] handler configure the generic parameters for the estimator
Returns
True in case of success, false otherwise.
Reimplemented from BipedalLocomotion::System::Advanceable< EmptySignal, FloatingBaseEstimators::Output >.
Definition at line 40 of file FloatingBaseEstimator.cpp.
References customInitialization(), Initialized, std::weak_ptr< T >::lock(), BipedalLocomotion::log(), m_dt, m_estimatorState, m_modelComp, m_useModelInfo, and NotInitialized.
initialize() [2/2]
bool FloatingBaseEstimator::initialize (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler, std::shared_ptr< iDynTree::KinDynComputations > kindyn)
Configure generic parameters and the model.
The generic parameters include,
sampling_period_in_s [PARAMETER|REQUIRED|Sampling period of the estimator in seconds]
ModelInfo [GROUP|REQUIRED|URDF Model specific parameters used by the estimator]
base_link [PARAMETER|REQUIRED|base link frame from the URDF model| Exists in "ModelInfo" GROUP]
base_link_imu [PARAMETER|REQUIRED|IMU frame rigidly attached to thebase link from the URDF model| Exists in "ModelInfo" GROUP]
left_foot_contact_frame [PARAMETER|REQUIRED|left foot contact frame from the URDF model| Exists in "ModelInfo" GROUP]
right_foot_contact_frame [PARAMETER|REQUIRED|right foot contact frame from the URDF model| Exists in "ModelInfo" GROUP]
Parameters
[in] handler configure the generic parameters for the estimator
[in] kindyn shared pointer of iDynTree kindyncomputations object (model will be loaded internally)
Note
any custom initialization of parameters or the algorithm implementation is not done here, it must be done in customInitialization() by the child class implementing the algorithm
Returns
True in case of success, false otherwise.
Definition at line 22 of file FloatingBaseEstimator.cpp.
References BipedalLocomotion::log(), m_modelComp, and BipedalLocomotion::Estimators::FloatingBaseEstimator::ModelComputations::setKinDynObject().
isOutputValid()
virtual bool BipedalLocomotion::Estimators::FloatingBaseEstimator::isOutputValid () const inline final virtual
Determines the validity of the object retrieved with get()
Returns
True in case of success, false otherwise.
Definition at line 261 of file FloatingBaseEstimator.h.
References m_estimatorState, and Running.
modelComputations()
FloatingBaseEstimator::ModelComputations & FloatingBaseEstimator::modelComputations ()
Get ModelComputations object by reference.
Returns
ModelComputations object providing information between considered model related quantities in the estimator like the base link, IMU, feet contact frames.
Definition at line 406 of file FloatingBaseEstimator.cpp.
References m_modelComp.
Referenced by setKinematics().
predictState()
virtual bool BipedalLocomotion::Estimators::FloatingBaseEstimator::predictState (const FloatingBaseEstimators::Measurements & meas, const double & dt) inline protected virtual
Propagate the states through the prediction model, if there exists any (eg.
a strap-down IMU model)
Parameters
[in] meas measurements passed as exogeneous inputs to the prediction model
[in] dt sampling period in seconds
[out] state previous state estimate
[out] P previous state covariance matrix
Returns
True in case of success, false otherwise.
Reimplemented in BipedalLocomotion::Estimators::InvariantEKFBaseEstimator.
Definition at line 294 of file FloatingBaseEstimator.h.
Referenced by advance().
resetEstimator() [1/2]
bool FloatingBaseEstimator::resetEstimator (const Eigen::Quaterniond & newBaseOrientation, const Eigen::Vector3d & newBasePosition) virtual
Reset the base pose estimate and consequently the internal state of the estimator.
Parameters
[in] newBaseOrientation base link orientation as a Eigen quaternion
[in] newBasePosition base link position
Returns
True in case of success, false otherwise.
Note
reset and advance estimator to get updated estimator output
Definition at line 837 of file FloatingBaseEstimator.cpp.
References BipedalLocomotion::Estimators::FloatingBaseEstimator::ModelComputations::getIMU_H_feet(), BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::imuOrientation, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::imuPosition, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::lContactFrameOrientation, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::lContactFramePosition, BipedalLocomotion::log(), m_modelComp, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::rContactFrameOrientation, and BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::rContactFramePosition.
resetEstimator() [2/2]
bool FloatingBaseEstimator::resetEstimator (const FloatingBaseEstimators::InternalState & newState) virtual
Reset the internal state of the estimator.
Parameters
[in] newState Internal state of the estimator
Returns
True in case of success, false otherwise.
Note
reset and advance estimator to get updated estimator output
Definition at line 864 of file FloatingBaseEstimator.cpp.
setContacts()
bool FloatingBaseEstimator::setContacts (const bool & lfInContact, const bool & rfInContact)
Set feet contact states.
Parameters
[in] lfInContact left foot contact state [0, 1]
[in] rfInContact right foot contact state [0, 1]
Returns
True in case of success, false otherwise.
Definition at line 358 of file FloatingBaseEstimator.cpp.
References BipedalLocomotion::Estimators::FloatingBaseEstimators::Measurements::lfInContact, and BipedalLocomotion::Estimators::FloatingBaseEstimators::Measurements::rfInContact.
setContactStatus()
bool FloatingBaseEstimator::setContactStatus (const std::string & name, const bool & contactStatus, const double & switchTime, double timeNow = 0.)
Set contact status.
Parameters
[in] name contact frame name
[in] contactStatus flag to check active contact
[in] switchTime time of switching contact
[in] timeNow current measurement update time
Definition at line 366 of file FloatingBaseEstimator.cpp.
References BipedalLocomotion::log(), m_modelComp, and BipedalLocomotion::Estimators::FloatingBaseEstimators::Measurements::stampedContactsStatus.
setIMUMeasurement()
bool FloatingBaseEstimator::setIMUMeasurement (const Eigen::Vector3d & accMeas, const Eigen::Vector3d & gyroMeas)
Set the polled IMU measurement.
Parameters
[in] accMeas linear accelerometer measurement expressed in the local IMU frame (m/s^2)
[in] gyroMeas gyroscope measurement expressed in the local IMU frame (rad/s)
Returns
True in case of success, false otherwise.
Definition at line 332 of file FloatingBaseEstimator.cpp.
References BipedalLocomotion::Estimators::FloatingBaseEstimators::Measurements::gyro.
setKinematics()
bool FloatingBaseEstimator::setKinematics (const Eigen::VectorXd & encoders, const Eigen::VectorXd & encoderSpeeds)
Set kinematic measurements.
Note
it is assumed that the order of the joints loaded in the model and the order of the measurements in these vectors match
Parameters
[in] encoders joint positions measured through encoders
[in] encoderSpeeds joint velocities measured through encoders
Returns
True in case of success, false otherwise.
Definition at line 342 of file FloatingBaseEstimator.cpp.
References BipedalLocomotion::Estimators::FloatingBaseEstimators::Measurements::encodersSpeed, BipedalLocomotion::log(), and modelComputations().
setLandmarkRelativePose()
bool FloatingBaseEstimator::setLandmarkRelativePose (const int & landmarkID, const Eigen::Quaterniond & quat, const Eigen::Vector3d & pos, const double & timeNow)
Set the relative pose of a landmark relative to the base link.
Parameters
[in] landmarkID unique landmark ID
[in] quat relative orientation of the landmark as a quaternion
[in] pos relative position of the landmark
[in] timeNow relative position of the landmark
Returns
true in case of success, false otherwise
Definition at line 392 of file FloatingBaseEstimator.cpp.
References BipedalLocomotion::Estimators::FloatingBaseEstimators::Measurements::stampedRelLandmarkPoses.
setupInitialStates()
bool FloatingBaseEstimator::setupInitialStates (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler) protected
Setup initial states.
The parameters in the InitialStates group are,
imu_orientation_quaternion_wxyz [PARAMETER|REQUIRED|Initial IMU orientation wrt inertial frame, as a quaternion]
imu_position_xyz [PARAMETER|REQUIRED|Initial IMU position wrt inertial frame]
imu_linear_velocity_xyz [PARAMETER|REQUIRED|Initial IMU linear velocity wrt inertial frame, in a mixed-velocity representation]
l_contact_frame_orientation_quaternion_wxyz [PARAMETER|REQUIRED|Initial left foot contact frame orientation wrt inertial frame, as a quaternion]
l_contact_frame_position_xyz [PARAMETER|REQUIRED|Initial left foot contact frame position wrt inertial frame]
r_contact_frame_orientation_quaternion_wxyz [PARAMETER|REQUIRED|Initial right foot contact frame orientation wrt inertial frame, as a quaternion]
r_contact_frame_position_xyz [PARAMETER|REQUIRED|Initial right foot contact frame position wrt inertial frame]
accelerometer_bias [PARAMETER|REQUIRED, if imuBiasEstimationEnabled is set to true|Initial accelerometer bias expressed in IMU frame]
gyroscope_bias [PARAMETER|REQUIRED, if imuBiasEstimationEnabled is set to true|Initial gyroscope bias expressed in IMU frame]
Note
this is a recipe method that can be called by the derived class from within customInitialization()
ensure to call setupOptions() before calling setupInitialStates() to handle bias related parameters to be configured properly
Parameters
[in] handler parameter handler
Returns
True in case of success, false otherwise.
Definition at line 636 of file FloatingBaseEstimator.cpp.
References BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::accelerometerBias, BipedalLocomotion::Estimators::FloatingBaseEstimators::Output::basePose, BipedalLocomotion::Estimators::FloatingBaseEstimators::Output::baseTwist, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::gyroscopeBias, BipedalLocomotion::Estimators::FloatingBaseEstimators::Options::imuBiasEstimationEnabled, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::imuLinearVelocity, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::imuOrientation, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::imuPosition, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::lContactFrameOrientation, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::lContactFramePosition, std::weak_ptr< T >::lock(), BipedalLocomotion::log(), m_estimatorOut, m_isInvEKF, m_measPrev, m_options, m_statePrev, m_useModelInfo, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::rContactFrameOrientation, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::rContactFramePosition, and updateBaseStateFromIMUState().
Referenced by BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::customInitialization().
setupOptions()
bool FloatingBaseEstimator::setupOptions (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler) protected
Setup estimator options.
The parameters in the Options group are,
enable_imu_bias_estimation [PARAMETER|-|Enable/disable IMU bias estimation]
enable_static_imu_bias_initialization [PARAMETER|-|Enable/disable IMU bias initialization assuming static configuration]
nr_samples_for_imu_bias_initialization [PARAMETER|REQUIRED, if staticImuBiasInitializationEnabled is set to true|Number of samples for static bias initialization]
enable_ekf_update [PARAMETER|-|Enable/disable update step of EKF (not recommended to set to false)]
acceleration_due_to_gravity [PARAMETER|-|Acceleration due to gravity, 3d vector]
Note
this is a recipe method that can be called by the derived class from within customInitialization()
Parameters
[in] handler parameter handler
Returns
True in case of success, false otherwise.
Definition at line 473 of file FloatingBaseEstimator.cpp.
References BipedalLocomotion::Estimators::FloatingBaseEstimators::Options::accelerationDueToGravity, BipedalLocomotion::Estimators::FloatingBaseEstimators::Options::ekfUpdateEnabled, std::endl(), BipedalLocomotion::Estimators::FloatingBaseEstimators::Options::imuBiasEstimationEnabled, BipedalLocomotion::Estimators::FloatingBaseEstimators::Options::kinematicsUpdateEnabled, std::weak_ptr< T >::lock(), BipedalLocomotion::log(), m_options, BipedalLocomotion::Estimators::FloatingBaseEstimators::Options::nrSamplesForImuBiasInitialization, std::vector< T >::resize(), BipedalLocomotion::Estimators::FloatingBaseEstimators::Options::staticImuBiasInitializationEnabled, and BipedalLocomotion::Estimators::FloatingBaseEstimators::Options::staticLandmarksUpdateEnabled.
Referenced by BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::customInitialization().
setupPriorDevs()
bool FloatingBaseEstimator::setupPriorDevs (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler) protected
Setup initial state standard deviations.
The parameters in the PriorsStdDev group are,
imu_orientation_quaternion_wxyz [PARAMETER|REQUIRED|Initial IMU orientation as wrt inertial frame]
imu_position [PARAMETER|REQUIRED|Initial IMU position deviation wrt inertial frame]
imu_linear_velocity [PARAMETER|REQUIRED|Initial IMU linear velocity deviation wrt inertial frame, in a mixed-velocity representation]
l_contact_frame_orientation_quaternion [PARAMETER|REQUIRED|Initial left foot contact frame orientation deviation wrt inertial frame]
l_contact_frame_position [PARAMETER|REQUIRED|Initial left foot contact frame position deviation wrt inertial frame]
r_contact_frame_orientation_quaternion [PARAMETER|REQUIRED|Initial right foot contact frame orientation deviation wrt inertial frame]
r_contact_frame_position [PARAMETER|REQUIRED|Initial right foot contact frame position deviation wrt inertial frame]
accelerometer_bias [PARAMETER|REQUIRED, if imuBiasEstimationEnabled is set to true|Initial accelerometer bias devitaion expressed in IMU frame]
gyroscope_bias [PARAMETER|REQUIRED, if imuBiasEstimationEnabled is set to true|Initial gyroscope bias deviation expressed in IMU frame]
Note
this is a recipe method that can be called by the derived class from within customInitialization()
ensure to call setupOptions() before calling setupPriorDevs() to handle bias related parameters to be configured properly
Parameters
[in] handler parameter handler
Returns
True in case of success, false otherwise.
Definition at line 711 of file FloatingBaseEstimator.cpp.
References BipedalLocomotion::Estimators::FloatingBaseEstimators::StateStdDev::accelerometerBias, BipedalLocomotion::Estimators::FloatingBaseEstimators::StateStdDev::gyroscopeBias, BipedalLocomotion::Estimators::FloatingBaseEstimators::Options::imuBiasEstimationEnabled, BipedalLocomotion::Estimators::FloatingBaseEstimators::StateStdDev::imuLinearVelocity, BipedalLocomotion::Estimators::FloatingBaseEstimators::StateStdDev::imuOrientation, BipedalLocomotion::Estimators::FloatingBaseEstimators::StateStdDev::imuPosition, BipedalLocomotion::Estimators::FloatingBaseEstimators::StateStdDev::lContactFrameOrientation, BipedalLocomotion::Estimators::FloatingBaseEstimators::StateStdDev::lContactFramePosition, std::weak_ptr< T >::lock(), BipedalLocomotion::log(), m_isInvEKF, m_options, m_useModelInfo, BipedalLocomotion::Estimators::FloatingBaseEstimators::StateStdDev::rContactFrameOrientation, and BipedalLocomotion::Estimators::FloatingBaseEstimators::StateStdDev::rContactFramePosition.
Referenced by BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::customInitialization().
setupSensorDevs()
bool FloatingBaseEstimator::setupSensorDevs (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler) protected
Setup measurement noise standard deviations The parameters in the SensorsStdDev group are,.
accelerometer_measurement_noise_std_dev [PARAMETER|REQUIRED|Accelerometer measurement white noise deviation]
gyroscope_measurement_noise_std_dev [PARAMETER|REQUIRED|Gyroscope measurement white noise deviation]
accelerometer_measurement_bias_noise_std_dev [PARAMETER|REQUIRED, if imuBiasEstimationEnabled is set to true|Accelerometer measurement bias noise deviation]
gyroscope_measurement_bias_noise_std_dev [PARAMETER|REQUIRED, if imuBiasEstimationEnabled is set to true|Gyroscope measurement bias noise deviation]
contact_foot_linear_velocity_noise_std_dev [PARAMETER|REQUIRED|Linear velocity white noise deviation when foot is in contact]
contact_foot_angular_velocity_noise_std_dev [PARAMETER|REQUIRED|Angular velocity white noise deviation when foot is in contact]
swing_foot_linear_velocity_noise_std_dev [PARAMETER|REQUIRED|Linear velocity white noise deviation when foot is swinging off contact]
swing_foot_angular_velocity_noise_std_dev [PARAMETER|REQUIRED|Angular velocity white noise deviation when foot is swinging off contact]
forward_kinematic_measurement_noise_std_dev [PARAMETER|REQUIRED|White noise deviation in relative poses computed through forward kinematics]
encoders_measurement_noise_std_dev [PARAMETER|REQUIRED|Encoder measurement white noise deviation]
Note
this is a recipe method that can be called by the derived class from within customInitialization()
ensure to call setupOptions() before calling setupSensorDevs() to handle bias related parameters to be configured properly
Parameters
[in] handler parameter handler
Returns
True in case of success, false otherwise.
Definition at line 552 of file FloatingBaseEstimator.cpp.
References BipedalLocomotion::Estimators::FloatingBaseEstimators::SensorsStdDev::accelerometerBiasNoise, BipedalLocomotion::Estimators::FloatingBaseEstimators::SensorsStdDev::accelerometerNoise, BipedalLocomotion::Estimators::FloatingBaseEstimators::SensorsStdDev::contactFootAngvelNoise, BipedalLocomotion::Estimators::FloatingBaseEstimators::SensorsStdDev::contactFootLinvelNoise, std::vector< T >::data(), BipedalLocomotion::Estimators::FloatingBaseEstimators::SensorsStdDev::encodersNoise, BipedalLocomotion::Estimators::FloatingBaseEstimators::SensorsStdDev::forwardKinematicsNoise, BipedalLocomotion::Estimators::FloatingBaseEstimators::SensorsStdDev::gyroscopeBiasNoise, BipedalLocomotion::Estimators::FloatingBaseEstimators::SensorsStdDev::gyroscopeNoise, BipedalLocomotion::Estimators::FloatingBaseEstimators::Options::imuBiasEstimationEnabled, BipedalLocomotion::Estimators::FloatingBaseEstimators::SensorsStdDev::landmarkMeasurementNoise, BipedalLocomotion::Estimators::FloatingBaseEstimators::SensorsStdDev::landmarkPredictionNoise, std::weak_ptr< T >::lock(), BipedalLocomotion::log(), m_modelComp, m_options, m_sensorsDev, m_useModelInfo, BipedalLocomotion::Estimators::FloatingBaseEstimator::ModelComputations::nrJoints(), std::vector< T >::size(), BipedalLocomotion::Estimators::FloatingBaseEstimators::Options::staticLandmarksUpdateEnabled, BipedalLocomotion::Estimators::FloatingBaseEstimators::SensorsStdDev::swingFootAngvelNoise, and BipedalLocomotion::Estimators::FloatingBaseEstimators::SensorsStdDev::swingFootLinvelNoise.
Referenced by BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::customInitialization().
updateBaseStateFromIMUState()
bool FloatingBaseEstimator::updateBaseStateFromIMUState (const FloatingBaseEstimators::InternalState & state, const FloatingBaseEstimators::Measurements & meas, manif::SE3d & basePose, Eigen::Ref< Eigen::Matrix< double, 6, 1 >> baseTwist) protected
Wrapper method for getting base state from internal IMU state.
Parameters
[in] state internal state of the estimator
[in] meas previous measurement to the estimator
[in] basePose base pose as an iDynTree Transform object
[in] baseTwist mixe- trivialized base velocity as an iDynTree Twist object
Definition at line 795 of file FloatingBaseEstimator.cpp.
References BipedalLocomotion::Estimators::FloatingBaseEstimator::ModelComputations::getBaseStateFromIMUState(), BipedalLocomotion::Estimators::FloatingBaseEstimators::Measurements::gyro, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::gyroscopeBias, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::imuAngularVelocity, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::imuLinearVelocity, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::imuOrientation, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::imuPosition, BipedalLocomotion::log(), m_modelComp, m_useIMUForAngVelEstimate, m_useIMUVelForBaseVelComputation, and m_useModelInfo.
Referenced by advance(), and setupInitialStates().
updateKinematics()
virtual bool BipedalLocomotion::Estimators::FloatingBaseEstimator::updateKinematics (FloatingBaseEstimators::Measurements & meas, const double & dt) inline protected virtual
Update the predicted state estimates using kinematics and contact measurements.
Parameters
[in] meas measurements to update the predicted states
[in] dt sampling period in seconds
Returns
True in case of success, false otherwise.
Reimplemented in BipedalLocomotion::Estimators::LeggedOdometry, and BipedalLocomotion::Estimators::InvariantEKFBaseEstimator.
Definition at line 303 of file FloatingBaseEstimator.h.
Referenced by advance().
updateLandmarkRelativePoses()
virtual bool BipedalLocomotion::Estimators::FloatingBaseEstimator::updateLandmarkRelativePoses (FloatingBaseEstimators::Measurements & meas, const double & dt) inline protected virtual
Update the predicted state estimates using relative pose measurements of static landmarks in the environment.
Parameters
[in] meas measurements to update the predicted states
[in] dt sampling period in seconds
Returns
True in case of success, false otherwise.
Definition at line 312 of file FloatingBaseEstimator.h.
Referenced by advance().
Field Documentation
m_dt
double BipedalLocomotion::Estimators::FloatingBaseEstimator::m_dt {0.01} protected
Fixed time step of the estimator, in seconds.
Definition at line 416 of file FloatingBaseEstimator.h.
Referenced by advance(), and initialize().
m_estimatorOut
FloatingBaseEstimators::Output BipedalLocomotion::Estimators::FloatingBaseEstimator::m_estimatorOut protected
Struct holding outputs of the estimator.
Definition at line 399 of file FloatingBaseEstimator.h.
Referenced by advance(), getOutput(), BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::InvariantEKFBaseEstimator(), BipedalLocomotion::Estimators::LeggedOdometry::LeggedOdometry(), and setupInitialStates().
m_estimatorState
State BipedalLocomotion::Estimators::FloatingBaseEstimator::m_estimatorState {State::NotInitialized} protected
State of the estimator.
Definition at line 414 of file FloatingBaseEstimator.h.
Referenced by advance(), initialize(), and isOutputValid().
m_isInvEKF
bool BipedalLocomotion::Estimators::FloatingBaseEstimator::m_isInvEKF {false} protected
Flag to maintain soon to be deprecated functionalities currently existing only in InvEKFBaseEstimator.
Definition at line 420 of file FloatingBaseEstimator.h.
Referenced by BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::InvariantEKFBaseEstimator(), setupInitialStates(), and setupPriorDevs().
m_measPrev
FloatingBaseEstimators::Measurements BipedalLocomotion::Estimators::FloatingBaseEstimator::m_measPrev protected
Struct holding the latest measurements that were set to the estimator.
Definition at line 397 of file FloatingBaseEstimator.h.
Referenced by advance(), BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::InvariantEKFBaseEstimator(), BipedalLocomotion::Estimators::LeggedOdometry::LeggedOdometry(), and setupInitialStates().
m_modelComp
ModelComputations BipedalLocomotion::Estimators::FloatingBaseEstimator::m_modelComp protected
Model computations object.
Definition at line 395 of file FloatingBaseEstimator.h.
Referenced by advance(), BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::customInitialization(), BipedalLocomotion::Estimators::LeggedOdometry::customInitialization(), initialize(), modelComputations(), BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::predictState(), resetEstimator(), setContactStatus(), setupSensorDevs(), updateBaseStateFromIMUState(), and BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::updateKinematics().
m_options
FloatingBaseEstimators::Options BipedalLocomotion::Estimators::FloatingBaseEstimator::m_options protected
Struct holding estimator options.
Definition at line 396 of file FloatingBaseEstimator.h.
Referenced by advance(), BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::customInitialization(), BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::predictState(), BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::resetEstimator(), setupInitialStates(), setupOptions(), setupPriorDevs(), setupSensorDevs(), BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::toggleBiasEstimation(), BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::toggleEKFUpdate(), and BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::updateKinematics().
m_sensorsDev
FloatingBaseEstimators::SensorsStdDev BipedalLocomotion::Estimators::FloatingBaseEstimator::m_sensorsDev protected
Struct holding standard deviations associated to sensor measurements.
Definition at line 401 of file FloatingBaseEstimator.h.
Referenced by BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::InvariantEKFBaseEstimator(), BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::predictState(), BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::resetEstimator(), setupSensorDevs(), and BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::updateKinematics().
m_statePrev
FloatingBaseEstimators::InternalState BipedalLocomotion::Estimators::FloatingBaseEstimator::m_statePrev protected
Structs holding the curent and previous internal states of the estimation algorithm.
Definition at line 398 of file FloatingBaseEstimator.h.
Referenced by advance(), BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::InvariantEKFBaseEstimator(), BipedalLocomotion::Estimators::LeggedOdometry::LeggedOdometry(), BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::predictState(), and setupInitialStates().
m_stateStdDev
FloatingBaseEstimators::StateStdDev BipedalLocomotion::Estimators::FloatingBaseEstimator::m_stateStdDev protected
Struct holding standard deviations associated to prior state estimates.
Definition at line 400 of file FloatingBaseEstimator.h.
Referenced by advance(), BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::InvariantEKFBaseEstimator(), BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::predictState(), BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::resetEstimator(), and BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::updateKinematics().
m_useIMUForAngVelEstimate
bool BipedalLocomotion::Estimators::FloatingBaseEstimator::m_useIMUForAngVelEstimate {true} protected
Use IMU measurements as internal state imu angular velocity by default set to true for strap down IMU based EKF implementations, if IMU measurements not used, corresponding impl can set to false.
Definition at line 417 of file FloatingBaseEstimator.h.
Referenced by BipedalLocomotion::Estimators::LeggedOdometry::LeggedOdometry(), and updateBaseStateFromIMUState().
m_useIMUVelForBaseVelComputation
bool BipedalLocomotion::Estimators::FloatingBaseEstimator::m_useIMUVelForBaseVelComputation {true} protected
Compute base velocity using inertnal state IMU velocity.
by default set to true for strap down IMU based EKF implementations, if IMU measurements not used, corresponding impl can set to false
Definition at line 418 of file FloatingBaseEstimator.h.
Referenced by BipedalLocomotion::Estimators::LeggedOdometry::LeggedOdometry(), and updateBaseStateFromIMUState().
m_useModelInfo
bool BipedalLocomotion::Estimators::FloatingBaseEstimator::m_useModelInfo {true} protected
Flag to enable running the estimator without using the URDF model information.
Definition at line 419 of file FloatingBaseEstimator.h.
Referenced by advance(), initialize(), setupInitialStates(), setupPriorDevs(), setupSensorDevs(), and updateBaseStateFromIMUState().
The documentation for this class was generated from the following files:
Estimators/include/BipedalLocomotion/FloatingBaseEstimators/FloatingBaseEstimator.h
Estimators/src/FloatingBaseEstimator.cpp