bipedal-locomotion-framework: BipedalLocomotion::ParametersHandler::YarpImplementation Class Reference
BipedalLocomotion::ParametersHandler::YarpImplementation Class Reference
YarpImplementation Yarp implementation of the IParametersHandler interface.
#include <BipedalLocomotion/ParametersHandler/YarpImplementation.h>
Public Member Functions
YarpImplementation (const yarp::os::Searchable &searchable)
Constructor.
YarpImplementation ()=default
Constructor.
void set (const yarp::os::Searchable &searchable)
Set the handler from an object.
bool getParameter (const std::string &parameterName, int &parameter) const final
Get a parameter [int].
bool getParameter (const std::string &parameterName, double &parameter) const final
Get a parameter [double].
bool getParameter (const std::string &parameterName, std::string &parameter) const final
Get a parameter [std::string].
bool getParameter (const std::string &parameterName, bool &parameter) const final
Get a parameter [bool].
bool getParameter (const std::string &parameterName, std::vector< bool > &parameter) const final
Get a parameter [std::vector<bool>].
bool getParameter (const std::string &parameterName, GenericContainer::Vector< int >::Ref parameter) const final
Get a parameter [GenericContainer::Vector<int>].
bool getParameter (const std::string &parameterName, GenericContainer::Vector< double >::Ref parameter) const final
Get a parameter [GenericContainer::Vector<double>].
bool getParameter (const std::string &parameterName, GenericContainer::Vector< std::string >::Ref parameter) const final
Get a parameter [GenericContainer::Vector<std::string>].
void setParameter (const std::string &parameterName, const int &parameter) final
Set a parameter [int].
void setParameter (const std::string &parameterName, const double &parameter) final
Set a parameter [double].
void setParameter (const std::string &parameterName, const std::string &parameter) final
Set a parameter [std::string].
void setParameter (const std::string &parameterName, const char *parameter) final
Set a parameter [const char*].
void setParameter (const std::string &parameterName, const bool &parameter) final
Set a parameter [bool].
void setParameter (const std::string &parameterName, const std::vector< bool > &parameter) final
Set a parameter [std::vector<bool>].
void setParameter (const std::string &parameterName, const GenericContainer::Vector< const int >::Ref parameter) final
Set a parameter [GenericContainer::Vector<int>].
void setParameter (const std::string &parameterName, const GenericContainer::Vector< const double >::Ref parameter) final
Set a parameter [GenericContainer::Vector<double>].
void setParameter (const std::string &parameterName, const GenericContainer::Vector< const std::string >::Ref parameter) final
Set a parameter [GenericContainer::Vector<std::string>].
weak_ptr getGroup (const std::string &name) const final
Get a Group from the handler.
bool setGroup (const std::string &name, shared_ptr newGroup) final
Set a new group on the handler.
std::string toString () const final
Return a standard text representation of the content of the object.
bool isEmpty () const final
Check if the handler contains parameters.
void clear () final
Clears the handler from all the parameters.
shared_ptr clone () const final
Clone the content of the content.
~YarpImplementation ()=default
Destructor.
Public Member Functions inherited from BipedalLocomotion::ParametersHandler::IParametersHandler
virtual ~IParametersHandler ()=default
Destructor.
Additional Inherited Members
Public Types inherited from BipedalLocomotion::ParametersHandler::IParametersHandler
using unique_ptr = std::unique_ptr< IParametersHandler >
using shared_ptr = std::shared_ptr< IParametersHandler >
using weak_ptr = std::weak_ptr< IParametersHandler >
Detailed Description
YarpImplementation Yarp implementation of the IParametersHandler interface.
Definition at line 31 of file YarpImplementation.h.
Constructor & Destructor Documentation
YarpImplementation() [1/2]
YarpImplementation::YarpImplementation (const yarp::os::Searchable & searchable)
Constructor.
Parameters
searchable reference to a searchable object. The object is copied inside the Handler
Definition at line 111 of file YarpImplementation.cpp.
References set().
YarpImplementation() [2/2]
BipedalLocomotion::ParametersHandler::YarpImplementation::YarpImplementation () default
Constructor.
~YarpImplementation()
BipedalLocomotion::ParametersHandler::YarpImplementation::~YarpImplementation () default
Destructor.
Member Function Documentation
clear()
void YarpImplementation::clear () final virtual
Clears the handler from all the parameters.
Implements BipedalLocomotion::ParametersHandler::IParametersHandler.
Definition at line 200 of file YarpImplementation.cpp.
Referenced by set().
clone()
IParametersHandler::shared_ptr YarpImplementation::clone () const final virtual
Clone the content of the content.
Returns
a IParametersHandler::shared_ptr clone of the current handler.
Warning
Implements BipedalLocomotion::ParametersHandler::IParametersHandler.
Definition at line 219 of file YarpImplementation.cpp.
getGroup()
YarpImplementation::weak_ptr YarpImplementation::getGroup (const std::string & name) const final virtual
Get a Group from the handler.
Parameters
name name of the group
Returns
A pointer to IParametersHandler, if the group is not found the weak pointer cannot be locked
Implements BipedalLocomotion::ParametersHandler::IParametersHandler.
Definition at line 147 of file YarpImplementation.cpp.
getParameter() [1/8]
bool YarpImplementation::getParameter (const std::string & parameterName, bool & parameter) const final virtual
Get a parameter [bool].
Parameters
parameterName name of the parameter
parameter parameter
Returns
true/false in case of success/failure
Implements BipedalLocomotion::ParametersHandler::IParametersHandler.
Definition at line 34 of file YarpImplementation.cpp.
getParameter() [2/8]
bool YarpImplementation::getParameter (const std::string & parameterName, double & parameter) const final virtual
Get a parameter [double].
Parameters
parameterName name of the parameter
parameter parameter
Returns
true/false in case of success/failure
Implements BipedalLocomotion::ParametersHandler::IParametersHandler.
Definition at line 23 of file YarpImplementation.cpp.
getParameter() [3/8]
bool YarpImplementation::getParameter (const std::string & parameterName, GenericContainer::Vector< double >::Ref parameter) const final virtual
Get a parameter [GenericContainer::Vector<double>].
Parameters
parameterName name of the parameter
parameter parameter
Returns
true/false in case of success/failure
Implements BipedalLocomotion::ParametersHandler::IParametersHandler.
Definition at line 45 of file YarpImplementation.cpp.
getParameter() [4/8]
bool YarpImplementation::getParameter (const std::string & parameterName, GenericContainer::Vector< int >::Ref parameter) const final virtual
Get a parameter [GenericContainer::Vector<int>].
Parameters
parameterName name of the parameter
parameter parameter
Returns
true/false in case of success/failure
Implements BipedalLocomotion::ParametersHandler::IParametersHandler.
Definition at line 39 of file YarpImplementation.cpp.
getParameter() [5/8]
bool YarpImplementation::getParameter (const std::string & parameterName, GenericContainer::Vector< std::string >::Ref parameter) const final virtual
Get a parameter [GenericContainer::Vector<std::string>].
Parameters
parameterName name of the parameter
parameter parameter
Returns
true/false in case of success/failure
Implements BipedalLocomotion::ParametersHandler::IParametersHandler.
Definition at line 51 of file YarpImplementation.cpp.
getParameter() [6/8]
bool YarpImplementation::getParameter (const std::string & parameterName, int & parameter) const final virtual
Get a parameter [int].
Parameters
parameterName name of the parameter
parameter parameter
Returns
true/false in case of success/failure
Implements BipedalLocomotion::ParametersHandler::IParametersHandler.
Definition at line 18 of file YarpImplementation.cpp.
getParameter() [7/8]
bool YarpImplementation::getParameter (const std::string & parameterName, std::string & parameter) const final virtual
Get a parameter [std::string].
Parameters
parameterName name of the parameter
parameter parameter
Returns
true/false in case of success/failure
Implements BipedalLocomotion::ParametersHandler::IParametersHandler.
Definition at line 28 of file YarpImplementation.cpp.
getParameter() [8/8]
bool YarpImplementation::getParameter (const std::string & parameterName, std::vector< bool > & parameter) const final virtual
Get a parameter [std::vector<bool>].
Parameters
parameterName name of the parameter
parameter parameter
Returns
true/false in case of success/failure
Implements BipedalLocomotion::ParametersHandler::IParametersHandler.
Definition at line 57 of file YarpImplementation.cpp.
isEmpty()
bool YarpImplementation::isEmpty () const final virtual
Check if the handler contains parameters.
Returns
true if the handler does not contain any parameters, false otherwise
Implements BipedalLocomotion::ParametersHandler::IParametersHandler.
Definition at line 190 of file YarpImplementation.cpp.
set()
void YarpImplementation::set (const yarp::os::Searchable & searchable)
Set the handler from an object.
Parameters
object The object to copy
Definition at line 116 of file YarpImplementation.cpp.
References clear().
Referenced by YarpImplementation().
setGroup()
bool YarpImplementation::setGroup (const std::string & name, IParametersHandler::shared_ptr newGroup) final virtual
Set a new group on the handler.
Parameters
name name of the group
newGroup shared pointer to the new group
Implements BipedalLocomotion::ParametersHandler::IParametersHandler.
Definition at line 157 of file YarpImplementation.cpp.
References BipedalLocomotion::log().
setParameter() [1/9]
void YarpImplementation::setParameter (const std::string & parameterName, const bool & parameter) final virtual
Set a parameter [bool].
Parameters
parameterName name of the parameter
parameter parameter
Implements BipedalLocomotion::ParametersHandler::IParametersHandler.
Definition at line 84 of file YarpImplementation.cpp.
setParameter() [2/9]
void YarpImplementation::setParameter (const std::string & parameterName, const char * parameter) final virtual
Set a parameter [const char*].
Note
this is required because of https://www.bfilipek.com/2019/07/surprising-conversions-char-bool.html
Parameters
parameterName name of the parameter
parameter parameter
Implements BipedalLocomotion::ParametersHandler::IParametersHandler.
Definition at line 73 of file YarpImplementation.cpp.
setParameter() [3/9]
void YarpImplementation::setParameter (const std::string & parameterName, const double & parameter) final virtual
Set a parameter [double].
Parameters
parameterName name of the parameter
parameter parameter
Implements BipedalLocomotion::ParametersHandler::IParametersHandler.
Definition at line 68 of file YarpImplementation.cpp.
setParameter() [4/9]
void YarpImplementation::setParameter (const std::string & parameterName, const GenericContainer::Vector< const double >::Ref parameter) final virtual
Set a parameter [GenericContainer::Vector<double>].
Parameters
parameterName name of the parameter
parameter parameter
Implements BipedalLocomotion::ParametersHandler::IParametersHandler.
Definition at line 94 of file YarpImplementation.cpp.
setParameter() [5/9]
void YarpImplementation::setParameter (const std::string & parameterName, const GenericContainer::Vector< const int >::Ref parameter) final virtual
Set a parameter [GenericContainer::Vector<int>].
Parameters
parameterName name of the parameter
parameter parameter
Implements BipedalLocomotion::ParametersHandler::IParametersHandler.
Definition at line 89 of file YarpImplementation.cpp.
setParameter() [6/9]
void YarpImplementation::setParameter (const std::string & parameterName, const GenericContainer::Vector< const std::string >::Ref parameter) final virtual
Set a parameter [GenericContainer::Vector<std::string>].
Parameters
parameterName name of the parameter
parameter parameter
Implements BipedalLocomotion::ParametersHandler::IParametersHandler.
Definition at line 99 of file YarpImplementation.cpp.
setParameter() [7/9]
void YarpImplementation::setParameter (const std::string & parameterName, const int & parameter) final virtual
Set a parameter [int].
Parameters
parameterName name of the parameter
parameter parameter
Implements BipedalLocomotion::ParametersHandler::IParametersHandler.
Definition at line 63 of file YarpImplementation.cpp.
setParameter() [8/9]
void YarpImplementation::setParameter (const std::string & parameterName, const std::string & parameter) final virtual
Set a parameter [std::string].
Parameters
parameterName name of the parameter
parameter parameter
Implements BipedalLocomotion::ParametersHandler::IParametersHandler.
Definition at line 78 of file YarpImplementation.cpp.
setParameter() [9/9]
void YarpImplementation::setParameter (const std::string & parameterName, const std::vector< bool > & parameter) final virtual
Set a parameter [std::vector<bool>].
Parameters
parameterName name of the parameter
parameter parameter
Implements BipedalLocomotion::ParametersHandler::IParametersHandler.
Definition at line 105 of file YarpImplementation.cpp.
toString()
std::string YarpImplementation::toString () const final virtual
Return a standard text representation of the content of the object.
Returns
a string containing the standard text representation of the content of the object.
Implements BipedalLocomotion::ParametersHandler::IParametersHandler.
Definition at line 180 of file YarpImplementation.cpp.
The documentation for this class was generated from the following files:
ParametersHandler/YarpImplementation/include/BipedalLocomotion/ParametersHandler/YarpImplementation.h
ParametersHandler/YarpImplementation/include/BipedalLocomotion/ParametersHandler/YarpImplementation.tpp
ParametersHandler/YarpImplementation/src/YarpImplementation.cpp