bipedal-locomotion-framework: BipedalLocomotion::Estimators::LeggedOdometry Class Reference
BipedalLocomotion::Estimators::LeggedOdometry Class Reference
Floating base estimation algorithm using only kinematic measurements by assuming atleast one frame on the robot is in contact with the environment.
#include <BipedalLocomotion/FloatingBaseEstimators/LeggedOdometry.h>
Data Structures
class Impl
Public Member Functions
LeggedOdometry ()
Constructor.
~LeggedOdometry ()
Destructor (necessary for PIMPL idiom)
bool resetEstimator ()
Reset the internal state of the estimator using the initialized parameters.
bool resetEstimator (const std::string &refFramForWorld, const Eigen::Quaterniond &worldOrientationInRefFrame, const Eigen::Vector3d &worldPositionInRefFrame)
Reset the internal state of the estimator by setting a new reference for the inertial frame.
bool changeFixedFrame (const std::ptrdiff_t &frameIndex)
Change fixed frame externally.
bool changeFixedFrame (const std::string &frameName)
Change fixed frame externally.
bool changeFixedFrame (const std::ptrdiff_t &frameIndex, const Eigen::Quaterniond &frameOrientationInWorld, const Eigen::Vector3d &framePositionInWorld)
Change fixed frame externally by mentioning the world_H_frame transform.
int getFixedFrameIdx ()
Get the index of the frame currently in contact used for the legged odometry computations.
manif::SE3d & getFixedFramePose () const
Get the psoe of the current fixed frame in the inertial frame.
virtual bool resetEstimator (const FloatingBaseEstimators::InternalState &newState)
To prevent function hiding due to overloading of virtual methods.
virtual bool resetEstimator (const Eigen::Quaterniond &newBaseOrientation, const Eigen::Vector3d &newBasePosition)
To prevent function hiding due to overloading of virtual methods.
Public Member Functions inherited from BipedalLocomotion::Estimators::FloatingBaseEstimator
bool initialize (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler, std::shared_ptr< iDynTree::KinDynComputations > kindyn)
Configure generic parameters and the model.
bool initialize (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler)
Configure generic parameters, calling this overloaded method assumes model information is not going to be used.
bool setIMUMeasurement (const Eigen::Vector3d &accMeas, const Eigen::Vector3d &gyroMeas)
Set the polled IMU measurement.
bool setContacts (const bool &lfInContact, const bool &rfInContact)
Set feet contact states.
bool setContactStatus (const std::string &name, const bool &contactStatus, const double &switchTime, double timeNow=0.)
Set contact status.
bool setKinematics (const Eigen::VectorXd &encoders, const Eigen::VectorXd &encoderSpeeds)
Set kinematic measurements.
bool setLandmarkRelativePose (const int &landmarkID, const Eigen::Quaterniond &quat, const Eigen::Vector3d &pos, const double &timeNow)
Set the relative pose of a landmark relative to the base link.
virtual bool advance () final
Compute one step of the estimator.
virtual bool resetEstimator (const FloatingBaseEstimators::InternalState &newState)
Reset the internal state of the estimator.
virtual bool resetEstimator (const Eigen::Quaterniond &newBaseOrientation, const Eigen::Vector3d &newBasePosition)
Reset the base pose estimate and consequently the internal state of the estimator.
virtual const FloatingBaseEstimators::Output & getOutput () const final
Get estimator outputs.
virtual bool isOutputValid () const final
Determines the validity of the object retrieved with get()
ModelComputations & modelComputations ()
Get ModelComputations object by reference.
Public Member Functions inherited from BipedalLocomotion::System::Source< FloatingBaseEstimators::Output >
bool setInput (const EmptySignal &input) final
Get the object.
Public Member Functions inherited from BipedalLocomotion::System::Advanceable< EmptySignal, FloatingBaseEstimators::Output >
virtual const Output & getOutput () const=0
Get the output of the advanceable.
virtual bool isOutputValid () const=0
Determines the validity of the object retrieved with getOutput()
virtual bool close ()
Close the Advanceable.
Protected Member Functions
virtual bool customInitialization (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler) override
These custom parameter specifications should be specified by the derived class.
virtual bool updateKinematics (FloatingBaseEstimators::Measurements &meas, const double &dt) override
Update the base state estimate using kinematics and contact measurements.
Protected Member Functions inherited from BipedalLocomotion::Estimators::FloatingBaseEstimator
virtual bool predictState (const FloatingBaseEstimators::Measurements &meas, const double &dt)
Propagate the states through the prediction model, if there exists any (eg.
virtual bool updateLandmarkRelativePoses (FloatingBaseEstimators::Measurements &meas, const double &dt)
Update the predicted state estimates using relative pose measurements of static landmarks in the environment.
bool updateBaseStateFromIMUState (const FloatingBaseEstimators::InternalState &state, const FloatingBaseEstimators::Measurements &meas, manif::SE3d &basePose, Eigen::Ref< Eigen::Matrix< double, 6, 1 >> baseTwist)
Wrapper method for getting base state from internal IMU state.
bool setupOptions (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler)
Setup estimator options.
bool setupSensorDevs (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler)
Setup measurement noise standard deviations The parameters in the SensorsStdDev group are,.
bool setupInitialStates (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler)
Setup initial states.
bool setupPriorDevs (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler)
Setup initial state standard deviations.
Additional Inherited Members
Public Types inherited from BipedalLocomotion::System::Advanceable< EmptySignal, FloatingBaseEstimators::Output >
using Input = EmptySignal
using Output = FloatingBaseEstimators::Output
Protected Types inherited from BipedalLocomotion::Estimators::FloatingBaseEstimator
enum State { State::NotInitialized, State::Initialized, State::Running }
Enumerator used to determine the running state of the estimator.
Protected Attributes inherited from BipedalLocomotion::Estimators::FloatingBaseEstimator
ModelComputations m_modelComp
Model computations object.
FloatingBaseEstimators::Options m_options
Struct holding estimator options.
FloatingBaseEstimators::Measurements m_meas
FloatingBaseEstimators::Measurements m_measPrev
Struct holding the latest measurements that were set to the estimator.
FloatingBaseEstimators::InternalState m_state
FloatingBaseEstimators::InternalState m_statePrev
Structs holding the curent and previous internal states of the estimation algorithm.
FloatingBaseEstimators::Output m_estimatorOut
Struct holding outputs of the estimator.
FloatingBaseEstimators::StateStdDev m_priors
FloatingBaseEstimators::StateStdDev m_stateStdDev
Struct holding standard deviations associated to prior state estimates.
FloatingBaseEstimators::SensorsStdDev m_sensorsDev
Struct holding standard deviations associated to sensor measurements.
State m_estimatorState {State::NotInitialized}
State of the estimator.
double m_dt {0.01}
Fixed time step of the estimator, in seconds.
bool m_useIMUForAngVelEstimate {true}
Use IMU measurements as internal state imu angular velocity by default set to true for strap down IMU based EKF implementations, if IMU measurements not used, corresponding impl can set to false.
bool m_useIMUVelForBaseVelComputation {true}
Compute base velocity using inertnal state IMU velocity.
bool m_useModelInfo {true}
Flag to enable running the estimator without using the URDF model information.
bool m_isInvEKF {false}
Flag to maintain soon to be deprecated functionalities currently existing only in InvEKFBaseEstimator.
Detailed Description
Floating base estimation algorithm using only kinematic measurements by assuming atleast one frame on the robot is in contact with the environment.
Configuration parameters,
Group Parameter Type Required Description
LeggedOdom - group Yes Configuration group for initializing the legged odometry block
initial_fixed_frame string Yes Frame on the URDF model of the robot assumed to be fixed (in contact) during the initialization phase
initial_ref_frame_for_world string No Frame on the URDF model of the robot to be used as a reference to initialize the inertial frame for the estimation. If not present, the initial fixed frame is assumed as the reference
initial_world_orientation_in_ref_frame vector of 4 doubles No Orientation of the inertial frame wrt the the reference frame as quaternion wxyz. If not present, assumed to be unit quaternion.
initial_world_position_in_ref_frame vector of 3 doubles No Position of the inertial frame wrt the reference frame as xyz. If not present,assumed to be zero position
switching_pattern string No Options: latest, lastActive, useExternal. Switching pattern to decide the fixed frame from the set of all frames in contact. latest chooses the recently switched contact frame, lastActive chooses the earliest switched contact frame. Default is latest
vel_computation_method string No Options: single, multiAvg, multiLS, multLSJvel. Method used for computing the floating base velocity using the fixed frame constraints. single uses only the fixed frame, multiAvg computes a simple average from all the contact frames, multLS uses a least square solution and multLSJVel regualrizes the least square solution by augmenting joint velocities in the computation. Default is multiLS.
wLin double No weight used for linear velocity in the least square computation of base velocity. If not present, set to 1.0
wAng double No weight used for angular velocity in the least square computation of base velocity. If not present, set to 0.5
wJVel double No weight used for linear velocity in the least square (with joint velocities) computation of base velocity. If not present, set to 10.0
reg double No regularization used for matrix inversion operation in least square. If not present, set to 1e-6
Definition at line 37 of file LeggedOdometry.h.
Constructor & Destructor Documentation
LeggedOdometry()
LeggedOdometry::LeggedOdometry ()
Constructor.
Definition at line 130 of file LeggedOdometry.cpp.
References BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::accelerometerBias, BipedalLocomotion::Estimators::FloatingBaseEstimators::Output::basePose, BipedalLocomotion::Estimators::FloatingBaseEstimators::Output::baseTwist, BipedalLocomotion::Estimators::FloatingBaseEstimators::Measurements::gyro, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::gyroscopeBias, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::imuAngularVelocity, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::imuLinearVelocity, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::imuOrientation, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::imuPosition, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::lContactFrameOrientation, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::lContactFramePosition, BipedalLocomotion::Estimators::FloatingBaseEstimators::Measurements::lfInContact, BipedalLocomotion::Estimators::FloatingBaseEstimator::m_estimatorOut, BipedalLocomotion::Estimators::FloatingBaseEstimator::m_measPrev, BipedalLocomotion::Estimators::FloatingBaseEstimator::m_statePrev, BipedalLocomotion::Estimators::FloatingBaseEstimator::m_useIMUForAngVelEstimate, BipedalLocomotion::Estimators::FloatingBaseEstimator::m_useIMUVelForBaseVelComputation, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::rContactFrameOrientation, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::rContactFramePosition, BipedalLocomotion::Estimators::FloatingBaseEstimators::Measurements::rfInContact, and BipedalLocomotion::Estimators::FloatingBaseEstimators::Output::state.
~LeggedOdometry()
LeggedOdometry::~LeggedOdometry () default
Destructor (necessary for PIMPL idiom)
Member Function Documentation
changeFixedFrame() [1/3]
bool LeggedOdometry::changeFixedFrame (const std::ptrdiff_t & frameIndex)
Change fixed frame externally.
Parameters
[in] frameIndex valid frame index from the model
Definition at line 869 of file LeggedOdometry.cpp.
References std::endl().
changeFixedFrame() [2/3]
bool LeggedOdometry::changeFixedFrame (const std::ptrdiff_t & frameIndex, const Eigen::Quaterniond & frameOrientationInWorld, const Eigen::Vector3d & framePositionInWorld)
Change fixed frame externally by mentioning the world_H_frame transform.
Parameters
[in] frameIndex valid frame from the model
[in] frameOrientationInWorld orientation of the fixed frame wrt the inertial frame
[in] framePositionInWorld position of the fixed frame wrt the inertial frame
Note
ensure to pass unit quaternion
Definition at line 912 of file LeggedOdometry.cpp.
References std::endl().
changeFixedFrame() [3/3]
bool LeggedOdometry::changeFixedFrame (const std::string & frameName)
Change fixed frame externally.
Parameters
[in] frameIndex valid frame name from the model
Definition at line 856 of file LeggedOdometry.cpp.
References std::endl().
customInitialization()
bool LeggedOdometry::customInitialization (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler) override protected virtual
These custom parameter specifications should be specified by the derived class.
Parameters
[in] handler configure the custom parameters for the estimator
Returns
bool
Reimplemented from BipedalLocomotion::Estimators::FloatingBaseEstimator.
Definition at line 165 of file LeggedOdometry.cpp.
References std::endl(), std::weak_ptr< T >::lock(), and BipedalLocomotion::Estimators::FloatingBaseEstimator::m_modelComp.
getFixedFrameIdx()
int LeggedOdometry::getFixedFrameIdx ()
Get the index of the frame currently in contact used for the legged odometry computations.
Returns
Index of the frame in contact, invalid frame index if no contact.
Definition at line 466 of file LeggedOdometry.cpp.
getFixedFramePose()
manif::SE3d & LeggedOdometry::getFixedFramePose () const
Get the psoe of the current fixed frame in the inertial frame.
Returns
const ref of pose of the fixed frame
Definition at line 471 of file LeggedOdometry.cpp.
resetEstimator() [1/4]
bool LeggedOdometry::resetEstimator ()
Reset the internal state of the estimator using the initialized parameters.
Returns
True in case of success, false otherwise.
Note
reset and advance estimator to get updated estimator output
Definition at line 412 of file LeggedOdometry.cpp.
References std::endl().
resetEstimator() [2/4]
bool FloatingBaseEstimator::resetEstimator
To prevent function hiding due to overloading of virtual methods.
Definition at line 837 of file FloatingBaseEstimator.cpp.
resetEstimator() [3/4]
bool FloatingBaseEstimator::resetEstimator
To prevent function hiding due to overloading of virtual methods.
Definition at line 864 of file FloatingBaseEstimator.cpp.
resetEstimator() [4/4]
bool LeggedOdometry::resetEstimator (const std::string & refFramForWorld, const Eigen::Quaterniond & worldOrientationInRefFrame, const Eigen::Vector3d & worldPositionInRefFrame)
Reset the internal state of the estimator by setting a new reference for the inertial frame.
Parameters
[in] refFramForWorld frame from the model as a reference to set the new inertial frame
[in] worldOrientationInRefFrame orientation of the inertial frame wrt to the reference frame
[in] worldPositionInRefFrame position of the inertial frame wrt to the reference frame
Returns
True in case of success, false otherwise.
Note
reset and advance estimator to get updated estimator output
Definition at line 427 of file LeggedOdometry.cpp.
References std::endl().
updateKinematics()
bool LeggedOdometry::updateKinematics (FloatingBaseEstimators::Measurements & meas, const double & dt) override protected virtual
Update the base state estimate using kinematics and contact measurements.
Parameters
[in] meas measurements to update states
[in] dt sampling period in seconds
Returns
True in case of success, false otherwise.
Reimplemented from BipedalLocomotion::Estimators::FloatingBaseEstimator.
Definition at line 774 of file LeggedOdometry.cpp.
References BipedalLocomotion::Estimators::FloatingBaseEstimators::Measurements::encodersSpeed, and std::endl().
The documentation for this class was generated from the following files:
Estimators/include/BipedalLocomotion/FloatingBaseEstimators/LeggedOdometry.h
Estimators/src/LeggedOdometry.cpp