bipedal-locomotion-framework: BipedalLocomotion::TSID::BaseDynamicsTask Class Reference
BipedalLocomotion::TSID::BaseDynamicsTask Class Reference
BaseDynamicsTask is a concrete implementation of the Task.
#include <BipedalLocomotion/TSID/BaseDynamicsTask.h>
Public Member Functions
bool initialize (std::weak_ptr< ParametersHandler::IParametersHandler > paramHandler)
Initialize the planner.
bool setKinDyn (std::shared_ptr< iDynTree::KinDynComputations > kinDyn)
Set the kinDynComputations object.
bool setVariablesHandler (const System::VariablesHandler &variablesHandler) override
Set the set of variables required by the task.
bool update () override
Update the content of the element.
std::size_t size () const override
Get the size of the task.
Type type () const override
The BaseDynamicsTask is an equality task.
bool isValid () const override
Determines the validity of the objects retrieved with getA() and getB()
Public Member Functions inherited from BipedalLocomotion::System::LinearTask
Eigen::Ref< const Eigen::MatrixXd > getA () const
Get the matrix A.
Eigen::Ref< const Eigen::VectorXd > getB () const
Get the vector b.
const std::string & getDescription () const
Get the description of the task.
Additional Inherited Members
Public Types inherited from BipedalLocomotion::System::LinearTask
enum Type { equality, inequality }
Type of the task.
Protected Member Functions inherited from BipedalLocomotion::System::LinearTask
iDynTree::MatrixView< double > subA (const System::VariablesHandler::VariableDescription &description)
Extract the submatrix A associated to a given variable.
iDynTree::MatrixView< const double > subA (const System::VariablesHandler::VariableDescription &description) const
Extract the submatrix A associated to a given variable.
Protected Attributes inherited from BipedalLocomotion::System::LinearTask
Eigen::MatrixXd m_A
Task Matrix.
Eigen::VectorXd m_b
Task Vector.
std::string m_description {"Generic Linear Task Element"}
String describing the content of the task.
Detailed Description
BaseDynamicsTask is a concrete implementation of the Task.
Please use this element if you want to consider the base dynamics only. The task represents the following equation
\[ M_{b}(q) \dot{\nu} + h_{b}(q,\nu) = \sum J_k^\top f_k \]
where the suffix \(b\) indicates the first 6 rows of the vector/matrix. \(J_k\) is the robot jacobian associated to the contact wrench \(d_k\).
Note
Please consider that here the MIXED representation is used to define the 6d-velocity and 6d-forces. You can find further details in Section 2.3.4 of https://traversaro.github.io/phd-thesis/traversaro-phd-thesis.pdf.
Definition at line 40 of file BaseDynamicsTask.h.
Member Function Documentation
initialize()
bool BaseDynamicsTask::initialize (std::weak_ptr< ParametersHandler::IParametersHandler > paramHandler)
Initialize the planner.
Parameters
paramHandler pointer to the parameters handler.
variablesHandler reference to a variables handler.
Note
the following parameters are required by the class
Parameter Name Type Description Mandatory
robot_acceleration_variable_name string Name of the variable contained in VariablesHandler describing the robot acceleration Yes
max_number_of_contacts int Maximum number of contacts. The default value is 0. No
CONTACT_<i> group i is an int between 0 and max_number_of_contacts The group must contain variable_name and frame_name Yes
variable_name string Name of the variable contained in VariablesHandler describing the contact Yes
frame_name string Name of the frame associated to the contact Yes
Returns
True in case of success, false otherwise.
Definition at line 86 of file BaseDynamicsTask.cpp.
References std::weak_ptr< T >::lock(), BipedalLocomotion::log(), and std::to_string().
isValid()
bool BaseDynamicsTask::isValid () const override virtual
Determines the validity of the objects retrieved with getA() and getB()
Returns
True if the objects are valid, false otherwise.
Implements BipedalLocomotion::System::LinearTask.
Definition at line 222 of file BaseDynamicsTask.cpp.
setKinDyn()
bool BaseDynamicsTask::setKinDyn (std::shared_ptr< iDynTree::KinDynComputations > kinDyn)
Set the kinDynComputations object.
Parameters
kinDyn pointer to a kinDynComputations object.
Returns
True in case of success, false otherwise.
Definition at line 18 of file BaseDynamicsTask.cpp.
References BipedalLocomotion::log().
setVariablesHandler()
bool BaseDynamicsTask::setVariablesHandler (const System::VariablesHandler & variablesHandler) override virtual
Set the set of variables required by the task.
The variables are stored in the System::VariablesHandler.
Parameters
variablesHandler reference to a variables handler.
Note
The handler must contain variables named as the parameter robot_acceleration_variable_name, variable_name (in CONTACT_<i> group) and stored in the parameter handler. robot_acceleration_variable_name represents the generalized acceleration of the robot. Where the generalized robot acceleration is a vector containing the base spatial-acceleration (expressed in mixed representation) and the joints acceleration.
Returns
True in case of success, false otherwise.
Reimplemented from BipedalLocomotion::System::LinearTask.
Definition at line 30 of file BaseDynamicsTask.cpp.
References BipedalLocomotion::System::VariablesHandler::getNumberOfVariables(), BipedalLocomotion::System::VariablesHandler::getVariable(), and BipedalLocomotion::log().
size()
std::size_t BaseDynamicsTask::size () const override virtual
Get the size of the task.
(I.e the number of rows of the vector b)
Returns
the size of the task.
Implements BipedalLocomotion::System::LinearTask.
Definition at line 212 of file BaseDynamicsTask.cpp.
type()
BaseDynamicsTask::Type BaseDynamicsTask::type () const override virtual
The BaseDynamicsTask is an equality task.
Returns
the type of the task.
Implements BipedalLocomotion::System::LinearTask.
Definition at line 217 of file BaseDynamicsTask.cpp.
update()
bool BaseDynamicsTask::update () override virtual
Update the content of the element.
Returns
True in case of success, false otherwise.
Reimplemented from BipedalLocomotion::System::LinearTask.
Definition at line 172 of file BaseDynamicsTask.cpp.
References BipedalLocomotion::log().
The documentation for this class was generated from the following files:
TSID/include/BipedalLocomotion/TSID/BaseDynamicsTask.h
TSID/src/BaseDynamicsTask.cpp