bipedal-locomotion-framework: BipedalLocomotion::System::StdClock Class Reference
BipedalLocomotion::System::StdClock Class Reference final
StdClock implements the IClock interface using <chrono> from c++std library.
#include <BipedalLocomotion/System/StdClock.h>
Public Member Functions
std::chrono::duration< double > now () final
Get the system current time.
void sleepFor (const std::chrono::duration< double > &sleepDuration) final
Blocks the execution of the current thread for at least the specified sleepDuration.
void sleepUntil (const std::chrono::duration< double > &sleepTime) final
Blocks the execution of the current thread until specified sleepTime has been reached.
void yield () final
Provides a hint to the implementation to reschedule the execution of threads, allowing other threads to run.
Public Member Functions inherited from BipedalLocomotion::System::IClock
virtual ~IClock ()=default
Destructor.
Additional Inherited Members
Protected Member Functions inherited from BipedalLocomotion::System::IClock
IClock ()=default
The constructor is protected.
Detailed Description
StdClock implements the IClock interface using <chrono> from c++std library.
The clock can be easily used as follows
#include <BipedalLocomotion/System/Clock.h>
auto start = BipedalLocomotion::clock().now();
foo();
auto end = BipedalLocomotion::clock().now();
std::chrono::duration<double, std::milli> elapsed = end-start;
Definition at line 33 of file StdClock.h.
Member Function Documentation
now()
std::chrono::duration< double > StdClock::now () final virtual
Get the system current time.
Returns
the current time since epoch computed with std::chrono::system_clock
Note
BipedalLocomotion::clock().now().count() returns a double containing the seconds since epoch
Implements BipedalLocomotion::System::IClock.
Definition at line 15 of file StdClock.cpp.
References std::chrono::system_clock::now().
sleepFor()
void StdClock::sleepFor (const std::chrono::duration< double > & sleepDuration) final virtual
Blocks the execution of the current thread for at least the specified sleepDuration.
Parameters
time duration to sleep
Note
std::this_tread::sleep_for() function is used.
Implements BipedalLocomotion::System::IClock.
Definition at line 20 of file StdClock.cpp.
References std::this_thread::sleep_for().
sleepUntil()
void StdClock::sleepUntil (const std::chrono::duration< double > & sleepTime) final virtual
Blocks the execution of the current thread until specified sleepTime has been reached.
Parameters
time to block until
Note
sleepTime is the duration since epoch
Implements BipedalLocomotion::System::IClock.
Definition at line 25 of file StdClock.cpp.
References std::chrono::system_clock::now(), and std::this_thread::sleep_for().
yield()
void StdClock::yield () final virtual
Provides a hint to the implementation to reschedule the execution of threads, allowing other threads to run.
Implements BipedalLocomotion::System::IClock.
Definition at line 30 of file StdClock.cpp.
References std::this_thread::yield().
The documentation for this class was generated from the following files:
System/include/BipedalLocomotion/System/StdClock.h
System/src/StdClock.cpp