bipedal-locomotion-framework: BipedalLocomotion::YarpUtilities::RosPublisher::Impl Class Reference
BipedalLocomotion::YarpUtilities::RosPublisher::Impl Class Reference
Public Member Functions
yarp::rosmsg::TickTime getTimeStampFromYarp ()
Get ROS timestamp from Yarp time now.
template<typename Publisher >
bool openPublisher (Publisher *pub, const std::string &topicName)
Open the ROS topic for the corresponding publisher In ROS terms, advertise the topic over which the node is going to publish.
template<typename PublisherMsg >
void configurePublisher (std::unique_ptr< yarp::os::Publisher< PublisherMsg > > &ptr)
template<typename Scalar >
bool setupParamV (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler, const std::string &param, std::vector< Scalar > &vec, const std::string &prefix)
Utility function to load vector parameters.
void resizeJointStateBuffer (const std::size_t &size)
Data Fields
std::string nodeName
name of the ROS node
std::unique_ptr< yarp::os::Node > node
YARP object for a ROS node.
JointStatePublisherDetails jointStatePublisher
std::unordered_map< std::string, WrenchPublisherDetails > wrenchPublisherMap
map of wrench frame and corresponding publisher
yarp::dev::PolyDriver transformBroadcaster
YARP Polydriver object to open a transform client.
yarp::dev::IFrameTransform * transformInterface {nullptr}
YARP IFrameTransform interface to publish transforms.
bool publishTF {false}
flag to enable publishing transforms to YARP transform server
bool initialized {false}
flag to chekc if the publisher was initialized
yarp::sig::Matrix pose
placeholder variable for publishing transform data
std::vector< double > jointStateZero
placeholder variable for zero joint state data
Detailed Description
Definition at line 43 of file RosPublisher.cpp.
Member Function Documentation
getTimeStampFromYarp()
yarp::rosmsg::TickTime BipedalLocomotion::YarpUtilities::RosPublisher::Impl::getTimeStampFromYarp ()
Get ROS timestamp from Yarp time now.
Definition at line 445 of file RosPublisher.cpp.
References std::endl().
openPublisher()
template<typename Publisher > bool BipedalLocomotion::YarpUtilities::RosPublisher::Impl::openPublisher (Publisher * pub, const std::string & topicName) inline
Open the ROS topic for the corresponding publisher In ROS terms, advertise the topic over which the node is going to publish.
Definition at line 56 of file RosPublisher.cpp.
References std::endl().
setupParamV()
template<typename Scalar > bool BipedalLocomotion::YarpUtilities::RosPublisher::Impl::setupParamV (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler, const std::string & param, std::vector< Scalar > & vec, const std::string & prefix) inline
Utility function to load vector parameters.
Definition at line 84 of file RosPublisher.cpp.
References std::endl(), and std::weak_ptr< T >::lock().
Field Documentation
initialized
bool BipedalLocomotion::YarpUtilities::RosPublisher::Impl::initialized {false}
flag to chekc if the publisher was initialized
Definition at line 113 of file RosPublisher.cpp.
jointStateZero
std::vector<double> BipedalLocomotion::YarpUtilities::RosPublisher::Impl::jointStateZero
placeholder variable for zero joint state data
Definition at line 117 of file RosPublisher.cpp.
node
std::unique_ptr<yarp::os::Node> BipedalLocomotion::YarpUtilities::RosPublisher::Impl::node
YARP object for a ROS node.
Definition at line 104 of file RosPublisher.cpp.
nodeName
std::string BipedalLocomotion::YarpUtilities::RosPublisher::Impl::nodeName
name of the ROS node
Definition at line 103 of file RosPublisher.cpp.
pose
yarp::sig::Matrix BipedalLocomotion::YarpUtilities::RosPublisher::Impl::pose
placeholder variable for publishing transform data
Definition at line 116 of file RosPublisher.cpp.
publishTF
bool BipedalLocomotion::YarpUtilities::RosPublisher::Impl::publishTF {false}
flag to enable publishing transforms to YARP transform server
Definition at line 112 of file RosPublisher.cpp.
transformBroadcaster
yarp::dev::PolyDriver BipedalLocomotion::YarpUtilities::RosPublisher::Impl::transformBroadcaster
YARP Polydriver object to open a transform client.
Definition at line 109 of file RosPublisher.cpp.
transformInterface
yarp::dev::IFrameTransform* BipedalLocomotion::YarpUtilities::RosPublisher::Impl::transformInterface {nullptr}
YARP IFrameTransform interface to publish transforms.
Definition at line 110 of file RosPublisher.cpp.
wrenchPublisherMap
std::unordered_map<std::string, WrenchPublisherDetails> BipedalLocomotion::YarpUtilities::RosPublisher::Impl::wrenchPublisherMap
map of wrench frame and corresponding publisher
Definition at line 107 of file RosPublisher.cpp.
The documentation for this class was generated from the following file:
YarpUtilities/src/RosPublisher.cpp