bipedal-locomotion-framework: BipedalLocomotion::Contacts::FixedFootDetector Class Reference
BipedalLocomotion::Contacts::FixedFootDetector Class Reference
The FixedFootDetector is a class that can be used to find the fixed foot given a sequence of contacts.
#include <BipedalLocomotion/ContactDetectors/FixedFootDetector.h>
Public Member Functions
bool setContactPhaseList (const ContactPhaseList &phaseList)
Set the contact phase list.
const EstimatedContact & getFixedFoot () const
Get the fixed foot.
Public Member Functions inherited from BipedalLocomotion::Contacts::ContactDetector
bool initialize (std::weak_ptr< const ParametersHandler::IParametersHandler > handler) override
Configure generic parameters.
bool advance () final
Compute one step of the detector The derived class must implement its own methods for setting measurements and update states to be called within the advance() method.
bool isOutputValid () const final
Determines the validity of the object retrieved with get()
const EstimatedContactList & getOutput () const final
Get contact states.
bool resetContacts ()
Reset the internal contact states of the detector to false.
bool get (const std::string &contactName, Contacts::EstimatedContact &contact) const
Get state of specific contact.
Contacts::EstimatedContact get (const std::string &contactName) const
Get state of specific contact.
Public Member Functions inherited from BipedalLocomotion::System::Source< EstimatedContactList >
bool setInput (const EmptySignal &input) final
Get the object.
Public Member Functions inherited from BipedalLocomotion::System::Advanceable< EmptySignal, EstimatedContactList >
virtual const Output & getOutput () const=0
Get the output of the advanceable.
virtual bool isOutputValid () const=0
Determines the validity of the object retrieved with getOutput()
virtual bool close ()
Close the Advanceable.
Additional Inherited Members
Public Types inherited from BipedalLocomotion::System::Advanceable< EmptySignal, EstimatedContactList >
using Input = EmptySignal
using Output = EstimatedContactList
Protected Types inherited from BipedalLocomotion::Contacts::ContactDetector
enum State { State::NotInitialized, State::Initialized, State::Running }
Enumerator used to determine the running state of the estimator.
Protected Attributes inherited from BipedalLocomotion::Contacts::ContactDetector
State m_detectorState {State::NotInitialized}
State of the estimator.
EstimatedContactList m_contactStates
Detailed Description
The FixedFootDetector is a class that can be used to find the fixed foot given a sequence of contacts.
The logic used to find the fixed foot is the follow:
In the single support phase the fixed foot is the stance foot
In the double support phase the fixed foot is the foot in switch off phase, where switch off is the transition phase between stance and swing.
The aforementioned logic is described by the following diagram
time         0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17
L            |+++|---|+++++++++++|---|+++++++++++|---|+++++++++++|---|+++++++++++|
R            |+++++++++++|---|+++++++++++|---|+++++++++++|---|+++++++++++|---|+++|
stance foot  |LLL|RRR|RRR|LLL|LLL|RRR|RRR|LLL|LLL|RRR|RRR|LLL|LLL|RRR|RRR|LLL|LLL|
Warning
The FixedFootDetector class can handle only bipedal locomotion. I.e. the ContactPhaseList passed to FixedFootDetector::setContactPhaseList must contain only single support and double phases.
The presented logic may not fit in a real scenario. Indeed the class implements an approach completely based on the desired footsteps and it does not consider the current state of the robot. We suggest to use Contacts::SchmittTriggerDetector class if you want consider the force acting on the robot.
Note
Given the current implementation of the class, you should call ContactDetector::advance only to advance the current time stored within the class. If you want to get the fixed foot at the initial time \(t=t_i\), you should call FixedFootDetector::getFixedFoot before calling advance. The following snippet can be used as a reference:
FixedFootDetector detector;
// initialize the detector
detector.initialize(paramsHandler);
detector.setContactPhaseList(contactPhaseList);
// get the fixed frame at initial time instant (t = t_i)
auto fixedFoot = detector.getFixedFoot();
// get the fixed frame at initial time + sampling time instant (t = t_i + dt)
detector.advance();
auto fixedFoot = detector.getFixedFoot();
Definition at line 64 of file FixedFootDetector.h.
Member Function Documentation
getFixedFoot()
const EstimatedContact & FixedFootDetector::getFixedFoot () const
Get the fixed foot.
Returns
the fixed foot.
Definition at line 209 of file FixedFootDetector.cpp.
References BipedalLocomotion::log().
setContactPhaseList()
bool FixedFootDetector::setContactPhaseList (const ContactPhaseList & phaseList)
Set the contact phase list.
Parameters
phaseList a contact phase list
Definition at line 164 of file FixedFootDetector.cpp.
References BipedalLocomotion::Contacts::ContactList::cbegin(), std::unordered_map< K, T >::cend(), std::string::erase(), std::unordered_map< K, T >::find(), BipedalLocomotion::Contacts::ContactPhaseList::firstPhase(), BipedalLocomotion::Contacts::ContactPhaseList::lists(), and std::vector< T >::push_back().
The documentation for this class was generated from the following files:
Contacts/include/BipedalLocomotion/ContactDetectors/FixedFootDetector.h
Contacts/src/FixedFootDetector.cpp