bipedal-locomotion-framework: BipedalLocomotion::TSID::SE3Task Class Reference
BipedalLocomotion::TSID::SE3Task Class Reference
SE3Task is a concrete implementation of the OptimalControlElement.
#include <BipedalLocomotion/TSID/SE3Task.h>
Public Member Functions
bool initialize (std::weak_ptr< ParametersHandler::IParametersHandler > paramHandler)
Initialize the planner.
bool setKinDyn (std::shared_ptr< iDynTree::KinDynComputations > kinDyn)
Set the kinDynComputations object.
bool setVariablesHandler (const System::VariablesHandler &variablesHandler) override
Set the set of variables required by the task.
bool update () override
Update the content of the element.
bool setSetPoint (const manif::SE3d &I_H_F, const manif::SE3d::Tangent &mixedVelocity, const manif::SE3d::Tangent &mixedAcceleration)
Set the desired reference trajectory.
std::size_t size () const override
Get the size of the task.
Type type () const override
The SE3Task is an equality task.
bool isValid () const override
Determines the validity of the objects retrieved with getA() and getB()
Public Member Functions inherited from BipedalLocomotion::System::LinearTask
Eigen::Ref< const Eigen::MatrixXd > getA () const
Get the matrix A.
Eigen::Ref< const Eigen::VectorXd > getB () const
Get the vector b.
const std::string & getDescription () const
Get the description of the task.
Additional Inherited Members
Public Types inherited from BipedalLocomotion::System::LinearTask
enum Type { equality, inequality }
Type of the task.
Protected Member Functions inherited from BipedalLocomotion::System::LinearTask
iDynTree::MatrixView< double > subA (const System::VariablesHandler::VariableDescription &description)
Extract the submatrix A associated to a given variable.
iDynTree::MatrixView< const double > subA (const System::VariablesHandler::VariableDescription &description) const
Extract the submatrix A associated to a given variable.
Protected Attributes inherited from BipedalLocomotion::System::LinearTask
Eigen::MatrixXd m_A
Task Matrix.
Eigen::VectorXd m_b
Task Vector.
std::string m_description {"Generic Linear Task Element"}
String describing the content of the task.
Detailed Description
SE3Task is a concrete implementation of the OptimalControlElement.
Please use this element if you want to control the position and the orientation of a given frame rigidly attached to the robot. The task assumes perfect control of the robot acceleration \(\dot{\nu}\) that contains the base linear and angular acceleration expressed in mixed representation and the joints acceleration. The task represents the following equation
\[ J \dot{\nu} + \dot{J} \nu = \dot{\mathrm{v}} ^ * \]
where \(J\) is the robot jacobian and \(\dot{\mathrm{v}} ^ *\) is the desired acceleration. The desired acceleration is chosen such that the frame will asymptotically converge to the desired trajectory. The linear component of \(\dot{\mathrm{v}} ^ *\) is computed with a standard PD controller in \(R^3\) while the angular acceleration is computed by a PD controller in \(SO(3)\).
Note
Please refer to https://github.com/dic-iit/lie-group-controllers if you are interested in the implementation of the PD controllers.
The SE3Task is technically not a \(SE(3)\) space defined task, instead is a \(SO(3) \times \mathbb{R}^3\) task. Theoretically, there are differences between the two due to the different definitions of exponential maps and logarithm maps. Please consider that here the MIXED representation is used to define the 6d-velocity. You can find further details in Section 2.3.4 of https://traversaro.github.io/phd-thesis/traversaro-phd-thesis.pdf.
Definition at line 46 of file SE3Task.h.
Member Function Documentation
initialize()
bool SE3Task::initialize (std::weak_ptr< ParametersHandler::IParametersHandler > paramHandler)
Initialize the planner.
Parameters
paramHandler pointer to the parameters handler.
Note
the following parameters are required by the class
Parameter Name Type Description Mandatory
robot_acceleration_variable_name string Name of the variable contained in VariablesHandler describing the robot acceleration Yes
frame_name string Name of the frame controlled by the SE3Task Yes
kp_linear double Gain of the position controller Yes
kd_linear double Gain of the linear velocity controller Yes
kp_angular double Gain of the orientation controller Yes
kd_angular double Gain of the angular velocity controller Yes
Returns
True in case of success, false otherwise.
Definition at line 68 of file SE3Task.cpp.
References std::weak_ptr< T >::lock(), and BipedalLocomotion::log().
isValid()
bool SE3Task::isValid () const override virtual
Determines the validity of the objects retrieved with getA() and getB()
Returns
True if the objects are valid, false otherwise.
Implements BipedalLocomotion::System::LinearTask.
Definition at line 220 of file SE3Task.cpp.
setKinDyn()
bool SE3Task::setKinDyn (std::shared_ptr< iDynTree::KinDynComputations > kinDyn)
Set the kinDynComputations object.
Parameters
kinDyn pointer to a kinDynComputations object.
Returns
True in case of success, false otherwise.
Definition at line 56 of file SE3Task.cpp.
References BipedalLocomotion::log().
setSetPoint()
bool SE3Task::setSetPoint (const manif::SE3d & I_H_F, const manif::SE3d::Tangent & mixedVelocity, const manif::SE3d::Tangent & mixedAcceleration)
Set the desired reference trajectory.
Parameters
I_H_F Homogeneous transform between the link and the inertial frame.
mixedVelocity 6D-velocity written in mixed representation.
mixedAcceleration 6D-acceleration written in mixed representation.
Returns
True in case of success, false otherwise.
Definition at line 196 of file SE3Task.cpp.
setVariablesHandler()
bool SE3Task::setVariablesHandler (const System::VariablesHandler & variablesHandler) override virtual
Set the set of variables required by the task.
The variables are stored in the System::VariablesHandler.
Parameters
variablesHandler reference to a variables handler.
Note
The handler must contain a variable named as the parameter robot_acceleration_variable_name stored in the parameter handler. The variable represents the generalized acceleration of the robot. Where the generalized robot acceleration is a vector containing the base spatial-acceleration (expressed in mixed representation) and the joints acceleration.
Returns
True in case of success, false otherwise.
Reimplemented from BipedalLocomotion::System::LinearTask.
Definition at line 19 of file SE3Task.cpp.
References BipedalLocomotion::System::VariablesHandler::getNumberOfVariables(), BipedalLocomotion::System::VariablesHandler::getVariable(), and BipedalLocomotion::log().
size()
std::size_t SE3Task::size () const override virtual
Get the size of the task.
(I.e the number of rows of the vector b)
Returns
the size of the task.
Implements BipedalLocomotion::System::LinearTask.
Definition at line 210 of file SE3Task.cpp.
type()
SE3Task::Type SE3Task::type () const override virtual
The SE3Task is an equality task.
Returns
the type of the task.
Implements BipedalLocomotion::System::LinearTask.
Definition at line 215 of file SE3Task.cpp.
update()
bool SE3Task::update () override virtual
Update the content of the element.
Returns
True in case of success, false otherwise.
Reimplemented from BipedalLocomotion::System::LinearTask.
Definition at line 158 of file SE3Task.cpp.
References BipedalLocomotion::log().
The documentation for this class was generated from the following files:
TSID/include/BipedalLocomotion/TSID/SE3Task.h
TSID/src/SE3Task.cpp