bipedal-locomotion-framework: BipedalLocomotion::Math::CARE Class Reference
BipedalLocomotion::Math::CARE Class Reference
Computes the unique stabilizing solution S to the continuous-time algebraic equation.
#include <BipedalLocomotion/Math/CARE.h>
Data Structures
struct Impl
Public Member Functions
bool initialize (std::weak_ptr< ParametersHandler::IParametersHandler > handler)
Initialize the continuous algebraic riccati equation solver.
bool setMatrices (Eigen::Ref< const Eigen::MatrixXd > A, Eigen::Ref< const Eigen::MatrixXd > B, Eigen::Ref< const Eigen::MatrixXd > Q, Eigen::Ref< const Eigen::MatrixXd > R)
Initialize the matrices.
bool solve ()
Run the algorithm to compute the unique stabilizing solution of the continuous algebriac Riccati equation.
Eigen::Ref< const Eigen::MatrixXd > getSolution () const
Get the solution.
CARE ()
Constructor.
~CARE ()
Destructor.
Detailed Description
Computes the unique stabilizing solution S to the continuous-time algebraic equation.
\[ S A + A' S - S B R^{-1} B' S + Q = 0 \]
Note
This class implements the algorithm presented in the paper: Solving the algebraic Riccati equation with the matrix sign function https://www.sciencedirect.com/science/article/pii/0024379587902229
Definition at line 31 of file CARE.h.
Constructor & Destructor Documentation
CARE()
CARE::CARE ()
Constructor.
Definition at line 51 of file CARE.cpp.
~CARE()
CARE::~CARE () default
Destructor.
Member Function Documentation
getSolution()
Eigen::Ref< const Eigen::MatrixXd > CARE::getSolution () const
Get the solution.
Returns
the solution
Definition at line 194 of file CARE.cpp.
initialize()
bool CARE::initialize (std::weak_ptr< ParametersHandler::IParametersHandler > handler)
Initialize the continuous algebraic riccati equation solver.
Parameters
handler pointer to the parameter handler.
Note
The following parameters are optional:
Parameter Name Type Description Mandatory
tolerance double Tolerance of the solution (default value 1e-9) No
is_verbose boolean If true the algorithm will print some information (default value false) No
max_iterations int Max number of the interation used by the algorithm (default value 100) No
Returns
true in case of success/false otherwise.
Definition at line 58 of file CARE.cpp.
References std::weak_ptr< T >::lock().
setMatrices()
bool CARE::setMatrices (Eigen::Ref< const Eigen::MatrixXd > A, Eigen::Ref< const Eigen::MatrixXd > B, Eigen::Ref< const Eigen::MatrixXd > Q, Eigen::Ref< const Eigen::MatrixXd > R)
Initialize the matrices.
Parameters
A n x n square matrix
B n x m matrix
Q n x n symmetric-square matrix
R m x m square positive definite matrix
Returns
True in case of success and false otherwise.
Definition at line 73 of file CARE.cpp.
References std::endl().
solve()
bool CARE::solve ()
Run the algorithm to compute the unique stabilizing solution of the continuous algebriac Riccati equation.
Returns
True in case of success and false otherwise.
Definition at line 122 of file CARE.cpp.
References std::endl(), std::pow(), and std::stringstream::str().
The documentation for this class was generated from the following files:
Math/include/BipedalLocomotion/Math/CARE.h
Math/src/CARE.cpp