bipedal-locomotion-framework: BipedalLocomotion::GenericContainer::Vector< T > Class Template Reference
BipedalLocomotion::GenericContainer::Vector< T > Class Template Reference
Forward declaration of Vector class.
#include <BipedalLocomotion/GenericContainer/Vector.h>
Data Structures
class Ref
The class ref is used a substitution to a classical reference to a Vector.
Public Types
using vector_element_type = typename iDynTree::Span< T >::element_type
Utility aliases depending on the type T.
using value_type = typename iDynTree::Span< T >::value_type
using index_type = typename iDynTree::Span< T >::index_type
using pointer = typename iDynTree::Span< T >::pointer
using reference = typename iDynTree::Span< T >::reference
using const_reference = const value_type &
using size_type = typename iDynTree::Span< T >::size_type
using iterator = typename iDynTree::Span< T >::iterator
Utility aliases to define iterators.
using const_iterator = typename iDynTree::Span< T >::const_iterator
using reverse_iterator = typename iDynTree::Span< T >::reverse_iterator
using const_reverse_iterator = typename iDynTree::Span< T >::const_reverse_iterator
using resize_function_type = std::function< iDynTree::Span< T >(index_type)>
Alias for the type of lambda used to resize the original vector.
using eigen_map_type = typename Eigen::Map< Eigen::Matrix< T, Eigen::Dynamic, 1 > >
Alias to determine the output type of toEigen()
using eigen_map_const_type = typename Eigen::Map< const Eigen::Matrix< T, Eigen::Dynamic, 1 > >
Public Member Functions
Vector (iDynTree::Span< T > span, resize_function_type resizeLambda)
Constructor.
Vector (iDynTree::Span< T > span)
Constructor.
~Vector ()=default
Destructor.
Vector (const Vector< T > &other)=delete
Copy constructor.
Vector (Vector< T > &&other)
Move constructor.
bool clone (const Vector< T > &other)
Copies the content of the vector.
bool clone (iDynTree::Span< T > other)
Copies the content of the vector.
Vector< T > & operator= (const Vector< T > &other)
operator = Copies the content
Vector< T > & operator= (iDynTree::Span< T > other)
operator = Copies the content
Vector< T > & operator= (Vector< T > &&other)
Move operator = Copies the content.
bool resizeVector (index_type newSize)
resizeVector It resize the original vector (if possible)
void resize (index_type newSize)
resize It resize the original vector (if possible)
index_type size () const
size Get the size of the Vector
bool empty () const
empty Checks if the container is empty (zero size)
const_reference operator[] (index_type idx) const
operator [] Accessor
reference operator[] (index_type idx)
operator [] Accessor
vector_element_type getVal (index_type idx) const
getVal Accessor
bool setVal (index_type idx, vector_element_type val)
setVal Setter
const_reference at (index_type idx) const
at Accessor
reference at (index_type idx)
at Accessor
const_reference operator() (index_type idx) const
operator () Accessor
reference operator() (index_type idx)
operator () Accessor
pointer data () const
data Raw pointer to the data
iterator begin ()
begin Iterator
iterator end ()
end Iterator
const_iterator begin () const
begin Iterator
const_iterator end () const
end Iterator
const_iterator cbegin () const
cbegin Iterator
const_iterator cend () const
cend Iterator
reverse_iterator rbegin ()
rbegin Iterator to the first element of the reversed vector
reverse_iterator rend ()
rend Iterator to the element following the last element of the reversed vector.
const_reverse_iterator rbegin () const
rbegin Iterator to the first element of the reversed vector
const_reverse_iterator rend () const
rend Iterator to the element following the last element of the reversed vector.
const_reverse_iterator crbegin () const
crbegin Iterator to the first element of the reversed vector
const_reverse_iterator crend () const
crend Iterator to the element following the last element of the reversed vector.
eigen_map_type toEigen ()
Get an Eigen map corresponding to the current generic vector (see https://eigen.tuxfamily.org/dox/classEigen_1_1Map.html).
eigen_map_const_type toEigen () const
Get an Eigen const map corresponding to the current generic vector (see https://eigen.tuxfamily.org/dox/classEigen_1_1Map.html).
Protected Member Functions
Vector ()=default
The default constructor is private.
Protected Attributes
iDynTree::Span< T > m_span
Span of the pointed vector.
resize_function_type m_resizeLambda
User specified lambda to resize the existing container.
Detailed Description
template<typename T>
class BipedalLocomotion::GenericContainer::Vector< T >
Forward declaration of Vector class.
Vector is a utility class which maps another existing contiguous container.
T is the type of vector (double, float, int, string,...)
It does not contain any data, but only a pointer to an existing contiguous area of memory containing a sequence of objects. It also stores its size, i.e. the number of objects. It does not own this portion of memory, hence it needs to be properly initialized from an existing container, such as an iDynTree::Vector, std::vector, array, yarp::sig::Vector and similar. Even if it does not own the memory, it is possible to resize it. This is done through an user specified lambda, which calls the corresponding "resize" method on the original object from which Vector has been initialized.
Warning
The original object from which Vector has been initialized should not be deallocated before Vector. This would invalidate the pointer inside it.
Definition at line 30 of file Vector.h.
Member Typedef Documentation
eigen_map_type
template<typename T > using BipedalLocomotion::GenericContainer::Vector< T >::eigen_map_type = typename Eigen::Map<Eigen::Matrix<T, Eigen::Dynamic, 1> >
Alias to determine the output type of toEigen()
Definition at line 89 of file Vector.h.
iterator
template<typename T > using BipedalLocomotion::GenericContainer::Vector< T >::iterator = typename iDynTree::Span<T>::iterator
Utility aliases to define iterators.
Definition at line 75 of file Vector.h.
resize_function_type
template<typename T > using BipedalLocomotion::GenericContainer::Vector< T >::resize_function_type = std::function<iDynTree::Span<T>(index_type)>
Alias for the type of lambda used to resize the original vector.
In particular, it takes as input the new size (of type index size)
Definition at line 84 of file Vector.h.
vector_element_type
template<typename T > using BipedalLocomotion::GenericContainer::Vector< T >::vector_element_type = typename iDynTree::Span<T>::element_type
Utility aliases depending on the type T.
Some notes:
vector_element_type has a different name than the corresponding one in iDynTree::Span to avoid some compilation issues.
value_type is the same as vector_element_type, but without an eventual const attribute
Definition at line 63 of file Vector.h.
Constructor & Destructor Documentation
Vector() [1/5]
template<typename T > BipedalLocomotion::GenericContainer::Vector< T >::Vector () protected default
The default constructor is private.
In fact, once the Vector is built, it is assumed to point to an existing container. To be used only if m_span and m_resizeLamba are set manually.
Vector() [2/5]
template<typename T > BipedalLocomotion::GenericContainer::Vector< T >::Vector (iDynTree::Span< T > span, resize_function_type resizeLambda) inline
Constructor.
Parameters
span Span of the existing container
resizeLambda User defined lambda to resize the original container
Definition at line 116 of file Vector.h.
References BipedalLocomotion::GenericContainer::Vector< T >::m_resizeLambda, and BipedalLocomotion::GenericContainer::Vector< T >::m_span.
Vector() [3/5]
template<typename T > BipedalLocomotion::GenericContainer::Vector< T >::Vector (iDynTree::Span< T > span) inline
Constructor.
Parameters
span Span of the existing container
Since no resizeLambda is provided, it is assumed that the original container cannot be resized.
Definition at line 128 of file Vector.h.
References BipedalLocomotion::GenericContainer::Vector< T >::m_resizeLambda, BipedalLocomotion::GenericContainer::Vector< T >::m_span, and BipedalLocomotion::GenericContainer::Vector< T >::size().
~Vector()
template<typename T > BipedalLocomotion::GenericContainer::Vector< T >::~Vector () default
Destructor.
Vector() [4/5]
template<typename T > BipedalLocomotion::GenericContainer::Vector< T >::Vector (const Vector< T > & other) delete
Copy constructor.
Warning
It has been deleted since it would not be clear if the pointer or the pointed data would be copied.
Vector() [5/5]
template<typename T > BipedalLocomotion::GenericContainer::Vector< T >::Vector (Vector< T > && other) inline
Move constructor.
Parameters
other Another Vector
Warning
Here the pointers are copied, the content is not duplicated.
Definition at line 152 of file Vector.h.
References BipedalLocomotion::GenericContainer::Vector< T >::m_resizeLambda, and BipedalLocomotion::GenericContainer::Vector< T >::m_span.
Member Function Documentation
at() [1/2]
template<typename T > reference BipedalLocomotion::GenericContainer::Vector< T >::at (index_type idx) inline
at Accessor
Parameters
idx The index to be accessed
Returns
A reference to the requested element.
Definition at line 366 of file Vector.h.
References BipedalLocomotion::GenericContainer::Vector< T >::operator[]().
at() [2/2]
template<typename T > const_reference BipedalLocomotion::GenericContainer::Vector< T >::at (index_type idx) const inline
at Accessor
Parameters
idx The index to be accessed
Returns
A const reference to the requested element.
Definition at line 356 of file Vector.h.
References BipedalLocomotion::GenericContainer::Vector< T >::operator[]().
begin() [1/2]
template<typename T > iterator BipedalLocomotion::GenericContainer::Vector< T >::begin () inline
begin Iterator
Returns
An iterator to the end of the sequence
Definition at line 404 of file Vector.h.
References BipedalLocomotion::GenericContainer::Vector< T >::m_span.
begin() [2/2]
template<typename T > const_iterator BipedalLocomotion::GenericContainer::Vector< T >::begin () const inline
begin Iterator
Returns
A const iterator to the end of the sequence
Definition at line 423 of file Vector.h.
References BipedalLocomotion::GenericContainer::Vector< T >::m_span.
cbegin()
template<typename T > const_iterator BipedalLocomotion::GenericContainer::Vector< T >::cbegin () const inline
cbegin Iterator
Returns
A const iterator to the end of the sequence
Definition at line 442 of file Vector.h.
References BipedalLocomotion::GenericContainer::Vector< T >::m_span.
cend()
template<typename T > const_iterator BipedalLocomotion::GenericContainer::Vector< T >::cend () const inline
cend Iterator
Returns
A const iterator to the end of the sequence
Warning
This element acts as a placeholder; attempting to access it results in undefined behavior.
Definition at line 452 of file Vector.h.
References BipedalLocomotion::GenericContainer::Vector< T >::m_span.
clone() [1/2]
template<typename T > bool BipedalLocomotion::GenericContainer::Vector< T >::clone (const Vector< T > & other) inline
Copies the content of the vector.
Parameters
other Vector from which to copy
Returns
true in case of success. False if the two have different size and this is not resizable.
Warning
It performs memory allocation if this is resizable and the sizes are different.
Definition at line 165 of file Vector.h.
References std::endl(), BipedalLocomotion::GenericContainer::Vector< T >::operator[](), BipedalLocomotion::GenericContainer::Vector< T >::resizeVector(), and BipedalLocomotion::GenericContainer::Vector< T >::size().
Referenced by BipedalLocomotion::GenericContainer::Vector< T >::operator=().
clone() [2/2]
template<typename T > bool BipedalLocomotion::GenericContainer::Vector< T >::clone (iDynTree::Span< T > other) inline
Copies the content of the vector.
Parameters
other Span from which to copy
Returns
true in case of success. False if the two have different size and this is not resizable.
Warning
It performs memory allocation if this is resizable and the sizes are different.
Definition at line 191 of file Vector.h.
References std::endl(), BipedalLocomotion::GenericContainer::Vector< T >::operator[](), BipedalLocomotion::GenericContainer::Vector< T >::resizeVector(), and BipedalLocomotion::GenericContainer::Vector< T >::size().
crbegin()
template<typename T > const_reverse_iterator BipedalLocomotion::GenericContainer::Vector< T >::crbegin () const inline
crbegin Iterator to the first element of the reversed vector
Returns
Returns a const reverse iterator to the first element of the reversed vector. It corresponds to the last element of the non-reversed vector
Definition at line 504 of file Vector.h.
References BipedalLocomotion::GenericContainer::Vector< T >::m_span.
crend()
template<typename T > const_reverse_iterator BipedalLocomotion::GenericContainer::Vector< T >::crend () const inline
crend Iterator to the element following the last element of the reversed vector.
Returns
Returns a reverse iterator to the element following the last element of the reversed vector. It corresponds to the element preceding the first element of the non-reversed vector.
Warning
This element acts as a placeholder; attempting to access it results in undefined behavior.
Definition at line 515 of file Vector.h.
References BipedalLocomotion::GenericContainer::Vector< T >::m_span.
data()
template<typename T > pointer BipedalLocomotion::GenericContainer::Vector< T >::data () const inline
data Raw pointer to the data
Returns
THe raw pointer to the data
Definition at line 395 of file Vector.h.
References BipedalLocomotion::GenericContainer::Vector< T >::m_span.
Referenced by BipedalLocomotion::GenericContainer::Vector< T >::Ref::Ref(), and BipedalLocomotion::GenericContainer::Vector< T >::toEigen().
empty()
template<typename T > bool BipedalLocomotion::GenericContainer::Vector< T >::empty () const inline
empty Checks if the container is empty (zero size)
Returns
True if empty.
Definition at line 301 of file Vector.h.
References BipedalLocomotion::GenericContainer::Vector< T >::m_span.
end() [1/2]
template<typename T > iterator BipedalLocomotion::GenericContainer::Vector< T >::end () inline
end Iterator
Returns
An iterator to the end of the sequence
Warning
This element acts as a placeholder; attempting to access it results in undefined behavior.
Definition at line 414 of file Vector.h.
References BipedalLocomotion::GenericContainer::Vector< T >::m_span.
end() [2/2]
template<typename T > const_iterator BipedalLocomotion::GenericContainer::Vector< T >::end () const inline
end Iterator
Returns
A const iterator to the end of the sequence
Warning
This element acts as a placeholder; attempting to access it results in undefined behavior.
Definition at line 433 of file Vector.h.
References BipedalLocomotion::GenericContainer::Vector< T >::m_span.
getVal()
template<typename T > vector_element_type BipedalLocomotion::GenericContainer::Vector< T >::getVal (index_type idx) const inline
getVal Accessor
Parameters
idx The index to be accessed
Returns
A const reference to the requested element.
Definition at line 330 of file Vector.h.
References BipedalLocomotion::GenericContainer::Vector< T >::operator[]().
operator()() [1/2]
template<typename T > reference BipedalLocomotion::GenericContainer::Vector< T >::operator() (index_type idx) inline
operator () Accessor
Parameters
idx The index to be accessed
Returns
A reference to the requested element.
Definition at line 386 of file Vector.h.
References BipedalLocomotion::GenericContainer::Vector< T >::operator[]().
operator()() [2/2]
template<typename T > const_reference BipedalLocomotion::GenericContainer::Vector< T >::operator() (index_type idx) const inline
operator () Accessor
Parameters
idx The index to be accessed
Returns
A const reference to the requested element.
Definition at line 376 of file Vector.h.
References BipedalLocomotion::GenericContainer::Vector< T >::operator[]().
operator=() [1/3]
template<typename T > Vector<T>& BipedalLocomotion::GenericContainer::Vector< T >::operator= (const Vector< T > & other) inline
operator = Copies the content
Parameters
other Vector from which to copy
Returns
A reference to the vector.
It calls clone(). There is an assert on its return value.
Warning
It performs memory allocation if this is resizable and the sizes are different.
Definition at line 219 of file Vector.h.
References BipedalLocomotion::GenericContainer::Vector< T >::clone().
operator=() [2/3]
template<typename T > Vector<T>& BipedalLocomotion::GenericContainer::Vector< T >::operator= (iDynTree::Span< T > other) inline
operator = Copies the content
Parameters
other Vector from which to copy
Returns
A reference to the vector.
It calls clone(). There is an assert on its return value.
Warning
It performs memory allocation if this is resizable and the sizes are different.
Definition at line 236 of file Vector.h.
References BipedalLocomotion::GenericContainer::Vector< T >::clone().
operator=() [3/3]
template<typename T > Vector<T>& BipedalLocomotion::GenericContainer::Vector< T >::operator= (Vector< T > && other) inline
Move operator = Copies the content.
Parameters
other Vector from which to copy
Returns
A reference to the vector.
It calls clone(). There is an assert on its return value.
Warning
It performs memory allocation if this is resizable and the sizes are different.
Definition at line 253 of file Vector.h.
References BipedalLocomotion::GenericContainer::Vector< T >::clone().
operator[]() [1/2]
template<typename T > reference BipedalLocomotion::GenericContainer::Vector< T >::operator[] (index_type idx) inline
operator [] Accessor
Parameters
idx The index to be accessed
Returns
A reference to the requested element.
Definition at line 320 of file Vector.h.
References BipedalLocomotion::GenericContainer::Vector< T >::m_span.
operator[]() [2/2]
template<typename T > const_reference BipedalLocomotion::GenericContainer::Vector< T >::operator[] (index_type idx) const inline
operator [] Accessor
Parameters
idx The index to be accessed
Returns
A const reference to the requested element.
Definition at line 310 of file Vector.h.
References BipedalLocomotion::GenericContainer::Vector< T >::m_span.
Referenced by BipedalLocomotion::GenericContainer::Vector< T >::at(), BipedalLocomotion::GenericContainer::Vector< T >::clone(), BipedalLocomotion::GenericContainer::Vector< T >::getVal(), BipedalLocomotion::GenericContainer::Vector< T >::operator()(), and BipedalLocomotion::GenericContainer::Vector< T >::setVal().
rbegin() [1/2]
template<typename T > reverse_iterator BipedalLocomotion::GenericContainer::Vector< T >::rbegin () inline
rbegin Iterator to the first element of the reversed vector
Returns
Returns a reverse iterator to the first element of the reversed vector. It corresponds to the last element of the non-reversed vector
Definition at line 462 of file Vector.h.
References BipedalLocomotion::GenericContainer::Vector< T >::m_span.
rbegin() [2/2]
template<typename T > const_reverse_iterator BipedalLocomotion::GenericContainer::Vector< T >::rbegin () const inline
rbegin Iterator to the first element of the reversed vector
Returns
Returns a const reverse iterator to the first element of the reversed vector. It corresponds to the last element of the non-reversed vector
Definition at line 483 of file Vector.h.
References BipedalLocomotion::GenericContainer::Vector< T >::m_span.
rend() [1/2]
template<typename T > reverse_iterator BipedalLocomotion::GenericContainer::Vector< T >::rend () inline
rend Iterator to the element following the last element of the reversed vector.
Returns
Returns a reverse iterator to the element following the last element of the reversed vector. It corresponds to the element preceding the first element of the non-reversed vector.
Warning
This element acts as a placeholder; attempting to access it results in undefined behavior.
Definition at line 473 of file Vector.h.
References BipedalLocomotion::GenericContainer::Vector< T >::m_span.
rend() [2/2]
template<typename T > const_reverse_iterator BipedalLocomotion::GenericContainer::Vector< T >::rend () const inline
rend Iterator to the element following the last element of the reversed vector.
Returns
Returns a reverse iterator to the element following the last element of the reversed vector. It corresponds to the element preceding the first element of the non-reversed vector.
Warning
This element acts as a placeholder; attempting to access it results in undefined behavior.
Definition at line 494 of file Vector.h.
References BipedalLocomotion::GenericContainer::Vector< T >::m_span.
resize()
template<typename T > void BipedalLocomotion::GenericContainer::Vector< T >::resize (index_type newSize) inline
resize It resize the original vector (if possible)
Parameters
newSize New size of the vector It calls resizeVector(). There is an assert on its return value.
Warning
It may perform memory allocation if the new size is different from the current and the resizeLambda has been specified.
Definition at line 281 of file Vector.h.
References BipedalLocomotion::GenericContainer::Vector< T >::resizeVector().
resizeVector()
template<typename T > bool BipedalLocomotion::GenericContainer::Vector< T >::resizeVector (index_type newSize) inline
resizeVector It resize the original vector (if possible)
Parameters
newSize New size of the vector
Returns
true if the new size matches the desired. False otherwise.
Warning
It may perform memory allocation if the new size is different from the current and the resizeLambda has been specified.
Definition at line 268 of file Vector.h.
References BipedalLocomotion::GenericContainer::Vector< T >::m_resizeLambda, and BipedalLocomotion::GenericContainer::Vector< T >::m_span.
Referenced by BipedalLocomotion::GenericContainer::Vector< T >::clone(), and BipedalLocomotion::GenericContainer::Vector< T >::resize().
setVal()
template<typename T > bool BipedalLocomotion::GenericContainer::Vector< T >::setVal (index_type idx, vector_element_type val) inline
setVal Setter
Parameters
idx Index of the values to be set
val The new value
Returns
False if idx is not within [0, size()).
Definition at line 341 of file Vector.h.
References BipedalLocomotion::GenericContainer::Vector< T >::operator[](), and BipedalLocomotion::GenericContainer::Vector< T >::size().
size()
template<typename T > index_type BipedalLocomotion::GenericContainer::Vector< T >::size () const inline
size Get the size of the Vector
Returns
The size of the Vector
Definition at line 292 of file Vector.h.
References BipedalLocomotion::GenericContainer::Vector< T >::m_span.
Referenced by BipedalLocomotion::GenericContainer::Vector< T >::clone(), BipedalLocomotion::YarpUtilities::RosPublisher::publishJointStates(), BipedalLocomotion::YarpUtilities::RosPublisher::publishTransform(), BipedalLocomotion::YarpUtilities::RosPublisher::publishWrench(), BipedalLocomotion::GenericContainer::Vector< T >::Ref::Ref(), BipedalLocomotion::GenericContainer::Vector< T >::setVal(), BipedalLocomotion::GenericContainer::Vector< T >::toEigen(), and BipedalLocomotion::GenericContainer::Vector< T >::Vector().
toEigen() [1/2]
template<typename T > eigen_map_type BipedalLocomotion::GenericContainer::Vector< T >::toEigen () inline
Get an Eigen map corresponding to the current generic vector (see https://eigen.tuxfamily.org/dox/classEigen_1_1Map.html).
Definition at line 523 of file Vector.h.
References BipedalLocomotion::GenericContainer::Vector< T >::data(), and BipedalLocomotion::GenericContainer::Vector< T >::size().
toEigen() [2/2]
template<typename T > eigen_map_const_type BipedalLocomotion::GenericContainer::Vector< T >::toEigen () const inline
Get an Eigen const map corresponding to the current generic vector (see https://eigen.tuxfamily.org/dox/classEigen_1_1Map.html).
Definition at line 531 of file Vector.h.
References BipedalLocomotion::GenericContainer::Vector< T >::data(), and BipedalLocomotion::GenericContainer::Vector< T >::size().
Field Documentation
m_resizeLambda
template<typename T > resize_function_type BipedalLocomotion::GenericContainer::Vector< T >::m_resizeLambda protected
User specified lambda to resize the existing container.
Definition at line 101 of file Vector.h.
Referenced by BipedalLocomotion::GenericContainer::Vector< T >::Ref::Ref(), BipedalLocomotion::GenericContainer::Vector< T >::resizeVector(), and BipedalLocomotion::GenericContainer::Vector< T >::Vector().
m_span
template<typename T > iDynTree::Span<T> BipedalLocomotion::GenericContainer::Vector< T >::m_span protected
Span of the pointed vector.
This allows to point to an existing container without owning it.
Definition at line 97 of file Vector.h.
Referenced by BipedalLocomotion::GenericContainer::Vector< T >::begin(), BipedalLocomotion::GenericContainer::Vector< T >::cbegin(), BipedalLocomotion::GenericContainer::Vector< T >::cend(), BipedalLocomotion::GenericContainer::Vector< T >::crbegin(), BipedalLocomotion::GenericContainer::Vector< T >::crend(), BipedalLocomotion::GenericContainer::Vector< T >::data(), BipedalLocomotion::GenericContainer::Vector< T >::empty(), BipedalLocomotion::GenericContainer::Vector< T >::end(), BipedalLocomotion::GenericContainer::Vector< T >::operator[](), BipedalLocomotion::GenericContainer::Vector< T >::rbegin(), BipedalLocomotion::GenericContainer::Vector< T >::Ref::Ref(), BipedalLocomotion::GenericContainer::Vector< T >::rend(), BipedalLocomotion::GenericContainer::Vector< T >::resizeVector(), BipedalLocomotion::GenericContainer::Vector< T >::size(), and BipedalLocomotion::GenericContainer::Vector< T >::Vector().
The documentation for this class was generated from the following file:
GenericContainer/include/BipedalLocomotion/GenericContainer/Vector.h