bipedal-locomotion-framework: BipedalLocomotion::IK::JointTrackingTask Class Reference
BipedalLocomotion::IK::JointTrackingTask Class Reference
JointsTrackingTask is a concrete implementation of the Task.
#include <BipedalLocomotion/IK/JointTrackingTask.h>
Public Member Functions
bool initialize (std::weak_ptr< ParametersHandler::IParametersHandler > paramHandler)
Initialize the task.
bool setKinDyn (std::shared_ptr< iDynTree::KinDynComputations > kinDyn)
Set the kinDynComputations object.
bool setVariablesHandler (const System::VariablesHandler &variablesHandler) override
Set the set of variables required by the task.
bool update () override
Update the content of the element.
bool setSetPoint (Eigen::Ref< const Eigen::VectorXd > jointPosition)
Set the desired setpoint.
bool setSetPoint (Eigen::Ref< const Eigen::VectorXd > jointPosition, Eigen::Ref< const Eigen::VectorXd > jointVelocity)
Set the desired setpoint.
std::size_t size () const override
Get the size of the task.
Type type () const override
The JointsTrackingTask is an equality task.
bool isValid () const override
Determines the validity of the objects retrieved with getA() and getB()
Public Member Functions inherited from BipedalLocomotion::System::LinearTask
Eigen::Ref< const Eigen::MatrixXd > getA () const
Get the matrix A.
Eigen::Ref< const Eigen::VectorXd > getB () const
Get the vector b.
const std::string & getDescription () const
Get the description of the task.
Additional Inherited Members
Public Types inherited from BipedalLocomotion::System::LinearTask
enum Type { equality, inequality }
Type of the task.
Protected Member Functions inherited from BipedalLocomotion::System::LinearTask
iDynTree::MatrixView< double > subA (const System::VariablesHandler::VariableDescription &description)
Extract the submatrix A associated to a given variable.
iDynTree::MatrixView< const double > subA (const System::VariablesHandler::VariableDescription &description) const
Extract the submatrix A associated to a given variable.
Protected Attributes inherited from BipedalLocomotion::System::LinearTask
Eigen::MatrixXd m_A
Task Matrix.
Eigen::VectorXd m_b
Task Vector.
std::string m_description {"Generic Linear Task Element"}
String describing the content of the task.
Detailed Description
JointsTrackingTask is a concrete implementation of the Task.
Please use this element if you want to control the desired joint position of the robot. The task represents the following equation
\[ \begin{bmatrix} 0_6 & I_n \end{bmatrix} \nu = \dot{s} ^ * \]
where \(0_6\) and \(I_n\) are the zero and the identity matrix. The desired joint velocity is chosen such that the joint will converge to the desired trajectory and it is computed with a standard standard PD controller in \(\mathbb{R}^n\).
Definition at line 35 of file JointTrackingTask.h.
Member Function Documentation
initialize()
bool JointTrackingTask::initialize (std::weak_ptr< ParametersHandler::IParametersHandler > paramHandler)
Initialize the task.
Parameters
paramHandler pointer to the parameters handler.
Note
the following parameters are required by the class
Parameter Name Type Description Mandatory
robot_velocity_variable_name string Name of the variable contained in VariablesHandler describing the robot velocity Yes
kp vector Proportional controller gain Yes
Returns
True in case of success, false otherwise. Where the generalized robot velocity is a vector containing the base spatial-velocity (expressed in mixed representation) and the joint velocities.
True in case of success, false otherwise.
Definition at line 74 of file JointTrackingTask.cpp.
References std::weak_ptr< T >::lock(), and BipedalLocomotion::log().
isValid()
bool JointTrackingTask::isValid () const override virtual
Determines the validity of the objects retrieved with getA() and getB()
Returns
True if the objects are valid, false otherwise.
Implements BipedalLocomotion::System::LinearTask.
Definition at line 184 of file JointTrackingTask.cpp.
setKinDyn()
bool JointTrackingTask::setKinDyn (std::shared_ptr< iDynTree::KinDynComputations > kinDyn)
Set the kinDynComputations object.
Parameters
kinDyn pointer to a kinDynComputations object.
Returns
True in case of success, false otherwise.
Definition at line 17 of file JointTrackingTask.cpp.
References BipedalLocomotion::log().
setSetPoint() [1/2]
bool JointTrackingTask::setSetPoint (Eigen::Ref< const Eigen::VectorXd > jointPosition)
Set the desired setpoint.
Parameters
jointPosition vector containing the desired joint position in radians.
Note
The desired velocity is implicitly set to zero.
Returns
True in case of success, false otherwise.
Definition at line 136 of file JointTrackingTask.cpp.
setSetPoint() [2/2]
bool JointTrackingTask::setSetPoint (Eigen::Ref< const Eigen::VectorXd > jointPosition, Eigen::Ref< const Eigen::VectorXd > jointVelocity)
Set the desired setpoint.
Parameters
jointPosition vector containing the desired joint position in radians.
jointVelocity vector containing the desired joint velocity in radians per second.
Returns
True in case of success, false otherwise.
Definition at line 141 of file JointTrackingTask.cpp.
References BipedalLocomotion::log().
setVariablesHandler()
bool JointTrackingTask::setVariablesHandler (const System::VariablesHandler & variablesHandler) override virtual
Set the set of variables required by the task.
The variables are stored in the System::VariablesHandler.
Parameters
variablesHandler reference to a variables handler.
Note
The handler must contain a variable named as the parameter robot_velocity_variable_name stored in the parameter handler. The variable represents the generalized velocity of the robot. Where the generalized robot velocity is a vector containing the base spatial-velocity (expressed in mixed representation) and the joints velocity.
Returns
True in case of success, false otherwise.
Reimplemented from BipedalLocomotion::System::LinearTask.
Definition at line 29 of file JointTrackingTask.cpp.
References BipedalLocomotion::System::VariablesHandler::getNumberOfVariables(), BipedalLocomotion::System::VariablesHandler::getVariable(), and BipedalLocomotion::log().
size()
std::size_t JointTrackingTask::size () const override virtual
Get the size of the task.
(I.e the number of rows of the vector b)
Returns
the size of the task.
Implements BipedalLocomotion::System::LinearTask.
Definition at line 164 of file JointTrackingTask.cpp.
References BipedalLocomotion::log().
type()
JointTrackingTask::Type JointTrackingTask::type () const override virtual
The JointsTrackingTask is an equality task.
Returns
the size of the task.
Implements BipedalLocomotion::System::LinearTask.
Definition at line 179 of file JointTrackingTask.cpp.
update()
bool JointTrackingTask::update () override virtual
Update the content of the element.
Returns
True in case of success, false otherwise.
Reimplemented from BipedalLocomotion::System::LinearTask.
Definition at line 118 of file JointTrackingTask.cpp.
References BipedalLocomotion::log().
The documentation for this class was generated from the following files:
IK/include/BipedalLocomotion/IK/JointTrackingTask.h
IK/src/JointTrackingTask.cpp