bipedal-locomotion-framework: BipedalLocomotion::RobotInterface::YarpCameraBridge Class Reference
BipedalLocomotion::RobotInterface::YarpCameraBridge Class Reference
YarpCameraBridge Yarp implementation of the ICameraBridge interface Currently available interfaces.
#include <BipedalLocomotion/RobotInterface/YarpCameraBridge.h>
Data Structures
struct Impl
Public Member Functions
YarpCameraBridge ()
Constructor.
~YarpCameraBridge ()
Destructor.
bool initialize (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler) final
Initialize estimator.
bool setDriversList (const yarp::dev::PolyDriverList &deviceDriversList)
Set the list of device drivers from which the sensor measurements need to be streamed.
bool isValid () const
Determines the validity of the object retrieved with get()
const BipedalLocomotion::RobotInterface::CameraBridgeMetaData & get () const
Get the object.
bool getRGBCamerasList (std::vector< std::string > &rgbCamerasList) final
Get rgb cameras.
bool getRGBDCamerasList (std::vector< std::string > &rgbdCamerasList) final
Get RGBD cameras.
bool getColorImage (const std::string &camName, cv::Mat &colorImg, std::optional< std::reference_wrapper< double >> receiveTimeInSeconds={}) final
Get color image from the camera.
bool getDepthImage (const std::string &camName, cv::Mat &depthImg, std::optional< std::reference_wrapper< double >> receiveTimeInSeconds={}) final
Get depth image.
Public Member Functions inherited from BipedalLocomotion::RobotInterface::ICameraBridge
virtual ~ICameraBridge ()=default
Destructor.
Additional Inherited Members
Public Types inherited from BipedalLocomotion::RobotInterface::ICameraBridge
using unique_ptr = std::unique_ptr< ICameraBridge >
using shared_ptr = std::shared_ptr< ICameraBridge >
using weak_ptr = std::weak_ptr< ICameraBridge >
Protected Member Functions inherited from BipedalLocomotion::RobotInterface::ICameraBridge
virtual bool populateCameraBridgeOptionsFromConfig (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler, CameraBridgeOptions &cameraBridgeOptions)
Helper method to maintain CameraBridgeOptions struct by populating it from the configuration parameters.
virtual bool populateCameraListsFromConfig (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler, const CameraBridgeOptions &cameraBridgeOptions, CameraLists &cameraLists)
Helper method to maintain CameraLists struct by populating it from the configuration parameters.
virtual bool populateCameraBridgeMetaDataFromConfig (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler, CameraBridgeMetaData &cameraBridgeMetaData)
Helper method to maintain CameraBridgeMetaData struct by populating it from the configuration parameters.
Detailed Description
YarpCameraBridge Yarp implementation of the ICameraBridge interface Currently available interfaces.
Depth Cameras through RGBD sensor interface
Camera images through OpenCV Grabber interface
The YarpCameraBridge expects a list of device drivers through the yarp::dev::PolyDriverList object. Each PolyDriver object in the list is compared with the configured sensor names and the assumptions listed below to infer the sensor types and relevant interfaces in order to to read the relevant data.
MAJOR ASSUMPTIONS
Every sensor unit(device driver) attached to this Bridge is identified by a unique name
The images are available through a FrameGrabber interface (RGB only) and a RGBD interface (RGB and Depth).
The current internal design (read all sensors in a serial fashion) may not be suitable for a heavy measurement set
The parameters for writing the configuration file for this class is given as,
Group Parameter Type Description
Cameras Expects cameras to be opened either as remote frame grabber ("RemoteFrameGrabber") with IFrameGrabber interface or rgbd sensor ("RGBDSensorClient") with IRGBDSensor interface
rgbd_cameras_list vector of strings list containing the devices opened as RGBDSensorClients containing the IRGBD sensor interface
rgbd_image_width vector of integers list containing the image width dimensions of RGBD cameras. Required parameter if cameras are enabled. The list must be the same size and order as rgbd_list
rgbd_image_height vector of integers list containing the image height dimensions of RGBD cameras. Required parameter if cameras are enabled. The list must be the same size and order as rgbd_list
rgb_cameras_list vector of strings list containing the devices opened as RemoteFrameGrabber devices containing the IFrameGrabber interface
rgb_image_width vector of integers list containing the image width dimensions of RGB cameras. Required parameter if cameras are enabled. The list must be the same size and order as rgb_list
rgb_image_height vector of integers list containing the image height dimensions of RGB cameras. Required parameter if cameras are enabled. The list must be the same size and order as rgb_list
Definition at line 50 of file YarpCameraBridge.h.
Constructor & Destructor Documentation
YarpCameraBridge()
YarpCameraBridge::YarpCameraBridge ()
Constructor.
Definition at line 458 of file YarpCameraBridge.cpp.
~YarpCameraBridge()
YarpCameraBridge::~YarpCameraBridge () default
Destructor.
Member Function Documentation
get()
const CameraBridgeMetaData & YarpCameraBridge::get () const
Get the object.
Returns
a const reference of the requested object.
Definition at line 520 of file YarpCameraBridge.cpp.
getColorImage()
bool YarpCameraBridge::getColorImage (const std::string & camName, cv::Mat & colorImg, std::optional< std::reference_wrapper< double >> receiveTimeInSeconds = {}) final virtual
Get color image from the camera.
Parameters
[in] camName name of the camera
[out] colorImg image as cv Mat object
[out] receiveTimeInSeconds time at which the measurement was received
Warning
the size is decided at the configuration and remains fixed, and internal checks must be done at the implementation level by the Derived class. This means that the user must pass a resized argument "colorImg" to this method
Returns
true/false in case of success/failure
Reimplemented from BipedalLocomotion::RobotInterface::ICameraBridge.
Definition at line 544 of file YarpCameraBridge.cpp.
References BipedalLocomotion::log().
getDepthImage()
bool YarpCameraBridge::getDepthImage (const std::string & camName, cv::Mat & depthImg, std::optional< std::reference_wrapper< double >> receiveTimeInSeconds = {}) final virtual
Get depth image.
Parameters
[in] camName name of the gyroscope
[out] depthImg depth image as cv Mat object
[out] receiveTimeInSeconds time at which the measurement was received
Warning
the size is decided at the configuration and remains fixed, and internal checks must be done at the implementation level by the Derived class. This means that the user must pass a resized argument "depthImg" to this method
Returns
true/false in case of success/failure
Reimplemented from BipedalLocomotion::RobotInterface::ICameraBridge.
Definition at line 595 of file YarpCameraBridge.cpp.
References BipedalLocomotion::log().
getRGBCamerasList()
bool YarpCameraBridge::getRGBCamerasList (std::vector< std::string > & rgbCamerasList) final virtual
Get rgb cameras.
Parameters
[out] rgbCamerasList list of rgb cameras attached to the bridge
Returns
true/false in case of success/failure
Reimplemented from BipedalLocomotion::RobotInterface::ICameraBridge.
Definition at line 523 of file YarpCameraBridge.cpp.
getRGBDCamerasList()
bool YarpCameraBridge::getRGBDCamerasList (std::vector< std::string > & rgbdCamerasList) final virtual
Get RGBD cameras.
Parameters
[out] rgbdCamerasList list of depth cameras attached to the bridge
Returns
true/false in case of success/failure
Reimplemented from BipedalLocomotion::RobotInterface::ICameraBridge.
Definition at line 533 of file YarpCameraBridge.cpp.
initialize()
bool YarpCameraBridge::initialize (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler) final virtual
Initialize estimator.
Parameters
[in] handler Parameters handler
Implements BipedalLocomotion::RobotInterface::ICameraBridge.
Definition at line 464 of file YarpCameraBridge.cpp.
References BipedalLocomotion::RobotInterface::YarpCameraBridge::Impl::configureCameras(), std::weak_ptr< T >::lock(), and BipedalLocomotion::log().
isValid()
bool YarpCameraBridge::isValid () const
Determines the validity of the object retrieved with get()
Returns
True if the object is valid, false otherwise.
Definition at line 515 of file YarpCameraBridge.cpp.
setDriversList()
bool YarpCameraBridge::setDriversList (const yarp::dev::PolyDriverList & deviceDriversList)
Set the list of device drivers from which the sensor measurements need to be streamed.
Parameters
deviceDriversList device drivers holding the pointer to sensor interfaces
Returns
True/False in case of success/failure.
Definition at line 493 of file YarpCameraBridge.cpp.
References BipedalLocomotion::log().
The documentation for this class was generated from the following files:
RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpCameraBridge.h
RobotInterface/YarpImplementation/src/YarpCameraBridge.cpp