bipedal-locomotion-framework: BipedalLocomotion::Contacts::ContactDetector Class Reference
BipedalLocomotion::Contacts::ContactDetector Class Reference abstract
Public Member Functions
bool initialize (std::weak_ptr< const ParametersHandler::IParametersHandler > handler) override
Configure generic parameters.
bool advance () final
Compute one step of the detector The derived class must implement its own methods for setting measurements and update states to be called within the advance() method.
bool isOutputValid () const final
Determines the validity of the object retrieved with get()
const EstimatedContactList & getOutput () const final
Get contact states.
bool resetContacts ()
Reset the internal contact states of the detector to false.
bool get (const std::string &contactName, Contacts::EstimatedContact &contact) const
Get state of specific contact.
Contacts::EstimatedContact get (const std::string &contactName) const
Get state of specific contact.
Public Member Functions inherited from BipedalLocomotion::System::Source< EstimatedContactList >
bool setInput (const EmptySignal &input) final
Get the object.
Public Member Functions inherited from BipedalLocomotion::System::Advanceable< EmptySignal, EstimatedContactList >
virtual const Output & getOutput () const=0
Get the output of the advanceable.
virtual bool isOutputValid () const=0
Determines the validity of the object retrieved with getOutput()
virtual bool close ()
Close the Advanceable.
Protected Types
enum State { State::NotInitialized, State::Initialized, State::Running }
Enumerator used to determine the running state of the estimator.
Protected Member Functions
virtual bool customInitialization (std::weak_ptr< const ParametersHandler::IParametersHandler > handler)
These custom parameter specifications should be specified by the derived class.
virtual bool updateContactStates ()=0
The derived class must implement the contact detection technique to update the contact states.
Protected Attributes
State m_detectorState {State::NotInitialized}
State of the estimator.
EstimatedContactList m_contactStates
Additional Inherited Members
Public Types inherited from BipedalLocomotion::System::Advanceable< EmptySignal, EstimatedContactList >
using Input = EmptySignal
using Output = EstimatedContactList
Detailed Description
Definition at line 24 of file ContactDetector.h.
Member Enumeration Documentation
State
enum BipedalLocomotion::Contacts::ContactDetector::State strong protected
Enumerator used to determine the running state of the estimator.
Enumerator
NotInitialized
The estimator is not initialized yet call ContactDetector::initialze method to initialize it.
Initialized
The estimator is initialized and ready to be used.
Running
The estimator is running.
Definition at line 95 of file ContactDetector.h.
Member Function Documentation
advance()
bool ContactDetector::advance () final virtual
Compute one step of the detector The derived class must implement its own methods for setting measurements and update states to be called within the advance() method.
Returns
True in case of success, false otherwise.
Implements BipedalLocomotion::System::Advanceable< EmptySignal, EstimatedContactList >.
Definition at line 48 of file ContactDetector.cpp.
References BipedalLocomotion::log().
customInitialization()
bool ContactDetector::customInitialization (std::weak_ptr< const ParametersHandler::IParametersHandler > handler) protected virtual
These custom parameter specifications should be specified by the derived class.
Parameters
[in] handler configure the custom parameters for the estimator
Returns
True if success, false otherwise
Reimplemented in BipedalLocomotion::Contacts::SchmittTriggerDetector.
Definition at line 43 of file ContactDetector.cpp.
get() [1/2]
EstimatedContact ContactDetector::get (const std::string & contactName) const
Get state of specific contact.
Parameters
[in] contactName name of contact
Returns
contact state if contact exists, a dummy contact otherwise
Definition at line 96 of file ContactDetector.cpp.
References BipedalLocomotion::log().
get() [2/2]
bool ContactDetector::get (const std::string & contactName, Contacts::EstimatedContact & contact) const
Get state of specific contact.
Parameters
[in] contactName name of contact
[out] contact estimated contact
Returns
true if contact exists, false otherwise
Definition at line 84 of file ContactDetector.cpp.
References BipedalLocomotion::log().
getOutput()
const EstimatedContactList & ContactDetector::getOutput () const final
Get contact states.
Returns
container of contacts
Definition at line 79 of file ContactDetector.cpp.
initialize()
bool ContactDetector::initialize (std::weak_ptr< const ParametersHandler::IParametersHandler > handler) override virtual
Configure generic parameters.
Parameters
[in] handler configure the generic parameters for the estimator
Returns
True in case of success, false otherwise.
Reimplemented from BipedalLocomotion::System::Advanceable< EmptySignal, EstimatedContactList >.
Definition at line 14 of file ContactDetector.cpp.
References std::weak_ptr< T >::lock(), and BipedalLocomotion::log().
isOutputValid()
bool ContactDetector::isOutputValid () const final
Determines the validity of the object retrieved with get()
Returns
True in case of success, false otherwise.
Definition at line 107 of file ContactDetector.cpp.
resetContacts()
bool ContactDetector::resetContacts ()
Reset the internal contact states of the detector to false.
Returns
True in case of success, false otherwise.
Definition at line 69 of file ContactDetector.cpp.
updateContactStates()
virtual bool BipedalLocomotion::Contacts::ContactDetector::updateContactStates () protected pure virtual
The derived class must implement the contact detection technique to update the contact states.
Returns
True if success, false otherwise
Implemented in BipedalLocomotion::Contacts::SchmittTriggerDetector.
Field Documentation
m_detectorState
State BipedalLocomotion::Contacts::ContactDetector::m_detectorState {State::NotInitialized} protected
State of the estimator.
Definition at line 103 of file ContactDetector.h.
The documentation for this class was generated from the following files:
Contacts/include/BipedalLocomotion/ContactDetectors/ContactDetector.h
Contacts/src/ContactDetector.cpp