bipedal-locomotion-framework: BipedalLocomotion::YarpUtilities::RosPublisher Class Reference
BipedalLocomotion::YarpUtilities::RosPublisher Class Reference
The class internally contains a YARP based ROS node and a set of publishers.
#include <BipedalLocomotion/YarpUtilities/RosPublisher.h>
Data Structures
class Impl
Public Member Functions
RosPublisher (const std::string &nodeName)
Constructor.
~RosPublisher ()
Destructor.
bool initialize (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler)
Configures the publishers and ROS topics for publishing messages The parameters used to configure the RosPublisher,.
void stop ()
Clear internal configuration and close the node.
bool publishJointStates (const BipedalLocomotion::GenericContainer::Vector< const std::string >::Ref jointList, const BipedalLocomotion::GenericContainer::Vector< const double >::Ref jointPositions)
Publish the joint states over the configured joint states topic The joint velocities and joint efforts are set to zero.
bool publishJointStates (const BipedalLocomotion::GenericContainer::Vector< const std::string >::Ref jointList, const BipedalLocomotion::GenericContainer::Vector< const double >::Ref jointPositions, const BipedalLocomotion::GenericContainer::Vector< const double >::Ref jointVelocities)
Publish the joint states over the configured joint states topic The joint velocities and joint efforts are set to zero.
bool publishJointStates (const BipedalLocomotion::GenericContainer::Vector< const std::string >::Ref jointList, const BipedalLocomotion::GenericContainer::Vector< const double >::Ref jointPositions, const BipedalLocomotion::GenericContainer::Vector< const double >::Ref jointVelocities, const BipedalLocomotion::GenericContainer::Vector< const double >::Ref jointEfforts)
Publish the joint states over the configured joint states topic The joint velocities and joint efforts are set to zero.
bool publishWrench (const std::string &frameName, BipedalLocomotion::GenericContainer::Vector< const double >::Ref wrench6d)
Publish the wrenches over the configured wrench topic associated to the frame.
bool publishTransform (const std::string &target, const std::string &source, const BipedalLocomotion::GenericContainer::Vector< const double >::Ref transformAsVector16d)
Publish transforms to the transform server.
bool configureTransformServer (const std::string &transformServerPort)
Configure which transform server to connect to.
bool configureJointStatePublisher (const std::string &topicName)
Configure the topic over which joint states are published.
bool configureWrenchPublisher (const std::string &frameName, const std::string &topicName)
Add or reconfigure a wrench publisher.
bool removeWrenchPublisher (const std::string &frameName)
Remove wrench publisher.
RosPublisher (const RosPublisher &other)=delete
delete copy constructor
RosPublisher (RosPublisher &&other)=delete
delete move constructor
RosPublisher & operator= (const RosPublisher &other)=delete
delete copy assignment operator
RosPublisher & operator= (RosPublisher &&other)=delete
delete move assignment operator
Detailed Description
The class internally contains a YARP based ROS node and a set of publishers.
Current implementation consists of
Joint states publisher
Wrenches publisher
Transform broadcaster Although the class might be ROS independent, in order to run the code, ROS is required and usual YARP-ROS connections need to be made.
Definition at line 33 of file RosPublisher.h.
Constructor & Destructor Documentation
RosPublisher() [1/3]
RosPublisher::RosPublisher (const std::string & nodeName)
Constructor.
Parameters
[in] nodeName Name of the ROS publisher node
Definition at line 120 of file RosPublisher.cpp.
References std::endl().
~RosPublisher()
RosPublisher::~RosPublisher () default
Destructor.
RosPublisher() [2/3]
BipedalLocomotion::YarpUtilities::RosPublisher::RosPublisher (const RosPublisher & other) delete
delete copy constructor
RosPublisher() [3/3]
BipedalLocomotion::YarpUtilities::RosPublisher::RosPublisher (RosPublisher && other) delete
delete move constructor
Member Function Documentation
configureJointStatePublisher()
bool RosPublisher::configureJointStatePublisher (const std::string & topicName)
Configure the topic over which joint states are published.
Parameters
[in] topicName topic name
Definition at line 209 of file RosPublisher.cpp.
Referenced by initialize().
configureTransformServer()
bool RosPublisher::configureTransformServer (const std::string & transformServerPort)
Configure which transform server to connect to.
Parameters
[in] transformServerPort name of the transform server port
Definition at line 259 of file RosPublisher.cpp.
References std::endl().
Referenced by initialize().
configureWrenchPublisher()
bool RosPublisher::configureWrenchPublisher (const std::string & frameName, const std::string & topicName)
Add or reconfigure a wrench publisher.
Parameters
[in] frameName frame name
[in] topicName topic name
Definition at line 222 of file RosPublisher.cpp.
References std::endl().
Referenced by initialize().
initialize()
bool RosPublisher::initialize (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler)
Configures the publishers and ROS topics for publishing messages The parameters used to configure the RosPublisher,.
"joint_states_topic" name of the topic over which the joint states need to be published
"transform_server_port" name of the already running transform server's remote port
"WrenchPublishers" is group with the following parameters,
"frame_names" a list containing the frames at which the published wrenches should be expressed
"topics" a list containing the topics over which the wrenches need to be published. Must be the same size and order as frame_names.
Parameters
[in] handler Parameter handler
Note
this method needs to be called after construction and before publishing
Definition at line 132 of file RosPublisher.cpp.
References configureJointStatePublisher(), configureTransformServer(), configureWrenchPublisher(), std::endl(), std::weak_ptr< T >::lock(), and std::vector< T >::size().
operator=() [1/2]
RosPublisher& BipedalLocomotion::YarpUtilities::RosPublisher::operator= (const RosPublisher & other) delete
delete copy assignment operator
operator=() [2/2]
RosPublisher& BipedalLocomotion::YarpUtilities::RosPublisher::operator= (RosPublisher && other) delete
delete move assignment operator
publishJointStates() [1/3]
bool RosPublisher::publishJointStates (const BipedalLocomotion::GenericContainer::Vector< const std::string >::Ref jointList, const BipedalLocomotion::GenericContainer::Vector< const double >::Ref jointPositions)
Publish the joint states over the configured joint states topic The joint velocities and joint efforts are set to zero.
Parameters
[in] jointList list of joints
[in] jointPositions list of joint positions in m or rad with the same size as the joints list
Definition at line 337 of file RosPublisher.cpp.
References BipedalLocomotion::GenericContainer::Vector< T >::size().
publishJointStates() [2/3]
bool RosPublisher::publishJointStates (const BipedalLocomotion::GenericContainer::Vector< const std::string >::Ref jointList, const BipedalLocomotion::GenericContainer::Vector< const double >::Ref jointPositions, const BipedalLocomotion::GenericContainer::Vector< const double >::Ref jointVelocities)
Publish the joint states over the configured joint states topic The joint velocities and joint efforts are set to zero.
Parameters
[in] jointList list of joints
[in] jointPositions list of joint positions in m or rad with the same size as the joints list
[in] jointVelocities list of joint velocities in m/s or rad/s with the same size as the joints list
Definition at line 344 of file RosPublisher.cpp.
References BipedalLocomotion::GenericContainer::Vector< T >::size().
publishJointStates() [3/3]
bool RosPublisher::publishJointStates (const BipedalLocomotion::GenericContainer::Vector< const std::string >::Ref jointList, const BipedalLocomotion::GenericContainer::Vector< const double >::Ref jointPositions, const BipedalLocomotion::GenericContainer::Vector< const double >::Ref jointVelocities, const BipedalLocomotion::GenericContainer::Vector< const double >::Ref jointEfforts)
Publish the joint states over the configured joint states topic The joint velocities and joint efforts are set to zero.
Parameters
[in] jointList list of joints
[in] jointPositions list of joint positions in m or rad with the same size as the joints list
[in] jointVelocities list of joint velocities in m/s or rad/s with the same size as the joints list
[in] jointPositions list of joint torques/forces in Nm or N with the same size as the joints list
Definition at line 352 of file RosPublisher.cpp.
References std::endl(), and BipedalLocomotion::GenericContainer::Vector< T >::size().
publishTransform()
bool RosPublisher::publishTransform (const std::string & target, const std::string & source, const BipedalLocomotion::GenericContainer::Vector< const double >::Ref transformAsVector16d)
Publish transforms to the transform server.
Parameters
[in] target target frame for the transform
[in] source source frame of the transform
[in] transformAsVector16d 4x4 transform as a vector data in row-major order
Definition at line 287 of file RosPublisher.cpp.
References std::endl(), and BipedalLocomotion::GenericContainer::Vector< T >::size().
publishWrench()
bool RosPublisher::publishWrench (const std::string & frameName, BipedalLocomotion::GenericContainer::Vector< const double >::Ref wrench6d)
Publish the wrenches over the configured wrench topic associated to the frame.
Parameters
[in] frameName frame at which the wrench will be expressed
[in] wrench6d 6d wrench as force-torque in N-Nm with serialziation as fx fy fz tx ty tz
Definition at line 400 of file RosPublisher.cpp.
References std::endl(), and BipedalLocomotion::GenericContainer::Vector< T >::size().
removeWrenchPublisher()
bool RosPublisher::removeWrenchPublisher (const std::string & frameName)
Remove wrench publisher.
Parameters
[in] frameName frame name
Definition at line 242 of file RosPublisher.cpp.
References std::endl().
stop()
void RosPublisher::stop ()
Clear internal configuration and close the node.
Definition at line 468 of file RosPublisher.cpp.
References std::vector< T >::push_back().
The documentation for this class was generated from the following files:
YarpUtilities/include/BipedalLocomotion/YarpUtilities/RosPublisher.h
YarpUtilities/src/RosPublisher.cpp