bipedal-locomotion-framework: BipedalLocomotion::System::AdvanceableRunner< _Advanceable > Class Template Reference
BipedalLocomotion::System::AdvanceableRunner< _Advanceable > Class Template Reference
AdvanceableRunner is an helper class that can be used to run a advanceable at a given period.
#include <BipedalLocomotion/System/AdvanceableRunner.h>
Public Types
using Input = typename _Advanceable::Input
using Output = typename _Advanceable::Output
Public Member Functions
bool initialize (std::weak_ptr< const ParametersHandler::IParametersHandler > handler)
Initialize the AdvanceableRunner class.
bool setAdvanceable (std::unique_ptr< _Advanceable > advanceable)
Set the advanceable inside the runner.
bool setInputResource (std::shared_ptr< SharedResource< Input >> resource)
Set the input resource.
bool setOutputResource (std::shared_ptr< SharedResource< Output >> resource)
Set the output resource.
Info getInfo ()
Get some info of the runner,.
std::thread run ()
Run the advanceable runner.
void stop ()
Stop the thread.
Detailed Description
template<class _Advanceable>
class BipedalLocomotion::System::AdvanceableRunner< _Advanceable >
AdvanceableRunner is an helper class that can be used to run a advanceable at a given period.
Different AdvanceableRunners can communicate trough the SharedResource class. The AdvanceableRunner can be used only with Advanceable. Do not try to use if with a class that does not inherit from advanceable, a compile time assert will be thrown. This is a visual example of usage
Here we want to run two advanceables in parallel with a different sampling time. The AdvanceableRunner is a class that helps you in creating a periodic thread. The SharedResource is the way that can be used to communicate between two advanceables running in separate threads (i.e. the wired between two AdvanceableRunners)
Definition at line 40 of file AdvanceableRunner.h.
Member Function Documentation
getInfo()
template<class _Advanceable > AdvanceableRunner< _Advanceable >::Info BipedalLocomotion::System::AdvanceableRunner< _Advanceable >::getInfo
Get some info of the runner,.
Returns
A copy of the Info struct
Definition at line 335 of file AdvanceableRunner.h.
initialize()
template<class _Advanceable > bool BipedalLocomotion::System::AdvanceableRunner< _Advanceable >::initialize (std::weak_ptr< const ParametersHandler::IParametersHandler > handler)
Initialize the AdvanceableRunner class.
Parameters
handler pointer to a parameter handler
Note
The following parameters are required | Parameter Name | Type | Description | Mandatory | |:---------------—:|:-----—:|:------------------------------------------------------------------—:|:------—:| | sampling_time | double | Strictly positive number rapresenting the sampling time in seconds | Yes | | enable_telemetry | bool | If True some additional information are stored. Default value false | No |
Returns
true in case of success, false otherwise.
Definition at line 126 of file AdvanceableRunner.h.
References std::weak_ptr< T >::lock(), and BipedalLocomotion::log().
run()
template<class _Advanceable > std::thread BipedalLocomotion::System::AdvanceableRunner< _Advanceable >::run
Run the advanceable runner.
The function create a periodic thread running with a period of m_dT seconds.
Returns
a thread of containing the running process. If the runner was not correctly initialized the thread is invalid.
Definition at line 218 of file AdvanceableRunner.h.
References BipedalLocomotion::clock(), BipedalLocomotion::log(), BipedalLocomotion::System::IClock::now(), BipedalLocomotion::System::IClock::sleepUntil(), and BipedalLocomotion::System::IClock::yield().
setAdvanceable()
template<class _Advanceable > bool BipedalLocomotion::System::AdvanceableRunner< _Advanceable >::setAdvanceable (std::unique_ptr< _Advanceable > advanceable)
Set the advanceable inside the runner.
Parameters
advanceable an unique pointer representing the advanceable
Returns
true in case of success, false otherwise
Definition at line 171 of file AdvanceableRunner.h.
References BipedalLocomotion::log(), and std::move().
setInputResource()
template<class _Advanceable > bool BipedalLocomotion::System::AdvanceableRunner< _Advanceable >::setInputResource (std::shared_ptr< SharedResource< Input >> resource)
Set the input resource.
Parameters
resource pointer representing the input resource
Returns
true in case of success, false otherwise
Definition at line 186 of file AdvanceableRunner.h.
References BipedalLocomotion::log().
setOutputResource()
template<class _Advanceable > bool BipedalLocomotion::System::AdvanceableRunner< _Advanceable >::setOutputResource (std::shared_ptr< SharedResource< Output >> resource)
Set the output resource.
Parameters
resource pointer representing the output resource
Returns
true in case of success, false otherwise
Definition at line 202 of file AdvanceableRunner.h.
References BipedalLocomotion::log().
stop()
template<class _Advanceable > void BipedalLocomotion::System::AdvanceableRunner< _Advanceable >::stop
Stop the thread.
Returns
true in case of success, false otherwise
Definition at line 328 of file AdvanceableRunner.h.
The documentation for this class was generated from the following file:
System/include/BipedalLocomotion/System/AdvanceableRunner.h