bipedal-locomotion-framework: BipedalLocomotion::ParametersHandler::StdImplementation Class Reference
BipedalLocomotion::ParametersHandler::StdImplementation Class Reference
Parameters handler interface.
#include <BipedalLocomotion/ParametersHandler/StdImplementation.h>
Public Member Functions
StdImplementation (const std::unordered_map< std::string, std::any > &map)
Constructor.
StdImplementation ()=default
Constructor.
void set (const std::unordered_map< std::string, std::any > &searchable)
Set the handler from an object.
bool getParameter (const std::string &parameterName, int &parameter) const final
Get a parameter [int].
bool getParameter (const std::string &parameterName, double &parameter) const final
Get a parameter [double].
bool getParameter (const std::string &parameterName, std::string &parameter) const final
Get a parameter [std::string].
bool getParameter (const std::string &parameterName, bool &parameter) const final
Get a parameter [bool].
bool getParameter (const std::string &parameterName, std::vector< bool > &parameter) const final
Get a parameter [std::vector<bool>].
bool getParameter (const std::string &parameterName, GenericContainer::Vector< int >::Ref parameter) const final
Get a parameter [GenericContainer::Vector<int>].
bool getParameter (const std::string &parameterName, GenericContainer::Vector< double >::Ref parameter) const final
Get a parameter [GenericContainer::Vector<double>].
bool getParameter (const std::string &parameterName, GenericContainer::Vector< std::string >::Ref parameter) const final
Get a parameter [GenericContainer::Vector<std::string>].
void setParameter (const std::string &parameterName, const int &parameter) final
Set a parameter [int].
void setParameter (const std::string &parameterName, const double &parameter) final
Set a parameter [double].
void setParameter (const std::string &parameterName, const std::string &parameter) final
Set a parameter [std::string].
void setParameter (const std::string &parameterName, const char *parameter) final
Set a parameter [const char*].
void setParameter (const std::string &parameterName, const bool &parameter) final
Set a parameter [bool].
void setParameter (const std::string &parameterName, const std::vector< bool > &parameter) final
Set a parameter [std::vector<bool>].
void setParameter (const std::string &parameterName, const GenericContainer::Vector< const int >::Ref parameter) final
Set a parameter [GenericContainer::Vector<int>].
void setParameter (const std::string &parameterName, const GenericContainer::Vector< const double >::Ref parameter) final
Set a parameter [GenericContainer::Vector<double>].
void setParameter (const std::string &parameterName, const GenericContainer::Vector< const std::string >::Ref parameter) final
Set a parameter [GenericContainer::Vector<std::string>].
weak_ptr getGroup (const std::string &name) const final
Get a Group from the handler.
bool setGroup (const std::string &name, shared_ptr newGroup) final
Set a new group on the handler.
std::string toString () const final
Return a standard text representation of the content of the object.
bool isEmpty () const final
Check if the handler contains parameters.
void clear () final
Clears the handler from all the parameters.
shared_ptr clone () const final
Clone the content of the content.
Public Member Functions inherited from BipedalLocomotion::ParametersHandler::IParametersHandler
virtual ~IParametersHandler ()=default
Destructor.
Additional Inherited Members
Public Types inherited from BipedalLocomotion::ParametersHandler::IParametersHandler
using unique_ptr = std::unique_ptr< IParametersHandler >
using shared_ptr = std::shared_ptr< IParametersHandler >
using weak_ptr = std::weak_ptr< IParametersHandler >
Detailed Description
Parameters handler interface.
Definition at line 27 of file StdImplementation.h.
Constructor & Destructor Documentation
StdImplementation() [1/2]
BipedalLocomotion::ParametersHandler::StdImplementation::StdImplementation (const std::unordered_map< std::string, std::any > & map) inline
Constructor.
Parameters
map reference to a map object. The object is copied inside the Handler
Definition at line 56 of file StdImplementation.h.
StdImplementation() [2/2]
BipedalLocomotion::ParametersHandler::StdImplementation::StdImplementation () default
Constructor.
Member Function Documentation
clear()
void StdImplementation::clear () final virtual
Clears the handler from all the parameters.
Implements BipedalLocomotion::ParametersHandler::IParametersHandler.
Definition at line 168 of file StdImplementation.cpp.
References std::unordered_map< K, T >::clear().
clone()
IParametersHandler::shared_ptr StdImplementation::clone () const final virtual
Clone the content of the content.
Returns
a IParametersHandler::shared_ptr clone of the current handler.
Implements BipedalLocomotion::ParametersHandler::IParametersHandler.
Definition at line 173 of file StdImplementation.cpp.
getGroup()
IParametersHandler::weak_ptr StdImplementation::getGroup (const std::string & name) const final virtual
Get a Group from the handler.
Parameters
name name of the group
Returns
A pointer to IParametersHandler, if the group is not found the weak pointer cannot be locked
Implements BipedalLocomotion::ParametersHandler::IParametersHandler.
Definition at line 127 of file StdImplementation.cpp.
References std::unordered_map< K, T >::end(), std::unordered_map< K, T >::find(), and BipedalLocomotion::log().
getParameter() [1/8]
bool StdImplementation::getParameter (const std::string & parameterName, bool & parameter) const final virtual
Get a parameter [bool].
Parameters
parameterName name of the parameter
parameter parameter
Returns
true/false in case of success/failure
Implements BipedalLocomotion::ParametersHandler::IParametersHandler.
Definition at line 68 of file StdImplementation.cpp.
getParameter() [2/8]
bool StdImplementation::getParameter (const std::string & parameterName, double & parameter) const final virtual
Get a parameter [double].
Parameters
parameterName name of the parameter
parameter parameter
Returns
true/false in case of success/failure
Implements BipedalLocomotion::ParametersHandler::IParametersHandler.
Definition at line 56 of file StdImplementation.cpp.
getParameter() [3/8]
bool StdImplementation::getParameter (const std::string & parameterName, GenericContainer::Vector< double >::Ref parameter) const final virtual
Get a parameter [GenericContainer::Vector<double>].
Parameters
parameterName name of the parameter
parameter parameter
Returns
true/false in case of success/failure
Implements BipedalLocomotion::ParametersHandler::IParametersHandler.
Definition at line 39 of file StdImplementation.cpp.
getParameter() [4/8]
bool StdImplementation::getParameter (const std::string & parameterName, GenericContainer::Vector< int >::Ref parameter) const final virtual
Get a parameter [GenericContainer::Vector<int>].
Parameters
parameterName name of the parameter
parameter parameter
Returns
true/false in case of success/failure
Implements BipedalLocomotion::ParametersHandler::IParametersHandler.
Definition at line 33 of file StdImplementation.cpp.
getParameter() [5/8]
bool StdImplementation::getParameter (const std::string & parameterName, GenericContainer::Vector< std::string >::Ref parameter) const final virtual
Get a parameter [GenericContainer::Vector<std::string>].
Parameters
parameterName name of the parameter
parameter parameter
Returns
true/false in case of success/failure
Implements BipedalLocomotion::ParametersHandler::IParametersHandler.
Definition at line 45 of file StdImplementation.cpp.
getParameter() [6/8]
bool StdImplementation::getParameter (const std::string & parameterName, int & parameter) const final virtual
Get a parameter [int].
Parameters
parameterName name of the parameter
parameter parameter
Returns
true/false in case of success/failure
Implements BipedalLocomotion::ParametersHandler::IParametersHandler.
Definition at line 51 of file StdImplementation.cpp.
getParameter() [7/8]
bool StdImplementation::getParameter (const std::string & parameterName, std::string & parameter) const final virtual
Get a parameter [std::string].
Parameters
parameterName name of the parameter
parameter parameter
Returns
true/false in case of success/failure
Implements BipedalLocomotion::ParametersHandler::IParametersHandler.
Definition at line 62 of file StdImplementation.cpp.
getParameter() [8/8]
bool StdImplementation::getParameter (const std::string & parameterName, std::vector< bool > & parameter) const final virtual
Get a parameter [std::vector<bool>].
Parameters
parameterName name of the parameter
parameter parameter
Returns
true/false in case of success/failure
Implements BipedalLocomotion::ParametersHandler::IParametersHandler.
Definition at line 73 of file StdImplementation.cpp.
isEmpty()
bool StdImplementation::isEmpty () const final virtual
Check if the handler contains parameters.
Returns
true if the handler does not contain any parameters, false otherwise
Implements BipedalLocomotion::ParametersHandler::IParametersHandler.
Definition at line 163 of file StdImplementation.cpp.
References std::unordered_map< K, T >::size().
set()
void StdImplementation::set (const std::unordered_map< std::string, std::any > & searchable)
Set the handler from an object.
Parameters
object The object to copy
Definition at line 149 of file StdImplementation.cpp.
setGroup()
bool StdImplementation::setGroup (const std::string & name, IParametersHandler::shared_ptr newGroup) final virtual
Set a new group on the handler.
Parameters
name name of the group
newGroup shared pointer to the new group
Implements BipedalLocomotion::ParametersHandler::IParametersHandler.
Definition at line 112 of file StdImplementation.cpp.
References BipedalLocomotion::log().
setParameter() [1/9]
void StdImplementation::setParameter (const std::string & parameterName, const bool & parameter) final virtual
Set a parameter [bool].
Parameters
parameterName name of the parameter
parameter parameter
Implements BipedalLocomotion::ParametersHandler::IParametersHandler.
Definition at line 101 of file StdImplementation.cpp.
setParameter() [2/9]
void StdImplementation::setParameter (const std::string & parameterName, const char * parameter) final virtual
Set a parameter [const char*].
Note
this is required because of https://www.bfilipek.com/2019/07/surprising-conversions-char-bool.html
Parameters
parameterName name of the parameter
parameter parameter
Implements BipedalLocomotion::ParametersHandler::IParametersHandler.
Definition at line 90 of file StdImplementation.cpp.
setParameter() [3/9]
void StdImplementation::setParameter (const std::string & parameterName, const double & parameter) final virtual
Set a parameter [double].
Parameters
parameterName name of the parameter
parameter parameter
Implements BipedalLocomotion::ParametersHandler::IParametersHandler.
Definition at line 84 of file StdImplementation.cpp.
setParameter() [4/9]
void StdImplementation::setParameter (const std::string & parameterName, const GenericContainer::Vector< const double >::Ref parameter) final virtual
Set a parameter [GenericContainer::Vector<double>].
Parameters
parameterName name of the parameter
parameter parameter
Implements BipedalLocomotion::ParametersHandler::IParametersHandler.
Definition at line 21 of file StdImplementation.cpp.
setParameter() [5/9]
void StdImplementation::setParameter (const std::string & parameterName, const GenericContainer::Vector< const int >::Ref parameter) final virtual
Set a parameter [GenericContainer::Vector<int>].
Parameters
parameterName name of the parameter
parameter parameter
Implements BipedalLocomotion::ParametersHandler::IParametersHandler.
Definition at line 15 of file StdImplementation.cpp.
setParameter() [6/9]
void StdImplementation::setParameter (const std::string & parameterName, const GenericContainer::Vector< const std::string >::Ref parameter) final virtual
Set a parameter [GenericContainer::Vector<std::string>].
Parameters
parameterName name of the parameter
parameter parameter
Implements BipedalLocomotion::ParametersHandler::IParametersHandler.
Definition at line 27 of file StdImplementation.cpp.
setParameter() [7/9]
void StdImplementation::setParameter (const std::string & parameterName, const int & parameter) final virtual
Set a parameter [int].
Parameters
parameterName name of the parameter
parameter parameter
Implements BipedalLocomotion::ParametersHandler::IParametersHandler.
Definition at line 79 of file StdImplementation.cpp.
setParameter() [8/9]
void StdImplementation::setParameter (const std::string & parameterName, const std::string & parameter) final virtual
Set a parameter [std::string].
Parameters
parameterName name of the parameter
parameter parameter
Implements BipedalLocomotion::ParametersHandler::IParametersHandler.
Definition at line 95 of file StdImplementation.cpp.
setParameter() [9/9]
void StdImplementation::setParameter (const std::string & parameterName, const std::vector< bool > & parameter) final virtual
Set a parameter [std::vector<bool>].
Parameters
parameterName name of the parameter
parameter parameter
Implements BipedalLocomotion::ParametersHandler::IParametersHandler.
Definition at line 106 of file StdImplementation.cpp.
toString()
std::string StdImplementation::toString () const final virtual
Return a standard text representation of the content of the object.
Returns
a string containing the standard text representation of the content of the object.
Implements BipedalLocomotion::ParametersHandler::IParametersHandler.
Definition at line 154 of file StdImplementation.cpp.
The documentation for this class was generated from the following files:
ParametersHandler/include/BipedalLocomotion/ParametersHandler/StdImplementation.h
ParametersHandler/include/BipedalLocomotion/ParametersHandler/StdImplementation.tpp
ParametersHandler/src/StdImplementation.cpp