bipedal-locomotion-framework: BipedalLocomotion::System::VariablesHandler Class Reference
BipedalLocomotion::System::VariablesHandler Class Reference
VariableHandler is useful to handle variables in an optimization problem, Their name, dimension and position.
#include <BipedalLocomotion/System/VariablesHandler.h>
Data Structures
struct VariableDescription
Public Member Functions
bool initialize (std::weak_ptr< const ParametersHandler::IParametersHandler > handler) noexcept
Initialize the VariablesHandler class.
bool addVariable (const std::string &name, const std::size_t &size) noexcept
Add a new variable to the list.
const VariableDescription & getVariable (const std::string &name) const noexcept
Get a variable from the list.
bool getVariable (const std::string &name, VariableDescription &description) const noexcept
Get a variable from the list.
const std::size_t & getNumberOfVariables () const noexcept
Get the number of variables.
std::string toString () const noexcept
Get the string representation of the handler.
void clear () noexcept
Clear the content of the handler.
Detailed Description
VariableHandler is useful to handle variables in an optimization problem, Their name, dimension and position.
Definition at line 26 of file VariablesHandler.h.
Member Function Documentation
addVariable()
bool VariablesHandler::addVariable (const std::string & name, const std::size_t & size) noexcept
Add a new variable to the list.
Parameters
name of the variable
size the size of the variable
Returns
true/false in case of success/failure
Definition at line 90 of file VariablesHandler.cpp.
References BipedalLocomotion::log().
clear()
void VariablesHandler::clear () noexcept
Clear the content of the handler.
Definition at line 147 of file VariablesHandler.cpp.
getNumberOfVariables()
const std::size_t & VariablesHandler::getNumberOfVariables () const noexcept
Get the number of variables.
Returns
the total number of variables
Definition at line 130 of file VariablesHandler.cpp.
Referenced by BipedalLocomotion::IK::QPInverseKinematics::finalize(), BipedalLocomotion::IK::JointTrackingTask::setVariablesHandler(), BipedalLocomotion::TSID::JointTrackingTask::setVariablesHandler(), BipedalLocomotion::TSID::SO3Task::setVariablesHandler(), BipedalLocomotion::IK::SO3Task::setVariablesHandler(), BipedalLocomotion::IK::CoMTask::setVariablesHandler(), BipedalLocomotion::TSID::SE3Task::setVariablesHandler(), BipedalLocomotion::IK::SE3Task::setVariablesHandler(), BipedalLocomotion::TSID::BaseDynamicsTask::setVariablesHandler(), and BipedalLocomotion::TSID::JointDynamicsTask::setVariablesHandler().
getVariable() [1/2]
const VariablesHandler::VariableDescription & VariablesHandler::getVariable (const std::string & name) const noexcept
Get a variable from the list.
Parameters
name of the variable
Returns
the variable description associated to the variable
Definition at line 111 of file VariablesHandler.cpp.
Referenced by BipedalLocomotion::IK::QPInverseKinematics::finalize(), BipedalLocomotion::IK::JointTrackingTask::setVariablesHandler(), BipedalLocomotion::TSID::JointTrackingTask::setVariablesHandler(), BipedalLocomotion::TSID::SO3Task::setVariablesHandler(), BipedalLocomotion::IK::SO3Task::setVariablesHandler(), BipedalLocomotion::IK::CoMTask::setVariablesHandler(), BipedalLocomotion::TSID::SE3Task::setVariablesHandler(), BipedalLocomotion::IK::SE3Task::setVariablesHandler(), BipedalLocomotion::TSID::BaseDynamicsTask::setVariablesHandler(), and BipedalLocomotion::TSID::JointDynamicsTask::setVariablesHandler().
getVariable() [2/2]
bool VariablesHandler::getVariable (const std::string & name, VariablesHandler::VariableDescription & description) const noexcept
Get a variable from the list.
Parameters
name of the variable
[out] description the description of the variable
Returns
true/false in case of success/failure
Definition at line 124 of file VariablesHandler.cpp.
initialize()
bool VariablesHandler::initialize (std::weak_ptr< const ParametersHandler::IParametersHandler > handler) noexcept
Initialize the VariablesHandler class.
This method calls VariablesHandler::addVariable using the parameters stored in the handler
Parameters
handler pointer to parameters handler @notice The following parameters are required
Parameter Name Type Description Mandatory
variables_name vector<string> List containing the name of the variables Yes
variables_size vector<int> List containing the size of the variables. The size must be a strictly positive number Yes
Warning
The previous content of the VariablesHandler is erased.
Returns
true/false in case of success/failure
Definition at line 26 of file VariablesHandler.cpp.
References std::vector< T >::begin(), std::vector< T >::end(), std::find_if(), BipedalLocomotion::log(), and std::vector< T >::size().
toString()
std::string VariablesHandler::toString () const noexcept
Get the string representation of the handler.
Returns
a string containing the name of all the variables and their description.
Definition at line 135 of file VariablesHandler.cpp.
References std::to_string().
The documentation for this class was generated from the following files:
System/include/BipedalLocomotion/System/VariablesHandler.h
System/src/VariablesHandler.cpp