bipedal-locomotion-framework: BipedalLocomotion::RobotInterface::YarpSensorBridge Class Reference
BipedalLocomotion::RobotInterface::YarpSensorBridge Class Reference
YarpSensorBridge Yarp implementation of the ISensorBridge interface Currently available interfaces.
#include <BipedalLocomotion/RobotInterface/YarpSensorBridge.h>
Data Structures
struct Impl
Public Member Functions
YarpSensorBridge ()
Constructor.
~YarpSensorBridge ()
Destructor.
bool initialize (std::weak_ptr< const ParametersHandler::IParametersHandler > handler) final
Initialize estimator.
bool setDriversList (const yarp::dev::PolyDriverList &deviceDriversList)
Set the list of device drivers from which the sensor measurements need to be streamed.
bool advance () final
Advance the internal state.
bool isOutputValid () const final
Determines the validity of the object retrieved with get()
std::vector< std::string > getFailedSensorReads () const
list of sensors that was failed to be read in the current advance() step
const SensorBridgeMetaData & getOutput () const final
Get the object.
bool getJointsList (std::vector< std::string > &jointsList) final
Get joints list.
bool getIMUsList (std::vector< std::string > &IMUsList) final
Get imu sensors.
bool getLinearAccelerometersList (std::vector< std::string > &linearAccelerometersList) final
Get linear accelerometers.
bool getGyroscopesList (std::vector< std::string > &gyroscopesList) final
Get gyroscopes.
bool getOrientationSensorsList (std::vector< std::string > &orientationSensorsList) final
Get orientation sensors.
bool getMagnetometersList (std::vector< std::string > &magnetometersList) final
Get magnetometers sensors.
bool getSixAxisForceTorqueSensorsList (std::vector< std::string > &sixAxisForceTorqueSensorsList) final
Get 6 axis FT sensors.
bool getThreeAxisForceTorqueSensorsList (std::vector< std::string > &threeAxisForceTorqueSensorsList) final
Get 6 axis FT sensors.
bool getCartesianWrenchesList (std::vector< std::string > &cartesianWrenchesList) final
Get cartesian wrenches.
bool getJointPosition (const std::string &jointName, double &jointPosition, OptionalDoubleRef receiveTimeInSeconds={}) final
Get joint position in radians.
bool getJointPositions (Eigen::Ref< Eigen::VectorXd > jointPositions, OptionalDoubleRef receiveTimeInSeconds={}) final
Get all joints' positions in radians.
bool getJointVelocity (const std::string &jointName, double &jointVelocity, OptionalDoubleRef receiveTimeInSeconds={}) final
Get joint velocity in rad/s.
bool getJointVelocities (Eigen::Ref< Eigen::VectorXd > jointVelocties, OptionalDoubleRef receiveTimeInSeconds={}) final
Get all joints' velocities in rad/s.
bool getIMUMeasurement (const std::string &imuName, Eigen::Ref< Vector12d > imuMeasurement, OptionalDoubleRef receiveTimeInSeconds={}) final
Get IMU measurement The serialization of measurments is as follows, (rpy acc omega mag)
bool getLinearAccelerometerMeasurement (const std::string &accName, Eigen::Ref< Eigen::Vector3d > accMeasurement, OptionalDoubleRef receiveTimeInSeconds={}) final
Get linear accelerometer measurement in m/s^2.
bool getGyroscopeMeasure (const std::string &gyroName, Eigen::Ref< Eigen::Vector3d > gyroMeasurement, OptionalDoubleRef receiveTimeInSeconds={}) final
Get gyroscope measurement in rad/s.
bool getOrientationSensorMeasurement (const std::string &rpyName, Eigen::Ref< Eigen::Vector3d > rpyMeasurement, OptionalDoubleRef receiveTimeInSeconds={}) final
Get orientation sensor measurement in radians as roll pitch yaw Euler angles.
bool getMagnetometerMeasurement (const std::string &magName, Eigen::Ref< Eigen::Vector3d > magMeasurement, OptionalDoubleRef receiveTimeInSeconds={}) final
Get magentometer measurement in tesla.
bool getSixAxisForceTorqueMeasurement (const std::string &ftName, Eigen::Ref< Vector6d > ftMeasurement, OptionalDoubleRef receiveTimeInSeconds={}) final
Get six axis force torque measurement.
bool getThreeAxisForceTorqueMeasurement (const std::string &ftName, Eigen::Ref< Eigen::Vector3d > ftMeasurement, OptionalDoubleRef receiveTimeInSeconds={}) final
Get three axis force-torque measurement containing normal force (N) and tangential moments (Nm)
bool getCartesianWrench (const std::string &cartesianWrenchName, Eigen::Ref< Vector6d > cartesianWrenchMeasurement, OptionalDoubleRef receiveTimeInSeconds={}) final
Get 6D end effector wrenches in N and Nm for forces and torques respectively.
bool getMotorCurrent (const std::string &jointName, double &motorCurrent, OptionalDoubleRef receiveTimeInSeconds={}) final
Get motor current in ampere.
bool getMotorCurrents (Eigen::Ref< Eigen::VectorXd > motorCurrents, OptionalDoubleRef receiveTimeInSeconds={}) final
Get all motors' currents in ampere.
Public Member Functions inherited from BipedalLocomotion::RobotInterface::ISensorBridge
virtual ~ISensorBridge ()=default
Destructor.
Public Member Functions inherited from BipedalLocomotion::System::Source< SensorBridgeMetaData >
bool setInput (const EmptySignal &input) final
Get the object.
Public Member Functions inherited from BipedalLocomotion::System::Advanceable< EmptySignal, SensorBridgeMetaData >
virtual const Output & getOutput () const=0
Get the output of the advanceable.
virtual bool isOutputValid () const=0
Determines the validity of the object retrieved with getOutput()
virtual bool close ()
Close the Advanceable.
Additional Inherited Members
Public Types inherited from BipedalLocomotion::RobotInterface::ISensorBridge
using unique_ptr = std::unique_ptr< ISensorBridge >
using shared_ptr = std::shared_ptr< ISensorBridge >
using weak_ptr = std::weak_ptr< ISensorBridge >
using OptionalDoubleRef = std::optional< std::reference_wrapper< double > >
using Vector12d = Eigen::Matrix< double, 12, 1 >
using Vector6d = Eigen::Matrix< double, 6, 1 >
Public Types inherited from BipedalLocomotion::System::Advanceable< EmptySignal, SensorBridgeMetaData >
using Input = EmptySignal
using Output = SensorBridgeMetaData
Protected Member Functions inherited from BipedalLocomotion::RobotInterface::ISensorBridge
virtual bool populateSensorBridgeOptionsFromConfig (std::weak_ptr< const ParametersHandler::IParametersHandler > handler, SensorBridgeOptions &sensorBridgeOptions)
Helper method to maintain SensorBridgeOptions struct by populating it from the configuration parameters.
virtual bool populateSensorListsFromConfig (std::weak_ptr< const ParametersHandler::IParametersHandler > handler, const SensorBridgeOptions &sensorBridgeOptions, SensorLists &sensorLists)
Helper method to maintain SensorLists struct by populating it from the configuration parameters.
virtual bool populateSensorBridgeMetaDataFromConfig (std::weak_ptr< const ParametersHandler::IParametersHandler > handler, SensorBridgeMetaData &sensorBridgeMetaData)
Helper method to maintain SensorBridgeMetaData struct by populating it from the configuration parameters.
Detailed Description
YarpSensorBridge Yarp implementation of the ISensorBridge interface Currently available interfaces.
Remapped Remote Control Board for joint states
Inertial Measurement Units through generic sensor interface and remapped multiple analog sensor interface
Whole Body Dynamics Estimated end effector wrenches through a generic sensor interface
Force Torque Sensors through analog sensor interface and remapped multiple analog sensor interface
Depth Cameras through RGBD sensor interface
Camera images through OpenCV Grabber interface
The YarpSensorBridge expects a list of device drivers through the yarp::dev::PolyDriverList object. Each PolyDriver object in the list is compared with the configured sensor names and the assumptions listed below to infer the sensor types and relevant interfaces in order to to read the relevant data.
MAJOR ASSUMPTIONS
Every sensor unit(device driver) attached to this Bridge is identified by a unique name
A single instance of a remote control board remapper and a multiple analog sensor remapper is expected if the suer wants to use the control board interfaces and multiple analog sensor interfaces
Any generic sensor interface with channel dimensions of 6 is considered to be a cartesian wrench interface
Any generic sensor interface with channel dimensions of 12 is considered as a IMU interface (server inertial)
Any analog sensor interface with channel dimensions of 6 is considered as a force torque sensor interface
The images are available through a FrameGrabber interface (RGB only) and a RGBD interface (RGB and Depth).
The current internal design (read all sensors in a serial fashion) may not be suitable for a heavy measurement set
The parameters for writing the configuration file for this class is given as,
Group Parameter Type Description
check_for_nan boolean flag to activate checking for NANs in the incoming measurement buffers, not applicable for images
stream_joint_states boolean Flag to activate the attachment to IMU sensor devices
stream_inertials boolean Flag to activate the attachment to IMU sensor devices
stream_cartesian_wrenches boolean Flag to activate the attachment to Cartesian wrench related devices
stream_forcetorque_sensors boolean Flag to activate the attachment to six axis FT sensor devices
stream_cameras boolean Flag to activate the attachment to Cameras devices
RemoteControlBoardRemapper Expects only one remapped remotecontrolboard device attached to it, if there multiple remote control boards, then use a remapper to create a single remotecontrolboard
joints_list vector of strings This parameter is optional. The joints list used to open the remote control board remapper. If the list is not passed, the order of the joint stored in the PolyDriver is used
InertialSensors Expects IMU to be opened as genericSensorClient devices communicating through the inertial server and other inertials as a part multiple analog sensors remapper ("multipleanalogsensorsremapper")
imu_list vector of strings list of the names of devices opened as genericSensorClient device and having a channel dimension of 12
gyroscopes_list vector of strings list of the names of devices opened with ThreeAxisGyroscope interface remapped through the "multipleanalogsensorsremapper" interfaces and having a channel dimension of 3
accelerometers_list vector of strings list of the names of devices opened with ThreeAxisLinearAccelerometers interface remapped through the "multipleanalogsensorsremapper" interfaces and having a channel dimension of 3
orientation_sensors_list vector of strings list of the names of devices opened with OrientationSensors interface remapped through the "multipleanalogsensorsremapper" interfaces and having a channel dimension of 3
magnetometers_list vector of strings list of the names of devices opened with ThreeAxisMagnetometer interface remapped through the "multipleanalogsensorsremapper" interfaces and having a channel dimension of 3
CartesianWrenches Expects the devices wrapping the cartesian wrenches ports to be opened as "genericSensorClient" device and have a channel dimension of 6
cartesian_wrenches_list vector of strings list of the names of devices opened as genericSensorClient device and having a channel dimension of 6
SixAxisForceTorqueSensors Expects the Six axis FT sensors to be opened with SixAxisForceTorqueSensors interface remapped through multiple analog sensors remapper ("multipleanalogsensorsremapper") or to be opened as analog sensor ("analogsensorclient") device having channel dimensions as 6
sixaxis_forcetorque_sensors_list vector of strings list of six axis FT sensors (the difference between a MAS FT and an analog FT is done internally assuming that the names are distinct form each other)
Cameras Expects cameras to be opened either as remote frame grabber ("RemoteFrameGrabber") with IFrameGrabber interface or rgbd sensor ("RGBDSensorClient") with IRGBDSensor interface
rgbd_list vector of strings list containing the devices opened as RGBDSensorClients containing the IRGBD sensor interface
rgbd_image_width vector of strings list containing the image width dimensions of RGBD cameras. Required parameter if cameras are enabled. The list must be the same size and order as rgbd_list
rgbd_image_height vector of strings list containing the image height dimensions of RGBD cameras. Required parameter if cameras are enabled. The list must be the same size and order as rgbd_list
rgb_cameras_list vector of strings list containing the devices opened as RemoteFrameGrabber devices containing the IFrameGrabber interface
rgb_image_width vector of strings list containing the image width dimensions of RGB cameras. Required parameter if cameras are enabled. The list must be the same size and order as rgb_list
rgb_image_height vector of strings list containing the image height dimensions of RGB cameras. Required parameter if cameras are enabled. The list must be the same size and order as rgb_list
Definition at line 81 of file YarpSensorBridge.h.
Constructor & Destructor Documentation
YarpSensorBridge()
YarpSensorBridge::YarpSensorBridge ()
Constructor.
Definition at line 17 of file YarpSensorBridge.cpp.
~YarpSensorBridge()
YarpSensorBridge::~YarpSensorBridge () default
Destructor.
Member Function Documentation
advance()
bool YarpSensorBridge::advance () final virtual
Advance the internal state.
This may change the value retrievable from get().
Returns
True if the advance is successful.
Implements BipedalLocomotion::System::Advanceable< EmptySignal, SensorBridgeMetaData >.
Definition at line 125 of file YarpSensorBridge.cpp.
References BipedalLocomotion::log().
getCartesianWrench()
bool YarpSensorBridge::getCartesianWrench (const std::string & cartesianWrenchName, Eigen::Ref< Vector6d > cartesianWrenchMeasurement, OptionalDoubleRef receiveTimeInSeconds = {}) final virtual
Get 6D end effector wrenches in N and Nm for forces and torques respectively.
Parameters
[in] cartesianWrenchName name of the end effector wrench
[out] cartesianWrenchMeasurement end effector wrench measurement of size 6
[out] rreceiveTimeInSeconds time at which the measurement was received
Returns
true/false in case of success/failure
Reimplemented from BipedalLocomotion::RobotInterface::ISensorBridge.
Definition at line 411 of file YarpSensorBridge.cpp.
getCartesianWrenchesList()
bool YarpSensorBridge::getCartesianWrenchesList (std::vector< std::string > & cartesianWrenchesList) final virtual
Get cartesian wrenches.
Parameters
[out] cartesianWrenchesList list of cartesian wrenches attached to the bridge
Returns
true/false in case of success/failure
Reimplemented from BipedalLocomotion::RobotInterface::ISensorBridge.
Definition at line 225 of file YarpSensorBridge.cpp.
getFailedSensorReads()
std::vector< std::string > YarpSensorBridge::getFailedSensorReads () const
list of sensors that was failed to be read in the current advance() step
Returns
list of sensors as a vector of strings
Definition at line 143 of file YarpSensorBridge.cpp.
getGyroscopeMeasure()
bool YarpSensorBridge::getGyroscopeMeasure (const std::string & gyroName, Eigen::Ref< Eigen::Vector3d > gyroMeasurement, OptionalDoubleRef receiveTimeInSeconds = {}) final virtual
Get gyroscope measurement in rad/s.
Parameters
[in] gyroName name of the gyroscope
[out] gyroMeasurement gyroscope measurements of size 3
[out] receiveTimeInSeconds time at which the measurement was received
Returns
true/false in case of success/failure
Reimplemented from BipedalLocomotion::RobotInterface::ISensorBridge.
Definition at line 339 of file YarpSensorBridge.cpp.
getGyroscopesList()
bool YarpSensorBridge::getGyroscopesList (std::vector< std::string > & gyroscopesList) final virtual
Get gyroscopes.
Parameters
[out] gyroscopesList list of gyroscopes attached to the bridge
Returns
true/false in case of success/failure
Reimplemented from BipedalLocomotion::RobotInterface::ISensorBridge.
Definition at line 184 of file YarpSensorBridge.cpp.
getIMUMeasurement()
bool YarpSensorBridge::getIMUMeasurement (const std::string & imuName, Eigen::Ref< Vector12d > imuMeasurement, OptionalDoubleRef receiveTimeInSeconds = {}) final virtual
Get IMU measurement The serialization of measurments is as follows, (rpy acc omega mag)
rpy in radians Roll-Pitch-Yaw Euler angles
acc in m/s^2 linear accelerometer measurements
omega in rad/s gyroscope measurements
mag in tesla magnetometer measurements
Parameters
[in] imuName name of the IMU
[out] imuMeasurement imu measurement of size 12
[out] receiveTimeInSeconds time at which the measurement was received
Returns
true/false in case of success/failure
Reimplemented from BipedalLocomotion::RobotInterface::ISensorBridge.
Definition at line 303 of file YarpSensorBridge.cpp.
getIMUsList()
bool YarpSensorBridge::getIMUsList (std::vector< std::string > & IMUsList) final virtual
Get imu sensors.
Parameters
[out] IMUsList list of IMUs attached to the bridge
Returns
true/false in case of success/failure
Reimplemented from BipedalLocomotion::RobotInterface::ISensorBridge.
Definition at line 163 of file YarpSensorBridge.cpp.
getJointPosition()
bool YarpSensorBridge::getJointPosition (const std::string & jointName, double & jointPosition, OptionalDoubleRef receiveTimeInSeconds = {}) final virtual
Get joint position in radians.
Parameters
[in] jointName name of the joint
[out] jointPosition joint position in radians
[out] receiveTimeInSeconds time at which the measurement was received
Returns
true/false in case of success/failure
Reimplemented from BipedalLocomotion::RobotInterface::ISensorBridge.
Definition at line 235 of file YarpSensorBridge.cpp.
References BipedalLocomotion::log().
getJointPositions()
bool YarpSensorBridge::getJointPositions (Eigen::Ref< Eigen::VectorXd > jointPositions, OptionalDoubleRef receiveTimeInSeconds = {}) final virtual
Get all joints' positions in radians.
Parameters
[out] parameter all joints' position in radians
[out] receiveTimeInSeconds time at which the measurement was received
Warning
the size is decided at the configuration and remains fixed, and internal checks must be done at the implementation level by the Derived class. This means that the user must pass a resized argument "jointPositions" to this method
Returns
true/false in case of success/failure
Reimplemented from BipedalLocomotion::RobotInterface::ISensorBridge.
Definition at line 258 of file YarpSensorBridge.cpp.
getJointsList()
bool YarpSensorBridge::getJointsList (std::vector< std::string > & jointsList) final virtual
Get joints list.
Parameters
[out] jointsList list of joints attached to the bridge
Returns
true/false in case of success/failure
Reimplemented from BipedalLocomotion::RobotInterface::ISensorBridge.
Definition at line 153 of file YarpSensorBridge.cpp.
getJointVelocities()
bool YarpSensorBridge::getJointVelocities (Eigen::Ref< Eigen::VectorXd > jointVelocties, OptionalDoubleRef receiveTimeInSeconds = {}) final virtual
Get all joints' velocities in rad/s.
Parameters
[out] parameter all joints' velocities in radians per second
[out] receiveTimeInSeconds time at which the measurement was received
Warning
the size is decided at the configuration and remains fixed, and internal checks must be done at the implementation level by the Derived class. This means that the user must pass a resized argument "jointVelocties" to this method
Returns
true/false in case of success/failure
Reimplemented from BipedalLocomotion::RobotInterface::ISensorBridge.
Definition at line 291 of file YarpSensorBridge.cpp.
getJointVelocity()
bool YarpSensorBridge::getJointVelocity (const std::string & jointName, double & jointVelocity, OptionalDoubleRef receiveTimeInSeconds = {}) final virtual
Get joint velocity in rad/s.
Parameters
[in] jointName name of the joint
[out] jointVelocity joint velocity in radians per second
[out] receiveTimeInSeconds time at which the measurement was received
Returns
true/false in case of success/failure
Reimplemented from BipedalLocomotion::RobotInterface::ISensorBridge.
Definition at line 269 of file YarpSensorBridge.cpp.
References BipedalLocomotion::log().
getLinearAccelerometerMeasurement()
bool YarpSensorBridge::getLinearAccelerometerMeasurement (const std::string & accName, Eigen::Ref< Eigen::Vector3d > accMeasurement, OptionalDoubleRef receiveTimeInSeconds = {}) final virtual
Get linear accelerometer measurement in m/s^2.
Parameters
[in] accName name of the linear accelerometer
[out] accMeasurement linear accelerometer measurements of size 3
[out] receiveTimeInSeconds time at which the measurement was received
Returns
true/false in case of success/failure
Reimplemented from BipedalLocomotion::RobotInterface::ISensorBridge.
Definition at line 321 of file YarpSensorBridge.cpp.
getLinearAccelerometersList()
bool YarpSensorBridge::getLinearAccelerometersList (std::vector< std::string > & linearAccelerometersList) final virtual
Get linear accelerometers.
Parameters
[out] linearAccelerometersList list of linear accelerometers attached to the bridge
Returns
true/false in case of success/failure
Reimplemented from BipedalLocomotion::RobotInterface::ISensorBridge.
Definition at line 173 of file YarpSensorBridge.cpp.
getMagnetometerMeasurement()
bool YarpSensorBridge::getMagnetometerMeasurement (const std::string & magName, Eigen::Ref< Eigen::Vector3d > magMeasurement, OptionalDoubleRef receiveTimeInSeconds = {}) final virtual
Get magentometer measurement in tesla.
Parameters
[in] magName name of the magnetometer
[out] magMeasurement magnetometer measurements of size 3
[out] receiveTimeInSeconds time at which the measurement was received
Returns
true/false in case of success/failure
Reimplemented from BipedalLocomotion::RobotInterface::ISensorBridge.
Definition at line 375 of file YarpSensorBridge.cpp.
getMagnetometersList()
bool YarpSensorBridge::getMagnetometersList (std::vector< std::string > & magnetometersList) final virtual
Get magnetometers sensors.
Parameters
[out] magnetometersList list of magnetometers attached to the bridge
Returns
true/false in case of success/failure
Reimplemented from BipedalLocomotion::RobotInterface::ISensorBridge.
Definition at line 204 of file YarpSensorBridge.cpp.
getMotorCurrent()
bool YarpSensorBridge::getMotorCurrent (const std::string & jointName, double & motorCurrent, OptionalDoubleRef receiveTimeInSeconds = {}) final virtual
Get motor current in ampere.
Parameters
[in] jointName name of the joint
[out] motorCurrent motor current in ampere
[out] receiveTimeInSeconds time at which the measurement was received
Returns
true/false in case of success/failure
Reimplemented from BipedalLocomotion::RobotInterface::ISensorBridge.
Definition at line 444 of file YarpSensorBridge.cpp.
References BipedalLocomotion::log().
getMotorCurrents()
bool YarpSensorBridge::getMotorCurrents (Eigen::Ref< Eigen::VectorXd > motorCurrents, OptionalDoubleRef receiveTimeInSeconds = {}) final virtual
Get all motors' currents in ampere.
Parameters
[out] motorCurrents all motors' current in ampere
[out] receiveTimeInSeconds time at which the measurement was received
Warning
the size is decided at the configuration and remains fixed, and internal checks must be done at the implementation level by the Derived class. This means that the user must pass a resized argument "motorCurrents" to this method
Returns
true/false in case of success/failure
Reimplemented from BipedalLocomotion::RobotInterface::ISensorBridge.
Definition at line 466 of file YarpSensorBridge.cpp.
getOrientationSensorMeasurement()
bool YarpSensorBridge::getOrientationSensorMeasurement (const std::string & rpyName, Eigen::Ref< Eigen::Vector3d > rpyMeasurement, OptionalDoubleRef receiveTimeInSeconds = {}) final virtual
Get orientation sensor measurement in radians as roll pitch yaw Euler angles.
Parameters
[in] rpyName name of the orientation sensor
[out] rpyMeasurement rpy measurements of size 3
[out] receiveTimeInSeconds time at which the measurement was received
Returns
true/false in case of success/failure
Reimplemented from BipedalLocomotion::RobotInterface::ISensorBridge.
Definition at line 357 of file YarpSensorBridge.cpp.
getOrientationSensorsList()
bool YarpSensorBridge::getOrientationSensorsList (std::vector< std::string > & orientationSensorsList) final virtual
Get orientation sensors.
Parameters
[out] orientationSensorsList list of orientation sensors attached to the bridge
Returns
true/false in case of success/failure
Reimplemented from BipedalLocomotion::RobotInterface::ISensorBridge.
Definition at line 194 of file YarpSensorBridge.cpp.
getOutput()
const SensorBridgeMetaData & YarpSensorBridge::getOutput () const final
Get the object.
Returns
a const reference of the requested object.
Definition at line 148 of file YarpSensorBridge.cpp.
getSixAxisForceTorqueMeasurement()
bool YarpSensorBridge::getSixAxisForceTorqueMeasurement (const std::string & ftName, Eigen::Ref< Vector6d > ftMeasurement, OptionalDoubleRef receiveTimeInSeconds = {}) final virtual
Get six axis force torque measurement.
Parameters
[in] ftName name of the FT sensor
[out] ftMeasurement FT measurements of size 6 containing 3d forces and 3d torques
[out] receiveTimeInSeconds time at which the measurement was received
Returns
true/false in case of success/failure
Reimplemented from BipedalLocomotion::RobotInterface::ISensorBridge.
Definition at line 393 of file YarpSensorBridge.cpp.
getSixAxisForceTorqueSensorsList()
bool YarpSensorBridge::getSixAxisForceTorqueSensorsList (std::vector< std::string > & sixAxisForceTorqueSensorsList) final virtual
Get 6 axis FT sensors.
Parameters
[out] sixAxisForceTorqueSensorsList list of 6 axis force torque sensors attached to the bridge
Returns
true/false in case of success/failure
Reimplemented from BipedalLocomotion::RobotInterface::ISensorBridge.
Definition at line 214 of file YarpSensorBridge.cpp.
getThreeAxisForceTorqueMeasurement()
bool YarpSensorBridge::getThreeAxisForceTorqueMeasurement (const std::string & ftName, Eigen::Ref< Eigen::Vector3d > ftMeasurement, OptionalDoubleRef receiveTimeInSeconds = {}) final virtual
Get three axis force-torque measurement containing normal force (N) and tangential moments (Nm)
Parameters
[in] ftName name of the FT sensor
[out] ftMeasurement FT measurements of size 3 containing tau_x tau_y and fz
[out] receiveTimeInSeconds time at which the measurement was received
Returns
true/false in case of success/failure
Reimplemented from BipedalLocomotion::RobotInterface::ISensorBridge.
Definition at line 429 of file YarpSensorBridge.cpp.
References BipedalLocomotion::log().
getThreeAxisForceTorqueSensorsList()
bool YarpSensorBridge::getThreeAxisForceTorqueSensorsList (std::vector< std::string > & threeAxisForceTorqueSensorsList) final virtual
Get 6 axis FT sensors.
Parameters
[out] threeAxisForceTorqueSensorsList list of 3 axis force torque sensors attached to the bridge
Returns
true/false in case of success/failure
Reimplemented from BipedalLocomotion::RobotInterface::ISensorBridge.
Definition at line 437 of file YarpSensorBridge.cpp.
References BipedalLocomotion::log().
initialize()
bool YarpSensorBridge::initialize (std::weak_ptr< const ParametersHandler::IParametersHandler > handler) final virtual
Initialize estimator.
Parameters
[in] handler Parameters handler
Reimplemented from BipedalLocomotion::System::Advanceable< EmptySignal, SensorBridgeMetaData >.
Definition at line 24 of file YarpSensorBridge.cpp.
References BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::configureCartesianWrenches(), BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::configureInertialSensors(), BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::configureRemoteControlBoardRemapper(), BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::configureSixAxisForceTorqueSensors(), std::weak_ptr< T >::lock(), and BipedalLocomotion::log().
isOutputValid()
bool YarpSensorBridge::isOutputValid () const final
Determines the validity of the object retrieved with get()
Returns
True if the object is valid, false otherwise.
Definition at line 138 of file YarpSensorBridge.cpp.
setDriversList()
bool YarpSensorBridge::setDriversList (const yarp::dev::PolyDriverList & deviceDriversList)
Set the list of device drivers from which the sensor measurements need to be streamed.
Parameters
deviceDriversList device drivers holding the pointer to sensor interfaces
Returns
True/False in case of success/failure.
Definition at line 99 of file YarpSensorBridge.cpp.
References BipedalLocomotion::log().
The documentation for this class was generated from the following files:
RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpSensorBridge.h
RobotInterface/YarpImplementation/src/YarpSensorBridge.cpp