bipedal-locomotion-framework: BipedalLocomotion::System::IClock Class Reference
BipedalLocomotion::System::IClock Class Reference abstract
IClock is the interface to the clock.
#include <BipedalLocomotion/System/IClock.h>
Public Member Functions
virtual ~IClock ()=default
Destructor.
virtual std::chrono::duration< double > now ()=0
Get the current time.
virtual void sleepFor (const std::chrono::duration< double > &sleepDuration)=0
Blocks the execution of the current thread for at least the specified sleepDuration.
virtual void sleepUntil (const std::chrono::duration< double > &time)=0
Blocks the execution of the current thread until specified sleepTime has been reached.
virtual void yield ()=0
Provides a hint to the implementation to reschedule the execution of threads, allowing other threads to run.
Protected Member Functions
IClock ()=default
The constructor is protected.
Detailed Description
IClock is the interface to the clock.
The Clock is considered as a singleton. Please use the ClockBuilder to create a clock. The default clock is the System::StdClock which uses only the std methods. To get the current time you can simply use the following line of code
BipedalLocomotion::clock().now();
Definition at line 26 of file IClock.h.
Constructor & Destructor Documentation
IClock()
BipedalLocomotion::System::IClock::IClock () protected default
The constructor is protected.
Please create the clock with ClockBulder.
~IClock()
virtual BipedalLocomotion::System::IClock::~IClock () virtual default
Destructor.
Member Function Documentation
now()
virtual std::chrono::duration<double> BipedalLocomotion::System::IClock::now () pure virtual
Get the current time.
Returns
The current time. The output of the function depends on the concrete implementation.
Note
BipedalLocomotion::clock().now().count() returns a double containing the seconds since epoch.
Implemented in BipedalLocomotion::System::YarpClock, and BipedalLocomotion::System::StdClock.
Referenced by BipedalLocomotion::System::AdvanceableRunner< _Advanceable >::run().
sleepFor()
virtual void BipedalLocomotion::System::IClock::sleepFor (const std::chrono::duration< double > & sleepDuration) pure virtual
Blocks the execution of the current thread for at least the specified sleepDuration.
Parameters
time duration to sleep
Implemented in BipedalLocomotion::System::YarpClock, and BipedalLocomotion::System::StdClock.
sleepUntil()
virtual void BipedalLocomotion::System::IClock::sleepUntil (const std::chrono::duration< double > & time) pure virtual
Blocks the execution of the current thread until specified sleepTime has been reached.
Parameters
time to block until
Implemented in BipedalLocomotion::System::YarpClock, and BipedalLocomotion::System::StdClock.
Referenced by BipedalLocomotion::System::AdvanceableRunner< _Advanceable >::run().
yield()
virtual void BipedalLocomotion::System::IClock::yield () pure virtual
Provides a hint to the implementation to reschedule the execution of threads, allowing other threads to run.
Implemented in BipedalLocomotion::System::YarpClock, and BipedalLocomotion::System::StdClock.
Referenced by BipedalLocomotion::System::AdvanceableRunner< _Advanceable >::run().
The documentation for this class was generated from the following file:
System/include/BipedalLocomotion/System/IClock.h