bipedal-locomotion-framework: BipedalLocomotion::Perception::Capture::RealSense Class Reference
BipedalLocomotion::Perception::Capture::RealSense Class Reference
Realsense driver class.
#include <BipedalLocomotion/Perception/Capture/RealSense.h>
Data Structures
struct Impl
Public Member Functions
bool initialize (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler) final
Initialize estimator.
bool isValid ()
bool getRGBCamerasList (std::vector< std::string > &rgbCamerasList) final
Get rgb cameras.
bool getRGBDCamerasList (std::vector< std::string > &rgbdCamerasList) final
Get RGBD cameras.
bool getPCLDevicesList (std::vector< std::string > &pclDevList) final
Get RGBD cameras.
bool getColorImage (const std::string &camName, cv::Mat &colorImg, std::optional< std::reference_wrapper< double >> receiveTimeInSeconds={}) final
Get color image from the camera.
bool getDepthImage (const std::string &camName, cv::Mat &depthImg, std::optional< std::reference_wrapper< double >> receiveTimeInSeconds={}) final
Get depth image.
bool getColorizedDepthImage (const std::string &camName, cv::Mat &depthImg, std::optional< std::reference_wrapper< double >> receiveTimeInSeconds={})
bool getInfraredImage (const std::string &camName, cv::Mat &irImage, std::optional< std::reference_wrapper< double >> receiveTimeInSeconds={})
bool getPointCloud (const std::string &pclDevName, pcl::PointCloud< pcl::PointXYZRGB >::Ptr coloredPointCloud, std::optional< std::reference_wrapper< double >> receiveTimeInSeconds={}) final
Public Member Functions inherited from BipedalLocomotion::RobotInterface::ICameraBridge
virtual ~ICameraBridge ()=default
Destructor.
Public Member Functions inherited from BipedalLocomotion::RobotInterface::IPointCloudBridge
virtual ~IPointCloudBridge ()=default
Destructor.
Additional Inherited Members
Public Types inherited from BipedalLocomotion::RobotInterface::ICameraBridge
using unique_ptr = std::unique_ptr< ICameraBridge >
using shared_ptr = std::shared_ptr< ICameraBridge >
using weak_ptr = std::weak_ptr< ICameraBridge >
Public Types inherited from BipedalLocomotion::RobotInterface::IPointCloudBridge
using unique_ptr = std::unique_ptr< IPointCloudBridge >
using shared_ptr = std::shared_ptr< IPointCloudBridge >
using weak_ptr = std::weak_ptr< IPointCloudBridge >
Protected Member Functions inherited from BipedalLocomotion::RobotInterface::ICameraBridge
virtual bool populateCameraBridgeOptionsFromConfig (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler, CameraBridgeOptions &cameraBridgeOptions)
Helper method to maintain CameraBridgeOptions struct by populating it from the configuration parameters.
virtual bool populateCameraListsFromConfig (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler, const CameraBridgeOptions &cameraBridgeOptions, CameraLists &cameraLists)
Helper method to maintain CameraLists struct by populating it from the configuration parameters.
virtual bool populateCameraBridgeMetaDataFromConfig (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler, CameraBridgeMetaData &cameraBridgeMetaData)
Helper method to maintain CameraBridgeMetaData struct by populating it from the configuration parameters.
Detailed Description
Realsense driver class.
The following parameters are required to initialize the class
Parameter Name Type Description Mandatory Default Value
camera_name string name of the camera device No RealSense
frame_width size_t image frame width No 640
frame_height size_t image frame height No 480
fps boolean frames per second No 30
stream_color boolean flag to enable streaming BGR images No false
stream_depth boolean flag to enable streaming depth images No false
stream_ir boolean flag to enable streaming IR images No false
stream_pcl boolean flag to enable streaming pointcloud No false
align_frames_to_color boolean flag to align other images to BGR images No false
Definition at line 37 of file RealSense.h.
Member Function Documentation
getColorImage()
bool RealSense::getColorImage (const std::string & camName, cv::Mat & colorImg, std::optional< std::reference_wrapper< double >> receiveTimeInSeconds = {}) final virtual
Get color image from the camera.
Parameters
[in] camName name of the camera
[out] colorImg image as cv Mat object
[out] receiveTimeInSeconds time at which the measurement was received
Warning
the size is decided at the configuration and remains fixed, and internal checks must be done at the implementation level by the Derived class. This means that the user must pass a resized argument "colorImg" to this method
Returns
true/false in case of success/failure
Reimplemented from BipedalLocomotion::RobotInterface::ICameraBridge.
Definition at line 189 of file RealSense.cpp.
References BipedalLocomotion::log().
getDepthImage()
bool RealSense::getDepthImage (const std::string & camName, cv::Mat & depthImg, std::optional< std::reference_wrapper< double >> receiveTimeInSeconds = {}) final virtual
Get depth image.
Parameters
[in] camName name of the gyroscope
[out] depthImg depth image as a cv Mat object
[out] receiveTimeInSeconds time at which the measurement was received
Warning
the size is decided at the configuration and remains fixed, and internal checks must be done at the implementation level by the Derived class. This means that the user must pass a resized argument "depthImg" to this method
Returns
true/false in case of success/failure
Reimplemented from BipedalLocomotion::RobotInterface::ICameraBridge.
Definition at line 217 of file RealSense.cpp.
References BipedalLocomotion::log().
getPCLDevicesList()
bool RealSense::getPCLDevicesList (std::vector< std::string > & pclDevList) final virtual
Get RGBD cameras.
Parameters
[out] rgbdCamerasList list of rgbd cameras attached to the bridge
Returns
true/false in case of success/failure
Reimplemented from BipedalLocomotion::RobotInterface::IPointCloudBridge.
Definition at line 182 of file RealSense.cpp.
References std::vector< T >::clear(), and std::vector< T >::push_back().
getRGBCamerasList()
bool RealSense::getRGBCamerasList (std::vector< std::string > & rgbCamerasList) final virtual
Get rgb cameras.
Parameters
[out] rgbCamerasList list of rgb cameras attached to the bridge
Returns
true/false in case of success/failure
Reimplemented from BipedalLocomotion::RobotInterface::ICameraBridge.
Definition at line 168 of file RealSense.cpp.
References std::vector< T >::clear(), and std::vector< T >::push_back().
getRGBDCamerasList()
bool RealSense::getRGBDCamerasList (std::vector< std::string > & rgbdCamerasList) final virtual
Get RGBD cameras.
Parameters
[out] rgbdCamerasList list of rgbd cameras attached to the bridge
Returns
true/false in case of success/failure
Reimplemented from BipedalLocomotion::RobotInterface::ICameraBridge.
Definition at line 175 of file RealSense.cpp.
References std::vector< T >::clear(), and std::vector< T >::push_back().
initialize()
bool RealSense::initialize (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler) final virtual
Initialize estimator.
Parameters
[in] handler Parameters handler
Implements BipedalLocomotion::RobotInterface::ICameraBridge.
Definition at line 74 of file RealSense.cpp.
References std::weak_ptr< T >::lock(), and BipedalLocomotion::log().
The documentation for this class was generated from the following files:
Perception/include/BipedalLocomotion/Perception/Capture/RealSense.h
Perception/src/RealSense.cpp