bipedal-locomotion-framework: BipedalLocomotion::Estimators::InvariantEKFBaseEstimator Class Reference
BipedalLocomotion::Estimators::InvariantEKFBaseEstimator Class Reference
InvariantEKFBaseEstimator class implements the Contact Aided Invariant EKF algorithm, developed by Ross Hartley, Maani Ghaffari, Ryan M.
#include <BipedalLocomotion/FloatingBaseEstimators/InvariantEKFBaseEstimator.h>
Data Structures
class Impl
Public Member Functions
InvariantEKFBaseEstimator ()
Constructor.
~InvariantEKFBaseEstimator ()
Destructor (necessary for PIMPL idiom)
bool resetEstimator (const FloatingBaseEstimators::InternalState &newState, const FloatingBaseEstimators::StateStdDev &newPriorDev)
Reset the base pose estimate and consequently the internal state of the estimator.
bool resetEstimator (const FloatingBaseEstimators::InternalState &newState, const FloatingBaseEstimators::StateStdDev &newPriorDev, const FloatingBaseEstimators::SensorsStdDev &newSensorsDev)
Reset the base pose estimate and consequently the internal state of the estimator.
void toggleBiasEstimation (const bool &flag)
Toggle bias estimation.
void toggleEKFUpdate (const bool &flag)
Toggle EKF update.
virtual bool resetEstimator (const FloatingBaseEstimators::InternalState &newState)
To prevent function hiding due to overloading of virtual methods.
virtual bool resetEstimator (const Eigen::Quaterniond &newBaseOrientation, const Eigen::Vector3d &newBasePosition)
To prevent function hiding due to overloading of virtual methods.
Public Member Functions inherited from BipedalLocomotion::Estimators::FloatingBaseEstimator
bool initialize (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler, std::shared_ptr< iDynTree::KinDynComputations > kindyn)
Configure generic parameters and the model.
bool initialize (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler)
Configure generic parameters, calling this overloaded method assumes model information is not going to be used.
bool setIMUMeasurement (const Eigen::Vector3d &accMeas, const Eigen::Vector3d &gyroMeas)
Set the polled IMU measurement.
bool setContacts (const bool &lfInContact, const bool &rfInContact)
Set feet contact states.
bool setContactStatus (const std::string &name, const bool &contactStatus, const double &switchTime, double timeNow=0.)
Set contact status.
bool setKinematics (const Eigen::VectorXd &encoders, const Eigen::VectorXd &encoderSpeeds)
Set kinematic measurements.
bool setLandmarkRelativePose (const int &landmarkID, const Eigen::Quaterniond &quat, const Eigen::Vector3d &pos, const double &timeNow)
Set the relative pose of a landmark relative to the base link.
virtual bool advance () final
Compute one step of the estimator.
virtual bool resetEstimator (const FloatingBaseEstimators::InternalState &newState)
Reset the internal state of the estimator.
virtual bool resetEstimator (const Eigen::Quaterniond &newBaseOrientation, const Eigen::Vector3d &newBasePosition)
Reset the base pose estimate and consequently the internal state of the estimator.
virtual const FloatingBaseEstimators::Output & getOutput () const final
Get estimator outputs.
virtual bool isOutputValid () const final
Determines the validity of the object retrieved with get()
ModelComputations & modelComputations ()
Get ModelComputations object by reference.
Public Member Functions inherited from BipedalLocomotion::System::Source< FloatingBaseEstimators::Output >
bool setInput (const EmptySignal &input) final
Get the object.
Public Member Functions inherited from BipedalLocomotion::System::Advanceable< EmptySignal, FloatingBaseEstimators::Output >
virtual const Output & getOutput () const=0
Get the output of the advanceable.
virtual bool isOutputValid () const=0
Determines the validity of the object retrieved with getOutput()
virtual bool close ()
Close the Advanceable.
Protected Member Functions
virtual bool customInitialization (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler) override
These custom parameter specifications should be specified by the derived class.
virtual bool predictState (const FloatingBaseEstimators::Measurements &meas, const double &dt) override
Propagate the states through the prediction model, if there exists any (eg.
virtual bool updateKinematics (FloatingBaseEstimators::Measurements &meas, const double &dt) override
Update the predicted state estimates using kinematics and contact measurements.
Protected Member Functions inherited from BipedalLocomotion::Estimators::FloatingBaseEstimator
virtual bool updateLandmarkRelativePoses (FloatingBaseEstimators::Measurements &meas, const double &dt)
Update the predicted state estimates using relative pose measurements of static landmarks in the environment.
bool updateBaseStateFromIMUState (const FloatingBaseEstimators::InternalState &state, const FloatingBaseEstimators::Measurements &meas, manif::SE3d &basePose, Eigen::Ref< Eigen::Matrix< double, 6, 1 >> baseTwist)
Wrapper method for getting base state from internal IMU state.
bool setupOptions (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler)
Setup estimator options.
bool setupSensorDevs (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler)
Setup measurement noise standard deviations The parameters in the SensorsStdDev group are,.
bool setupInitialStates (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler)
Setup initial states.
bool setupPriorDevs (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler)
Setup initial state standard deviations.
Additional Inherited Members
Public Types inherited from BipedalLocomotion::System::Advanceable< EmptySignal, FloatingBaseEstimators::Output >
using Input = EmptySignal
using Output = FloatingBaseEstimators::Output
Protected Types inherited from BipedalLocomotion::Estimators::FloatingBaseEstimator
enum State { State::NotInitialized, State::Initialized, State::Running }
Enumerator used to determine the running state of the estimator.
Protected Attributes inherited from BipedalLocomotion::Estimators::FloatingBaseEstimator
ModelComputations m_modelComp
Model computations object.
FloatingBaseEstimators::Options m_options
Struct holding estimator options.
FloatingBaseEstimators::Measurements m_meas
FloatingBaseEstimators::Measurements m_measPrev
Struct holding the latest measurements that were set to the estimator.
FloatingBaseEstimators::InternalState m_state
FloatingBaseEstimators::InternalState m_statePrev
Structs holding the curent and previous internal states of the estimation algorithm.
FloatingBaseEstimators::Output m_estimatorOut
Struct holding outputs of the estimator.
FloatingBaseEstimators::StateStdDev m_priors
FloatingBaseEstimators::StateStdDev m_stateStdDev
Struct holding standard deviations associated to prior state estimates.
FloatingBaseEstimators::SensorsStdDev m_sensorsDev
Struct holding standard deviations associated to sensor measurements.
State m_estimatorState {State::NotInitialized}
State of the estimator.
double m_dt {0.01}
Fixed time step of the estimator, in seconds.
bool m_useIMUForAngVelEstimate {true}
Use IMU measurements as internal state imu angular velocity by default set to true for strap down IMU based EKF implementations, if IMU measurements not used, corresponding impl can set to false.
bool m_useIMUVelForBaseVelComputation {true}
Compute base velocity using inertnal state IMU velocity.
bool m_useModelInfo {true}
Flag to enable running the estimator without using the URDF model information.
bool m_isInvEKF {false}
Flag to maintain soon to be deprecated functionalities currently existing only in InvEKFBaseEstimator.
Detailed Description
InvariantEKFBaseEstimator class implements the Contact Aided Invariant EKF algorithm, developed by Ross Hartley, Maani Ghaffari, Ryan M.
Eustice, Jessy W. Grizzle in the research article, "Contact-Aided Invariant Extended Kalman Filtering for Robot State Estimation" arXiv:1904.09251 [cs.RO] Please cite this paper, if using this implementation as well. Link to the paper (https://arxiv.org/abs/1904.09251). For the original version of the filter implementation, please see https://github.com/RossHartley/invariant-ekf.
This implementation is a reduced version of the algorithm used to estimate only the bipedal feet poses along with the base pose and IMU biases.
Usage:
setup the estimator using the configuration paremeters related to
Options group
SensorsStdDev group
InitialStates group
PriorsStdDev group (For details on these parameter configuration groups, plese see the documentation of FloatingBaseEstimator class)
set the measurments
IMU measurements (accelerometer and gyroscope)
Kinematic measurements (joint positions and velocities)
Feet contact states (left foot contact state and right foot contact state)
advance the filter to run the computation step
get estimator outputs
Definition at line 44 of file InvariantEKFBaseEstimator.h.
Constructor & Destructor Documentation
InvariantEKFBaseEstimator()
InvariantEKFBaseEstimator::InvariantEKFBaseEstimator ()
Constructor.
Definition at line 197 of file InvariantEKFBaseEstimator.cpp.
References BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::accelerometerBias, BipedalLocomotion::Estimators::FloatingBaseEstimators::StateStdDev::accelerometerBias, BipedalLocomotion::Estimators::FloatingBaseEstimators::SensorsStdDev::accelerometerBiasNoise, BipedalLocomotion::Estimators::FloatingBaseEstimators::SensorsStdDev::accelerometerNoise, BipedalLocomotion::Estimators::FloatingBaseEstimators::SensorsStdDev::contactFootAngvelNoise, BipedalLocomotion::Estimators::FloatingBaseEstimators::SensorsStdDev::contactFootLinvelNoise, BipedalLocomotion::Estimators::FloatingBaseEstimators::Measurements::gyro, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::gyroscopeBias, BipedalLocomotion::Estimators::FloatingBaseEstimators::StateStdDev::gyroscopeBias, BipedalLocomotion::Estimators::FloatingBaseEstimators::SensorsStdDev::gyroscopeBiasNoise, BipedalLocomotion::Estimators::FloatingBaseEstimators::SensorsStdDev::gyroscopeNoise, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::imuLinearVelocity, BipedalLocomotion::Estimators::FloatingBaseEstimators::StateStdDev::imuLinearVelocity, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::imuOrientation, BipedalLocomotion::Estimators::FloatingBaseEstimators::StateStdDev::imuOrientation, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::imuPosition, BipedalLocomotion::Estimators::FloatingBaseEstimators::StateStdDev::imuPosition, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::lContactFrameOrientation, BipedalLocomotion::Estimators::FloatingBaseEstimators::StateStdDev::lContactFrameOrientation, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::lContactFramePosition, BipedalLocomotion::Estimators::FloatingBaseEstimators::StateStdDev::lContactFramePosition, BipedalLocomotion::Estimators::FloatingBaseEstimators::Measurements::lfInContact, BipedalLocomotion::Estimators::FloatingBaseEstimator::m_estimatorOut, BipedalLocomotion::Estimators::FloatingBaseEstimator::m_isInvEKF, BipedalLocomotion::Estimators::FloatingBaseEstimator::m_measPrev, BipedalLocomotion::Estimators::FloatingBaseEstimator::m_sensorsDev, BipedalLocomotion::Estimators::FloatingBaseEstimator::m_statePrev, BipedalLocomotion::Estimators::FloatingBaseEstimator::m_stateStdDev, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::rContactFrameOrientation, BipedalLocomotion::Estimators::FloatingBaseEstimators::StateStdDev::rContactFrameOrientation, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::rContactFramePosition, BipedalLocomotion::Estimators::FloatingBaseEstimators::StateStdDev::rContactFramePosition, BipedalLocomotion::Estimators::FloatingBaseEstimators::Measurements::rfInContact, BipedalLocomotion::Estimators::FloatingBaseEstimators::Output::state, BipedalLocomotion::Estimators::FloatingBaseEstimators::Output::stateStdDev, BipedalLocomotion::Estimators::FloatingBaseEstimators::SensorsStdDev::swingFootAngvelNoise, and BipedalLocomotion::Estimators::FloatingBaseEstimators::SensorsStdDev::swingFootLinvelNoise.
~InvariantEKFBaseEstimator()
InvariantEKFBaseEstimator::~InvariantEKFBaseEstimator () default
Destructor (necessary for PIMPL idiom)
Member Function Documentation
customInitialization()
bool InvariantEKFBaseEstimator::customInitialization (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler) override protected virtual
These custom parameter specifications should be specified by the derived class.
Parameters
[in] handler configure the custom parameters for the estimator
Returns
bool
Reimplemented from BipedalLocomotion::Estimators::FloatingBaseEstimator.
Definition at line 245 of file InvariantEKFBaseEstimator.cpp.
References BipedalLocomotion::Estimators::FloatingBaseEstimators::Options::accelerationDueToGravity, std::endl(), BipedalLocomotion::Estimators::FloatingBaseEstimators::Options::imuBiasEstimationEnabled, std::weak_ptr< T >::lock(), BipedalLocomotion::Estimators::FloatingBaseEstimator::m_modelComp, BipedalLocomotion::Estimators::FloatingBaseEstimator::m_options, BipedalLocomotion::Estimators::FloatingBaseEstimator::ModelComputations::nrJoints(), BipedalLocomotion::Estimators::FloatingBaseEstimator::setupInitialStates(), BipedalLocomotion::Estimators::FloatingBaseEstimator::setupOptions(), BipedalLocomotion::Estimators::FloatingBaseEstimator::setupPriorDevs(), and BipedalLocomotion::Estimators::FloatingBaseEstimator::setupSensorDevs().
predictState()
bool InvariantEKFBaseEstimator::predictState (const FloatingBaseEstimators::Measurements & meas, const double & dt) override protected virtual
Propagate the states through the prediction model, if there exists any (eg.
a strap-down IMU model)
Parameters
[in] meas measurements passed as exogeneous inputs to the prediction model
[in] dt sampling period in seconds
[out] state previous state estimate
[out] P previous state covariance matrix
Returns
True in case of success, false otherwise.
Reimplemented from BipedalLocomotion::Estimators::FloatingBaseEstimator.
Definition at line 334 of file InvariantEKFBaseEstimator.cpp.
References BipedalLocomotion::Estimators::FloatingBaseEstimators::Options::accelerationDueToGravity, BipedalLocomotion::Estimators::FloatingBaseEstimator::ModelComputations::getIMU_H_feet(), BipedalLocomotion::Estimators::FloatingBaseEstimators::Options::imuBiasEstimationEnabled, BipedalLocomotion::Estimators::FloatingBaseEstimator::m_modelComp, BipedalLocomotion::Estimators::FloatingBaseEstimator::m_options, BipedalLocomotion::Estimators::FloatingBaseEstimator::m_sensorsDev, BipedalLocomotion::Estimators::FloatingBaseEstimator::m_statePrev, and BipedalLocomotion::Estimators::FloatingBaseEstimator::m_stateStdDev.
resetEstimator() [1/4]
bool FloatingBaseEstimator::resetEstimator
To prevent function hiding due to overloading of virtual methods.
Definition at line 837 of file FloatingBaseEstimator.cpp.
resetEstimator() [2/4]
bool FloatingBaseEstimator::resetEstimator
To prevent function hiding due to overloading of virtual methods.
Definition at line 864 of file FloatingBaseEstimator.cpp.
resetEstimator() [3/4]
bool InvariantEKFBaseEstimator::resetEstimator (const FloatingBaseEstimators::InternalState & newState, const FloatingBaseEstimators::StateStdDev & newPriorDev)
Reset the base pose estimate and consequently the internal state of the estimator.
Parameters
[in] newState internal state of the estimator
[in] newPriorDev internal state priors
Returns
True in case of success, false otherwise.
Note
reset and advance estimator to get updated estimator output
Definition at line 302 of file InvariantEKFBaseEstimator.cpp.
References BipedalLocomotion::Estimators::FloatingBaseEstimators::Options::imuBiasEstimationEnabled, BipedalLocomotion::Estimators::FloatingBaseEstimator::m_options, and BipedalLocomotion::Estimators::FloatingBaseEstimator::m_stateStdDev.
Referenced by resetEstimator().
resetEstimator() [4/4]
bool InvariantEKFBaseEstimator::resetEstimator (const FloatingBaseEstimators::InternalState & newState, const FloatingBaseEstimators::StateStdDev & newPriorDev, const FloatingBaseEstimators::SensorsStdDev & newSensorsDev)
Reset the base pose estimate and consequently the internal state of the estimator.
Parameters
[in] newState internal state of the estimator
[in] newPriorDev internal state priors
[in] newSensorsDev sensor measurement noise
Returns
True in case of success, false otherwise.
Note
reset and advance estimator to get updated estimator output
Definition at line 313 of file InvariantEKFBaseEstimator.cpp.
References BipedalLocomotion::Estimators::FloatingBaseEstimator::m_sensorsDev, and resetEstimator().
toggleBiasEstimation()
void BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::toggleBiasEstimation (const bool & flag) inline
Toggle bias estimation.
Parameters
[in] flag flag for bias estimation
Definition at line 90 of file InvariantEKFBaseEstimator.h.
References BipedalLocomotion::Estimators::FloatingBaseEstimators::Options::imuBiasEstimationEnabled, and BipedalLocomotion::Estimators::FloatingBaseEstimator::m_options.
toggleEKFUpdate()
void BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::toggleEKFUpdate (const bool & flag) inline
Toggle EKF update.
Parameters
[in] flag flag for ekf update
Definition at line 96 of file InvariantEKFBaseEstimator.h.
References BipedalLocomotion::Estimators::FloatingBaseEstimators::Options::ekfUpdateEnabled, and BipedalLocomotion::Estimators::FloatingBaseEstimator::m_options.
updateKinematics()
bool InvariantEKFBaseEstimator::updateKinematics (FloatingBaseEstimators::Measurements & meas, const double & dt) override protected virtual
Update the predicted state estimates using kinematics and contact measurements.
Parameters
[in] meas measurements to update the predicted states
[in] dt sampling period in seconds
Returns
True in case of success, false otherwise.
Reimplemented from BipedalLocomotion::Estimators::FloatingBaseEstimator.
Definition at line 371 of file InvariantEKFBaseEstimator.cpp.
References BipedalLocomotion::Estimators::FloatingBaseEstimators::SensorsStdDev::encodersNoise, BipedalLocomotion::Estimators::FloatingBaseEstimator::ModelComputations::getIMU_H_feet(), BipedalLocomotion::Estimators::FloatingBaseEstimators::Options::imuBiasEstimationEnabled, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::imuOrientation, BipedalLocomotion::Estimators::FloatingBaseEstimators::Measurements::lfInContact, BipedalLocomotion::Estimators::FloatingBaseEstimator::m_modelComp, BipedalLocomotion::Estimators::FloatingBaseEstimator::m_options, BipedalLocomotion::Estimators::FloatingBaseEstimator::m_sensorsDev, BipedalLocomotion::Estimators::FloatingBaseEstimator::m_stateStdDev, and BipedalLocomotion::Estimators::FloatingBaseEstimators::Measurements::rfInContact.
The documentation for this class was generated from the following files:
Estimators/include/BipedalLocomotion/FloatingBaseEstimators/InvariantEKFBaseEstimator.h
Estimators/src/InvariantEKFBaseEstimator.cpp