bipedal-locomotion-framework: BipedalLocomotion::RobotInterface::YarpRobotControl Class Reference
BipedalLocomotion::RobotInterface::YarpRobotControl Class Reference
YarpRobotControl Yarp implementation of the IRobotControl interface.
#include <BipedalLocomotion/RobotInterface/YarpRobotControl.h>
Data Structures
struct Impl
Public Member Functions
YarpRobotControl ()
Constructor.
bool initialize (std::weak_ptr< ParametersHandler::IParametersHandler > handler) final
Initialize the Interface.
bool setDriver (std::shared_ptr< yarp::dev::PolyDriver > robotDevice)
Set the driver required to control the robot.
bool checkMotionDone (bool &motionDone, bool &isTimeExpired, std::vector< std::pair< std::string, double >> &info) final
Check if the motion set through the position control mode ended.
bool setReferences (Eigen::Ref< const Eigen::VectorXd > jointValues, const std::vector< IRobotControl::ControlMode > &controlModes) final
Set the desired reference.
bool setReferences (Eigen::Ref< const Eigen::VectorXd > desiredJointValues, const IRobotControl::ControlMode &mode) final
Set the desired reference.
std::vector< std::string > getJointList () const final
Get the list of the controlled joints.
~YarpRobotControl ()
Destructor.
Public Member Functions inherited from BipedalLocomotion::RobotInterface::IRobotControl
virtual ~IRobotControl ()=default
Destructor.
Additional Inherited Members
Public Types inherited from BipedalLocomotion::RobotInterface::IRobotControl
enum ControlMode {
Position, PositionDirect, Velocity, Torque,
Idle, Unknown
}
ControlMode contains the supported control mode.
using unique_ptr = std::unique_ptr< IRobotControl >
using shared_ptr = std::shared_ptr< IRobotControl >
using weak_ptr = std::weak_ptr< IRobotControl >
Detailed Description
YarpRobotControl Yarp implementation of the IRobotControl interface.
Warning
At the current stage only revolute joints are supported.
Definition at line 31 of file YarpRobotControl.h.
Constructor & Destructor Documentation
YarpRobotControl()
YarpRobotControl::YarpRobotControl ()
Constructor.
Definition at line 510 of file YarpRobotControl.cpp.
~YarpRobotControl()
YarpRobotControl::~YarpRobotControl () default
Destructor.
Member Function Documentation
checkMotionDone()
bool YarpRobotControl::checkMotionDone (bool & motionDone, bool & isTimeExpired, std::vector< std::pair< std::string, double >> & info) final virtual
Check if the motion set through the position control mode ended.
Parameters
[out] motionDone true if the motion ended.
[out] isTimerExpired true if the internal timer is expired or not.
[out] info vector containing the list of the joint whose motion did not finish yet.
Returns
True/False in case of success/failure.
Note
If the timer is expired and the motion did not finish yet, there may be a problem with the robot.
Implements BipedalLocomotion::RobotInterface::IRobotControl.
Definition at line 610 of file YarpRobotControl.cpp.
References BipedalLocomotion::log().
getJointList()
std::vector< std::string > YarpRobotControl::getJointList () const final virtual
Get the list of the controlled joints.
Returns
A vector containing the name of the controlled joints.
Implements BipedalLocomotion::RobotInterface::IRobotControl.
Definition at line 663 of file YarpRobotControl.cpp.
initialize()
bool YarpRobotControl::initialize (std::weak_ptr< ParametersHandler::IParametersHandler > handler) final virtual
Initialize the Interface.
Parameters
handler pointer to a parameter handler interface
Note
the following parameters are required by the class
Parameter name Type Description Mandatory
reading_timeout int Timeout used while reading from the YARP interfaces in microseconds. (Positive Number) No
max_reading_attempts int Max number of attempts used for reading from the YARP interfaces. (Positive Number) No
positioning_duration double Duration of the trajectory generated when the joint is controlled in position mode [seconds] Yes
positioning_tolerance double Max Admissible error for position control joint [rad] Yes
position_direct_max_admissible_error double Max admissible error for position direct control joint [rad] Yes
Returns
True/False in case of success/failure.
Reimplemented from BipedalLocomotion::RobotInterface::IRobotControl.
Definition at line 522 of file YarpRobotControl.cpp.
References std::weak_ptr< T >::lock(), and BipedalLocomotion::log().
setDriver()
bool YarpRobotControl::setDriver (std::shared_ptr< yarp::dev::PolyDriver > robotDevice)
Set the driver required to control the robot.
Parameters
robotDevice device used to control the robot.
Returns
True/False in case of success/failure.
Definition at line 517 of file YarpRobotControl.cpp.
setReferences() [1/2]
bool YarpRobotControl::setReferences (Eigen::Ref< const Eigen::VectorXd > desiredJointValues, const IRobotControl::ControlMode & mode) final virtual
Set the desired reference.
Parameters
jointValues desired joint values.
controlMode a control mode for all the joints.
Returns
True/False in case of success/failure.
Note
In case of position control the values has to be expressed in rad, in case of velocity control in rad/s. If the robot is controlled in torques, the desired joint values are expressed in Nm.
Warning
Call this function if you want to control all the joint with the same control mode. Otherwise call setReferences(Eigen::Ref<const Eigen::VectorXd>, const std::vector<IRobotControl::ControlMode>&).
Implements BipedalLocomotion::RobotInterface::IRobotControl.
Definition at line 590 of file YarpRobotControl.cpp.
References std::all_of(), std::fill(), and BipedalLocomotion::log().
setReferences() [2/2]
bool YarpRobotControl::setReferences (Eigen::Ref< const Eigen::VectorXd > jointValues, const std::vector< IRobotControl::ControlMode > & controlModes) final virtual
Set the desired reference.
Parameters
jointValues desired joint values.
controlModes vector containing the control mode for each joint.
Returns
True/False in case of success/failure.
Note
In case of position control the values has to be expressed in rad, in case of velocity control in rad/s. If the robot is controlled in torques, the desired joint values are expressed in Nm.
Warning
At the current stage only revolute joints are supported.
Implements BipedalLocomotion::RobotInterface::IRobotControl.
Definition at line 574 of file YarpRobotControl.cpp.
References BipedalLocomotion::log().
The documentation for this class was generated from the following files:
RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpRobotControl.h
RobotInterface/YarpImplementation/src/YarpRobotControl.cpp