bipedal-locomotion-framework: BipedalLocomotion::Planners::SwingFootPlanner Class Reference
BipedalLocomotion::Planners::SwingFootPlanner Class Reference
SwingFootPlanner implement a minimum jerk trajectory planner for the swing foot.
#include <BipedalLocomotion/Planners/SwingFootPlanner.h>
Public Member Functions
bool initialize (std::weak_ptr< const ParametersHandler::IParametersHandler > handler) final
Initialize the planner.
void setContactList (const Contacts::ContactList &contactList)
Set the contact list.
const SwingFootPlannerState & getOutput () const final
Get the object.
bool isOutputValid () const final
Determines the validity of the object retrieved with get()
bool advance () final
Advance the internal state.
Public Member Functions inherited from BipedalLocomotion::System::Source< SwingFootPlannerState >
bool setInput (const EmptySignal &input) final
Get the object.
Public Member Functions inherited from BipedalLocomotion::System::Advanceable< EmptySignal, SwingFootPlannerState >
virtual const Output & getOutput () const=0
Get the output of the advanceable.
virtual bool isOutputValid () const=0
Determines the validity of the object retrieved with getOutput()
virtual bool close ()
Close the Advanceable.
Additional Inherited Members
Public Types inherited from BipedalLocomotion::System::Advanceable< EmptySignal, SwingFootPlannerState >
using Input = EmptySignal
using Output = SwingFootPlannerState
Detailed Description
SwingFootPlanner implement a minimum jerk trajectory planner for the swing foot.
The planner is designed in SE(3) and we assume that initial 6d-acceleration and 6d-velocity of the foot is always equal to zero at take off. The trajectory of the foot will belong to the Geodesic.
Definition at line 42 of file SwingFootPlanner.h.
Member Function Documentation
advance()
bool SwingFootPlanner::advance () final virtual
Advance the internal state.
This may change the value retrievable from get().
Returns
True if the advance is successfull.
Implements BipedalLocomotion::System::Advanceable< EmptySignal, SwingFootPlannerState >.
Definition at line 165 of file SwingFootPlanner.cpp.
References std::endl(), std::min(), and std::next().
getOutput()
const SwingFootPlannerState & SwingFootPlanner::getOutput () const final
Get the object.
Returns
a const reference of the requested object.
Definition at line 106 of file SwingFootPlanner.cpp.
initialize()
bool SwingFootPlanner::initialize (std::weak_ptr< const ParametersHandler::IParametersHandler > handler) final virtual
Initialize the planner.
Parameters
handler pointer to the parameter handler.
Note
the following parameters are required by the class
Parameter Name Type Description Mandatory
sampling_time double Sampling time of the planner in seconds Yes
step_height double Height of the swing foot. It is not the maximum height of the foot. If apex time is 0.5 step_height is the maximum Yes
foot_apex_time double Number between 0 and 1 representing the foot apex instant. If 0 the apex happens at take off if 1 at touch down Yes
foot_landing_velocity double Landing vertical velocity Yes
foot_landing_acceleration double Landing vertical acceleration Yes
Returns
True in case of success/false otherwise.
Reimplemented from BipedalLocomotion::System::Advanceable< EmptySignal, SwingFootPlannerState >.
Definition at line 17 of file SwingFootPlanner.cpp.
References std::endl(), and std::weak_ptr< T >::lock().
isOutputValid()
bool SwingFootPlanner::isOutputValid () const final
Determines the validity of the object retrieved with get()
Returns
True if the object is valid, false otherwise.
Definition at line 101 of file SwingFootPlanner.cpp.
setContactList()
void SwingFootPlanner::setContactList (const Contacts::ContactList & contactList)
Set the contact list.
Parameters
contactList contains the list fora given contact
Definition at line 85 of file SwingFootPlanner.cpp.
References BipedalLocomotion::Contacts::ContactList::firstContact().
The documentation for this class was generated from the following files:
Planners/include/BipedalLocomotion/Planners/SwingFootPlanner.h
Planners/src/SwingFootPlanner.cpp