bipedal-locomotion-framework: BipedalLocomotion::Contacts::ContactList Class Reference
BipedalLocomotion::Contacts::ContactList Class Reference
Class containing a list of contacts.
#include <BipedalLocomotion/Contacts/ContactList.h>
Public Types
using const_iterator = std::set< BipedalLocomotion::Contacts::PlannedContact, ContactCompare >::const_iterator
using const_reverse_iterator = std::set< BipedalLocomotion::Contacts::PlannedContact, ContactCompare >::const_reverse_iterator
Public Member Functions
void setDefaultName (const std::string &defaultName)
Set the default name.
const std::string & defaultName () const
Get the default name.
void setDefaultContactType (const BipedalLocomotion::Contacts::ContactType &type)
Set the default contact type.
void setDefaultIndex (int defaultIndex)
Set the default frame index of the contact.
int defaultIndex () const
Get the default frame index of the contact.
const BipedalLocomotion::Contacts::ContactType & defaultContactType () const
Get the default contact type.
bool addContact (const BipedalLocomotion::Contacts::PlannedContact &newContact)
Add a new contact to the list.
bool addContact (const manif::SE3d &newTransform, double activationTime, double deactivationTime)
Add a new contact to the list.
const_iterator erase (const_iterator iterator)
Erase a contact.
const_iterator begin () const
Return a const iterator to the begin of the contacts.
const_iterator cbegin () const
Return a const iterator to the begin of the contacts.
const_reverse_iterator rbegin () const
Return a const reverse iterator to the contacts (basically starting from the last contact going backward).
const_reverse_iterator crbegin () const
Return a const reverse iterator to the contacts (basically starting from the last contact going backward).
const_iterator end () const
Return a const iterator to the end of the list.
const_iterator cend () const
Return a const iterator to the end of the list.
const_reverse_iterator rend () const
Return a const reverse iterator to the end of the list.
const_reverse_iterator crend () const
Return a const reverse iterator to the end of the list.
const BipedalLocomotion::Contacts::PlannedContact & operator[] (size_t index) const
Access contacts by index.
size_t size () const
Get the size of the list.
const_iterator firstContact () const
Iterator pointing to the first contact.
const_iterator lastContact () const
Iterator pointing to the last contact.
bool editContact (const_iterator element, const BipedalLocomotion::Contacts::PlannedContact &newContact)
Edit an existing contact.
const_iterator getPresentContact (double time) const
Get the contact given the time.
bool keepOnlyPresentContact (double time)
Clear all the steps, except the one returned by getPresentContact.
void clear ()
Clear the contacts.
void removeLastContact ()
Remove only the last contact.
Detailed Description
Class containing a list of contacts.
The contact are added such that the activation time is strictly growing. In addition, contacts cannot be overlapping. It represents a series of contact activations and deactivations of a single entity.
Definition at line 32 of file ContactList.h.
Member Function Documentation
addContact() [1/2]
bool ContactList::addContact (const BipedalLocomotion::Contacts::PlannedContact & newContact)
Add a new contact to the list.
Parameters
newContact The new contact
Returns
false if it was not possible to insert the contact. Possible failures: the activation time is greater than the deactivation time, or the new contact ovelaps with an existing contact.
Definition at line 51 of file ContactList.cpp.
References BipedalLocomotion::Contacts::PlannedContact::activationTime, BipedalLocomotion::Contacts::PlannedContact::deactivationTime, end(), std::set< K >::insert(), and BipedalLocomotion::log().
Referenced by addContact(), and keepOnlyPresentContact().
addContact() [2/2]
bool ContactList::addContact (const manif::SE3d & newTransform, double activationTime, double deactivationTime)
Add a new contact to the list.
It uses the defaultName and the defaultContactType for the missing informations.
Parameters
newTransform The contact pose.
activationTime The activation time.
deactivationTime The deactivation time.
Returns
false if it was not possible to insert the contact. Possible failures: the activation time is greater than the deactivation time, or the new contact ovelaps with an existing contact.
Definition at line 82 of file ContactList.cpp.
References BipedalLocomotion::Contacts::PlannedContact::activationTime, addContact(), BipedalLocomotion::Contacts::PlannedContact::deactivationTime, BipedalLocomotion::Contacts::ContactBase::index, BipedalLocomotion::Contacts::ContactBase::name, BipedalLocomotion::Contacts::ContactBase::pose, and BipedalLocomotion::Contacts::ContactBase::type.
begin()
ContactList::const_iterator ContactList::begin () const
Return a const iterator to the begin of the contacts.
Definition at line 100 of file ContactList.cpp.
References std::set< K >::begin().
Referenced by editContact(), firstContact(), and operator[]().
cbegin()
ContactList::const_iterator ContactList::cbegin () const
Return a const iterator to the begin of the contacts.
Definition at line 105 of file ContactList.cpp.
References std::set< K >::cbegin().
Referenced by BipedalLocomotion::Contacts::FixedFootDetector::setContactPhaseList().
cend()
ContactList::const_iterator ContactList::cend () const
Return a const iterator to the end of the list.
This is only a placeholder, it does not reference any contact.
Definition at line 125 of file ContactList.cpp.
References std::set< K >::cend().
clear()
void ContactList::clear ()
Clear the contacts.
Definition at line 244 of file ContactList.cpp.
References std::set< K >::clear().
Referenced by keepOnlyPresentContact().
crbegin()
ContactList::const_reverse_iterator ContactList::crbegin () const
Return a const reverse iterator to the contacts (basically starting from the last contact going backward).
Definition at line 115 of file ContactList.cpp.
References std::set< K >::crbegin().
crend()
ContactList::const_reverse_iterator ContactList::crend () const
Return a const reverse iterator to the end of the list.
This is only a placeholder, it does not reference any contact.
Definition at line 135 of file ContactList.cpp.
References std::set< K >::crend().
defaultContactType()
const ContactType & ContactList::defaultContactType () const
Get the default contact type.
Returns
the default contact type.
Definition at line 36 of file ContactList.cpp.
defaultIndex()
int ContactList::defaultIndex () const
Get the default frame index of the contact.
Returns
the default index.
Definition at line 46 of file ContactList.cpp.
Referenced by setDefaultIndex().
defaultName()
const std::string & ContactList::defaultName () const
Get the default name.
Returns
the default name.
Definition at line 26 of file ContactList.cpp.
Referenced by setDefaultName().
editContact()
bool ContactList::editContact (ContactList::const_iterator element, const BipedalLocomotion::Contacts::PlannedContact & newContact)
Edit an existing contact.
Parameters
element Iterator to the element to edit.
newContact The new contact
Returns
false if the element is not valid or if the new contact timing would require a reordering of the list.
Definition at line 173 of file ContactList.cpp.
References BipedalLocomotion::Contacts::PlannedContact::activationTime, begin(), BipedalLocomotion::Contacts::PlannedContact::deactivationTime, end(), std::set< K >::erase(), std::set< K >::insert(), and BipedalLocomotion::log().
end()
ContactList::const_iterator ContactList::end () const
Return a const iterator to the end of the list.
This is only a placeholder, it does not reference any contact.
Definition at line 120 of file ContactList.cpp.
References std::set< K >::end().
Referenced by addContact(), editContact(), getPresentContact(), keepOnlyPresentContact(), and lastContact().
erase()
ContactList::const_iterator ContactList::erase (const_iterator iterator)
Erase a contact.
Parameters
iterator to the contact to erase.
Returns
an iterator to the contact that follows the one removed.
Definition at line 95 of file ContactList.cpp.
References std::set< K >::erase().
Referenced by removeLastContact().
firstContact()
ContactList::const_iterator ContactList::firstContact () const
Iterator pointing to the first contact.
Definition at line 163 of file ContactList.cpp.
References begin().
Referenced by BipedalLocomotion::Planners::SwingFootPlanner::setContactList().
getPresentContact()
ContactList::const_iterator ContactList::getPresentContact (double time) const
Get the contact given the time.
It returns the contact with the highest activation time lower than time. If no contacts have an activation time lower than time, it returns an iterator to the end. Notice that the contact may not be active, i.e. the deactivationTime may be lower than time.
Parameters
time The present time.
Returns
an iterator to the last contact having an activation time lower than time. If no contact satisfy this condition, it returns a pointer to the end.
Definition at line 211 of file ContactList.cpp.
References BipedalLocomotion::Contacts::PlannedContact::activationTime, end(), std::find_if(), rbegin(), and rend().
Referenced by keepOnlyPresentContact().
keepOnlyPresentContact()
bool ContactList::keepOnlyPresentContact (double time)
Clear all the steps, except the one returned by getPresentContact.
Parameters
time The present time.
Returns
false if no contact is available at this time.
Definition at line 225 of file ContactList.cpp.
References addContact(), clear(), end(), getPresentContact(), and BipedalLocomotion::log().
lastContact()
ContactList::const_iterator ContactList::lastContact () const
Iterator pointing to the last contact.
Definition at line 168 of file ContactList.cpp.
References end().
Referenced by removeLastContact().
operator[]()
const PlannedContact & ContactList::operator[] (size_t index) const
Access contacts by index.
Warning
This method in a for loop is much less efficient than using iterators.
Parameters
index of the phase to be accessed.
Returns
A const reference to the desired contact.
Definition at line 140 of file ContactList.cpp.
References std::advance(), begin(), rbegin(), and size().
rbegin()
ContactList::const_reverse_iterator ContactList::rbegin () const
Return a const reverse iterator to the contacts (basically starting from the last contact going backward).
Definition at line 110 of file ContactList.cpp.
References std::set< K >::rbegin().
Referenced by getPresentContact(), and operator[]().
removeLastContact()
void ContactList::removeLastContact ()
Remove only the last contact.
Definition at line 249 of file ContactList.cpp.
References erase(), and lastContact().
rend()
ContactList::const_reverse_iterator ContactList::rend () const
Return a const reverse iterator to the end of the list.
This is only a placeholder, it does not reference any contact.
Definition at line 130 of file ContactList.cpp.
References std::set< K >::rend().
Referenced by getPresentContact().
setDefaultContactType()
void ContactList::setDefaultContactType (const BipedalLocomotion::Contacts::ContactType & type)
Set the default contact type.
Parameters
The default contact type.
Definition at line 31 of file ContactList.cpp.
setDefaultIndex()
void ContactList::setDefaultIndex (int defaultIndex)
Set the default frame index of the contact.
Parameters
defaultIndex the default index.
Definition at line 41 of file ContactList.cpp.
References defaultIndex().
setDefaultName()
void ContactList::setDefaultName (const std::string & defaultName)
Set the default name.
Parameters
defaultName the default name.
Definition at line 21 of file ContactList.cpp.
References defaultName().
size()
size_t ContactList::size () const
Get the size of the list.
Returns
The number of contacts.
Definition at line 158 of file ContactList.cpp.
References std::set< K >::size().
Referenced by operator[]().
The documentation for this class was generated from the following files:
Contacts/include/BipedalLocomotion/Contacts/ContactList.h
Contacts/src/ContactList.cpp