bipedal-locomotion-framework: BipedalLocomotion::Perception::ArucoDetector Class Reference
BipedalLocomotion::Perception::ArucoDetector Class Reference
Data Structures
class Impl
Public Member Functions
bool initialize (std::weak_ptr< const ParametersHandler::IParametersHandler > handler) final
Initialize the detector.
bool setImage (const cv::Mat &inputImg, double timeNow)
Set image for which markers need to be detected.
bool advance () final
Compute one step of the detector.
const ArucoDetectorOutput & getOutput () const final
Get the detected markers' data from the current step.
bool getDetectedMarkerData (const int &id, ArucoMarkerData &markerData)
Get the detected marker data.
bool getImageWithDetectedMarkers (cv::Mat &outputImg, const bool &drawFrames=false, const double &axisLengthForDrawing=0.1)
Get the image with drawn detected markers.
bool isOutputValid () const final
Determines the validity of the object retrieved with get()
Public Member Functions inherited from BipedalLocomotion::System::Source< ArucoDetectorOutput >
bool setInput (const EmptySignal &input) final
Get the object.
Public Member Functions inherited from BipedalLocomotion::System::Advanceable< EmptySignal, ArucoDetectorOutput >
virtual const Output & getOutput () const=0
Get the output of the advanceable.
virtual bool isOutputValid () const=0
Determines the validity of the object retrieved with getOutput()
virtual bool close ()
Close the Advanceable.
Additional Inherited Members
Public Types inherited from BipedalLocomotion::System::Advanceable< EmptySignal, ArucoDetectorOutput >
using Input = EmptySignal
using Output = ArucoDetectorOutput
Detailed Description
Definition at line 62 of file ArucoDetector.h.
Member Function Documentation
advance()
bool ArucoDetector::advance () final virtual
Compute one step of the detector.
Returns
True in case of success, false otherwise
Implements BipedalLocomotion::System::Advanceable< EmptySignal, ArucoDetectorOutput >.
Definition at line 175 of file ArucoDetector.cpp.
References BipedalLocomotion::log(), and BipedalLocomotion::Conversions::toEigenPose().
getDetectedMarkerData()
bool ArucoDetector::getDetectedMarkerData (const int & id, ArucoMarkerData & markerData)
Get the detected marker data.
Parameters
[in] id marker id
[in] markerData detected marker identifiers data
Returns
True in case of success, false if marker was not detected
Definition at line 242 of file ArucoDetector.cpp.
getImageWithDetectedMarkers()
bool ArucoDetector::getImageWithDetectedMarkers (cv::Mat & outputImg, const bool & drawFrames = false, const double & axisLengthForDrawing = 0.1)
Get the image with drawn detected markers.
Parameters
[in] outputImg image with detected markers drawn on it
[in] drawFrames draw also estimated marker poses, set to false by default
[in] axisLengthForDrawing axis length for drawing the frame axes, 0.1 by default
Returns
True in case of success, false if no marker was detected
Definition at line 253 of file ArucoDetector.cpp.
getOutput()
const ArucoDetectorOutput & ArucoDetector::getOutput () const final
Get the detected markers' data from the current step.
Returns
A struct containing a map container of detected markers.
Definition at line 227 of file ArucoDetector.cpp.
initialize()
bool ArucoDetector::initialize (std::weak_ptr< const ParametersHandler::IParametersHandler > handler) final virtual
Initialize the detector.
Note
The following parameter are required by the filter:
"marker_dictionary" OpenCV predefined aruco marker dictionary (available options: "4X4_50", "4X4_100", "4X4_250", "4X4_1000", "5X5_50", "5X5_100", "5X5_250", "5X5_1000", "6X6_50", "6X6_100", "6X6_250", "6X6_1000", "7X7_50", "7X7_100", "7X7_250", "7X7_1000", "ARUCO_ORIGINAL") options coherent with https://docs.opencv.org/master/d9/d6a/group__aruco.html#gac84398a9ed9dd01306592dd616c2c975
"marker_length" marker length in m
"camera_matrix" 9d vector representing the camera calbration matrix in row major order
"distortion_coefficients" 5d vector containing camera distortion coefficients
Parameters
[in] handlerWeak weak pointer to a ParametersHandler::IParametersHandler interface @tparameter Derived particular implementation of the IParameterHandler
Returns
True in case of success, false otherwise.
Reimplemented from BipedalLocomotion::System::Advanceable< EmptySignal, ArucoDetectorOutput >.
Definition at line 86 of file ArucoDetector.cpp.
References std::weak_ptr< T >::lock(), and BipedalLocomotion::log().
isOutputValid()
bool ArucoDetector::isOutputValid () const final
Determines the validity of the object retrieved with get()
Returns
True if the object is valid, false otherwise.
Definition at line 232 of file ArucoDetector.cpp.
setImage()
bool ArucoDetector::setImage (const cv::Mat & inputImg, double timeNow)
Set image for which markers need to be detected.
Parameters
[in] inputImg image as OpenCV mat
[in] timeNow current time in chosen time units it is useful for bookkeeping or time delay synchronization
Returns
True in case of success, false otherwise
Definition at line 158 of file ArucoDetector.cpp.
References BipedalLocomotion::log().
The documentation for this class was generated from the following files:
Perception/include/BipedalLocomotion/Perception/Features/ArucoDetector.h
Perception/src/ArucoDetector.cpp