bipedal-locomotion-framework: BipedalLocomotion::Perception::Features::PointCloudProcessor< PointType > Class Template Reference
BipedalLocomotion::Perception::Features::PointCloudProcessor< PointType > Class Template Reference
A wrapper class to do a basic PCL processing for perception aided locomotion.
#include <BipedalLocomotion/Perception/Features/PointCloudProcessor.h>
Public Member Functions
bool initialize (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler)
bool downsample (const typename pcl::PointCloud< PointType >::Ptr inCloud, typename pcl::PointCloud< PointType >::Ptr outCloud)
Downsample the point cloud using voxel grid filter See https://pcl.readthedocs.io/projects/tutorials/en/latest/voxel_grid.html#voxelgrid.
bool removeOutliers (const typename pcl::PointCloud< PointType >::Ptr inCloud, typename pcl::PointCloud< PointType >::Ptr outCloud)
Remove outliers from point cloud based on nearest neighbors See https://pcl.readthedocs.io/projects/tutorials/en/latest/statistical_outlier.html#statistical-outlier-removal.
bool extractClusters (const typename pcl::PointCloud< PointType >::Ptr inCloud, std::vector< pcl::PointIndices > &clusterIndices, std::vector< typename pcl::PointCloud< PointType >::Ptr > &cloudClusters)
Extract Euclidean clustering based point cloud clusters See https://pcl.readthedocs.io/projects/tutorials/en/latest/cluster_extraction.html#cluster-extraction.
bool transform (const typename pcl::PointCloud< PointType >::Ptr inCloud, Eigen::Ref< const Eigen::Matrix4f > transform, typename pcl::PointCloud< PointType >::Ptr outCloud)
Transform point cloud See https://pcl.readthedocs.io/projects/tutorials/en/latest/matrix_transform.html.
bool transform (const typename pcl::PointCloud< PointType >::Ptr inCloud, const Eigen::Affine3f &transform, typename pcl::PointCloud< PointType >::Ptr outCloud)
Transform point cloud See https://pcl.readthedocs.io/projects/tutorials/en/latest/matrix_transform.html.
Detailed Description
template<class PointType>
class BipedalLocomotion::Perception::Features::PointCloudProcessor< PointType >
A wrapper class to do a basic PCL processing for perception aided locomotion.
The available operations,
Downsample a point cloud
Remove outliers
Extract spatial clusters of point cloud
Transform a point cloud
Definition at line 47 of file PointCloudProcessor.h.
Member Function Documentation
downsample()
template<class PointType > bool BipedalLocomotion::Perception::Features::PointCloudProcessor< PointType >::downsample (const typename pcl::PointCloud< PointType >::Ptr inCloud, typename pcl::PointCloud< PointType >::Ptr outCloud)
Downsample the point cloud using voxel grid filter See https://pcl.readthedocs.io/projects/tutorials/en/latest/voxel_grid.html#voxelgrid.
Definition at line 193 of file PointCloudProcessor.h.
References BipedalLocomotion::log().
extractClusters()
template<class PointType > bool BipedalLocomotion::Perception::Features::PointCloudProcessor< PointType >::extractClusters (const typename pcl::PointCloud< PointType >::Ptr inCloud, std::vector< pcl::PointIndices > & clusterIndices, std::vector< typename pcl::PointCloud< PointType >::Ptr > & cloudClusters)
Extract Euclidean clustering based point cloud clusters See https://pcl.readthedocs.io/projects/tutorials/en/latest/cluster_extraction.html#cluster-extraction.
Definition at line 271 of file PointCloudProcessor.h.
References std::vector< T >::begin(), std::vector< T >::clear(), std::vector< T >::end(), and BipedalLocomotion::log().
removeOutliers()
template<class PointType > bool BipedalLocomotion::Perception::Features::PointCloudProcessor< PointType >::removeOutliers (const typename pcl::PointCloud< PointType >::Ptr inCloud, typename pcl::PointCloud< PointType >::Ptr outCloud)
Remove outliers from point cloud based on nearest neighbors See https://pcl.readthedocs.io/projects/tutorials/en/latest/statistical_outlier.html#statistical-outlier-removal.
Definition at line 244 of file PointCloudProcessor.h.
References BipedalLocomotion::log().
transform() [1/2]
template<class PointType > bool BipedalLocomotion::Perception::Features::PointCloudProcessor< PointType >::transform (const typename pcl::PointCloud< PointType >::Ptr inCloud, const Eigen::Affine3f & transform, typename pcl::PointCloud< PointType >::Ptr outCloud)
Transform point cloud See https://pcl.readthedocs.io/projects/tutorials/en/latest/matrix_transform.html.
Definition at line 338 of file PointCloudProcessor.h.
References BipedalLocomotion::log().
transform() [2/2]
template<class PointType > bool BipedalLocomotion::Perception::Features::PointCloudProcessor< PointType >::transform (const typename pcl::PointCloud< PointType >::Ptr inCloud, Eigen::Ref< const Eigen::Matrix4f > transform, typename pcl::PointCloud< PointType >::Ptr outCloud)
Transform point cloud See https://pcl.readthedocs.io/projects/tutorials/en/latest/matrix_transform.html.
Definition at line 317 of file PointCloudProcessor.h.
References BipedalLocomotion::log().
The documentation for this class was generated from the following file:
Perception/include/BipedalLocomotion/Perception/Features/PointCloudProcessor.h