bipedal-locomotion-framework: BipedalLocomotion::Estimators::RecursiveLeastSquare Class Reference
BipedalLocomotion::Estimators::RecursiveLeastSquare Class Reference
Public Member Functions
bool initialize (std::weak_ptr< const ParametersHandler::IParametersHandler > handlerWeak) override
Initialize the filter.
void setRegressorFunction (std::function< Eigen::MatrixXd(void)> regressor)
Set the regressor function.
void setRegressor (const Eigen::Ref< const Eigen::MatrixXd > &regressor)
Set the regressor function.
void setMeasurements (const Eigen::Ref< const Eigen::VectorXd > &measurements)
Set the measurements @parameter measurements vector containing all the measurements.
bool advance () final
Compute one step of the filter.
const RecursiveLeastSquareState & getOutput () const final
Get the expected value and the covariance matrix of the estimated parameters.
bool isOutputValid () const final
Determines the validity of the object retrieved with get()
Public Member Functions inherited from BipedalLocomotion::System::Source< RecursiveLeastSquareState >
bool setInput (const EmptySignal &input) final
Get the object.
Public Member Functions inherited from BipedalLocomotion::System::Advanceable< EmptySignal, RecursiveLeastSquareState >
virtual const Output & getOutput () const=0
Get the output of the advanceable.
virtual bool isOutputValid () const=0
Determines the validity of the object retrieved with getOutput()
virtual bool close ()
Close the Advanceable.
Additional Inherited Members
Public Types inherited from BipedalLocomotion::System::Advanceable< EmptySignal, RecursiveLeastSquareState >
using Input = EmptySignal
using Output = RecursiveLeastSquareState
Detailed Description
Definition at line 36 of file RecursiveLeastSquare.h.
Member Function Documentation
advance()
bool RecursiveLeastSquare::advance () final virtual
Compute one step of the filter.
Returns
True in case of success, false otherwise
Implements BipedalLocomotion::System::Advanceable< EmptySignal, RecursiveLeastSquareState >.
Definition at line 100 of file RecursiveLeastSquare.cpp.
References std::endl().
getOutput()
const RecursiveLeastSquareState & RecursiveLeastSquare::getOutput () const final
Get the expected value and the covariance matrix of the estimated parameters.
Returns
A struct containing the expected value and the covariance of the estimated parameters.
Definition at line 145 of file RecursiveLeastSquare.cpp.
initialize()
bool RecursiveLeastSquare::initialize (std::weak_ptr< const ParametersHandler::IParametersHandler > handlerWeak) override virtual
Initialize the filter.
Note
The following parameter are required by the filter:
"measurement_covariance" vector containing the covariance of the measurements. We assume that the measurements are uncorrelated (furthermore since the model of the noise is Gaussian the random variable are also independent) Since the variable are independent we are interested only on the element in the diagonal of the matrix
"lambda" double containing the filter gain. (The recursive least square filter is equivalent to a kalman filter if lambda is equal to 1)
"state" vector containing the initial guess of the state
"state_covariance" vector containing the diagonal matrix of the covariance of the state
Parameters
handlerWeak weak pointer to a ParametersHandler::IParametersHandler interface @tparameter Derived particular implementation of the IParameterHandler
Returns
True in case of success, false otherwise.
Reimplemented from BipedalLocomotion::System::Advanceable< EmptySignal, RecursiveLeastSquareState >.
Definition at line 15 of file RecursiveLeastSquare.cpp.
References std::endl(), and std::weak_ptr< T >::lock().
isOutputValid()
bool RecursiveLeastSquare::isOutputValid () const final
Determines the validity of the object retrieved with get()
Returns
True if the object is valid, false otherwise.
Definition at line 150 of file RecursiveLeastSquare.cpp.
setMeasurements()
void RecursiveLeastSquare::setMeasurements (const Eigen::Ref< const Eigen::VectorXd > & measurements)
Set the measurements @parameter measurements vector containing all the measurements.
Definition at line 139 of file RecursiveLeastSquare.cpp.
setRegressor()
void RecursiveLeastSquare::setRegressor (const Eigen::Ref< const Eigen::MatrixXd > & regressor)
Set the regressor function.
@parameter regressor is the regressor matrix.
Note
The user can decide to set the regressor function or set the regressor matrix by calling setReressor(). If setRegressorFunction() is called, the RLS algorithm will compute the regressor every time the advance() function is called.
Definition at line 95 of file RecursiveLeastSquare.cpp.
setRegressorFunction()
void RecursiveLeastSquare::setRegressorFunction (std::function< Eigen::MatrixXd(void)> regressor)
Set the regressor function.
@parameter regressor function that return an Eigen::MatrixXd containing the regressor of the system
Note
The user can decide to set the regressor function or set the regressor matrix by calling setReressor(). If setRegressorFunction() is called, the RLS algorithm will compute the regressor every time the advance() function is called.
Definition at line 90 of file RecursiveLeastSquare.cpp.
The documentation for this class was generated from the following files:
Estimators/include/BipedalLocomotion/Estimators/RecursiveLeastSquare.h
Estimators/src/RecursiveLeastSquare.cpp