bipedal-locomotion-framework: BipedalLocomotion::Contacts::SchmittTriggerDetector Class Reference
BipedalLocomotion::Contacts::SchmittTriggerDetector Class Reference
Schmitt Trigger thresholding based contact detector that maintains and updates the contact states for a prescribed set of contacts.
#include <BipedalLocomotion/ContactDetectors/SchmittTriggerDetector.h>
Data Structures
class Impl
Public Member Functions
bool setTimedTriggerInput (const std::string &contactName, const double &time, const double &triggerInput)
Set trigger input and time stamp for an existing SchmittTrigger unit.
bool setTimedTriggerInputs (const std::unordered_map< std::string, SchmittTriggerInput > &timedInputs)
Set trigger input and time stamp for existing units.
bool addContact (const std::string &contactName, const bool &initialState, const SchmittTriggerParams &params)
Add a contact whose contact state need to be tracked.
bool addContact (const std::string &contactName, const bool &initialState, const SchmittTriggerParams &params, const double &time_now)
Add a contact whose contact state need to be tracked.
bool resetState (const std::string &contactName, const bool &state)
Reset a contact's state.
bool resetContact (const std::string &contactName, const bool &state, const SchmittTriggerParams &params)
Reset a contact's parameters.
bool removeContact (const std::string &contactName)
Remove contact from the Detector.
Public Member Functions inherited from BipedalLocomotion::Contacts::ContactDetector
bool initialize (std::weak_ptr< const ParametersHandler::IParametersHandler > handler) override
Configure generic parameters.
bool advance () final
Compute one step of the detector The derived class must implement its own methods for setting measurements and update states to be called within the advance() method.
bool isOutputValid () const final
Determines the validity of the object retrieved with get()
const EstimatedContactList & getOutput () const final
Get contact states.
bool resetContacts ()
Reset the internal contact states of the detector to false.
bool get (const std::string &contactName, Contacts::EstimatedContact &contact) const
Get state of specific contact.
Contacts::EstimatedContact get (const std::string &contactName) const
Get state of specific contact.
Public Member Functions inherited from BipedalLocomotion::System::Source< EstimatedContactList >
bool setInput (const EmptySignal &input) final
Get the object.
Public Member Functions inherited from BipedalLocomotion::System::Advanceable< EmptySignal, EstimatedContactList >
virtual const Output & getOutput () const=0
Get the output of the advanceable.
virtual bool isOutputValid () const=0
Determines the validity of the object retrieved with getOutput()
virtual bool close ()
Close the Advanceable.
Protected Member Functions
virtual bool customInitialization (std::weak_ptr< const ParametersHandler::IParametersHandler > handler) override
These custom parameter specifications should be specified by the derived class.
virtual bool updateContactStates () override
Update contact states based on thresholding of contact normal forces and timing parameters.
Additional Inherited Members
Public Types inherited from BipedalLocomotion::System::Advanceable< EmptySignal, EstimatedContactList >
using Input = EmptySignal
using Output = EstimatedContactList
Protected Types inherited from BipedalLocomotion::Contacts::ContactDetector
enum State { State::NotInitialized, State::Initialized, State::Running }
Enumerator used to determine the running state of the estimator.
Protected Attributes inherited from BipedalLocomotion::Contacts::ContactDetector
State m_detectorState {State::NotInitialized}
State of the estimator.
EstimatedContactList m_contactStates
Detailed Description
Schmitt Trigger thresholding based contact detector that maintains and updates the contact states for a prescribed set of contacts.
Definition at line 29 of file SchmittTriggerDetector.h.
Member Function Documentation
addContact() [1/2]
bool SchmittTriggerDetector::addContact (const std::string & contactName, const bool & initialState, const SchmittTriggerParams & params)
Add a contact whose contact state need to be tracked.
Parameters
[in] contactName name of the contact
[in] initialState initial contact state
[in] params Schmitt Trigger parameters
Note
this method does not reset the state and parameters if the contact already exists
Returns
True in case of success, false otherwise.
Definition at line 180 of file SchmittTriggerDetector.cpp.
addContact() [2/2]
bool SchmittTriggerDetector::addContact (const std::string & contactName, const bool & initialState, const SchmittTriggerParams & params, const double & time_now)
Add a contact whose contact state need to be tracked.
Parameters
[in] contactName name of the contact
[in] initialState initial contact state
[in] params Schmitt Trigger parameters
[in] time_now current time instant to initialize the Schmitt trigger timers
Note
this method does not reset the state and parameters if the contact already exists
Returns
True in case of success, false otherwise.
Definition at line 189 of file SchmittTriggerDetector.cpp.
References std::endl(), BipedalLocomotion::Contacts::EstimatedContact::isActive, std::make_pair(), BipedalLocomotion::Contacts::ContactBase::name, BipedalLocomotion::Contacts::SchmittTriggerUnit::setParams(), and BipedalLocomotion::Contacts::SchmittTriggerUnit::setState().
customInitialization()
bool SchmittTriggerDetector::customInitialization (std::weak_ptr< const ParametersHandler::IParametersHandler > handler) override protected virtual
These custom parameter specifications should be specified by the derived class.
Parameters
[in] handler configure the custom parameters for the detector
Returns
True in case of success, false otherwise.
Reimplemented from BipedalLocomotion::Contacts::ContactDetector.
Definition at line 56 of file SchmittTriggerDetector.cpp.
References std::endl(), std::weak_ptr< T >::lock(), BipedalLocomotion::Contacts::SchmittTriggerParams::offThreshold, BipedalLocomotion::Contacts::SchmittTriggerParams::onThreshold, std::vector< T >::size(), BipedalLocomotion::Contacts::SchmittTriggerParams::switchOffAfter, and BipedalLocomotion::Contacts::SchmittTriggerParams::switchOnAfter.
removeContact()
bool SchmittTriggerDetector::removeContact (const std::string & contactName)
Remove contact from the Detector.
Parameters
[in] contactName name of the contact
Returns
True in case of success, false if does not exist/otherwise.
Definition at line 215 of file SchmittTriggerDetector.cpp.
References std::endl().
resetContact()
bool SchmittTriggerDetector::resetContact (const std::string & contactName, const bool & state, const SchmittTriggerParams & params)
Reset a contact's parameters.
Parameters
[in] contactName name of the contact
[in] initialState initial contact state
[in] params Schmitt Trigger parameters
Returns
True in case of success, false if contact does not exist/otherwise.
Definition at line 230 of file SchmittTriggerDetector.cpp.
References std::endl().
resetState()
bool SchmittTriggerDetector::resetState (const std::string & contactName, const bool & state)
Reset a contact's state.
Parameters
[in] contactName name of the contact
[in] initialState contact state
Returns
True in case of success, false if contact does not exist/otherwise.
Definition at line 249 of file SchmittTriggerDetector.cpp.
References std::endl().
setTimedTriggerInput()
bool SchmittTriggerDetector::setTimedTriggerInput (const std::string & contactName, const double & time, const double & triggerInput)
Set trigger input and time stamp for an existing SchmittTrigger unit.
Parameters
[in] contactName name of the contact
[in] time time of measurement
[in] force contact force intensity (typically contact normal force)
Returns
True in case of success, false otherwise.
Definition at line 136 of file SchmittTriggerDetector.cpp.
References std::endl().
setTimedTriggerInputs()
bool SchmittTriggerDetector::setTimedTriggerInputs (const std::unordered_map< std::string, SchmittTriggerInput > & timedInputs)
Set trigger input and time stamp for existing units.
Parameters
[in] timedInputs container of timed trigger inputs, pair(first, second): (time, force)
Note
any unit names in the input container that does not already exist will be ignored
Returns
True in case of success, false otherwise.
Definition at line 153 of file SchmittTriggerDetector.cpp.
References std::string::at(), std::vector< T >::emplace_back(), std::endl(), and std::vector< T >::size().
updateContactStates()
bool SchmittTriggerDetector::updateContactStates () override protected virtual
Update contact states based on thresholding of contact normal forces and timing parameters.
Returns
True in case of success, false otherwise.
Implements BipedalLocomotion::Contacts::ContactDetector.
Definition at line 121 of file SchmittTriggerDetector.cpp.
The documentation for this class was generated from the following files:
Contacts/include/BipedalLocomotion/ContactDetectors/SchmittTriggerDetector.h
Contacts/src/SchmittTriggerDetector.cpp