bipedal-locomotion-framework: BipedalLocomotion::ContactModels::ContactModel Class Reference
BipedalLocomotion::ContactModels::ContactModel Class Reference abstract
ContactModel is a generic implementation of a contact model.
#include <BipedalLocomotion/ContactModels/ContactModel.h>
Public Member Functions
bool initialize (std::weak_ptr< ParametersHandler::IParametersHandler > handler)
Initialization of the class.
const iDynTree::Wrench & getContactWrench ()
Get and compute (only if it is necessary) the contact wrench.
const iDynTree::Vector6 & getAutonomousDynamics ()
Get and compute (only if it is necessary) the autonomous system dynamics.
const iDynTree::Matrix6x6 & getControlMatrix ()
Get and compute (only if it is necessary) the control matrix.
const iDynTree::MatrixDynSize & getRegressor ()
Get and compute (only if it is necessary) the regressor.
void setState (const iDynTree::Twist &twist, const iDynTree::Transform &transform)
Set the internal state of the model.
void setNullForceTransform (const iDynTree::Transform &transform)
Protected Member Functions
virtual void computeContactWrench ()=0
Evaluate the contact wrench given a specific contact model.
virtual void computeAutonomousDynamics ()=0
Evaluate the Autonomous System Dynamics of the derivative of a specific contact model.
virtual void computeControlMatrix ()=0
Evaluate the Control Matrix of the derivative of a specific contact model.
virtual void computeRegressor ()=0
Evaluate the regressor matrix.
virtual bool initializePrivate (std::weak_ptr< ParametersHandler::IParametersHandler > handler)=0
Initialization of the class.
virtual void setStatePrivate (const iDynTree::Twist &twist, const iDynTree::Transform &transform)=0
Set the internal state of the model.
virtual void setNullForceTransformPrivate (const iDynTree::Transform &transform)=0
Set the null force transform.
Protected Attributes
iDynTree::Wrench m_contactWrench
Contact wrench between the robot and the environment expressed in mixed representation.
iDynTree::Vector6 m_autonomousDynamics
Autonomous dynamics of the contact model rate of change (i.e.
iDynTree::Matrix6x6 m_controlMatrix
Control matrix of the contact model rate of change (i.e.
iDynTree::MatrixDynSize m_regressor
Contains the regressor of the contact model.
Detailed Description
ContactModel is a generic implementation of a contact model.
It computes the contact wrench between the robot and the environments.
Definition at line 33 of file ContactModel.h.
Member Function Documentation
computeAutonomousDynamics()
virtual void BipedalLocomotion::ContactModels::ContactModel::computeAutonomousDynamics () protected pure virtual
Evaluate the Autonomous System Dynamics of the derivative of a specific contact model.
Referenced by getAutonomousDynamics().
computeContactWrench()
virtual void BipedalLocomotion::ContactModels::ContactModel::computeContactWrench () protected pure virtual
Evaluate the contact wrench given a specific contact model.
Referenced by getContactWrench().
computeControlMatrix()
virtual void BipedalLocomotion::ContactModels::ContactModel::computeControlMatrix () protected pure virtual
Evaluate the Control Matrix of the derivative of a specific contact model.
Referenced by getControlMatrix().
computeRegressor()
virtual void BipedalLocomotion::ContactModels::ContactModel::computeRegressor () protected pure virtual
Evaluate the regressor matrix.
Referenced by getRegressor().
getAutonomousDynamics()
const iDynTree::Vector6 & ContactModel::getAutonomousDynamics ()
Get and compute (only if it is necessary) the autonomous system dynamics.
Returns
the autonomous system dynamics at a given state
Definition at line 61 of file ContactModel.cpp.
References computeAutonomousDynamics(), and m_autonomousDynamics.
getContactWrench()
const iDynTree::Wrench & ContactModel::getContactWrench ()
Get and compute (only if it is necessary) the contact wrench.
Returns
the contact wrench expressed in mixed representation
Definition at line 50 of file ContactModel.cpp.
References computeContactWrench(), and m_contactWrench.
getControlMatrix()
const iDynTree::Matrix6x6 & ContactModel::getControlMatrix ()
Get and compute (only if it is necessary) the control matrix.
Returns
the control matrix at a given state
Definition at line 72 of file ContactModel.cpp.
References computeControlMatrix(), and m_controlMatrix.
getRegressor()
const iDynTree::MatrixDynSize & ContactModel::getRegressor ()
Get and compute (only if it is necessary) the regressor.
Returns
the regressor at a given state
Definition at line 83 of file ContactModel.cpp.
References computeRegressor(), and m_regressor.
initialize()
bool ContactModel::initialize (std::weak_ptr< ParametersHandler::IParametersHandler > handler)
Initialization of the class.
Please call this method before evaluating any other function
Parameters
handler std::weak_ptr to a parameter container. This class does not have the ownership of the container.
Warning
std::weak_ptr models temporary ownership: when the handler is accessed only if it exists, the std::weak_ptr is converted in a std::shared_ptr.
Note
the required parameters may depends on the particular implementation. An example can be found in BipedalLocomotionControllers::ContactModel::ContinuousContactmodel::initializePrivate
Returns
true/false in case of success/failure
Definition at line 12 of file ContactModel.cpp.
References initializePrivate().
initializePrivate()
virtual bool BipedalLocomotion::ContactModels::ContactModel::initializePrivate (std::weak_ptr< ParametersHandler::IParametersHandler > handler) protected pure virtual
Initialization of the class.
Parameters
handler std::weak_ptr to a parameter container. This class does not have the ownership of the container.
Note
the required parameters may depends on the particular implementation. An example can be found in BipedalLocomotionControllers::ContactModel::ContinuousContactmodel::initializePrivate
Returns
true/false in case of success/failure
Referenced by initialize().
setNullForceTransformPrivate()
virtual void BipedalLocomotion::ContactModels::ContactModel::setNullForceTransformPrivate (const iDynTree::Transform & transform) protected pure virtual
Set the null force transform.
setState()
void ContactModel::setState (const iDynTree::Twist & twist, const iDynTree::Transform & transform)
Set the internal state of the model.
Note
the meaning of the parameters may depend on the particular implementation. An example can be found in BipedalLocomotionControllers::ContactModel::ContinuousContactmodel::setState
Definition at line 35 of file ContactModel.cpp.
References setStatePrivate().
setStatePrivate()
virtual void BipedalLocomotion::ContactModels::ContactModel::setStatePrivate (const iDynTree::Twist & twist, const iDynTree::Transform & transform) protected pure virtual
Set the internal state of the model.
Referenced by setState().
Field Documentation
m_autonomousDynamics
iDynTree::Vector6 BipedalLocomotion::ContactModels::ContactModel::m_autonomousDynamics protected
Autonomous dynamics of the contact model rate of change (i.e.
given a non linear system \(\dot{x} = f + g u\) the autonomous dynamics is f
Definition at line 48 of file ContactModel.h.
Referenced by getAutonomousDynamics().
m_contactWrench
iDynTree::Wrench BipedalLocomotion::ContactModels::ContactModel::m_contactWrench protected
Contact wrench between the robot and the environment expressed in mixed representation.
Definition at line 43 of file ContactModel.h.
Referenced by getContactWrench().
m_controlMatrix
iDynTree::Matrix6x6 BipedalLocomotion::ContactModels::ContactModel::m_controlMatrix protected
Control matrix of the contact model rate of change (i.e.
given a non linear system \(\dot{x} = f + g u\) the control matrix is g
Definition at line 52 of file ContactModel.h.
Referenced by getControlMatrix().
m_regressor
iDynTree::MatrixDynSize BipedalLocomotion::ContactModels::ContactModel::m_regressor protected
Contains the regressor of the contact model.
\(f = A \theta\), where \(f\) is the contact wrench, \(A\) the regressor and \(\theta\) the parameters
Definition at line 56 of file ContactModel.h.
Referenced by getRegressor().
The documentation for this class was generated from the following files:
ContactModels/include/BipedalLocomotion/ContactModels/ContactModel.h
ContactModels/src/ContactModel.cpp