bipedal-locomotion-framework: BipedalLocomotion::ContinuousDynamicalSystem::FixedStepIntegrator< _Derived > Class Template Reference
BipedalLocomotion::ContinuousDynamicalSystem::FixedStepIntegrator< _Derived > Class Template Reference
Fixed step integrator base class.
#include </home/runner/work/bipedal-locomotion-framework/bipedal-locomotion-framework/gh-pages/src/ContinuousDynamicalSystem/include/BipedalLocomotion/ContinuousDynamicalSystem/FixedStepIntegrator.h>
Public Member Functions
bool setIntegrationStep (const double &dT)
Set the integration step time.
bool integrate (double initialTime, double finalTime)
Integrate the dynamical system from initialTime to finalTime.
Public Member Functions inherited from BipedalLocomotion::ContinuousDynamicalSystem::Integrator< _Derived >
bool setDynamicalSystem (std::shared_ptr< DynamicalSystem > dynamicalSystem)
Set the DynamicalSystem to be considered.
std::weak_ptr< DynamicalSystem > dynamicalSystem () const
Get the dynamical system.
const State & getSolution () const
Retrieve the solution.
bool integrate (double initialTime, double finalTime)
Integrate the dynamical system from initialTime to finalTime.
Protected Attributes
double m_dT {-1}
Fixed step size.
Protected Attributes inherited from BipedalLocomotion::ContinuousDynamicalSystem::Integrator< _Derived >
std::shared_ptr< DynamicalSystem > m_dynamicalSystem
Pointer to a dynamical system.
Additional Inherited Members
Public Types inherited from BipedalLocomotion::ContinuousDynamicalSystem::Integrator< _Derived >
using DynamicalSystem = typename internal::traits< _Derived >::DynamicalSystem
DynamicalSystem type.
using State = typename internal::traits< _Derived >::State
State of the integrator type.
Detailed Description
template<class _Derived>
class BipedalLocomotion::ContinuousDynamicalSystem::FixedStepIntegrator< _Derived >
Fixed step integrator base class.
Please inherit publicly from this class in order to specify a custom integration method. The custom integration method must define a method called oneStepIntegration()
Definition at line 26 of file FixedStepIntegrator.h.
Member Function Documentation
integrate()
template<class _Derived > bool BipedalLocomotion::ContinuousDynamicalSystem::FixedStepIntegrator< _Derived >::integrate (double initialTime, double finalTime)
Integrate the dynamical system from initialTime to finalTime.
Note
We assume a constant control input in the interval.
Parameters
initialTime initial time of the integration.
finalTime final time of the integration.
Returns
true in case of success, false otherwise.
Definition at line 64 of file FixedStepIntegrator.h.
References std::ceil(), and BipedalLocomotion::log().
setIntegrationStep()
template<class _Derived > bool BipedalLocomotion::ContinuousDynamicalSystem::FixedStepIntegrator< _Derived >::setIntegrationStep (const double & dT)
Set the integration step time.
Parameters
dT integration step time
Definition at line 49 of file FixedStepIntegrator.h.
References BipedalLocomotion::log().
Field Documentation
m_dT
template<class _Derived > double BipedalLocomotion::ContinuousDynamicalSystem::FixedStepIntegrator< _Derived >::m_dT {-1} protected
Fixed step size.
Definition at line 30 of file FixedStepIntegrator.h.
The documentation for this class was generated from the following file:
ContinuousDynamicalSystem/include/BipedalLocomotion/ContinuousDynamicalSystem/FixedStepIntegrator.h