bipedal-locomotion-framework: BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::Impl Class Reference
BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::Impl Class Reference
Data Structures
struct SkewSymContainter
Struct containing skew-symmetric matrices.
Public Member Functions
bool constructState (const Eigen::MatrixXd &X, const Eigen::Matrix< double, 6, 1 > &theta, FloatingBaseEstimators::InternalState &state)
Construct internal state object given,.
void extractState (const FloatingBaseEstimators::InternalState &state, Eigen::MatrixXd &X, Eigen::Matrix< double, 6, 1 > &theta)
Extract.
void constuctStateVar (const FloatingBaseEstimators::StateStdDev &stateStdDev, const bool &estimateBias, Eigen::MatrixXd &P)
Construct the state covariance matrix from the internal state standard deviation object,.
void extractStateVar (const Eigen::MatrixXd &P, const bool &estimateBias, FloatingBaseEstimators::StateStdDev &stateStdDev)
Extract internal state standard deviation object, from the diagonal elements of the state covariance matrix.
bool propagateStates (const FloatingBaseEstimators::Measurements &meas, const double &dt, const Eigen::Vector3d &g, const manif::SE3d &IMU_H_RF, const manif::SE3d &IMU_H_LF, FloatingBaseEstimators::InternalState &X)
Propagate internal state of the estimator, given previous IMU measurements and predicted foot poses relative to IMU.
bool updateStates (const Eigen::VectorXd &obs, const Eigen::MatrixXd measModelJacobian, const Eigen::MatrixXd &measNoiseVar, const Eigen::MatrixXd &auxMat, FloatingBaseEstimators::InternalState &state, Eigen::MatrixXd &P)
Perform the Kalman filter update step given measurements and Jacobians.
bool calcExpHatX (const Eigen::VectorXd &vec, Eigen::MatrixXd &X)
Compute exponential map of.
void calcAdjointX (const FloatingBaseEstimators::InternalState &X, const SkewSymContainter &skew, Eigen::MatrixXd &AdjX)
Compute Adjoint matrix of.
bool copyDiagX (const Eigen::MatrixXd &X, const int &n, Eigen::MatrixXd &BigX)
Copy the state matrix X along block diagonal.
void calcQc (const FloatingBaseEstimators::InternalState &X, const FloatingBaseEstimators::SensorsStdDev &sensStdDev, const FloatingBaseEstimators::Measurements &meas, const bool &estimateBias, Eigen::MatrixXd &Qc)
Compute continuous time system noise covariance matrix using the predicted internal state estimates.
void calcLc (const FloatingBaseEstimators::InternalState &X, const SkewSymContainter &skew, const bool &estimateBias, Eigen::MatrixXd &Lc)
Compute transformation matrix for the system noise using the predicted internal state estimates.
void calcFc (const FloatingBaseEstimators::InternalState &X, const SkewSymContainter &skew, const bool &estimateBias, Eigen::MatrixXd &Fc)
Compute continuous time linearized state propagation matrix.
void calcSkewSymAtCurrenState (const FloatingBaseEstimators::InternalState &X, SkewSymContainter &skew)
Compute skew symmetric matrices given states.
void updateFilterMatrixDimensions (const bool &estimateBias)
Dynamically update filter matrices depending on bias estimation flag.
Data Fields
SkewSymContainter m_skew
skew symmetric matrix container
Eigen::MatrixXd m_P
state covariance matrix
Eigen::MatrixXd m_Fc
Eigen::MatrixXd m_Qc
Eigen::MatrixXd m_Lc
continuous time system propagation matrices
Eigen::MatrixXd m_Fk
Eigen::MatrixXd m_Qk
discrete time system propagation matrices
Eigen::MatrixXd m_In
Eigen::MatrixXd m_PHT
identity matrix with dimensions of state manifold tangent space
Eigen::MatrixXd m_S
Eigen::MatrixXd m_K
Eigen::MatrixXd m_IminusKH
Eigen::VectorXd m_obs
measurement update matrices
Eigen::MatrixXd m_measModelJacobian
Eigen::MatrixXd m_measNoiseVar
Eigen::MatrixXd m_auxMat
measurement model matrices
Eigen::MatrixXd m_BigX
Eigen::MatrixXd m_innovation
invariant error update related matrices
Eigen::VectorXd m_delta
correction term
Eigen::MatrixXd m_X
Eigen::MatrixXd m_dX
placeholder for state update variables
Eigen::Matrix< double, 6, 1 > m_theta
Eigen::Matrix< double, 6, 1 > m_deltaTheta
placeholder for parameter update variables
manif::SE3d IMU_H_LF
manif::SE3d IMU_H_RF
buffers for relative transforms
Eigen::MatrixXd J_IMULF
Eigen::MatrixXd J_IMURF
buffers for relative Jacobians
const size_t m_vecSizeWOBias {15}
Tangent space vector size without considering IMU biases.
const size_t m_vecSizeWBias {21}
Tangent space vector size considering IMU biases.
struct {
const size_t imuOrientation {0}
const size_t imuLinearVel {3}
const size_t imuPosition {6}
const size_t rContactFramePosition {9}
const size_t lContactFramePosition {12}
const size_t gyroBias {15}
const size_t accBias {18}
} m_vecOffsets
Tangent space vector offsets.
bool m_prevBiasEstimationFlag {false}
Friends
class InvariantEKFBaseEstimator
Detailed Description
Definition at line 15 of file InvariantEKFBaseEstimator.cpp.
Member Function Documentation
calcAdjointX()
void BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::Impl::calcAdjointX (const FloatingBaseEstimators::InternalState & X, const SkewSymContainter & skew, Eigen::MatrixXd & AdjX)
Compute Adjoint matrix of.
\[SE_2+2(3)\]
The order of vector, (w, a, v, vr, vl) where w - angular velocity IMU a - linear acceleration IMU v - linear velocity IMU vr - linear velocity of right foot contact freame vl - linear velocity of left foot contact freame We choose this order to be consistent with original paper implementation
Definition at line 777 of file InvariantEKFBaseEstimator.cpp.
References BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::imuOrientation, BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::Impl::SkewSymContainter::pCross, BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::Impl::SkewSymContainter::plCross, BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::Impl::SkewSymContainter::prCross, and BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::Impl::SkewSymContainter::vCross.
calcExpHatX()
bool BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::Impl::calcExpHatX (const Eigen::VectorXd & vec, Eigen::MatrixXd & X)
Compute exponential map of.
\[SE_2+2(3)\]
this is a composition of a hat and a exp operator Exp: R9 to SE_2+2(3) The order of vector, (w, a, v, vr, vl) where w - angular velocity IMU a - linear acceleration IMU v - linear velocity IMU vr - linear velocity of right foot contact freame vl - linear velocity of left foot contact freame We choose this order to be consistent with original paper implementation
Definition at line 749 of file InvariantEKFBaseEstimator.cpp.
References std::endl().
calcFc()
void BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::Impl::calcFc (const FloatingBaseEstimators::InternalState & X, const SkewSymContainter & skew, const bool & estimateBias, Eigen::MatrixXd & Fc)
Compute continuous time linearized state propagation matrix.
Definition at line 802 of file InvariantEKFBaseEstimator.cpp.
References BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::Impl::SkewSymContainter::gCross, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::imuOrientation, BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::Impl::SkewSymContainter::pCross, BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::Impl::SkewSymContainter::plCross, BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::Impl::SkewSymContainter::prCross, and BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::Impl::SkewSymContainter::vCross.
calcLc()
void BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::Impl::calcLc (const FloatingBaseEstimators::InternalState & X, const SkewSymContainter & skew, const bool & estimateBias, Eigen::MatrixXd & Lc)
Compute transformation matrix for the system noise using the predicted internal state estimates.
Definition at line 901 of file InvariantEKFBaseEstimator.cpp.
calcQc()
void BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::Impl::calcQc (const FloatingBaseEstimators::InternalState & X, const FloatingBaseEstimators::SensorsStdDev & sensStdDev, const FloatingBaseEstimators::Measurements & meas, const bool & estimateBias, Eigen::MatrixXd & Qc)
Compute continuous time system noise covariance matrix using the predicted internal state estimates.
Definition at line 844 of file InvariantEKFBaseEstimator.cpp.
References BipedalLocomotion::Estimators::FloatingBaseEstimators::SensorsStdDev::accelerometerBiasNoise, BipedalLocomotion::Estimators::FloatingBaseEstimators::SensorsStdDev::accelerometerNoise, BipedalLocomotion::Estimators::FloatingBaseEstimators::SensorsStdDev::contactFootLinvelNoise, BipedalLocomotion::Estimators::FloatingBaseEstimators::SensorsStdDev::gyroscopeBiasNoise, BipedalLocomotion::Estimators::FloatingBaseEstimators::SensorsStdDev::gyroscopeNoise, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::imuOrientation, BipedalLocomotion::Estimators::FloatingBaseEstimators::Measurements::lfInContact, BipedalLocomotion::Estimators::FloatingBaseEstimators::Measurements::rfInContact, and BipedalLocomotion::Estimators::FloatingBaseEstimators::SensorsStdDev::swingFootLinvelNoise.
calcSkewSymAtCurrenState()
void BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::Impl::calcSkewSymAtCurrenState (const FloatingBaseEstimators::InternalState & X, SkewSymContainter & skew)
Compute skew symmetric matrices given states.
Definition at line 928 of file InvariantEKFBaseEstimator.cpp.
References BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::imuLinearVelocity, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::imuPosition, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::lContactFramePosition, BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::Impl::SkewSymContainter::pCross, BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::Impl::SkewSymContainter::plCross, BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::Impl::SkewSymContainter::prCross, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::rContactFramePosition, and BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::Impl::SkewSymContainter::vCross.
constructState()
bool BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::Impl::constructState (const Eigen::MatrixXd & X, const Eigen::Matrix< double, 6, 1 > & theta, FloatingBaseEstimators::InternalState & state)
Construct internal state object given,.
state matrix
\[ X \in SE_2+2(3) \]
and
parameters vector
\[ \theta \in \mathbb{R}^6 \]
Definition at line 729 of file InvariantEKFBaseEstimator.cpp.
References BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::accelerometerBias, std::endl(), BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::gyroscopeBias, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::imuLinearVelocity, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::imuOrientation, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::imuPosition, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::lContactFramePosition, and BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::rContactFramePosition.
constuctStateVar()
void BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::Impl::constuctStateVar (const FloatingBaseEstimators::StateStdDev & stateStdDev, const bool & estimateBias, Eigen::MatrixXd & P)
Construct the state covariance matrix from the internal state standard deviation object,.
Definition at line 671 of file InvariantEKFBaseEstimator.cpp.
References BipedalLocomotion::Estimators::FloatingBaseEstimators::StateStdDev::accelerometerBias, BipedalLocomotion::Estimators::FloatingBaseEstimators::StateStdDev::gyroscopeBias, BipedalLocomotion::Estimators::FloatingBaseEstimators::StateStdDev::imuLinearVelocity, BipedalLocomotion::Estimators::FloatingBaseEstimators::StateStdDev::imuOrientation, BipedalLocomotion::Estimators::FloatingBaseEstimators::StateStdDev::imuPosition, BipedalLocomotion::Estimators::FloatingBaseEstimators::StateStdDev::lContactFramePosition, and BipedalLocomotion::Estimators::FloatingBaseEstimators::StateStdDev::rContactFramePosition.
copyDiagX()
bool BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::Impl::copyDiagX (const Eigen::MatrixXd & X, const int & n, Eigen::MatrixXd & BigX)
Copy the state matrix X along block diagonal.
This is used for multiplying the stacked observations
Definition at line 938 of file InvariantEKFBaseEstimator.cpp.
References std::endl().
extractState()
void BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::Impl::extractState (const FloatingBaseEstimators::InternalState & state, Eigen::MatrixXd & X, Eigen::Matrix< double, 6, 1 > & theta)
Extract.
state matrix
\[ X \in SE_2+2(3) \]
and
parameters vector
\[ \theta \in \mathbb{R}^6 \]
, from internal state object
Definition at line 707 of file InvariantEKFBaseEstimator.cpp.
References BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::accelerometerBias, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::gyroscopeBias, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::imuLinearVelocity, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::imuOrientation, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::imuPosition, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::lContactFramePosition, and BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::rContactFramePosition.
extractStateVar()
void BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::Impl::extractStateVar (const Eigen::MatrixXd & P, const bool & estimateBias, FloatingBaseEstimators::StateStdDev & stateStdDev)
Extract internal state standard deviation object, from the diagonal elements of the state covariance matrix.
Definition at line 655 of file InvariantEKFBaseEstimator.cpp.
References BipedalLocomotion::Estimators::FloatingBaseEstimators::StateStdDev::accelerometerBias, BipedalLocomotion::Estimators::FloatingBaseEstimators::StateStdDev::gyroscopeBias, BipedalLocomotion::Estimators::FloatingBaseEstimators::StateStdDev::imuLinearVelocity, BipedalLocomotion::Estimators::FloatingBaseEstimators::StateStdDev::imuOrientation, BipedalLocomotion::Estimators::FloatingBaseEstimators::StateStdDev::imuPosition, BipedalLocomotion::Estimators::FloatingBaseEstimators::StateStdDev::lContactFramePosition, and BipedalLocomotion::Estimators::FloatingBaseEstimators::StateStdDev::rContactFramePosition.
propagateStates()
bool BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::Impl::propagateStates (const FloatingBaseEstimators::Measurements & meas, const double & dt, const Eigen::Vector3d & g, const manif::SE3d & IMU_H_RF, const manif::SE3d & IMU_H_LF, FloatingBaseEstimators::InternalState & X)
Propagate internal state of the estimator, given previous IMU measurements and predicted foot poses relative to IMU.
Definition at line 551 of file InvariantEKFBaseEstimator.cpp.
References BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::accelerometerBias, BipedalLocomotion::Estimators::FloatingBaseEstimators::Measurements::gyro, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::gyroscopeBias, BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::Impl::IMU_H_RF, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::imuLinearVelocity, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::imuOrientation, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::imuPosition, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::lContactFramePosition, BipedalLocomotion::Estimators::FloatingBaseEstimators::Measurements::lfInContact, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::rContactFramePosition, and BipedalLocomotion::Estimators::FloatingBaseEstimators::Measurements::rfInContact.
updateFilterMatrixDimensions()
void BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::Impl::updateFilterMatrixDimensions (const bool & estimateBias)
Dynamically update filter matrices depending on bias estimation flag.
Definition at line 322 of file InvariantEKFBaseEstimator.cpp.
updateStates()
bool BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::Impl::updateStates (const Eigen::VectorXd & obs, const Eigen::MatrixXd measModelJacobian, const Eigen::MatrixXd & measNoiseVar, const Eigen::MatrixXd & auxMat, FloatingBaseEstimators::InternalState & state, Eigen::MatrixXd & P)
Perform the Kalman filter update step given measurements and Jacobians.
Definition at line 586 of file InvariantEKFBaseEstimator.cpp.
References std::endl().
Field Documentation
IMU_H_RF
manif::SE3d BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::Impl::IMU_H_RF
buffers for relative transforms
Definition at line 176 of file InvariantEKFBaseEstimator.cpp.
Referenced by BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::Impl::propagateStates().
J_IMURF
Eigen::MatrixXd BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::Impl::J_IMURF
buffers for relative Jacobians
Definition at line 177 of file InvariantEKFBaseEstimator.cpp.
m_auxMat
Eigen::MatrixXd BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::Impl::m_auxMat
measurement model matrices
Definition at line 170 of file InvariantEKFBaseEstimator.cpp.
m_delta
Eigen::VectorXd BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::Impl::m_delta
correction term
Definition at line 172 of file InvariantEKFBaseEstimator.cpp.
m_deltaTheta
Eigen::Matrix<double, 6, 1> BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::Impl::m_deltaTheta
placeholder for parameter update variables
Definition at line 174 of file InvariantEKFBaseEstimator.cpp.
m_dX
Eigen::MatrixXd BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::Impl::m_dX
placeholder for state update variables
Definition at line 173 of file InvariantEKFBaseEstimator.cpp.
m_innovation
Eigen::MatrixXd BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::Impl::m_innovation
invariant error update related matrices
Definition at line 171 of file InvariantEKFBaseEstimator.cpp.
m_Lc
Eigen::MatrixXd BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::Impl::m_Lc
continuous time system propagation matrices
Definition at line 165 of file InvariantEKFBaseEstimator.cpp.
m_obs
Eigen::VectorXd BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::Impl::m_obs
measurement update matrices
observation vector
Definition at line 169 of file InvariantEKFBaseEstimator.cpp.
m_P
Eigen::MatrixXd BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::Impl::m_P
state covariance matrix
Definition at line 164 of file InvariantEKFBaseEstimator.cpp.
m_PHT
Eigen::MatrixXd BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::Impl::m_PHT
identity matrix with dimensions of state manifold tangent space
Definition at line 168 of file InvariantEKFBaseEstimator.cpp.
m_Qk
Eigen::MatrixXd BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::Impl::m_Qk
discrete time system propagation matrices
Definition at line 166 of file InvariantEKFBaseEstimator.cpp.
m_skew
SkewSymContainter BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::Impl::m_skew
skew symmetric matrix container
Definition at line 162 of file InvariantEKFBaseEstimator.cpp.
m_vecOffsets
struct { ... } BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::Impl::m_vecOffsets
Tangent space vector offsets.
m_vecSizeWBias
const size_t BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::Impl::m_vecSizeWBias {21}
Tangent space vector size considering IMU biases.
Definition at line 180 of file InvariantEKFBaseEstimator.cpp.
m_vecSizeWOBias
const size_t BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::Impl::m_vecSizeWOBias {15}
Tangent space vector size without considering IMU biases.
Definition at line 179 of file InvariantEKFBaseEstimator.cpp.
The documentation for this class was generated from the following file:
Estimators/src/InvariantEKFBaseEstimator.cpp