bipedal-locomotion-framework: BipedalLocomotion::Math::LinearizedFrictionCone Class Reference
BipedalLocomotion::Math::LinearizedFrictionCone Class Reference
LinearizedFrictionCone computes the polyhedral approximation of the friction cone.
#include <BipedalLocomotion/Math/LinearizedFrictionCone.h>
Public Member Functions
bool initialize (std::weak_ptr< ParametersHandler::IParametersHandler > handler)
Initialize the continuous algebraic riccati equation solver.
Eigen::Ref< const Eigen::MatrixXd > getA () const
Get the matrix A.
Eigen::Ref< const Eigen::VectorXd > getB () const
Get the vector B.
Detailed Description
LinearizedFrictionCone computes the polyhedral approximation of the friction cone.
A point contact remains fixed with respect the environment if the contact force lies in a cone described by
\[ f ^c \cdot n > 0 \quad | f ^t | \le \mu f^c \cdot n \]
where \(f^c \) is the contact force, \(n \) is the vector normal to the contact surface. \(f^t \) is the tangential force to the contact surface and \(\mu \) is the friction parameter. The LinearizedFrictionCone aims to compute the polyhedral approximation of \(| f ^t | \le \mu f^c \cdot n \) by spitting the base of the cone into slices.
Definition at line 33 of file LinearizedFrictionCone.h.
Member Function Documentation
getA()
Eigen::Ref< const Eigen::MatrixXd > LinearizedFrictionCone::getA () const
Get the matrix A.
Returns
the matrix A.
Definition at line 87 of file LinearizedFrictionCone.cpp.
References BipedalLocomotion::log().
getB()
Eigen::Ref< const Eigen::VectorXd > LinearizedFrictionCone::getB () const
Get the vector B.
Returns
the matrix B..
Definition at line 100 of file LinearizedFrictionCone.cpp.
References BipedalLocomotion::log().
initialize()
bool LinearizedFrictionCone::initialize (std::weak_ptr< ParametersHandler::IParametersHandler > handler)
Initialize the continuous algebraic riccati equation solver.
Parameters
handler pointer to the parameter handler.
Note
The following parameters are required:
Parameter Name Type Description
number_of_slices int Number of slices used to split 90 deg.
static_friction_coefficient double Static friction coefficient.
Returns
true in case of success/false otherwise.
Definition at line 15 of file LinearizedFrictionCone.cpp.
References std::vector< T >::back(), std::cos(), std::weak_ptr< T >::lock(), BipedalLocomotion::log(), std::vector< T >::push_back(), and std::sin().
The documentation for this class was generated from the following files:
Math/include/BipedalLocomotion/Math/LinearizedFrictionCone.h
Math/src/LinearizedFrictionCone.cpp