bipedal-locomotion-framework: BipedalLocomotion::IK::QPInverseKinematics Class Reference
BipedalLocomotion::IK::QPInverseKinematics Class Reference
QPInverseKinematics is a concrete class and implements an integration base inverse kinematics.
#include <BipedalLocomotion/IK/QPInverseKinematics.h>
Data Structures
struct Impl
Public Member Functions
QPInverseKinematics ()
Constructor.
~QPInverseKinematics ()
Destructor.
bool addTask (std::shared_ptr< System::LinearTask > task, const std::string &taskName, std::size_t priority, std::optional< Eigen::Ref< const Eigen::VectorXd >> weight={}) override
Add a linear task in the inverse kinematics.
bool finalize (const System::VariablesHandler &handler) override
Finalize the IK.
bool initialize (std::weak_ptr< const ParametersHandler::IParametersHandler > handler) override
Initialize the inverse kinematics algorithm.
std::vector< std::string > getTaskNames () const override
Get a vector containing the name of the tasks.
bool isOutputValid () const override
Return true if the content of get is valid.
bool advance () override
Solve the inverse kinematics.
const IntegrationBasedIKState & getOutput () const override
Get the outcome of the optimization problem.
std::weak_ptr< System::LinearTask > getTask (const std::string &name) const override
Get a specific task.
Public Member Functions inherited from BipedalLocomotion::IK::IntegrationBasedIK
virtual ~IntegrationBasedIK ()=default
Destructor.
Public Member Functions inherited from BipedalLocomotion::System::Source< IntegrationBasedIKState >
bool setInput (const EmptySignal &input) final
Get the object.
Public Member Functions inherited from BipedalLocomotion::System::Advanceable< EmptySignal, IntegrationBasedIKState >
virtual const Output & getOutput () const=0
Get the output of the advanceable.
virtual bool isOutputValid () const=0
Determines the validity of the object retrieved with getOutput()
virtual bool close ()
Close the Advanceable.
Additional Inherited Members
Public Types inherited from BipedalLocomotion::System::Advanceable< EmptySignal, IntegrationBasedIKState >
using Input = EmptySignal
using Output = IntegrationBasedIKState
Detailed Description
QPInverseKinematics is a concrete class and implements an integration base inverse kinematics.
The inverse kinematics is here implemented as Quadratic Programming (QP) problem. The user should set the desired task with the method QPInverseKinematics::addTask. Each task has a given priority. Currently we support only priority equal to 0 or 1. If the task priority is set to 0 the task will be considered as hard task, thus treated as an equality constraint. If the priority is equal to 1 the task will be embedded in the cost function. The class is also able to treat inequality constraints. A possible usage of the IK can be found in "Romualdi et al. A Benchmarking of DCM Based Architectures for Position and Velocity Controlled Walking of Humanoid Robots" https://doi.org/10.1109/HUMANOIDS.2018.8625025
Definition at line 41 of file QPInverseKinematics.h.
Constructor & Destructor Documentation
QPInverseKinematics()
QPInverseKinematics::QPInverseKinematics ()
Constructor.
Definition at line 128 of file QPInverseKinematics.cpp.
~QPInverseKinematics()
QPInverseKinematics::~QPInverseKinematics () default
Destructor.
Member Function Documentation
addTask()
bool QPInverseKinematics::addTask (std::shared_ptr< System::LinearTask > task, const std::string & taskName, std::size_t priority, std::optional< Eigen::Ref< const Eigen::VectorXd >> weight = {}) override virtual
Add a linear task in the inverse kinematics.
Parameters
task pointer to a given linear task
priority Priority associated to the task. The lower the number the higher the priority.
weight weight associated to the task. This parameter is optional. The default value is an object that does not contain any value. So is an invalid weight.
Note
currently we support only task with priority 0 or 1. If the priority is set to 0 the task will be considered as a constraint. In this case the weight is not required.
Warning
The QPInverseKinematics cannot handle inequality tasks (please check Task::Type) with priority equal to 1.
Returns
true if the task has been added to the inverse kinematics.
Implements BipedalLocomotion::IK::IntegrationBasedIK.
Definition at line 135 of file QPInverseKinematics.cpp.
References BipedalLocomotion::log(), std::string::size(), BipedalLocomotion::System::LinearTask::size(), and BipedalLocomotion::System::LinearTask::type().
advance()
bool QPInverseKinematics::advance () override virtual
Solve the inverse kinematics.
Returns
true in case of success and false otherwise.
Implements BipedalLocomotion::System::Advanceable< EmptySignal, IntegrationBasedIKState >.
Definition at line 285 of file QPInverseKinematics.cpp.
References BipedalLocomotion::log().
finalize()
bool QPInverseKinematics::finalize (const System::VariablesHandler & handler) override virtual
Finalize the IK.
Parameters
handler parameter handler.
Note
You should call this method after you add ALL the tasks.
Returns
true in case of success, false otherwise.
Implements BipedalLocomotion::IK::IntegrationBasedIK.
Definition at line 214 of file QPInverseKinematics.cpp.
References BipedalLocomotion::System::VariablesHandler::getNumberOfVariables(), BipedalLocomotion::System::VariablesHandler::getVariable(), and BipedalLocomotion::log().
getOutput()
const IntegrationBasedIKState & QPInverseKinematics::getOutput () const override
Get the outcome of the optimization problem.
Returns
the state of the inverse kinematics.
Definition at line 417 of file QPInverseKinematics.cpp.
getTask()
std::weak_ptr< System::LinearTask > QPInverseKinematics::getTask (const std::string & name) const override virtual
Get a specific task.
Parameters
name name associated to the task.
Returns
a weak ptr associated to an existing task in the IK. If the task does not exist a nullptr is returned.
Implements BipedalLocomotion::IK::IntegrationBasedIK.
Definition at line 422 of file QPInverseKinematics.cpp.
References BipedalLocomotion::log().
getTaskNames()
std::vector< std::string > QPInverseKinematics::getTaskNames () const override virtual
Get a vector containing the name of the tasks.
Returns
an std::vector containing all the names associated to the tasks
Implements BipedalLocomotion::IK::IntegrationBasedIK.
Definition at line 273 of file QPInverseKinematics.cpp.
References std::vector< T >::push_back().
initialize()
bool QPInverseKinematics::initialize (std::weak_ptr< const ParametersHandler::IParametersHandler > handler) override virtual
Initialize the inverse kinematics algorithm.
Parameters
handler pointer to the IParametersHandler interface.g
Note
the following parameters are required by the class
Parameter Name Type Description Mandatory
robot_velocity_variable_name string Name of the variable contained in VariablesHandler describing the generalized robot velocity Yes
verbosity bool Verbosity of the solver. Default value false No
Where the generalized robot velocity is a vector containing the base spatialvelocity (expressed in mixed representation) and the joint velocities.
Returns
True in case of success, false otherwise.
Reimplemented from BipedalLocomotion::System::Advanceable< EmptySignal, IntegrationBasedIKState >.
Definition at line 438 of file QPInverseKinematics.cpp.
References std::weak_ptr< T >::lock(), and BipedalLocomotion::log().
isOutputValid()
bool QPInverseKinematics::isOutputValid () const override
Return true if the content of get is valid.
Definition at line 412 of file QPInverseKinematics.cpp.
The documentation for this class was generated from the following files:
IK/include/BipedalLocomotion/IK/QPInverseKinematics.h
IK/src/QPInverseKinematics.cpp