bipedal-locomotion-framework: BipedalLocomotion::Planners::TimeVaryingDCMPlanner Class Reference
BipedalLocomotion::Planners::TimeVaryingDCMPlanner Class Reference
DCMPlanner defines a trajectory generator for the variable height Divergent component of motion (DCM).
#include <BipedalLocomotion/Planners/TimeVaryingDCMPlanner.h>
Data Structures
struct Impl
Private implementation of the TimeVaryingDCMPlanner class.
Public Member Functions
TimeVaryingDCMPlanner ()
Constructor.
~TimeVaryingDCMPlanner () override
Destructor.
bool initialize (std::weak_ptr< const ParametersHandler::IParametersHandler > handler) override
Initialize the planner.
bool computeTrajectory () final
Compute the DCM trajectory.
bool setContactPhaseList (const Contacts::ContactPhaseList &contactPhaseList) final
Set the contact phase list.
bool setDCMReference (Eigen::Ref< const Eigen::MatrixXd > dcmReference) final
Set the DCM reference.
void setInitialState (const DCMPlannerState &initialState) final
Set the initial state of the planner.
const DCMPlannerState & getOutput () const final
Get the object.
bool isOutputValid () const final
Determines the validity of the object retrieved with get()
bool advance () final
Advance the internal state.
Public Member Functions inherited from BipedalLocomotion::Planners::DCMPlanner
virtual ~DCMPlanner ()=default
Destructor.
Public Member Functions inherited from BipedalLocomotion::System::Source< DCMPlannerState >
bool setInput (const EmptySignal &input) final
Get the object.
Public Member Functions inherited from BipedalLocomotion::System::Advanceable< EmptySignal, DCMPlannerState >
virtual const Output & getOutput () const=0
Get the output of the advanceable.
virtual bool isOutputValid () const=0
Determines the validity of the object retrieved with getOutput()
virtual bool close ()
Close the Advanceable.
Additional Inherited Members
Public Types inherited from BipedalLocomotion::System::Advanceable< EmptySignal, DCMPlannerState >
using Input = EmptySignal
using Output = DCMPlannerState
Protected Attributes inherited from BipedalLocomotion::Planners::DCMPlanner
Contacts::ContactPhaseList m_contactPhaseList
Contact phases.
DCMPlannerState m_initialState
Initial state of the planner.
Detailed Description
DCMPlanner defines a trajectory generator for the variable height Divergent component of motion (DCM).
Definition at line 24 of file TimeVaryingDCMPlanner.h.
Constructor & Destructor Documentation
TimeVaryingDCMPlanner()
TimeVaryingDCMPlanner::TimeVaryingDCMPlanner ()
Constructor.
Definition at line 583 of file TimeVaryingDCMPlanner.cpp.
~TimeVaryingDCMPlanner()
TimeVaryingDCMPlanner::~TimeVaryingDCMPlanner () override default
Destructor.
Member Function Documentation
advance()
bool TimeVaryingDCMPlanner::advance () final virtual
Advance the internal state.
This may change the value retrievable from get().
Returns
True if the advance is successfull.
Implements BipedalLocomotion::System::Advanceable< EmptySignal, DCMPlannerState >.
Definition at line 845 of file TimeVaryingDCMPlanner.cpp.
References isOutputValid(), BipedalLocomotion::log(), and std::min().
computeTrajectory()
bool TimeVaryingDCMPlanner::computeTrajectory () final virtual
Compute the DCM trajectory.
Returns
true in case of success, false otherwise.
Implements BipedalLocomotion::Planners::DCMPlanner.
Definition at line 710 of file TimeVaryingDCMPlanner.cpp.
References BipedalLocomotion::Contacts::ContactPhaseList::cbegin(), std::ceil(), BipedalLocomotion::Contacts::ContactPhaseList::lastPhase(), BipedalLocomotion::log(), BipedalLocomotion::Planners::DCMPlanner::m_contactPhaseList, BipedalLocomotion::Planners::DCMPlanner::m_initialState, and std::exception::what().
getOutput()
const DCMPlannerState & TimeVaryingDCMPlanner::getOutput () const final
Get the object.
Returns
a const reference of the requested object.
Definition at line 833 of file TimeVaryingDCMPlanner.cpp.
initialize()
bool TimeVaryingDCMPlanner::initialize (std::weak_ptr< const ParametersHandler::IParametersHandler > handler) override virtual
Initialize the planner.
Parameters
handler pointer to the parameter handler.
Note
the following parameters are required by the class
Parameter Name Type Description Mandatory
linear_solver string Linear solver used by ipopt, the default value is mumps. Please check https://coin-or.github.io/Ipopt/#PREREQUISITES for the available solvers No
planner_sampling_time double Sampling time of the planner Yes
number_of_foot_corners int Number of the corner of the polygon used to describe the foot. E.g. 4 Yes
foot_corner_<i> Vector3d A 3d vector describing the position of the corner w.r.t. frame associated to the foot. i = 0:number_of_foot_corners. Yes
omega_dot_weight double Weight associated to the \(\dot{omega}\) Yes
dcm_tracking_weight double Weight associated to the DCM tracking Yes
omega_dot_rate_of_change_weight double Weight associated to the rate of change of \(\dot{omega}\) Yes
vrp_rate_of_change_weight double Weight associated to the rate of change of the VRP Yes
dcm_rate_of_change_weight double Weight associated to the rate of change of the DCM Yes
use_external_dcm_reference bool Set this option to true if you want provide an external DCM reference with TimeVaryingDCMPlanner::setDCMReference(). (Default value False) No
gravity double Value of the gravity acceleration. It should be a positive number (Default value BipedalLocomotion::Math::StandardAccelerationOfGravitation) No
Returns
true in case of success/false otherwise.
Reimplemented from BipedalLocomotion::System::Advanceable< EmptySignal, DCMPlannerState >.
Definition at line 592 of file TimeVaryingDCMPlanner.cpp.
References std::weak_ptr< T >::lock(), BipedalLocomotion::log(), and std::to_string().
isOutputValid()
bool TimeVaryingDCMPlanner::isOutputValid () const final
Determines the validity of the object retrieved with get()
Returns
True if the object is valid, false otherwise.
Definition at line 839 of file TimeVaryingDCMPlanner.cpp.
Referenced by advance().
setContactPhaseList()
bool TimeVaryingDCMPlanner::setContactPhaseList (const Contacts::ContactPhaseList & contactPhaseList) final virtual
Set the contact phase list.
Note
the contactPhaseList pointer should point to an already initialized ContactPhaseList. Please be sure that the memory pointed is reachable for the entire life time of the DCMPlanner class.
Parameters
contactPhaseList pointer containing the list of the contact phases
Returns
true in case of success, false otherwise.
Reimplemented from BipedalLocomotion::Planners::DCMPlanner.
Definition at line 775 of file TimeVaryingDCMPlanner.cpp.
References BipedalLocomotion::log(), and BipedalLocomotion::Planners::DCMPlanner::m_contactPhaseList.
setDCMReference()
bool TimeVaryingDCMPlanner::setDCMReference (Eigen::Ref< const Eigen::MatrixXd > dcmReference) final virtual
Set the DCM reference.
This value will be used as regularization term from the planner.
Parameters
dcmReference matrix containing the DCM trajectory. dcmReference must be a 3 x n matrix where the rows are the x y and z coordinates of the DCM and the columns contain the trajectory of the DCM.
Note
The number of columns should be coherent with the contactPhaseList. In details the number of samples \(s\) is equal to
\[ s = \ceil*{\frac{t_f - t_i}{dT}} \]
where \(dT\) is the sampling time of the planner, \(t_f\) and \(t_i\) are the end time of the last contact and the initial time of the first contact.
Returns
true in case of success, false otherwise.
Reimplemented from BipedalLocomotion::Planners::DCMPlanner.
Definition at line 794 of file TimeVaryingDCMPlanner.cpp.
References BipedalLocomotion::log().
setInitialState()
void TimeVaryingDCMPlanner::setInitialState (const DCMPlannerState & initialState) final virtual
Set the initial state of the planner.
Parameters
initialState the initial state of the planner
Reimplemented from BipedalLocomotion::Planners::DCMPlanner.
Definition at line 823 of file TimeVaryingDCMPlanner.cpp.
References BipedalLocomotion::Planners::DCMPlanner::m_initialState.
The documentation for this class was generated from the following files:
Planners/include/BipedalLocomotion/Planners/TimeVaryingDCMPlanner.h
Planners/src/TimeVaryingDCMPlanner.cpp