bipedal-locomotion-framework: BipedalLocomotion::Estimators::LeggedOdometry::Impl Class Reference
BipedalLocomotion::Estimators::LeggedOdometry::Impl Class Reference
Public Member Functions
bool changeFixedFrame (const iDynTree::FrameIndex &newIdx, std::shared_ptr< iDynTree::KinDynComputations > kinDyn)
Change fixed frame for the legged odometry.
bool updateInternalState (FloatingBaseEstimators::Measurements &meas, FloatingBaseEstimator::ModelComputations &modelComp, FloatingBaseEstimators::InternalState &state, FloatingBaseEstimators::Output &out)
Update internal state of the legged odometry block.
void updateInternalContactStates (FloatingBaseEstimators::Measurements &meas, FloatingBaseEstimator::ModelComputations &modelComp, std::map< int, EstimatedContact > &contacts)
Update internal contact states.
iDynTree::FrameIndex getLatestSwitchedContact (const std::map< int, EstimatedContact > &contacts)
iDynTree::FrameIndex getLastActiveContact (const std::map< int, EstimatedContact > &contacts, const int &activeIndex)
bool computeBaseVelocityUsingFixedFrameConstraint (FloatingBaseEstimators::Measurements &meas, FloatingBaseEstimator::ModelComputations &modelComp, FloatingBaseEstimators::Output &out)
Single fixed frame.
bool computeBaseVelocityUsingAllFixedFrameConstraint (const FloatingBaseEstimators::InternalState &state, FloatingBaseEstimators::Measurements &meas, FloatingBaseEstimator::ModelComputations &modelComp, FloatingBaseEstimators::Output &out)
All fixed frame least square solution with joint velocities in the solution vector.
bool computeBaseVelocityUsingAllFixedFrameAverage (const FloatingBaseEstimators::InternalState &state, FloatingBaseEstimators::Measurements &meas, FloatingBaseEstimator::ModelComputations &modelComp, FloatingBaseEstimators::Output &out)
All fixed frames average.
bool computeBaseVelocityUsingAllFixedFrames (const FloatingBaseEstimators::InternalState &state, FloatingBaseEstimators::Measurements &meas, FloatingBaseEstimator::ModelComputations &modelComp, FloatingBaseEstimators::Output &out)
All fixed frame least square solution without joint velocities in the solution vector.
void resetInternal (FloatingBaseEstimator::ModelComputations &modelComp, const FloatingBaseEstimators::Measurements &meas)
Reset internal state of the legged odometry block.
Data Fields
std::string m_initialFixedFrame
Fixed frame at initialization assumed to be in rigid contact with the environment.
std::string m_initialRefFrameForWorld
Reference frame for the world at initialization.
iDynTree::FrameIndex m_initialFixedFrameIdx {iDynTree::FRAME_INVALID_INDEX}
Index of fixed frame at initialization.
iDynTree::FrameIndex m_initialRefFrameForWorldIdx {iDynTree::FRAME_INVALID_INDEX}
Index of world reference frame at initialization.
manif::SE3d m_refFrame_H_world
pose of world wrt reference frame at initialization
bool m_odometryInitialized {false}
flag to check if odometry was initialized
iDynTree::FrameIndex m_prevFixedFrameIdx {iDynTree::FRAME_INVALID_INDEX}
iDynTree::FrameIndex m_currentFixedFrameIdx {iDynTree::FRAME_INVALID_INDEX}
manif::SE3d m_world_H_fixedFrame
Pose of fixed frame wrt world.
LOSwitching switching {LOSwitching::latest}
contact switching pattern
LOVelComputation velComp {LOVelComputation::multiFrameLeastSquare}
base velocity estimation method
Eigen::MatrixXd m_contactJacobian
mixed velocity jacobian of fixed frame with respect to floating base
Eigen::MatrixXd m_contactJacobianBase
base sub-block of mixed velocity jacobian of fixed frame with respect to floating base
Eigen::MatrixXd m_contactJacobianShape
shape sub-block of mixed velocity jacobian of fixed frame with respect to floating base
Eigen::VectorXd m_vBase
mixed velocity representation of base link
const int m_spatialDim {6}
const int m_baseOffset {0}
offset in contact Jacobian for the base sub-block
const int m_shapeOffset {6}
offset in contact Jacobian for the shape sub-block
double wLin {1.0}
double wAng {0.5}
double wJVel {10.0}
double reg {1e-6}
Eigen::VectorXd m_sDotFilt
Detailed Description
Definition at line 39 of file LeggedOdometry.cpp.
Member Function Documentation
changeFixedFrame()
bool BipedalLocomotion::Estimators::LeggedOdometry::Impl::changeFixedFrame (const iDynTree::FrameIndex & newIdx, std::shared_ptr< iDynTree::KinDynComputations > kinDyn)
Change fixed frame for the legged odometry.
Definition at line 890 of file LeggedOdometry.cpp.
References std::endl(), and BipedalLocomotion::Conversions::toManifPose().
computeBaseVelocityUsingAllFixedFrameAverage()
bool BipedalLocomotion::Estimators::LeggedOdometry::Impl::computeBaseVelocityUsingAllFixedFrameAverage (const FloatingBaseEstimators::InternalState & state, FloatingBaseEstimators::Measurements & meas, FloatingBaseEstimator::ModelComputations & modelComp, FloatingBaseEstimators::Output & out)
All fixed frames average.
Definition at line 653 of file LeggedOdometry.cpp.
References BipedalLocomotion::Estimators::FloatingBaseEstimators::Output::baseTwist, BipedalLocomotion::Estimators::FloatingBaseEstimators::Measurements::encodersSpeed, std::endl(), and BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::supportFrameData.
computeBaseVelocityUsingAllFixedFrameConstraint()
bool BipedalLocomotion::Estimators::LeggedOdometry::Impl::computeBaseVelocityUsingAllFixedFrameConstraint (const FloatingBaseEstimators::InternalState & state, FloatingBaseEstimators::Measurements & meas, FloatingBaseEstimator::ModelComputations & modelComp, FloatingBaseEstimators::Output & out)
All fixed frame least square solution with joint velocities in the solution vector.
Definition at line 573 of file LeggedOdometry.cpp.
References BipedalLocomotion::Estimators::FloatingBaseEstimators::Output::baseTwist, BipedalLocomotion::Estimators::FloatingBaseEstimators::Measurements::encodersSpeed, std::endl(), and BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::supportFrameData.
computeBaseVelocityUsingAllFixedFrames()
bool BipedalLocomotion::Estimators::LeggedOdometry::Impl::computeBaseVelocityUsingAllFixedFrames (const FloatingBaseEstimators::InternalState & state, FloatingBaseEstimators::Measurements & meas, FloatingBaseEstimator::ModelComputations & modelComp, FloatingBaseEstimators::Output & out)
All fixed frame least square solution without joint velocities in the solution vector.
Definition at line 699 of file LeggedOdometry.cpp.
References BipedalLocomotion::Estimators::FloatingBaseEstimators::Output::baseTwist, BipedalLocomotion::Estimators::FloatingBaseEstimators::Measurements::encodersSpeed, std::endl(), and BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::supportFrameData.
computeBaseVelocityUsingFixedFrameConstraint()
bool BipedalLocomotion::Estimators::LeggedOdometry::Impl::computeBaseVelocityUsingFixedFrameConstraint (FloatingBaseEstimators::Measurements & meas, FloatingBaseEstimator::ModelComputations & modelComp, FloatingBaseEstimators::Output & out)
Single fixed frame.
Definition at line 548 of file LeggedOdometry.cpp.
References BipedalLocomotion::Estimators::FloatingBaseEstimators::Output::baseTwist, BipedalLocomotion::Estimators::FloatingBaseEstimators::Measurements::encodersSpeed, and std::endl().
resetInternal()
void BipedalLocomotion::Estimators::LeggedOdometry::Impl::resetInternal (FloatingBaseEstimator::ModelComputations & modelComp, const FloatingBaseEstimators::Measurements & meas)
Reset internal state of the legged odometry block.
Definition at line 447 of file LeggedOdometry.cpp.
References BipedalLocomotion::Conversions::toManifPose().
updateInternalContactStates()
void BipedalLocomotion::Estimators::LeggedOdometry::Impl::updateInternalContactStates (FloatingBaseEstimators::Measurements & meas, FloatingBaseEstimator::ModelComputations & modelComp, std::map< int, EstimatedContact > & contacts)
Update internal contact states.
Definition at line 310 of file LeggedOdometry.cpp.
References std::map< K, T >::at(), std::map< K, T >::clear(), std::map< K, T >::end(), std::map< K, T >::find(), BipedalLocomotion::Contacts::ContactBase::index, BipedalLocomotion::Contacts::EstimatedContact::lastUpdateTime, BipedalLocomotion::Contacts::ContactBase::name, and BipedalLocomotion::Estimators::FloatingBaseEstimators::Measurements::stampedContactsStatus.
updateInternalState()
bool BipedalLocomotion::Estimators::LeggedOdometry::Impl::updateInternalState (FloatingBaseEstimators::Measurements & meas, FloatingBaseEstimator::ModelComputations & modelComp, FloatingBaseEstimators::InternalState & state, FloatingBaseEstimators::Output & out)
Update internal state of the legged odometry block.
Definition at line 476 of file LeggedOdometry.cpp.
References std::endl(), BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::imuOrientation, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::imuPosition, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::lContactFrameOrientation, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::lContactFramePosition, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::rContactFrameOrientation, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::rContactFramePosition, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::supportFrameData, and BipedalLocomotion::Conversions::toManifPose().
Field Documentation
m_baseOffset
const int BipedalLocomotion::Estimators::LeggedOdometry::Impl::m_baseOffset {0}
offset in contact Jacobian for the base sub-block
Definition at line 119 of file LeggedOdometry.cpp.
m_contactJacobian
Eigen::MatrixXd BipedalLocomotion::Estimators::LeggedOdometry::Impl::m_contactJacobian
mixed velocity jacobian of fixed frame with respect to floating base
Definition at line 114 of file LeggedOdometry.cpp.
m_contactJacobianBase
Eigen::MatrixXd BipedalLocomotion::Estimators::LeggedOdometry::Impl::m_contactJacobianBase
base sub-block of mixed velocity jacobian of fixed frame with respect to floating base
Definition at line 115 of file LeggedOdometry.cpp.
m_contactJacobianShape
Eigen::MatrixXd BipedalLocomotion::Estimators::LeggedOdometry::Impl::m_contactJacobianShape
shape sub-block of mixed velocity jacobian of fixed frame with respect to floating base
Definition at line 116 of file LeggedOdometry.cpp.
m_initialFixedFrame
std::string BipedalLocomotion::Estimators::LeggedOdometry::Impl::m_initialFixedFrame
Fixed frame at initialization assumed to be in rigid contact with the environment.
Definition at line 99 of file LeggedOdometry.cpp.
m_initialFixedFrameIdx
iDynTree::FrameIndex BipedalLocomotion::Estimators::LeggedOdometry::Impl::m_initialFixedFrameIdx {iDynTree::FRAME_INVALID_INDEX}
Index of fixed frame at initialization.
Definition at line 101 of file LeggedOdometry.cpp.
m_initialRefFrameForWorld
std::string BipedalLocomotion::Estimators::LeggedOdometry::Impl::m_initialRefFrameForWorld
Reference frame for the world at initialization.
Definition at line 100 of file LeggedOdometry.cpp.
m_initialRefFrameForWorldIdx
iDynTree::FrameIndex BipedalLocomotion::Estimators::LeggedOdometry::Impl::m_initialRefFrameForWorldIdx {iDynTree::FRAME_INVALID_INDEX}
Index of world reference frame at initialization.
Definition at line 102 of file LeggedOdometry.cpp.
m_odometryInitialized
bool BipedalLocomotion::Estimators::LeggedOdometry::Impl::m_odometryInitialized {false}
flag to check if odometry was initialized
Definition at line 105 of file LeggedOdometry.cpp.
m_refFrame_H_world
manif::SE3d BipedalLocomotion::Estimators::LeggedOdometry::Impl::m_refFrame_H_world
pose of world wrt reference frame at initialization
Definition at line 103 of file LeggedOdometry.cpp.
m_shapeOffset
const int BipedalLocomotion::Estimators::LeggedOdometry::Impl::m_shapeOffset {6}
offset in contact Jacobian for the shape sub-block
Definition at line 120 of file LeggedOdometry.cpp.
m_vBase
Eigen::VectorXd BipedalLocomotion::Estimators::LeggedOdometry::Impl::m_vBase
mixed velocity representation of base link
Definition at line 117 of file LeggedOdometry.cpp.
m_world_H_fixedFrame
manif::SE3d BipedalLocomotion::Estimators::LeggedOdometry::Impl::m_world_H_fixedFrame
Pose of fixed frame wrt world.
Definition at line 110 of file LeggedOdometry.cpp.
switching
LOSwitching BipedalLocomotion::Estimators::LeggedOdometry::Impl::switching {LOSwitching::latest}
contact switching pattern
Definition at line 111 of file LeggedOdometry.cpp.
velComp
LOVelComputation BipedalLocomotion::Estimators::LeggedOdometry::Impl::velComp {LOVelComputation::multiFrameLeastSquare}
base velocity estimation method
Definition at line 112 of file LeggedOdometry.cpp.
The documentation for this class was generated from the following file:
Estimators/src/LeggedOdometry.cpp