bipedal-locomotion-framework: Conversions/include/BipedalLocomotion/Conversions/CommonConversions.h File Reference
CommonConversions.h File Reference
#include <Eigen/Dense>
Namespaces
BipedalLocomotion
Functions
template<class Scalar >
Eigen::Matrix< Scalar, 4, 4 > BipedalLocomotion::Conversions::toEigenPose (const Eigen::Matrix< Scalar, 3, 3 > &rotation, const Eigen::Matrix< Scalar, 3, 1 > &translation)
Construct homogeneous transformation matrix from rotation matrix and translation vector.
Detailed Description
Authors
Prashanth Ramadoss
Copyright
2020 Istituto Italiano di Tecnologia (IIT). This software may be modified and distributed under the terms of the GNU Lesser General Public License v2.1 or any later version.
Definition in file CommonConversions.h.
Function Documentation
toEigenPose()
template<class Scalar > Eigen::Matrix<Scalar, 4, 4> BipedalLocomotion::Conversions::toEigenPose (const Eigen::Matrix< Scalar, 3, 3 > & rotation, const Eigen::Matrix< Scalar, 3, 1 > & translation)
Construct homogeneous transformation matrix from rotation matrix and translation vector.
Parameters
rotation reference of rotation matrix
translation reference of translation vector
Returns
homogeneous transform as a Eigen::Matrix4d object
Definition at line 25 of file CommonConversions.h.
References BipedalLocomotion::Conversions::toEigenPose().
Referenced by BipedalLocomotion::Perception::ArucoDetector::advance(), and BipedalLocomotion::Conversions::toEigenPose().