bipedal-locomotion-framework: Conversions/include/BipedalLocomotion/Conversions/ManifConversions.h File Reference
ManifConversions.h File Reference
#include <iDynTree/Core/Transform.h>
#include <iDynTree/Core/EigenHelpers.h>
#include <manif/manif.h>
Namespaces
BipedalLocomotion
Functions
template<class Scalar >
manif::SE3< Scalar > BipedalLocomotion::Conversions::toManifPose (const Eigen::Matrix< Scalar, 3, 3 > &rotation, const Eigen::Matrix< Scalar, 3, 1 > &translation)
Convert rotation matrix and translation vector to manif SE3 object.
manif::SE3d BipedalLocomotion::Conversions::toManifPose (Eigen::Ref< const Eigen::Matrix3d > rotation, Eigen::Ref< const Eigen::Vector3d > translation)
Convert rotation matrix and translation vector to manif SE3d object.
manif::SE3d BipedalLocomotion::Conversions::toManifPose (const iDynTree::Transform &H)
Convert iDynTree transform object to manif SE3d object.
template<class Scalar >
manif::SO3< Scalar > BipedalLocomotion::Conversions::toManifRot (const Eigen::Matrix< Scalar, 3, 3 > &rotation)
Convert rotation matrix to manif SO3 object.
manif::SO3d BipedalLocomotion::Conversions::toManifRot (Eigen::Ref< const Eigen::Matrix3d > rotation)
Convert rotation matrix to manif SO3d object.
manif::SO3d BipedalLocomotion::Conversions::toManifRot (const iDynTree::Rotation &R)
Convert iDynTree rotation object to manif SE3d object.
Detailed Description
Authors
Prashanth Ramadoss
Copyright
2020 Istituto Italiano di Tecnologia (IIT). This software may be modified and distributed under the terms of the GNU Lesser General Public License v2.1 or any later version.
Definition in file ManifConversions.h.
Function Documentation
toManifPose() [1/3]
template<class Scalar > manif::SE3<Scalar> BipedalLocomotion::Conversions::toManifPose (const Eigen::Matrix< Scalar, 3, 3 > & rotation, const Eigen::Matrix< Scalar, 3, 1 > & translation)
Convert rotation matrix and translation vector to manif SE3 object.
Parameters
rotation reference to 3x3 Eigen matrix
translation reference of 3x1 Eigen matrix
Returns
pose as manif SE3 object
Definition at line 28 of file ManifConversions.h.
References BipedalLocomotion::Conversions::toManifPose().
Referenced by BipedalLocomotion::Estimators::LeggedOdometry::Impl::changeFixedFrame(), BipedalLocomotion::Estimators::LeggedOdometry::Impl::resetInternal(), BipedalLocomotion::Conversions::toManifPose(), and BipedalLocomotion::Estimators::LeggedOdometry::Impl::updateInternalState().
toManifPose() [2/3]
manif::SE3d BipedalLocomotion::Conversions::toManifPose (const iDynTree::Transform & H) inline
Convert iDynTree transform object to manif SE3d object.
Parameters
H reference to iDynTree Tranform object
Returns
pose as manif SE3d object
Definition at line 57 of file ManifConversions.h.
References BipedalLocomotion::Conversions::toManifPose().
toManifPose() [3/3]
manif::SE3d BipedalLocomotion::Conversions::toManifPose (Eigen::Ref< const Eigen::Matrix3d > rotation, Eigen::Ref< const Eigen::Vector3d > translation) inline
Convert rotation matrix and translation vector to manif SE3d object.
Parameters
rotation Eigen ref of 3x3 rotation matrix
translation Eigen ref of 3x1 translation vector
Returns
pose as manif SE3d object
Definition at line 43 of file ManifConversions.h.
References BipedalLocomotion::Conversions::toManifPose().
toManifRot() [1/3]
template<class Scalar > manif::SO3<Scalar> BipedalLocomotion::Conversions::toManifRot (const Eigen::Matrix< Scalar, 3, 3 > & rotation)
Convert rotation matrix to manif SO3 object.
Parameters
rotation reference to 3x3 Eigen matrix
Returns
pose as manif SO3 object
Definition at line 70 of file ManifConversions.h.
References BipedalLocomotion::Conversions::toManifRot().
Referenced by BipedalLocomotion::Conversions::toManifRot(), BipedalLocomotion::IK::SO3Task::update(), and BipedalLocomotion::IK::SE3Task::update().
toManifRot() [2/3]
manif::SO3d BipedalLocomotion::Conversions::toManifRot (const iDynTree::Rotation & R) inline
Convert iDynTree rotation object to manif SE3d object.
Parameters
R reference to iDynTree rotation object
Returns
pose as manif SO3d object
Definition at line 97 of file ManifConversions.h.
References BipedalLocomotion::Conversions::toManifRot().
toManifRot() [3/3]
manif::SO3d BipedalLocomotion::Conversions::toManifRot (Eigen::Ref< const Eigen::Matrix3d > rotation) inline
Convert rotation matrix to manif SO3d object.
Parameters
rotation Eigen ref of 3x3 rotation matrix
translation Eigen ref of 3x1 translation vector
Returns
pose as manif SO3d object
Definition at line 84 of file ManifConversions.h.
References BipedalLocomotion::Conversions::toManifRot().