bipedal-locomotion-framework: Conversions/include/BipedalLocomotion/Conversions/matioCppConversions.h File Reference
matioCppConversions.h File Reference
#include <Eigen/Core>
#include <iDynTree/Core/MatrixDynSize.h>
#include <iDynTree/Core/EigenHelpers.h>
#include <iDynTree/Core/MatrixFixSize.h>
#include <matioCpp/matioCpp.h>
#include <BipedalLocomotion/GenericContainer/Vector.h>
Namespaces
BipedalLocomotion
Functions
template<typename type >
Eigen::Map< Eigen::Matrix< type, Eigen::Dynamic, Eigen::Dynamic > > BipedalLocomotion::Conversions::toEigen (matioCpp::MultiDimensionalArray< type > &input)
Conversion from a matioCpp::MultiDimensionalArray to an Eigen matrix.
template<typename type >
const Eigen::Map< Eigen::Matrix< type, Eigen::Dynamic, Eigen::Dynamic > > BipedalLocomotion::Conversions::toEigen (const matioCpp::MultiDimensionalArray< type > &input)
Conversion from a const matioCpp::MultiDimensionalArray to an Eigen matrix.
template<typename type >
Eigen::Map< Eigen::Matrix< type, Eigen::Dynamic, 1 > > BipedalLocomotion::Conversions::toEigen (matioCpp::Vector< type > &input)
Conversion from a matioCpp::Vector to an Eigen vector.
template<typename type >
const Eigen::Map< Eigen::Matrix< type, Eigen::Dynamic, 1 > > BipedalLocomotion::Conversions::toEigen (const matioCpp::Vector< type > &input)
Conversion from a const matioCpp::Vector to an Eigen vector.
template<typename EigenDerived , typename = std::enable_if_t<Eigen::MatrixBase<EigenDerived>::RowsAtCompileTime != 1 && Eigen::MatrixBase<EigenDerived>::ColsAtCompileTime != 1>>
matioCpp::MultiDimensionalArray< typename EigenDerived::Scalar > BipedalLocomotion::Conversions::tomatioCpp (const Eigen::MatrixBase< EigenDerived > &input, const std::string &name)
Conversion from an Eigen matrix to a matioCpp::MultiDimensionalArray.
matioCpp::MultiDimensionalArray< double > BipedalLocomotion::Conversions::tomatioCpp (const iDynTree::MatrixDynSize &input, const std::string &name)
Conversion from an iDynTree::MatrixDynSize to a matioCpp::MultiDimensionalArray.
template<unsigned int nRows, unsigned int nCols>
matioCpp::MultiDimensionalArray< double > BipedalLocomotion::Conversions::tomatioCpp (const iDynTree::MatrixFixSize< nRows, nCols > &input, const std::string &name)
Conversion from an iDynTree::MatrixFixSize to a matioCpp::MultiDimensionalArray.
template<class Vector , typename = typename std::enable_if_t<BipedalLocomotion::GenericContainer::is_vector_constructible<Vector>::value && !std::is_same_v<Vector, std::string>>>
matioCpp::Vector< typename std::remove_cv_t< typename BipedalLocomotion::container_data< Vector >::type > > BipedalLocomotion::Conversions::tomatioCpp (const Vector &input, const std::string &name)
Conversion from a generic Vector to a matioCpp::Vector.
matioCpp::String BipedalLocomotion::Conversions::tomatioCpp (const std::string &input, const std::string &name)
Conversion from a std::string to a matioCpp::String.
matioCpp::Vector< matioCpp::Logical > BipedalLocomotion::Conversions::tomatioCpp (const std::vector< bool > &input, const std::string &name)
Conversion from a boolean vector to a matioCpp::Vector<matioCpp::Logical>
template<typename type , typename = std::enable_if_t<std::is_fundamental_v<type> && !std::is_same_v<type, bool>>>
matioCpp::Element< type > BipedalLocomotion::Conversions::tomatioCpp (const type &input, const std::string &name)
Conversion from a fundamental type to the corresponding matioCpp::Element.
matioCpp::Element< matioCpp::Logical > BipedalLocomotion::Conversions::tomatioCpp (bool input, const std::string &name)
Conversion from a boolean to a matioCpp::Element<matioCpp::Logical>
matioCpp::CellArray BipedalLocomotion::Conversions::tomatioCpp (const std::vector< std::string > &input, const std::string &name)
Conversion from a vector of strings to a matioCpp::CellArray containing the input strings.
template<class iterator , typename = typename std::enable_if_t<is_pair_iterator_string<iterator>::value>>
matioCpp::Struct BipedalLocomotion::Conversions::tomatioCppStruct (iterator begin, iterator end, const std::string &name)
Create a matioCpp::Struct starting from the begin and end iterators of a map-like container The dereferenced value of the iterator has to be a pair (like with std::maps and std::unordered_map) with the key being a string.
template<class iterator >
matioCpp::CellArray BipedalLocomotion::Conversions::toMatioCppCellArray (const iterator &begin, const iterator &end, const std::string &name)
Create a matioCpp::CellArray starting from the begin and end iterators of a container.
Detailed Description
Authors
Stefano Dafarra
Copyright
2020 Istituto Italiano di Tecnologia (IIT). This software may be modified and distributed under the terms of the GNU Lesser General Public License v2.1 or any later version.
Definition in file matioCppConversions.h.
Function Documentation
toEigen() [1/4]
template<typename type > const Eigen::Map<Eigen::Matrix<type, Eigen::Dynamic, Eigen::Dynamic> > BipedalLocomotion::Conversions::toEigen (const matioCpp::MultiDimensionalArray< type > & input)
Conversion from a const matioCpp::MultiDimensionalArray to an Eigen matrix.
Parameters
input The matioCpp::MultiDimensionalArray
Returns
A const map from the internal data of the MultiDimensionalArray
Definition at line 40 of file matioCppConversions.h.
References BipedalLocomotion::Conversions::toEigen().
toEigen() [2/4]
template<typename type > const Eigen::Map<Eigen::Matrix<type, Eigen::Dynamic, 1> > BipedalLocomotion::Conversions::toEigen (const matioCpp::Vector< type > & input)
Conversion from a const matioCpp::Vector to an Eigen vector.
Parameters
input The matioCpp::Vector
Returns
A const map from the internal data of the Vector
Definition at line 65 of file matioCppConversions.h.
References BipedalLocomotion::Conversions::toEigen().
toEigen() [3/4]
template<typename type > Eigen::Map<Eigen::Matrix<type, Eigen::Dynamic, Eigen::Dynamic> > BipedalLocomotion::Conversions::toEigen (matioCpp::MultiDimensionalArray< type > & input)
Conversion from a matioCpp::MultiDimensionalArray to an Eigen matrix.
Parameters
input The matioCpp::MultiDimensionalArray
Returns
A map from the internal data of the MultiDimensionalArray
Definition at line 27 of file matioCppConversions.h.
References BipedalLocomotion::Conversions::toEigen().
Referenced by BipedalLocomotion::Conversions::toEigen(), BipedalLocomotion::Conversions::tomatioCpp(), BipedalLocomotion::IK::CoMTask::update(), and BipedalLocomotion::IK::SE3Task::update().
toEigen() [4/4]
template<typename type > Eigen::Map<Eigen::Matrix<type, Eigen::Dynamic, 1> > BipedalLocomotion::Conversions::toEigen (matioCpp::Vector< type > & input)
Conversion from a matioCpp::Vector to an Eigen vector.
Parameters
input The matioCpp::Vector
Returns
A map from the internal data of the Vector
Definition at line 53 of file matioCppConversions.h.
References BipedalLocomotion::Conversions::toEigen().
tomatioCpp() [1/9]
matioCpp::Element<matioCpp::Logical> BipedalLocomotion::Conversions::tomatioCpp (bool input, const std::string & name) inline
Conversion from a boolean to a matioCpp::Element<matioCpp::Logical>
Parameters
input The input element.
name The name of the resulting matioCpp variable.
Returns
A matioCpp::Element<matioCpp::Logical> whose value is equal to the input.
Definition at line 166 of file matioCppConversions.h.
References BipedalLocomotion::Conversions::tomatioCpp().
tomatioCpp() [2/9]
template<typename EigenDerived , typename = std::enable_if_t<Eigen::MatrixBase<EigenDerived>::RowsAtCompileTime != 1 && Eigen::MatrixBase<EigenDerived>::ColsAtCompileTime != 1>> matioCpp::MultiDimensionalArray<typename EigenDerived::Scalar> BipedalLocomotion::Conversions::tomatioCpp (const Eigen::MatrixBase< EigenDerived > & input, const std::string & name)
Conversion from an Eigen matrix to a matioCpp::MultiDimensionalArray.
Parameters
input The input matrix.
name The name of the resulting matioCpp variable.
Returns
A matioCpp::MultiDimensionalArray containing a copy of the input data
Definition at line 79 of file matioCppConversions.h.
References BipedalLocomotion::Conversions::toEigen(), and BipedalLocomotion::Conversions::tomatioCpp().
Referenced by BipedalLocomotion::Conversions::tomatioCpp(), BipedalLocomotion::Conversions::toMatioCppCellArray(), and BipedalLocomotion::Conversions::tomatioCppStruct().
tomatioCpp() [3/9]
matioCpp::MultiDimensionalArray<double> BipedalLocomotion::Conversions::tomatioCpp (const iDynTree::MatrixDynSize & input, const std::string & name) inline
Conversion from an iDynTree::MatrixDynSize to a matioCpp::MultiDimensionalArray.
Parameters
input The input matrix.
name The name of the resulting matioCpp variable.
Returns
A matioCpp::MultiDimensionalArray containing a copy of the input data
Definition at line 92 of file matioCppConversions.h.
References BipedalLocomotion::Conversions::tomatioCpp().
tomatioCpp() [4/9]
template<unsigned int nRows, unsigned int nCols> matioCpp::MultiDimensionalArray<double> BipedalLocomotion::Conversions::tomatioCpp (const iDynTree::MatrixFixSize< nRows, nCols > & input, const std::string & name)
Conversion from an iDynTree::MatrixFixSize to a matioCpp::MultiDimensionalArray.
Parameters
input The input matrix.
name The name of the resulting matioCpp variable.
Returns
A matioCpp::MultiDimensionalArray containing a copy of the input data
Definition at line 105 of file matioCppConversions.h.
References BipedalLocomotion::Conversions::tomatioCpp().
tomatioCpp() [5/9]
matioCpp::String BipedalLocomotion::Conversions::tomatioCpp (const std::string & input, const std::string & name) inline
Conversion from a std::string to a matioCpp::String.
Parameters
input The input string.
name The name of the resulting matioCpp variable.
Returns
A matioCpp::String containing a copy of the input data
Definition at line 132 of file matioCppConversions.h.
References BipedalLocomotion::Conversions::tomatioCpp().
tomatioCpp() [6/9]
matioCpp::Vector<matioCpp::Logical> BipedalLocomotion::Conversions::tomatioCpp (const std::vector< bool > & input, const std::string & name) inline
Conversion from a boolean vector to a matioCpp::Vector<matioCpp::Logical>
Parameters
input The input vector.
name The name of the resulting matioCpp variable.
Returns
A matioCpp::Vector<matioCpp::Logical> containing a copy of the input data
Definition at line 143 of file matioCppConversions.h.
References BipedalLocomotion::Conversions::tomatioCpp().
tomatioCpp() [7/9]
matioCpp::CellArray BipedalLocomotion::Conversions::tomatioCpp (const std::vector< std::string > & input, const std::string & name) inline
Conversion from a vector of strings to a matioCpp::CellArray containing the input strings.
Parameters
input The input vector of strings.
name The name of the resulting matioCpp variable.
Returns
A matioCpp::CellArray of dimensions nx1 (with n the number of strings)
Definition at line 177 of file matioCppConversions.h.
References std::vector< T >::size(), and BipedalLocomotion::Conversions::tomatioCpp().
tomatioCpp() [8/9]
template<typename type , typename = std::enable_if_t<std::is_fundamental_v<type> && !std::is_same_v<type, bool>>> matioCpp::Element<type> BipedalLocomotion::Conversions::tomatioCpp (const type & input, const std::string & name)
Conversion from a fundamental type to the corresponding matioCpp::Element.
Parameters
input The input element.
name The name of the resulting matioCpp variable.
Returns
A matioCpp::Element containing a copy of the input data
Definition at line 155 of file matioCppConversions.h.
References BipedalLocomotion::Conversions::tomatioCpp().
tomatioCpp() [9/9]
template<class Vector , typename = typename std::enable_if_t<BipedalLocomotion::GenericContainer::is_vector_constructible<Vector>::value && !std::is_same_v<Vector, std::string>>> matioCpp::Vector<typename std::remove_cv_t<typename BipedalLocomotion::container_data<Vector>::type> > BipedalLocomotion::Conversions::tomatioCpp (const Vector & input, const std::string & name)
Conversion from a generic Vector to a matioCpp::Vector.
Parameters
input The input vector.
name The name of the resulting matioCpp variable.
Returns
A matioCpp::Vector containing a copy of the input data
Definition at line 119 of file matioCppConversions.h.
References BipedalLocomotion::Conversions::tomatioCpp().
toMatioCppCellArray()
template<class iterator > matioCpp::CellArray BipedalLocomotion::Conversions::toMatioCppCellArray (const iterator & begin, const iterator & end, const std::string & name)
Create a matioCpp::CellArray starting from the begin and end iterators of a container.
If dereferenced value of the iterator is a pair (like with std::maps and std::unordered_map), only the "second" element is considered. The name of the imported variable in the CellArray is "imported_element_x", where "x" is the corresponding raw index. If the iterator is a pair, and "first" is a string, this will be used as a name.
Parameters
begin The iterator to the first element
end The iterator to the element after the last.
name The name of the CellArray.
Returns
The corresponding matioCpp::CellArray.
Definition at line 224 of file matioCppConversions.h.
References std::distance(), std::to_string(), BipedalLocomotion::Conversions::tomatioCpp(), and BipedalLocomotion::Conversions::toMatioCppCellArray().
Referenced by BipedalLocomotion::Conversions::toMatioCppCellArray().
tomatioCppStruct()
template<class iterator , typename = typename std::enable_if_t<is_pair_iterator_string<iterator>::value>> matioCpp::Struct BipedalLocomotion::Conversions::tomatioCppStruct (iterator begin, iterator end, const std::string & name)
Create a matioCpp::Struct starting from the begin and end iterators of a map-like container The dereferenced value of the iterator has to be a pair (like with std::maps and std::unordered_map) with the key being a string.
For each key, there is the corresponding field in the Struct.
Parameters
begin The iterator to the first element
end The iterator to the element after the last.
name The name of the struct.
Returns
The corresponding matioCpp::Struct
Definition at line 199 of file matioCppConversions.h.
References BipedalLocomotion::Conversions::tomatioCpp(), and BipedalLocomotion::Conversions::tomatioCppStruct().
Referenced by BipedalLocomotion::Conversions::tomatioCppStruct().