bipedal-locomotion-framework: Estimators/include/BipedalLocomotion/FloatingBaseEstimators/ModelComputationsHelper.h File Reference
ModelComputationsHelper.h File Reference
#include <memory>
#include <iDynTree/KinDynComputations.h>
#include <BipedalLocomotion/ParametersHandler/IParametersHandler.h>
Data Structures
struct BipedalLocomotion::Estimators::KinDynComputationsDescriptor
KinDynComputationsDescriptor wraps a pointer iDynTree KinDynComputations object.
Namespaces
BipedalLocomotion
Functions
KinDynComputationsDescriptor BipedalLocomotion::Estimators::constructKinDynComputationsDescriptor (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler)
Helper function that can be used to build a KinDynComputations object loaded with specified model.
Detailed Description
Authors
Prashanth Ramadoss
Copyright
2020 Istituto Italiano di Tecnologia (IIT). This software may be modified and distributed under the terms of the GNU Lesser General Public License v2.1 or any later version.
Definition in file ModelComputationsHelper.h.
Function Documentation
constructKinDynComputationsDescriptor()
KinDynComputationsDescriptor BipedalLocomotion::Estimators::constructKinDynComputationsDescriptor (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler)
Helper function that can be used to build a KinDynComputations object loaded with specified model.
Parameters
handler pointer to a parameter handler interface.
Note
the following parameters are required by the function
Parameter Name Type Description Mandatory Remark
joints_list vector<string> List of the joints to be used in the reduced model No Full model is loaded if unavailable
model_file_name string file name containing the full path to the urdf model Yes -
Warning
the joint list order that is obtained by loading the model without specifying joints_list is not stable in any way. It might not match any specific order across different environments, so one must be very careful while loading the model in this way.
Returns
A KinDynComputationsDescriptor. If one of the parameters is missing an invalid KinDynComputationsDescriptor is returned.
Definition at line 27 of file ModelComputationsHelper.cpp.
References BipedalLocomotion::Estimators::constructKinDynComputationsDescriptor(), std::endl(), BipedalLocomotion::Estimators::KinDynComputationsDescriptor::kindyn, and std::weak_ptr< T >::lock().
Referenced by BipedalLocomotion::Estimators::constructKinDynComputationsDescriptor().