bipedal-locomotion-framework: BipedalLocomotion Namespace Reference
BipedalLocomotion Namespace Reference
Namespaces
YarpUtilities
Helper for YARP library.
Functions
System::IClock & clock ()
Get the clock singleton.
TextLogging::Logger *const log ()
Get an the instance of the log.
std::shared_ptr< TextLogging::Logger > loggerCreation ()
Detailed Description
Copyright
2020 Istituto Italiano di Tecnologia (IIT). This software may be modified and distributed under the terms of the GNU Lesser General Public License v2.1 or any later version.
Function Documentation
clock()
BipedalLocomotion::System::IClock & BipedalLocomotion::clock ()
Get the clock singleton.
Definition at line 11 of file Clock.cpp.
Referenced by BipedalLocomotion::System::StdClockFactory::createClock(), BipedalLocomotion::System::YarpClockFactory::createClock(), and BipedalLocomotion::System::AdvanceableRunner< _Advanceable >::run().
log()
TextLogging::Logger *const BipedalLocomotion::log ()
Get an the instance of the log.
Definition at line 41 of file Logger.cpp.
References std::shared_ptr< T >::get().
Referenced by BipedalLocomotion::Contacts::ContactList::addContact(), BipedalLocomotion::IK::QPInverseKinematics::addTask(), BipedalLocomotion::System::VariablesHandler::addVariable(), BipedalLocomotion::YarpUtilities::addVectorOfStringToProperty(), BipedalLocomotion::Contacts::ContactDetector::advance(), BipedalLocomotion::Perception::ArucoDetector::advance(), BipedalLocomotion::RobotInterface::YarpSensorBridge::advance(), BipedalLocomotion::IK::QPInverseKinematics::advance(), BipedalLocomotion::Planners::TimeVaryingDCMPlanner::advance(), BipedalLocomotion::Estimators::FloatingBaseEstimator::advance(), BipedalLocomotion::RobotInterface::YarpCameraBridge::Impl::attachAllCameras(), BipedalLocomotion::RobotInterface::YarpCameraBridge::Impl::attachAllCamerasOfSpecificType(), BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::attachAndCheckMASSensors(), BipedalLocomotion::RobotInterface::YarpCameraBridge::Impl::attachCamera(), BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::attachGenericOrAnalogSensor(), BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::attachRemappedMASSensor(), BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::attachRemappedRemoteControlBoard(), BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::checkAttachedMASSensors(), BipedalLocomotion::RobotInterface::YarpRobotControl::checkMotionDone(), BipedalLocomotion::RobotInterface::YarpCameraBridge::Impl::checkValid(), BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::checkValid(), BipedalLocomotion::RobotInterface::YarpCameraBridge::Impl::checkValidSensorMeasure(), BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::checkValidSensorMeasure(), BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::compareControlBoardJointsList(), BipedalLocomotion::Planners::TimeVaryingDCMPlanner::computeTrajectory(), BipedalLocomotion::RobotInterface::YarpCameraBridge::Impl::configureCameras(), BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::configureCartesianWrenches(), BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::configureRemoteControlBoardRemapper(), BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::configureSixAxisForceTorqueSensors(), BipedalLocomotion::Perception::Features::PointCloudProcessor< PointType >::downsample(), BipedalLocomotion::Contacts::ContactList::editContact(), BipedalLocomotion::Perception::Features::PointCloudProcessor< PointType >::extractClusters(), BipedalLocomotion::IK::QPInverseKinematics::finalize(), BipedalLocomotion::Contacts::ContactDetector::get(), BipedalLocomotion::Math::LinearizedFrictionCone::getA(), BipedalLocomotion::Math::LinearizedFrictionCone::getB(), BipedalLocomotion::Estimators::FloatingBaseEstimator::ModelComputations::getBaseStateFromIMUState(), BipedalLocomotion::Perception::Capture::RealSense::getColorImage(), BipedalLocomotion::RobotInterface::YarpCameraBridge::getColorImage(), BipedalLocomotion::Perception::Capture::RealSense::getDepthImage(), BipedalLocomotion::RobotInterface::YarpCameraBridge::getDepthImage(), BipedalLocomotion::Contacts::FixedFootDetector::getFixedFoot(), BipedalLocomotion::ParametersHandler::StdImplementation::getGroup(), BipedalLocomotion::Estimators::FloatingBaseEstimator::ModelComputations::getIMU_H_feet(), BipedalLocomotion::RobotInterface::YarpSensorBridge::getJointPosition(), BipedalLocomotion::RobotInterface::YarpSensorBridge::getJointVelocity(), BipedalLocomotion::RobotInterface::YarpSensorBridge::getMotorCurrent(), BipedalLocomotion::IK::QPInverseKinematics::getTask(), BipedalLocomotion::RobotInterface::YarpSensorBridge::getThreeAxisForceTorqueMeasurement(), BipedalLocomotion::RobotInterface::YarpSensorBridge::getThreeAxisForceTorqueSensorsList(), BipedalLocomotion::Contacts::ContactDetector::initialize(), BipedalLocomotion::Perception::Capture::RealSense::initialize(), BipedalLocomotion::Math::LinearizedFrictionCone::initialize(), BipedalLocomotion::RobotInterface::YarpRobotControl::initialize(), BipedalLocomotion::Planners::TimeVaryingDCMPlanner::initialize(), BipedalLocomotion::System::VariablesHandler::initialize(), BipedalLocomotion::IK::JointTrackingTask::initialize(), BipedalLocomotion::TSID::JointTrackingTask::initialize(), BipedalLocomotion::RobotInterface::YarpCameraBridge::initialize(), BipedalLocomotion::TSID::SO3Task::initialize(), BipedalLocomotion::IK::SO3Task::initialize(), BipedalLocomotion::IK::CoMTask::initialize(), BipedalLocomotion::System::AdvanceableRunner< _Advanceable >::initialize(), BipedalLocomotion::TSID::SE3Task::initialize(), BipedalLocomotion::TSID::BaseDynamicsTask::initialize(), BipedalLocomotion::Perception::ArucoDetector::initialize(), BipedalLocomotion::IK::SE3Task::initialize(), BipedalLocomotion::TSID::JointDynamicsTask::initialize(), BipedalLocomotion::RobotInterface::YarpSensorBridge::initialize(), BipedalLocomotion::IK::QPInverseKinematics::initialize(), BipedalLocomotion::Estimators::FloatingBaseEstimator::initialize(), BipedalLocomotion::ContinuousDynamicalSystem::FixedStepIntegrator< _Derived >::integrate(), BipedalLocomotion::Contacts::ContactList::keepOnlyPresentContact(), BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::nanExistsInVec(), BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::readAnalogOrGenericSensor(), BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::readControlBoardInterface(), BipedalLocomotion::Perception::Features::PointCloudProcessor< PointType >::removeOutliers(), BipedalLocomotion::Estimators::FloatingBaseEstimator::resetEstimator(), BipedalLocomotion::System::AdvanceableRunner< _Advanceable >::run(), BipedalLocomotion::System::AdvanceableRunner< _Advanceable >::setAdvanceable(), BipedalLocomotion::Estimators::FloatingBaseEstimator::ModelComputations::setBaseLinkAndIMU(), BipedalLocomotion::Planners::TimeVaryingDCMPlanner::setContactPhaseList(), BipedalLocomotion::Estimators::FloatingBaseEstimator::setContactStatus(), BipedalLocomotion::Planners::TimeVaryingDCMPlanner::setDCMReference(), BipedalLocomotion::RobotInterface::YarpCameraBridge::setDriversList(), BipedalLocomotion::RobotInterface::YarpSensorBridge::setDriversList(), BipedalLocomotion::ContinuousDynamicalSystem::Integrator< _Derived >::setDynamicalSystem(), BipedalLocomotion::System::ClockBuilder::setFactory(), BipedalLocomotion::Estimators::FloatingBaseEstimator::ModelComputations::setFeetContactFrames(), BipedalLocomotion::ParametersHandler::StdImplementation::setGroup(), BipedalLocomotion::ParametersHandler::YarpImplementation::setGroup(), BipedalLocomotion::Perception::ArucoDetector::setImage(), BipedalLocomotion::System::AdvanceableRunner< _Advanceable >::setInputResource(), BipedalLocomotion::ContinuousDynamicalSystem::FixedStepIntegrator< _Derived >::setIntegrationStep(), BipedalLocomotion::IK::JointTrackingTask::setKinDyn(), BipedalLocomotion::TSID::JointTrackingTask::setKinDyn(), BipedalLocomotion::TSID::SO3Task::setKinDyn(), BipedalLocomotion::IK::SO3Task::setKinDyn(), BipedalLocomotion::IK::CoMTask::setKinDyn(), BipedalLocomotion::TSID::SE3Task::setKinDyn(), BipedalLocomotion::TSID::BaseDynamicsTask::setKinDyn(), BipedalLocomotion::IK::SE3Task::setKinDyn(), BipedalLocomotion::TSID::JointDynamicsTask::setKinDyn(), BipedalLocomotion::Estimators::FloatingBaseEstimator::ModelComputations::setKinDynObject(), BipedalLocomotion::Estimators::FloatingBaseEstimator::setKinematics(), BipedalLocomotion::Contacts::ContactPhaseList::setLists(), BipedalLocomotion::System::AdvanceableRunner< _Advanceable >::setOutputResource(), BipedalLocomotion::RobotInterface::YarpRobotControl::setReferences(), BipedalLocomotion::IK::JointTrackingTask::setSetPoint(), BipedalLocomotion::Estimators::FloatingBaseEstimator::setupInitialStates(), BipedalLocomotion::Estimators::FloatingBaseEstimator::setupOptions(), BipedalLocomotion::Estimators::FloatingBaseEstimator::setupPriorDevs(), BipedalLocomotion::Estimators::FloatingBaseEstimator::setupSensorDevs(), BipedalLocomotion::IK::JointTrackingTask::setVariablesHandler(), BipedalLocomotion::TSID::JointTrackingTask::setVariablesHandler(), BipedalLocomotion::TSID::SO3Task::setVariablesHandler(), BipedalLocomotion::IK::SO3Task::setVariablesHandler(), BipedalLocomotion::IK::CoMTask::setVariablesHandler(), BipedalLocomotion::TSID::SE3Task::setVariablesHandler(), BipedalLocomotion::IK::SE3Task::setVariablesHandler(), BipedalLocomotion::TSID::BaseDynamicsTask::setVariablesHandler(), BipedalLocomotion::TSID::JointDynamicsTask::setVariablesHandler(), BipedalLocomotion::IK::JointTrackingTask::size(), BipedalLocomotion::TSID::JointDynamicsTask::size(), BipedalLocomotion::TSID::JointTrackingTask::size(), BipedalLocomotion::RobotInterface::YarpCameraBridge::Impl::subConfigLoader(), BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::subConfigLoader(), BipedalLocomotion::Perception::Features::PointCloudProcessor< PointType >::transform(), BipedalLocomotion::IK::JointTrackingTask::update(), BipedalLocomotion::TSID::SO3Task::update(), BipedalLocomotion::IK::CoMTask::update(), BipedalLocomotion::IK::SO3Task::update(), BipedalLocomotion::TSID::SE3Task::update(), BipedalLocomotion::IK::SE3Task::update(), BipedalLocomotion::TSID::BaseDynamicsTask::update(), BipedalLocomotion::TSID::JointDynamicsTask::update(), and BipedalLocomotion::Estimators::FloatingBaseEstimator::updateBaseStateFromIMUState().