bipedal-locomotion-framework: BipedalLocomotion::YarpUtilities Namespace Reference
BipedalLocomotion::YarpUtilities Namespace Reference
Helper for YARP library.
Data Structures
class RosPublisher
The class internally contains a YARP based ROS node and a set of publishers.
Functions
template<typename T >
T convertValue (const yarp::os::Value &value)
Convert a value in a element of type T.
template<>
int convertValue< int > (const yarp::os::Value &value)
Convert a value in a element of type int.
template<>
double convertValue< double > (const yarp::os::Value &value)
Convert a value in a element of type double.
template<>
std::string convertValue< std::string > (const yarp::os::Value &value)
Convert a value in a element of type string.
template<>
bool convertValue< bool > (const yarp::os::Value &value)
Convert a value in a element of type Boolean.
bool addVectorOfStringToProperty (yarp::os::Property &prop, const std::string &key, const std::vector< std::string > &list)
Add a vector of string to a property of a given name.
template<typename T >
bool getElementFromSearchable (const yarp::os::Searchable &config, const std::string &key, T &number)
Extract a double from a searchable object.
template<typename T >
bool getVectorFromSearchable (const yarp::os::Searchable &config, const std::string &key, T &vector)
Extract a vector from searchable.
template<>
bool getVectorFromSearchable< std::vector< bool > > (const yarp::os::Searchable &config, const std::string &key, std::vector< bool > &vector)
Extract an std::vector<bool> from searchable.
template<typename T >
void mergeSigVector (yarp::sig::Vector &vector, const T &t)
Append a scalar to a vector.
template<typename T , typename... Args>
void mergeSigVector (yarp::sig::Vector &vector, const T &t, const Args &... args)
Variadic function used to merge several vectors.
template<typename... Args>
void sendVariadicVector (yarp::os::BufferedPort< yarp::sig::Vector > &port, const Args &... args)
Send a variadic vector through a yarp buffered port.
void populateBottleWithStrings (yarp::os::Bottle &bottle, const std::initializer_list< std::string > &strings)
Add strings to a bottle.
Detailed Description
Helper for YARP library.
Function Documentation
addVectorOfStringToProperty()
bool BipedalLocomotion::YarpUtilities::addVectorOfStringToProperty (yarp::os::Property & prop, const std::string & key, const std::vector< std::string > & list)
Add a vector of string to a property of a given name.
Parameters
prop yarp property;
key is the key;
list is the vector of strings that will be added into the property.
Returns
true/false in case of success/failure
Definition at line 12 of file Helper.cpp.
References BipedalLocomotion::log(), and std::vector< T >::size().
convertValue()
template<typename T > T BipedalLocomotion::YarpUtilities::convertValue (const yarp::os::Value & value)
Convert a value in a element of type T.
Parameters
value the value that will be converted
Template Parameters
T return type
Returns
an element of type T
Definition at line 51 of file Helper.tpp.
convertValue< bool >()
template<> bool BipedalLocomotion::YarpUtilities::convertValue< bool > (const yarp::os::Value & value)
Convert a value in a element of type Boolean.
Parameters
value the value that will be converted
Returns
a Boolean
Definition at line 54 of file Helper.cpp.
convertValue< double >()
template<> double BipedalLocomotion::YarpUtilities::convertValue< double > (const yarp::os::Value & value)
Convert a value in a element of type double.
Parameters
value the value that will be converted
Returns
a double
Definition at line 44 of file Helper.cpp.
convertValue< int >()
template<> int BipedalLocomotion::YarpUtilities::convertValue< int > (const yarp::os::Value & value)
Convert a value in a element of type int.
Parameters
value the value that will be converted
Returns
an integer
Definition at line 39 of file Helper.cpp.
convertValue< std::string >()
template<> std::string BipedalLocomotion::YarpUtilities::convertValue< std::string > (const yarp::os::Value & value)
Convert a value in a element of type string.
Parameters
value the value that will be converted
Returns
a string
getElementFromSearchable()
template<typename T > bool BipedalLocomotion::YarpUtilities::getElementFromSearchable (const yarp::os::Searchable & config, const std::string & key, T & number)
Extract a double from a searchable object.
Parameters
config is the searchable object;
key the name to check for;
number is the double.
Returns
true/false in case of success/failure
Definition at line 61 of file Helper.tpp.
getVectorFromSearchable()
template<typename T > bool BipedalLocomotion::YarpUtilities::getVectorFromSearchable (const yarp::os::Searchable & config, const std::string & key, T & vector)
Extract a vector from searchable.
Parameters
config is the searchable object;
key the name to check for;
vector a vector.
Returns
true/false in case of success/failure
Definition at line 94 of file Helper.tpp.
getVectorFromSearchable< std::vector< bool > >()
template<> bool BipedalLocomotion::YarpUtilities::getVectorFromSearchable< std::vector< bool > > (const yarp::os::Searchable & config, const std::string & key, std::vector< bool > & vector)
Extract an std::vector<bool> from searchable.
The specialization is required because vector.data() is not defined when vector is an std::vector<bool>
Parameters
config is the searchable object;
key the name to check for;
vector a std::vector<bool>
Returns
true/false in case of success/failure
mergeSigVector() [1/2]
template<typename T > void BipedalLocomotion::YarpUtilities::mergeSigVector (yarp::sig::Vector & vector, const T & t)
Append a scalar to a vector.
vector = [vector, t]
Parameters
vector the original vector. The new elements will be add at the end of this vector;
t is a container or a scalar. If t is a container it has to be an iterable object (the element has the methods T::begin() and T::end() or the operator[] has to be defined
Warning
If \at does not satisfies the previous assumptions the compilation will fail with a static assertion
Definition at line 175 of file Helper.tpp.
Referenced by mergeSigVector(), and sendVariadicVector().
mergeSigVector() [2/2]
template<typename T , typename... Args> void BipedalLocomotion::YarpUtilities::mergeSigVector (yarp::sig::Vector & vector, const T & t, const Args &... args)
Variadic function used to merge several vectors.
Parameters
vector the original vector. The new elements will be add at the end of this vector;
t is a container or a scalar. If t is a container it has to be an iterable object (the element has the methods T::begin() and T::end()) or the operator[] has to be defined
args list containing all the vector that will be merged.
Warning
If t does not satisfies the previous assumptions the compilation will fail with a static assertion
Definition at line 216 of file Helper.tpp.
References mergeSigVector().
populateBottleWithStrings()
void BipedalLocomotion::YarpUtilities::populateBottleWithStrings (yarp::os::Bottle & bottle, const std::initializer_list< std::string > & strings)
Add strings to a bottle.
Parameters
bottle this bottle will be filled.
strings list containing all the string.
Definition at line 32 of file Helper.cpp.
sendVariadicVector()
template<typename... Args> void BipedalLocomotion::YarpUtilities::sendVariadicVector (yarp::os::BufferedPort< yarp::sig::Vector > & port, const Args &... args)
Send a variadic vector through a yarp buffered port.
Parameters
port is a Yarp buffered port
args list containing all the vector that will be send.
Definition at line 225 of file Helper.tpp.
References mergeSigVector().