bipedal-locomotion-framework: BipedalLocomotion::RobotInterface::YarpCameraBridge::Impl Struct Reference
BipedalLocomotion::RobotInterface::YarpCameraBridge::Impl Struct Reference
Public Types
template<typename PixelCode >
using StampedYARPImage = std::pair< yarp::sig::ImageOf< PixelCode >, double >
using StampedYARPFlexImage = std::pair< yarp::sig::FlexImage, double >
using SubConfigLoader = bool(YarpCameraBridge::Impl::*)(std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler >, CameraBridgeMetaData &)
Public Member Functions
template<typename SensorType >
bool checkSensor (const std::unordered_map< std::string, SensorType * > &sensorMap, const std::string &sensorName)
Check if sensor is available in the relevant sensor map.
template<typename YARPDataType >
bool checkValidSensorMeasure (std::string_view logPrefix, const std::unordered_map< std::string, YARPDataType > &sensorMap, const std::string &sensorName)
Check if sensor is available in the relevant sensor measurement map.
bool checkValid (const std::string_view methodName)
Check if the bridge is successfully initialized and attached to required device drivers.
bool subConfigLoader (const std::string &enableStreamString, const std::string &streamGroupString, const SubConfigLoader loader, std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler, CameraBridgeMetaData &metaData, bool &enableStreamFlag)
Checks is a stream is enabled in configuration and loads the relevant stream group from configuration.
bool configureCameras (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler, CameraBridgeMetaData &metaData)
Configure cameras meta data.
template<typename CameraType >
bool attachCamera (const yarp::dev::PolyDriverList &devList, const std::string sensorName, std::unordered_map< std::string, CameraType * > &sensorMap)
Attach cameras.
bool attachAllCameras (const yarp::dev::PolyDriverList &devList)
Attach all cameras.
template<typename CameraType >
bool attachAllCamerasOfSpecificType (const yarp::dev::PolyDriverList &devList, const std::vector< std::string > &camList, std::string_view interfaceType, std::unordered_map< std::string, CameraType * > &sensorMap)
Attach all cameras of specific type and resize image buffers.
template<typename PixelType >
bool resizeImageBuffer (const std::string &cam, const std::unordered_map< std::string, std::pair< std::size_t, std::size_t > > &imgDimensionsMap, StampedYARPImage< PixelType > &img)
Resize image buffers ImageOf<PixelType>
bool resizeImageBuffer (const std::string &cam, const std::unordered_map< std::string, std::pair< std::size_t, std::size_t > > &imgDimensionsMap, StampedYARPFlexImage &img)
Resize image buffers - Flex Image.
template<typename CameraType , typename PixelType >
bool readCameraImage (const std::string &cameraName, std::unordered_map< std::string, CameraType * > &interfaceMap, StampedYARPImage< PixelType > &image)
template<typename CameraType >
bool readCameraImage (const std::string &cameraName, std::unordered_map< std::string, CameraType * > &interfaceMap, StampedYARPFlexImage &img)
Data Fields
std::unordered_map< std::string, yarp::dev::IFrameGrabberImage * > wholeBodyFrameGrabberInterface
std::unordered_map< std::string, yarp::dev::IRGBDSensor * > wholeBodyRGBDInterface
< map of cameras attached through frame grabber interfaces
CameraBridgeMetaData metaData
< map of cameras attached through RGBD interfaces
bool bridgeInitialized {false}
flag set to true if the bridge is successfully initialized
bool driversAttached {false}
flag set to true if the bridge is successfully attached to required device drivers
StampedYARPImage< yarp::sig::PixelFloat > depthImage
StampedYARPFlexImage flexImage
StampedYARPImage< yarp::sig::PixelRgb > rgbImage
Detailed Description
Definition at line 30 of file YarpCameraBridge.cpp.
Member Function Documentation
attachAllCameras()
bool BipedalLocomotion::RobotInterface::YarpCameraBridge::Impl::attachAllCameras (const yarp::dev::PolyDriverList & devList) inline
Attach all cameras.
Definition at line 271 of file YarpCameraBridge.cpp.
References BipedalLocomotion::RobotInterface::CameraBridgeOptions::isRGBCameraEnabled, BipedalLocomotion::RobotInterface::CameraBridgeOptions::isRGBDCameraEnabled, BipedalLocomotion::log(), BipedalLocomotion::RobotInterface::CameraLists::rgbCamerasList, and BipedalLocomotion::RobotInterface::CameraLists::rgbdCamerasList.
attachAllCamerasOfSpecificType()
template<typename CameraType > bool BipedalLocomotion::RobotInterface::YarpCameraBridge::Impl::attachAllCamerasOfSpecificType (const yarp::dev::PolyDriverList & devList, const std::vector< std::string > & camList, std::string_view interfaceType, std::unordered_map< std::string, CameraType * > & sensorMap) inline
Attach all cameras of specific type and resize image buffers.
Definition at line 313 of file YarpCameraBridge.cpp.
References BipedalLocomotion::log(), and std::unordered_map< K, T >::size().
attachCamera()
template<typename CameraType > bool BipedalLocomotion::RobotInterface::YarpCameraBridge::Impl::attachCamera (const yarp::dev::PolyDriverList & devList, const std::string sensorName, std::unordered_map< std::string, CameraType * > & sensorMap) inline
Attach cameras.
Definition at line 242 of file YarpCameraBridge.cpp.
References BipedalLocomotion::log().
checkSensor()
template<typename SensorType > bool BipedalLocomotion::RobotInterface::YarpCameraBridge::Impl::checkSensor (const std::unordered_map< std::string, SensorType * > & sensorMap, const std::string & sensorName) inline
Check if sensor is available in the relevant sensor map.
Definition at line 53 of file YarpCameraBridge.cpp.
References std::unordered_map< K, T >::end(), and std::unordered_map< K, T >::find().
checkValid()
bool BipedalLocomotion::RobotInterface::YarpCameraBridge::Impl::checkValid (const std::string_view methodName) inline
Check if the bridge is successfully initialized and attached to required device drivers.
Definition at line 88 of file YarpCameraBridge.cpp.
References BipedalLocomotion::log().
checkValidSensorMeasure()
template<typename YARPDataType > bool BipedalLocomotion::RobotInterface::YarpCameraBridge::Impl::checkValidSensorMeasure (std::string_view logPrefix, const std::unordered_map< std::string, YARPDataType > & sensorMap, const std::string & sensorName) inline
Check if sensor is available in the relevant sensor measurement map.
Definition at line 67 of file YarpCameraBridge.cpp.
References std::unordered_map< K, T >::end(), std::unordered_map< K, T >::find(), and BipedalLocomotion::log().
configureCameras()
bool BipedalLocomotion::RobotInterface::YarpCameraBridge::Impl::configureCameras (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler, CameraBridgeMetaData & metaData) inline
Configure cameras meta data.
Definition at line 143 of file YarpCameraBridge.cpp.
References BipedalLocomotion::RobotInterface::CameraBridgeOptions::isRGBCameraEnabled, BipedalLocomotion::RobotInterface::CameraBridgeOptions::isRGBDCameraEnabled, std::weak_ptr< T >::lock(), BipedalLocomotion::log(), BipedalLocomotion::RobotInterface::CameraLists::rgbCamerasList, BipedalLocomotion::RobotInterface::CameraLists::rgbdCamerasList, BipedalLocomotion::RobotInterface::CameraBridgeOptions::rgbdImgDimensions, BipedalLocomotion::RobotInterface::CameraBridgeOptions::rgbImgDimensions, and std::vector< T >::size().
Referenced by BipedalLocomotion::RobotInterface::YarpCameraBridge::initialize().
resizeImageBuffer() [1/2]
bool BipedalLocomotion::RobotInterface::YarpCameraBridge::Impl::resizeImageBuffer (const std::string & cam, const std::unordered_map< std::string, std::pair< std::size_t, std::size_t > > & imgDimensionsMap, StampedYARPFlexImage & img) inline
Resize image buffers - Flex Image.
Definition at line 360 of file YarpCameraBridge.cpp.
resizeImageBuffer() [2/2]
template<typename PixelType > bool BipedalLocomotion::RobotInterface::YarpCameraBridge::Impl::resizeImageBuffer (const std::string & cam, const std::unordered_map< std::string, std::pair< std::size_t, std::size_t > > & imgDimensionsMap, StampedYARPImage< PixelType > & img) inline
Resize image buffers ImageOf<PixelType>
Definition at line 340 of file YarpCameraBridge.cpp.
subConfigLoader()
bool BipedalLocomotion::RobotInterface::YarpCameraBridge::Impl::subConfigLoader (const std::string & enableStreamString, const std::string & streamGroupString, const SubConfigLoader loader, std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler, CameraBridgeMetaData & metaData, bool & enableStreamFlag) inline
Checks is a stream is enabled in configuration and loads the relevant stream group from configuration.
Definition at line 105 of file YarpCameraBridge.cpp.
References std::weak_ptr< T >::lock(), and BipedalLocomotion::log().
Field Documentation
bridgeInitialized
bool BipedalLocomotion::RobotInterface::YarpCameraBridge::Impl::bridgeInitialized {false}
flag set to true if the bridge is successfully initialized
Definition at line 42 of file YarpCameraBridge.cpp.
driversAttached
bool BipedalLocomotion::RobotInterface::YarpCameraBridge::Impl::driversAttached {false}
flag set to true if the bridge is successfully attached to required device drivers
Definition at line 43 of file YarpCameraBridge.cpp.
metaData
CameraBridgeMetaData BipedalLocomotion::RobotInterface::YarpCameraBridge::Impl::metaData
< map of cameras attached through RGBD interfaces
struct holding meta data
Definition at line 41 of file YarpCameraBridge.cpp.
wholeBodyRGBDInterface
std::unordered_map<std::string, yarp::dev::IRGBDSensor*> BipedalLocomotion::RobotInterface::YarpCameraBridge::Impl::wholeBodyRGBDInterface
< map of cameras attached through frame grabber interfaces
Definition at line 38 of file YarpCameraBridge.cpp.
The documentation for this struct was generated from the following file:
RobotInterface/YarpImplementation/src/YarpCameraBridge.cpp