bipedal-locomotion-framework: BipedalLocomotion::Planners::QuinticSpline::Impl Struct Reference
BipedalLocomotion::Planners::QuinticSpline::Impl Struct Reference
Data Structures
struct BoundaryConditions
Struct containing the boundary condtion.
struct Knot
Description of a knot.
struct Polynomial
Description of a 5-th polynomial.
Public Member Functions
void resetKnot (const double &timeInstant, Eigen::Ref< const Eigen::VectorXd > position, Knot &knot)
Reset a given knot with a time instant and a position.
void getPositionAtTime (const double &t, const Polynomial &poly, Eigen::Ref< Eigen::VectorXd > position)
Get the position at given time for a sub-trajectory.
void getVelocityAtTime (const double &t, const Polynomial &poly, Eigen::Ref< Eigen::VectorXd > velocity)
Get the velocity at given time for a sub-trajectory.
void getAccelerationAtTime (const double &t, const Polynomial &poly, Eigen::Ref< Eigen::VectorXd > acceleration)
Get the acceleration at given time for a sub-trajectory.
bool computePhasesDuration ()
Compute the duration of each phase.
bool setBoundaryVelocitiesAndAcceleration ()
Set the boundary condition.
void addTripletCurrentKnot (const int &knotIndex, const int &rowOffset, const int &columnOffset, std::vector< Eigen::Triplet< double >> &tripletList)
addTripletCurrentKnot is a helper function to generate a triplet containing a 2x2 matrix.
void addTripletPreviousKnot (const int &knotIndex, const int &rowOffset, const int &columnOffset, std::vector< Eigen::Triplet< double >> &tripletList)
addTripletPreviousKnot is a helper function to generate a triplet containing a 2x2 matrix.
void addTripletNextKnot (const int &knotIndex, const int &rowOffset, const int &columnOffset, std::vector< Eigen::Triplet< double >> &tripletList)
addTripletNextKnot is a helper function to generate a triplet containing a 2x2 matrix.
void addKnownTermKnotPosition (const std::size_t &knotIndex, const std::size_t &coordinateIndex, Eigen::Ref< Eigen::VectorXd > b)
addKnownTermKnotPosition is a helper function to generate a 2-d vector, This vector is the known term used to compute the intermediate velocity and acceleration.
void addKnownTermNextKnot (const std::size_t &knotIndex, const std::size_t &coordinateIndex, Eigen::Ref< Eigen::VectorXd > b)
addKnownTermNextKnot is a helper function to generate a 2-d vector, This vector is the known term used to compute the intermediate velocity and acceleration.
void addKnownTermPreviousKnot (const std::size_t &knotIndex, const std::size_t &coordinateIndex, Eigen::Ref< Eigen::VectorXd > b)
addKnownTermPreviousKnot is a helper function to generate a 2-d vector, This vector is the known term used to compute the intermediate velocity and acceleration.
void computeIntermediateVelocitiesAndAcceleration ()
Compute the intermediate velocity and accelerations.
void setPolynomialCoefficients (Polynomial &poly)
Function to set the coefficients of the polynomials.
bool computeCoefficients ()
This function is the entry point to compute the coefficients of the spline.
Data Fields
BoundaryConditions initialCondition
Initial condition.
BoundaryConditions finalCondition
Final condition.
std::vector< Knot > knots
Collection of all the knots.
std::vector< Polynomial > polynomials
Collection of all the polynomials.
bool areCoefficientsComputed {false}
If true the coefficients are computed and updated.
QuinticSplineState currentTrajectory
Current trajectory stored in the advance state.
double advanceTimeStep {0.0}
Time step of the advance interface.
double advanceCurrentTime {0.0}
current time of the advance object.
Detailed Description
Definition at line 16 of file QuinticSpline.cpp.
Member Function Documentation
addKnownTermKnotPosition()
void BipedalLocomotion::Planners::QuinticSpline::Impl::addKnownTermKnotPosition (const std::size_t & knotIndex, const std::size_t & coordinateIndex, Eigen::Ref< Eigen::VectorXd > b)
addKnownTermKnotPosition is a helper function to generate a 2-d vector, This vector is the known term used to compute the intermediate velocity and acceleration.
Definition at line 525 of file QuinticSpline.cpp.
References std::pow().
addKnownTermNextKnot()
void BipedalLocomotion::Planners::QuinticSpline::Impl::addKnownTermNextKnot (const std::size_t & knotIndex, const std::size_t & coordinateIndex, Eigen::Ref< Eigen::VectorXd > b)
addKnownTermNextKnot is a helper function to generate a 2-d vector, This vector is the known term used to compute the intermediate velocity and acceleration.
Definition at line 547 of file QuinticSpline.cpp.
References std::pow().
addKnownTermPreviousKnot()
void BipedalLocomotion::Planners::QuinticSpline::Impl::addKnownTermPreviousKnot (const std::size_t & knotIndex, const std::size_t & coordinateIndex, Eigen::Ref< Eigen::VectorXd > b)
addKnownTermPreviousKnot is a helper function to generate a 2-d vector, This vector is the known term used to compute the intermediate velocity and acceleration.
Definition at line 565 of file QuinticSpline.cpp.
References std::pow().
addTripletCurrentKnot()
void BipedalLocomotion::Planners::QuinticSpline::Impl::addTripletCurrentKnot (const int & knotIndex, const int & rowOffset, const int & columnOffset, std::vector< Eigen::Triplet< double >> & tripletList)
addTripletCurrentKnot is a helper function to generate a triplet containing a 2x2 matrix.
This matrix is used to compute the intermediate velocity and acceleration.
Definition at line 428 of file QuinticSpline.cpp.
References std::pow().
addTripletNextKnot()
void BipedalLocomotion::Planners::QuinticSpline::Impl::addTripletNextKnot (const int & knotIndex, const int & rowOffset, const int & columnOffset, std::vector< Eigen::Triplet< double >> & tripletList)
addTripletNextKnot is a helper function to generate a triplet containing a 2x2 matrix.
This matrix is used to compute the intermediate velocity and acceleration.
Definition at line 498 of file QuinticSpline.cpp.
References std::pow().
addTripletPreviousKnot()
void BipedalLocomotion::Planners::QuinticSpline::Impl::addTripletPreviousKnot (const int & knotIndex, const int & rowOffset, const int & columnOffset, std::vector< Eigen::Triplet< double >> & tripletList)
addTripletPreviousKnot is a helper function to generate a triplet containing a 2x2 matrix.
This matrix is used to compute the intermediate velocity and acceleration.
Definition at line 471 of file QuinticSpline.cpp.
References std::pow().
computeCoefficients()
bool BipedalLocomotion::Planners::QuinticSpline::Impl::computeCoefficients ()
This function is the entry point to compute the coefficients of the spline.
Definition at line 317 of file QuinticSpline.cpp.
References std::endl().
computeIntermediateVelocitiesAndAcceleration()
void BipedalLocomotion::Planners::QuinticSpline::Impl::computeIntermediateVelocitiesAndAcceleration ()
Compute the intermediate velocity and accelerations.
Definition at line 612 of file QuinticSpline.cpp.
References std::vector< T >::begin(), std::vector< T >::end(), and std::vector< T >::reserve().
computePhasesDuration()
bool BipedalLocomotion::Planners::QuinticSpline::Impl::computePhasesDuration ()
Compute the duration of each phase.
Definition at line 299 of file QuinticSpline.cpp.
References std::endl().
getAccelerationAtTime()
void BipedalLocomotion::Planners::QuinticSpline::Impl::getAccelerationAtTime (const double & t, const Polynomial & poly, Eigen::Ref< Eigen::VectorXd > acceleration)
Get the acceleration at given time for a sub-trajectory.
Definition at line 770 of file QuinticSpline.cpp.
References std::pow().
getPositionAtTime()
void BipedalLocomotion::Planners::QuinticSpline::Impl::getPositionAtTime (const double & t, const Polynomial & poly, Eigen::Ref< Eigen::VectorXd > position)
Get the position at given time for a sub-trajectory.
Definition at line 731 of file QuinticSpline.cpp.
References std::pow().
getVelocityAtTime()
void BipedalLocomotion::Planners::QuinticSpline::Impl::getVelocityAtTime (const double & t, const Polynomial & poly, Eigen::Ref< Eigen::VectorXd > velocity)
Get the velocity at given time for a sub-trajectory.
Definition at line 751 of file QuinticSpline.cpp.
References std::pow().
resetKnot()
void BipedalLocomotion::Planners::QuinticSpline::Impl::resetKnot (const double & timeInstant, Eigen::Ref< const Eigen::VectorXd > position, Knot & knot)
Reset a given knot with a time instant and a position.
Definition at line 287 of file QuinticSpline.cpp.
References BipedalLocomotion::Planners::QuinticSpline::Impl::Knot::acceleration, BipedalLocomotion::Planners::QuinticSpline::Impl::Knot::position, BipedalLocomotion::Planners::QuinticSpline::Impl::Knot::timeInstant, and BipedalLocomotion::Planners::QuinticSpline::Impl::Knot::velocity.
setBoundaryVelocitiesAndAcceleration()
bool BipedalLocomotion::Planners::QuinticSpline::Impl::setBoundaryVelocitiesAndAcceleration ()
Set the boundary condition.
This function is called before computing all the intermediate velocities and accelerations.
Definition at line 374 of file QuinticSpline.cpp.
References std::endl().
setPolynomialCoefficients()
void BipedalLocomotion::Planners::QuinticSpline::Impl::setPolynomialCoefficients (Polynomial & poly)
Function to set the coefficients of the polynomials.
Definition at line 583 of file QuinticSpline.cpp.
References BipedalLocomotion::Planners::QuinticSpline::Impl::Knot::acceleration, BipedalLocomotion::Planners::QuinticSpline::Impl::Knot::position, and BipedalLocomotion::Planners::QuinticSpline::Impl::Knot::velocity.
Field Documentation
advanceCurrentTime
double BipedalLocomotion::Planners::QuinticSpline::Impl::advanceCurrentTime {0.0}
current time of the advance object.
Definition at line 68 of file QuinticSpline.cpp.
advanceTimeStep
double BipedalLocomotion::Planners::QuinticSpline::Impl::advanceTimeStep {0.0}
Time step of the advance interface.
Definition at line 67 of file QuinticSpline.cpp.
areCoefficientsComputed
bool BipedalLocomotion::Planners::QuinticSpline::Impl::areCoefficientsComputed {false}
If true the coefficients are computed and updated.
Definition at line 64 of file QuinticSpline.cpp.
currentTrajectory
QuinticSplineState BipedalLocomotion::Planners::QuinticSpline::Impl::currentTrajectory
Current trajectory stored in the advance state.
Definition at line 66 of file QuinticSpline.cpp.
finalCondition
BoundaryConditions BipedalLocomotion::Planners::QuinticSpline::Impl::finalCondition
Final condition.
Definition at line 59 of file QuinticSpline.cpp.
initialCondition
BoundaryConditions BipedalLocomotion::Planners::QuinticSpline::Impl::initialCondition
Initial condition.
Definition at line 58 of file QuinticSpline.cpp.
knots
std::vector<Knot> BipedalLocomotion::Planners::QuinticSpline::Impl::knots
Collection of all the knots.
Definition at line 61 of file QuinticSpline.cpp.
polynomials
std::vector<Polynomial> BipedalLocomotion::Planners::QuinticSpline::Impl::polynomials
Collection of all the polynomials.
Definition at line 62 of file QuinticSpline.cpp.
The documentation for this struct was generated from the following file:
Planners/src/QuinticSpline.cpp