bipedal-locomotion-framework: Math/include/BipedalLocomotion/Math/Wrench.h File Reference
Wrench.h File Reference
#include <Eigen/Dense>
#include <manif/SE3.h>
#include <manif/SO3.h>
Data Structures
class BipedalLocomotion::Math::Wrench< Scalar >
Wrench represent a wrench, i.e.
Namespaces
BipedalLocomotion
Typedefs
using BipedalLocomotion::Math::Wrenchd = Wrench< double >
A wrench of double.
Functions
template<class Scalar >
Wrench< Scalar > BipedalLocomotion::Math::operator* (const manif::SE3< Scalar > &transform, const Wrench< Scalar > &wrench)
Change the frame in which the Wrench is expressed.
template<class Scalar >
Wrench< Scalar > BipedalLocomotion::Math::operator* (const manif::SO3< Scalar > &rotation, const Wrench< Scalar > &wrench)
Change the frame in which the Wrench is expressed.
Detailed Description
Authors
Giulio Romualdi
Copyright
2021 Istituto Italiano di Tecnologia (IIT). This software may be modified and distributed under the terms of the GNU Lesser General Public License v2.1 or any later version.
Definition in file Wrench.h.
Typedef Documentation
Wrenchd
using BipedalLocomotion::Math::Wrenchd = typedef Wrench<double>
A wrench of double.
Definition at line 181 of file Wrench.h.
Function Documentation
operator*() [1/2]
template<class Scalar > Wrench<Scalar> BipedalLocomotion::Math::operator* (const manif::SE3< Scalar > & transform, const Wrench< Scalar > & wrench)
Change the frame in which the Wrench is expressed.
If the tranform is \(H\) is
\[ (p,R) = ({}^{\texttt{refOrient}} p_{\texttt{refPoint},\texttt{point}} , {}^{\texttt{refOrient}} R_{\texttt{orient}}) \]
And the wrench is:
\[ {}_{\texttt{frame}} F = \begin{bmatrix} f \\ \tau \end{bmatrix} \]
The result of this operation is :
\[ {}_{\texttt{refFrame}} F = {}_{\texttt{refFrame}}X^{\texttt{frame}} {}_{\texttt{frame}} F = \begin{bmatrix} R & 0_{3\times3} \\ p \times R & R \end{bmatrix} \begin{bmatrix} f \\ \tau \end{bmatrix} = \begin{bmatrix} Rf \\ p \times R f + R\tau \end{bmatrix} \]
Parameters
transform a manif::SE3 object representing a homogeneous transformation that changes the coordinates of a vector expressed in the frame A into the coordinates in the frame B
wrench expressed in the frame A
Returns
the vector expressed in the frame B
Definition at line 122 of file Wrench.h.
References BipedalLocomotion::Math::Wrench< Scalar >::force(), BipedalLocomotion::Math::operator*(), and BipedalLocomotion::Math::Wrench< Scalar >::torque().
Referenced by BipedalLocomotion::Math::operator*().
operator*() [2/2]
template<class Scalar > Wrench<Scalar> BipedalLocomotion::Math::operator* (const manif::SO3< Scalar > & rotation, const Wrench< Scalar > & wrench)
Change the frame in which the Wrench is expressed.
If the tranform is \(H\) is
\[ (p,R) = (O _ {3 \times 1} , {}^{\texttt{refOrient}} R_{\texttt{orient}}) \]
And the wrench is:
\[ {}_{\texttt{frame}} F = \begin{bmatrix} f \\ \tau \end{bmatrix} \]
The result of this operation is :
\[ {}_{\texttt{refFrame}} F = {}_{\texttt{refFrame}}X^{\texttt{frame}} {}_{\texttt{frame}} F = \begin{bmatrix} R & 0_{3\times3} \\ 0_{3\times3} & R \end{bmatrix} \begin{bmatrix} f \\ \tau \end{bmatrix} = \begin{bmatrix} Rf \\ R\tau \end{bmatrix} \]
Parameters
rotation a manif::SO3 object representing a rotation that changes the coordinates of a vector expressed in the frame A into the coordinates in the frame B
wrench expressed in the frame A
Returns
the vector expressed in the frame B
Definition at line 170 of file Wrench.h.
References BipedalLocomotion::Math::Wrench< Scalar >::force(), BipedalLocomotion::Math::operator*(), and BipedalLocomotion::Math::Wrench< Scalar >::torque().