base_vel_norm = 0.4
base_ang_vel_norm = 0.4
ellipsoid_forward_axis = 6.0
ellipsoid_side_axis = 2.0
ellipsoid_backward_axis = 3.0
ellipsoid_scaling_factor = 0.4
max_base_direction_angle_forward = 0.79
max_base_direction_angle_backward = 0.1
max_base_direction_angle_side_opposite_sign = 0.26
max_base_direction_angle_side_same_sign = 0.17
number_of_knots = 7
