# Copyright (C) 2020 Istituto Italiano di Tecnologia (IIT). All rights reserved.
# This software may be modified and distributed under the terms of the
# GNU Lesser General Public License v2.1 or any later version.

find_package(PythonInterp 3.6 QUIET)
checkandset_dependency(PythonInterp)

find_package(PythonLibs   3.6 QUIET)
checkandset_dependency(PythonLibs)

framework_dependent_option(FRAMEWORK_GENERATE_urdf_models
  "Generate URDF Models?" ON
  "FRAMEWORK_HAS_PythonInterp;FRAMEWORK_HAS_PythonLibs" OFF)


function(generate_and_add_urdf_model)

    set(options )
    set(oneValueArgs SCRIPT_NAME INSTALLATION_FOLDER)
    set(multiValueArgs EXTRA_FILES)

    set(prefix "bipedal_model_generation")

    cmake_parse_arguments(${prefix}
      "${options}"
      "${oneValueArgs}"
      "${multiValueArgs}"
      ${ARGN})

    set(script_name ${${prefix}_SCRIPT_NAME})
    set(arguments ${${prefix}_ARGUMENTS})
    set(installation_folder ${${prefix}_INSTALLATION_FOLDER})
    set(extra_files ${${prefix}_EXTRA_FILES})

    message("-- Generating the Urdf Model from ${script_name}")

    execute_process (
      COMMAND ${PYTHON_EXECUTABLE} "${script_name}.py" --install_folder "${CMAKE_BINARY_DIR}/Autogenerated/gazebo/models/${installation_folder}"
      WORKING_DIRECTORY ${CMAKE_CURRENT_LIST_DIR}
      )

    file(GLOB files "${CMAKE_BINARY_DIR}/Autogenerated/gazebo/models/${installation_folder}/*.urdf")
    install(FILES ${files}
      DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}/share/gazebo/models/${installation_folder}")
    install(FILES ${extra_files}
      DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}/share/gazebo/models/${installation_folder}")

endfunction()
