name: Changelog Checker

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - master
jobs:
  build:
    name: Check Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Changelog check
        uses: Zomzog/changelog-checker@1.3.0
        with:
          fileName: CHANGELOG.md
          noChangelogLabel: "[disable changelog ci]"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
