name: gh-pages
on:
  push:
    branches:
      - '*'
      - '!gh-pages'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master

      - uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: conda-forge
          channel-priority: true

      - name: Dependencies
        shell: bash -l {0}
        run: |
          # Workaround for https://github.com/conda-incubator/setup-miniconda/issues/186
          conda config --remove channels defaults

          # Dependencies
          mamba install doxygen toml pygments docutils jinja2 texlive-core

      - name: Fetch m.css
        shell: bash -l {0}
        run: |
          # Use an unofficial version of m.css because of https://github.com/mosra/m.css/pull/189
          cd ${GITHUB_WORKSPACE}
          git clone https://github.com/crisluengo/m.css.git
          cd m.css
          git checkout fix-class-parsed-as-function

      - name: Build docs
        shell: bash -l {0}
        run: |
          cd docs
          git clone https://github.com/dic-iit/bipedal-locomotion-framework.git
          python3 ./generate_website.py --mcss_path ${GITHUB_WORKSPACE}/m.css/documentation/doxygen.py

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: site
          path: docs/site

  deploy:
    runs-on: ubuntu-20.04
    needs: [build]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: site
          path: site
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: site
