name: gh-pages
on:
  push:
    branches:
      - '*'
      - '!gh-pages'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master

      - name: Dependencies
        run: |
          sudo apt update
          sudo apt install -y xsltproc texlive ghostscript graphviz texlive-base texlive-latex-extra texlive-fonts-extra texlive-fonts-recommended flex bison
          git clone --depth 1 --branch Release_1_9_1 https://github.com/doxygen/doxygen.git
          cd doxygen && mkdir build && cd build
          cmake -G "Unix Makefiles" ..
          sudo make install

      - name: Fetch Python deps
        run: python3 -m pip install jinja2 Pygments docutils

      - name: Fetch m.css
        run: |
          # Use an unofficial version of m.css because of https://github.com/mosra/m.css/pull/189
          cd ${GITHUB_WORKSPACE}
          git clone https://github.com/crisluengo/m.css.git
          cd m.css
          git checkout fix-class-parsed-as-function

      - name: Build docs
        run: |
          cd docs
          git clone https://github.com/dic-iit/bipedal-locomotion-framework.git
          ./generate_website.sh ${GITHUB_WORKSPACE}/m.css/documentation/doxygen.py

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: site
          path: docs/site

  deploy:
    runs-on: ubuntu-20.04
    needs: [build]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: site
          path: site
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: site
